.

diff --git a/bin/c2 b/bin/c2
--- a/bin/c2
+++ b/bin/c2
@@ -7361,10 +7361,11 @@ top_level() {
       commands=${chosen_commands[$cell_group_index]:-}
       if [[ "$commands" ]]; then
         begin_for cell_path in $cell_paths; doo
-          if [[ $cell_path != /* ]]; then
-            cell_path=$PWD/${cell_path#./} || fail
-          fi
-          handle_cell $cell_path ${chosen_cells[$cell_group_index]} || fail
+#          cell_path=$(realpath $cell_path) || fail
+#          if [[ $cell_path != /* ]]; then
+#            cell_path=$PWD/${cell_path#./} || fail
+#          fi
+          handle_cell $cell_path $commands || fail
           (( handled++ ))
         end_for
       else
@@ -8348,7 +8349,7 @@ find_paths() {
       SIMPLETON_SEED=${SIMPLETON_SEED:-undefined} \
       SIMPLETON_CELL=${SIMPLETON_CELL:-undefined} \
 
-    if [[ $cell_path == $SIMPLETON_SEED/* || $cell_path == */.seed/* ]]; then
+    if [[ $cell_path == $SIMPLETON_SEED || $cell_path == $SIMPLETON_SEED/* || $cell_path == */.seed/* ]]; then
       unset work_path
       if [[ $cell_path == $SIMPLETON_SEED/* ]]; then
         base_path=
@@ -8381,7 +8382,7 @@ find_paths() {
         seed_path+="/$extend_folder"
       done
 
-    elif [[ $cell_path == $SIMPLETON_CELL/* || $cell_path == */.cell/* ]]; then
+    elif [[ $cell_path == $SIMPLETON_CELL || $cell_path == $SIMPLETON_CELL/* || $cell_path == */.cell/* ]]; then
       unset work_path
 
       find_base_seed $cell_path || fail
@@ -8395,6 +8396,9 @@ find_paths() {
       if [[ $cell_path == $SIMPLETON_CELL/* ]]; then
         base_path=
         extend_path=${cell_path#$SIMPLETON_CELL/}
+      elif [[ $cell_path == $SIMPLETON_CELL ]]; then
+        base_path=
+        extend_path=
       elif [[ $cell_path == */.cell/* ]]; then
         base_path=${cell_path%%/.cell/*}
         extend_path=${cell_path#$base_path/.cell/}
