.

diff --git a/bin/c2 b/bin/c2
--- a/bin/c2
+++ b/bin/c2
@@ -1317,13 +1317,19 @@ show_flag_usage() {
     out "  -d     debug flags: same as -vvi (debug logs + show debug ids)"
     out "  -g     grip++ (increase debug checkpoints, slowing down execution but making it easier to debug)"
     out "  -i     show_debug_id=t (if used twice, show_debug_id=a)"
-    out "  -l     less detail: command_detail-- (command_detail defaults to 0)"
+    out "  -l     less detail: command_detail-- (command_detail defaults to 0), can use twice for least detail"
     out "  -m     more detail: command_detail++ (can use this twice to get the most detail)"
     out "  -q     less logs. Can be used repeatedly. Without this, log=info, -q = warn, -qq = error, -qqq = fatal"
+    out "  -p     more paranoid: paranoia++ (up to 3 times). Makes the command execute more slowly and carefully."
+    out "         paranoia=0 fastest, assuming all cache invalidation mechanisms are working correctly."
+    out "         paranoia=1 does extra checks that are cheap, so it still should be reasonably fast, but will be more resilient to caching bugs."
+    out "         paranoia=2 does extra checks that are not cheap, further increasing robustness."
+    out "         paranoia=3 rebuilds every cell it touches completely. Similar to clean-all, except more efficient since it only cleans cells that are relevant to this command."
+    out "  -P     paranoia=3 (shortcut)"
     out "  -s     trace_structure=t"
     out "  -T     show_time=t"
     out "  -v     more logs. Can be used repeatedly. Without this, log=info, -v = verbose, -vv = debug, -vvv = trace"
-    out "  -x     debug_on_exit=t"
+#    out "  -x     debug_on_exit=t"
   } | sort
 }
 
@@ -1359,6 +1365,12 @@ handle_flag() {
           ;;
         m)
           (( command_detail++ )) || true
+          ;;
+        p)
+          (( paranoia++ )) || true
+          ;;
+        P)
+          paranoia=3
           ;;
         q)
           case "${log:-}" in
@@ -6233,8 +6245,8 @@ show_usage() {
     local name
     {
       begin_for name in ${cell_commands[*]}; doo
-
-        local -n command_description=command_${name}_description
+        local command_var=${name//-/_}
+        local -n command_description=command_${command_var}_description
         if [[ "$command_description" ]]; then
           local short_desc=$command_description
           trim_ws short_desc
@@ -6249,8 +6261,9 @@ show_usage() {
 
 
     begin_for name in ${cell_commands[*]}; doo
-      local -n command_aliases=command_${name}_aliases
-      local -n command_alias_command=command_${name}_alias_command
+      local command_var=${name//-/_}
+      local -n command_aliases=command_${command_var}_aliases
+      local -n command_alias_command=command_${command_var}_alias_command
       if [[ "${command_aliases:-}" ]]; then
         local i
         (( indent -= 2 ))
@@ -6474,19 +6487,13 @@ handle_cell() {
   begin_function
 
     local command_count=${#chosen_commands[*]}
-    #if [[ -e "$cell_path" ]]; then
-      cell_path=$(unrealpath $cell_path) || {
-        log_fatal "Invalid cell path: $cell_path"
-        fail1
-        }
-    #fi
+    cell_path=$(unrealpath $cell_path) || {
+      log_fatal "Invalid cell path: $cell_path"
+      fail1
+      }
 
     if (( command_count > 0 )); then
-#      if (( command_count > 1 )); then
-#        fork execute_commands $cell_path ${chosen_commands[*]} || fail
-#      else
-        execute_commands $cell_path ${chosen_commands[*]} || fail
-#      fi
+      execute_commands $cell_path ${chosen_commands[*]} || fail
     elif [[ ! "${parameter_questions:-}" ]]; then
       show_cell_help $cell_path || fail
     else # parameter_questions
@@ -6534,6 +6541,7 @@ top_level() {
       first_command=t \
       first_cell=t \
       clean_cells=${clean_cells:-${clean_cell:-${clean:-}}} \
+      paranoia=${paranoia:-0} \
 
     reset_flags
     get_help_depth_and_flags || fail
@@ -8031,6 +8039,20 @@ request_rm_command() {
   handle_return
 }
 
+# inputs:
+#   cell_path
+clear_ready_file() {
+  begin_function_lo
+    local branch=${cell_path##*/} \
+      parent_cell=${cell_path%/*} \
+
+    if [[ -e $parent_cell/.ready-$branch ]]; then
+      rm $parent_cell/.ready-$branch
+    fi
+  end_function
+  handle_return
+}
+
 # cell should already be locked before running this
 # inputs:
 #   cell_path
@@ -8069,9 +8091,8 @@ promote_request() {
     fi
 
     force=t safe_link $req_path/* $cell_path/in/ || fail
-
-    local req_file=${req_path##*/}
-    mv $cell_req_path/ready/$req_file $cell_req_path/running/ || fail
+    change_request_state ready running || fail
+    clear_ready_file || fail
 
   end_function
   handle_return
