.

diff --git a/bin/c2 b/bin/c2
--- a/bin/c2
+++ b/bin/c2
@@ -2791,12 +2791,12 @@ link_unlock() {
 #   otherwise it will keep trying until the timeout is reached or the lock is obtained.
 folder_lock() {
   local folder_to_lock=${folder_to_lock}
-  local timeout=${timeout:-$lock_timeout}
-  local pid_file=${pid_file:-$folder_to_lock/pid}
+  local timeout=${timeout:-${lock_timeout:-}}
+  local pid_file=${pid_file:-$folder_to_lock/.pid}
   local remove_folder_when_unlocked=${remove_folder_when_unlocked:-f}
 
   local interesting_vars='folder_to_lock timeout'
-  begin_function_hi
+  begin_function
 
     if [[ -d "$folder_to_lock" ]]; then
 
@@ -2884,7 +2884,7 @@ folder_is_locked() {
 # inputs: folder_to_unlock pid_file
 folder_unlock() {
   local folder_to_unlock=$folder_to_unlock
-  local pid_file=${pid_file:-$folder_to_unlock/pid}
+  local pid_file=${pid_file:-$folder_to_unlock/.pid}
   local remove_folder_when_unlocked=${remove_folder_when_unlocked:-f}
 
   if [[ ! "$folder_to_unlock" ]]; then
@@ -2894,9 +2894,7 @@ folder_unlock() {
 
   if [[ -d "$folder_to_unlock" && $remove_folder_when_unlocked == t ]]; then
     rm -r "$folder_to_unlock" || return 1
-  fi
-
-  if [[ -f "$pid_file" ]]; then
+  elif [[ -f "$pid_file" ]]; then
     rm "$pid_file" || return 1
   fi
 
@@ -6139,33 +6137,9 @@ is_command() {
   || array_contains command_aliases $parameter
 }
 
-get_cells() {
+get_cells_and_commands() {
   begin_function
-    for (( ; current_parameter_index < ${#parameters[*]}; current_parameter_index++ )); do
-      local parameter=${parameters[$current_parameter_index]}
-      case $parameter in
-        help|-*|\?|\?\?)
-          :
-        ;;
-        *)
-          if is_command $parameter; then
-            abort
-          elif [[ -d $parameter ]]; then
-            cells+=( $parameter )
-          else
-            log_fatal "Not a command or cell: $parameter"
-            fail1
-          fi
-        ;;
-      esac
-    done
-  end_function
-  handle_return
-}
-
-get_commands() {
-  begin_function
-    for (( ; current_parameter_index < ${#parameters[*]}; current_parameter_index++ )); do
+    begin_for (( ; current_parameter_index < ${#parameters[*]}; current_parameter_index++ )); doo
       local parameter=${parameters[$current_parameter_index]}
       case $parameter in
         help|-*|\?|\?\?)
@@ -6178,21 +6152,46 @@ get_commands() {
             leftover_command=${leftover_command// /-}-$parameter
           fi
 
-          if is_command $parameter \
-             || array_contains command_aliases $parameter; then
-            cell_commands+=( $parameter )
-          elif is_command $leftover_command; then
-            cell_commands+=( $leftover_command )
+          if is_command "$parameter" || is_command "$leftover_command"; then
             leftovers=()
+            case $previous_parameter in
+              cell)
+                commands+=( $parameter )
+              ;;
+              none)
+                cells+=( . )
+                (( cell_count++ ))
+                commands+=( $parameter )
+              ;;
+              command)
+                commands[-1]+=" $parameter"
+              ;;
+              *)
+                log_fatal "Internal error: invalid previous_parameter variable: $previous_parameter"
+                fail1
+              ;;
+            esac
+            (( command_count++ ))
           elif [[ -d $parameter ]]; then
-            # it's a cell
-            abort
+            case $previous_parameter in
+              cell|none)
+                cells[-1]+=" $parameter"
+              ;;
+              command)
+                cells+=( $parameter )
+              ;;
+              *)
+                log_fatal "Internal error: invalid previous_parameter variable: $previous_parameter"
+                fail1
+              ;;
+            esac
+            (( cell_count++ ))
           else
             leftovers+=( $parameter )
           fi
         ;;
       esac
-    done
+    end_for
   end_function
   handle_return
 }
@@ -6254,6 +6253,35 @@ handle_questions() {
   handle_return
 }
 
+execute_command() {
+  local command=$1
+  begin_function
+    if function_exists ${command}_command; then
+      ${command}_command || fail
+    else
+      log_fatal "Internal error: function doesn't exist: ${command}_command"
+      fail1
+    fi
+  end_function
+  handle_return
+}
+
+execute_commands() {
+  local cell_path=$1; shift
+  local commands=$*
+
+  begin_function
+# Not all commands require a lock, so lock within the command itself
+#    lock_cell || fail
+    local command
+    begin_for command in $commands; doo
+      execute_command $command || fail
+    end_for
+  end_function
+#  unlock_cell
+  handle_return
+}
+
 handle_cell() {
   local cell_path=$1
 
@@ -6267,11 +6295,11 @@ handle_cell() {
         }
     fi
 
-    if (( ${#cell_commands[*]} > 0 )); then
-      if [[ $multi_cell == f ]]; then
-        execute_commands $cell_path ${cell_commands[*]} || fail
+    if (( ${#commands[*]} > 0 )); then
+      if (( ${#commands[*]} > 1 )); then
+        fork execute_commands $cell_path ${commands[*]} || fail
       else
-        fork execute_commands $cell_path ${cell_commands[*]} || fail
+        execute_commands $cell_path ${commands[*]} || fail
       fi
     elif [[ ! "${parameter_questions:-}" ]]; then
       show_cell_help $cell_path || fail
@@ -6319,45 +6347,31 @@ top_level() {
     local cell_path \
       first_command=t \
       first_cell=t \
-      multi_cell=f \
-      multi_commands=f \
       clean_cells=${clean_cells:-${clean_cell:-${clean:-}}} \
 
     reset_flags
     get_help_depth_and_flags || fail
 
-    local current_parameter_index=0 leftovers=() leftover_command handled=0
+    local current_parameter_index=0 leftovers=() leftover_command \
+      handled=0 cell_count command_count cells commands \
+      previous_parameter=none \
+
     begin_while true; doo
 
       cells=() \
-      cell_commands=() \
+      commands=() \
       leftovers=() \
+      cell_count=0 \
+      command_count=0 \
 
-      if [[ -e $path_to_commands/all.info ]]; then
-        source $path_to_commands/all.info || fail
-      fi
       handle_questions || fail
-      get_cells || fail
-      get_commands || fail
+      get_cells_and_commands || fail
       handle_leftovers || fail
 
-      if (( ${#cell_commands[*]} > 1 )); then
-        multi_commands=t
-      fi
-
-      if (( ${#cells[*]} > 1 )); then
-        multi_cell=t
-      fi
-
-      if [[ ! "${cells:-}" ]]; then
-        if [[ ! "${cell_commands:-}" && ! "${parameter_questions:-}" ]]; then
-          if (( handled == 0 )); then
-            show_usage
-            abort
-          else
-            # nothing else to do
-            abort
-          fi
+      if (( cell_count == 0 )); then
+        if (( command_count == 0 )) && [[ ! "${parameter_questions:-}" ]]; then
+          show_usage
+          abort
         fi
 
         local potential_cell=$(realpath .) seed_path=
@@ -6374,7 +6388,6 @@ top_level() {
           done
         fi
 
-        cells=( $potential_cell )
       fi
 
       if [[ "${cell_commands:-}" && ! "${parameter_questions:-}" ]] && (( help_depth > 0 )); then
@@ -6413,6 +6426,9 @@ top_level() {
 # Used by the help system to describe a command and it's parameters to the user
 new_command() {
   local name=$name description=$description
+  commands+=( $name )
+  command=$name
+  local -n command_description=command_${name}_description
   command_description=$description
   unset \
     parameter_aliases \
@@ -6436,13 +6452,13 @@ add_parameter() {
     required=${required:-f} \
     delay_questions=${delay_questions:-f} \
 
-  local -n parameter_names=parameter_names_$type \
-    parameter_descriptions=parameter_descriptions_$type \
-    parameter_choices=parameter_choices_$type \
-    parameter_defaults=parameter_defaults_$type \
-    parameter_aliases=parameter_aliases_$type \
-    parameter_delay_questions=parameter_delay_questions_$type \
-    parameter_required=parameter_required_$type \
+  local -n parameter_names=parameter_${command}_names_$type \
+    parameter_descriptions=parameter_${command}_descriptions_$type \
+    parameter_choices=parameter_${command}_choices_$type \
+    parameter_defaults=parameter_${command}_defaults_$type \
+    parameter_aliases=parameter_${command}_aliases_$type \
+    parameter_delay_questions=parameter_${command}_delay_questions_$type \
+    parameter_required=parameter_${command}_required_$type \
 
   parameter_names+=( "$name" ) 
   parameter_descriptions+=( "$description" ) 
@@ -6602,7 +6618,7 @@ request_promote_command() {
   handle_return
 }
 
-execute_command() {
+execute_update() {
   begin_function
     # fail if in/ is missing
     # gather steps
@@ -6642,12 +6658,22 @@ pool_status_command() {
 update_command() {
   begin_function
     # check if update is needed
+    lock_cell || fail
     # make request
-    # execute command
+    # execute update
     # watch status
     # display results?
   end_function
+  unlock_cell
   handle_return
+}
+
+lock_cell() {
+  folder_to_lock=$cell_path/out.new folder_lock
+}
+
+unlock_cell() {
+  folder_to_lock=$cell_path/out folder_unlock
 }
 
 ### file: ./05-walk-lib.bash
