.

diff --git a/bin/c2 b/bin/c2
--- a/bin/c2
+++ b/bin/c2
@@ -8697,12 +8697,17 @@ mark_cell_ready() {
       fi
 
       if [[ $above_cell == t ]]; then
-        local ready_file=ready-$branch
-        if [[ -e $parent_cell/.cyto/$ready_file ]]; then
-          # we don't need to go further, since this entire branch has already been marked previously
-          break
+        #local ready_file=ready-$branch
+        #if [[ -e $parent_cell/.cyto/$ready_file ]]; then
+        #  # we don't need to go further, since this entire branch has already been marked previously
+        #  break
+        #else
+        #  ln -s $parent_cell/$branch $parent_cell/.cyto/$ready_file || fail
+        #fi
+        if [[ ! -e $parent_cell/.cyto/ready ]]; then
+          touch $parent_cell/.cyto/ready || fail
         else
-          ln -s $parent_cell/$branch $parent_cell/.cyto/$ready_file || fail
+          abort
         fi
       fi
       branch=${parent_cell##*/}
@@ -8816,8 +8821,8 @@ clear_ready_file() {
     local branch=${cell_path##*/} \
       parent_cell=${cell_path%/*} \
 
-    if [[ -e $parent_cell/.cyto/ready-$branch ]]; then
-      rm $parent_cell/.cyto/ready-$branch
+    if [[ -e $parent_cell/.cyto/ready ]]; then
+      rm $parent_cell/.cyto/ready
     fi
   end_function
   handle_return
