.

diff --git a/bin/c2 b/bin/c2
--- a/bin/c2
+++ b/bin/c2
@@ -6892,6 +6892,14 @@ plant_command() {
   handle_return
 }
 
+create_request() {
+  local cell_path=$cell_path
+  begin_function
+    
+  end_function
+  handle_return
+}
+
 request_new_command() {
   begin_function
     # plant seed if needed
@@ -7248,8 +7256,8 @@ update_command() {
     get_needs_update || fail
     if [[ $needs_update == t ]]; then
       plant_seed $seed_path $cell_path || fail
-      lock_out || fail
-      # make request
+      #lock_out || fail
+      create_request || fail
       cell_path=$cell_path.new execute_update || fail
       
       if [[ -e $cell_path/out.old ]]; then
@@ -7267,7 +7275,7 @@ update_command() {
     fi
 
   end_function
-  unlock_out
+  #unlock_out
   handle_return
 }
 
