.

diff --git a/bin/c2 b/bin/c2
--- a/bin/c2
+++ b/bin/c2
@@ -6567,6 +6567,144 @@ cell_lib_init() {
   trace_dims=${trace_dims:-${trace_dim:-}}
 }
 
+plant_seed_internal() {
+  local from=$1 to=$2 contents x x_part deep=${deep:-t} \
+    cell_is_leaf=${cell_is_leaf:-t} key_path=${key_path:-} \
+
+  begin_function
+
+    if [[ ! -d $to ]]; then
+
+      log_verbose "Planting seed from $from to $to"
+
+      if [[ $from == /seed/* && -d $from ]]; then
+        plant_seed_internal ${from%/*} ${to%/*} || fail
+      else
+        log_fatal "Seed doesn't exist for $to"
+        fail1
+      fi
+
+    else
+
+      contents=( $(find1 $from | sort -g) ) || fail
+      local target
+      begin_for x in ${contents[*]}; doo
+        x_part=${x##*/}
+        target=$to/$x_part
+        if [[ -d $x ]]; then
+          if [[ ! -e $target ]]; then
+
+            # remove broken links
+            if [[ -L $target ]]; then
+              rm $target || fail
+            fi
+
+            if [[ $x_part == .dna || $x_part == .root ]]; then
+              safe_link $(realpath $x) $to/ || fail
+            elif [[ $x_part == .key ]]; then
+              key_path=$x || fail
+            elif [[ $x_part == .lib ]]; then
+              mkdir $target || fail
+              safe_link $(realpath $x)/* $target/ || fail
+            elif [[ $x_part == .mock && "${current_mock:-f}" != f && -d $x/$current_mock ]]; then
+              safe_link $(realpath $x)/$current_mock/!(export) $to/ || fail
+            elif [[ $x_part == *:* ]]; then
+
+              if [[ "${branch_coordinate_fields:-}" ]]; then
+                local dim_part=${x_part%%:*} \
+                  mem_part=${x_part#*:}
+
+                if [[ ! $dim_part =~ ^[a-zA-Z0-9_]+$ ]]; then
+                  log_fatal "Invalid dim name: $dim_part, found in $x"
+                  fail1
+                fi
+
+                local values
+                coord_type=branch \
+                dim=$dim_part \
+                fetch_values_from_coordinates $dim_part || fail
+
+                local value_count=${#values[*]}
+
+                # Hashed members currently not supported
+                # Not too hard to implement, but isn't likely to be needed
+                if (( value_count == 1 )) && [[ "$values" == "$mem_part" ]]; then
+                  plant_seed_internal $x $to || fail
+                fi
+              fi
+
+            elif [[ $x_part != .* ]]; then
+              mkdir $target || fail
+            fi
+          fi
+          if [[ $x_part != .* && -d $target && $deep == t ]]; then
+            plant_seed_internal $x $target || fail
+          fi
+        elif [[ $cell_is_leaf == t && ! -e $target && $x_part != .* ]]; then
+          if [[ $x == *.safe ]]; then
+            ignore_failure=t \
+            cell_decrypt_file $x ${target%.safe} || fail
+          else
+            ln -s $x $to/ || fail
+          fi
+        fi
+      end_for
+
+    fi
+  end_function
+  handle_return
+}
+
+# inputs: $1  work path to the cell
+plant_seed() {
+  local seed_path cell_path=$1 \
+    deep=${deep:-t} \
+    ignore_nonexistent=${ignore_nonexistent:-f}
+
+  begin_function
+
+    # if in/ already exists, then consider it planted
+    # find seed if .seed doesn't exist
+    # link seed
+    # go through standard folders in seed and link/make
+    # go through _trunk _branch _leaf if matching
+    # figure out parent_branches
+    # go through *:_ if matching
+    # make in/
+
+    if [[ ! -d "$to" ]]; then
+      log_fatal "plant_seed called on a non-existant work path: $to"
+      fail1
+    fi
+
+    find_seed_path $from || fail
+    if [[ ! "$seed_path" ]]; then
+      log_fatal "No seed is associated with this path: $to"
+      fail1
+    fi
+
+    local dna_path=$seed_path
+    if [[ $command_requires_cell == t ]]; then
+      while [[ ! -d $dna_path/.dna ]]; do
+        dna_path=${dna_path%/*}
+        if [[ $dna_path != /*/* ]]; then
+          log_fatal "Could not find dna in seed: $seed_path"
+          fail1
+        fi
+      done
+
+      if [[ $dna_path != $seed_path ]]; then
+        safe_link $dna_path/.dna $to/ || fail
+      fi
+
+    fi
+
+    plant_seed_internal $seed_path $to || fail
+
+  end_function
+  handle_return
+}
+
 clean_command() {
   begin_function
     rm -rf $cell_path/!(.seed) || fail
@@ -6576,20 +6714,18 @@ clean_command() {
 
 plant_command() {
   begin_function
-    # if in/ already exists, then consider it planted
-    # find seed if .seed doesn't exist
-    # link seed
-    # go through standard folders in seed and link/make
-    # go through _trunk _branch _leaf if matching
-    # figure out parent_branches
-    # go through *:_ if matching
-    # make in/
+    plant_seed $cell_path || fail
   end_function
   handle_return
 }
 
 request_new_command() {
   begin_function
+    # plant seed if needed
+    if [[ ! -d $cell_path ]]; then
+      plant_seed $cell_path || fail
+    fi
+
     # do nothing if request already exists
     # make in.new
     # place input dims here
