Rename command variable to cell_command

diff --git a/bin/cell b/bin/cell
--- a/bin/cell
+++ b/bin/cell
@@ -220,11 +220,11 @@ clean_folder() {
 }
 
 handle_command() {
-  local command=$1
+  local cell_command=$1
 
   begin_function
 
-      case $command in
+      case $cell_command in
         shell)
           export prompt_name='cell shell'
           bash --init-file <(
@@ -244,9 +244,9 @@ handle_command() {
             bottom_cell=$cell_path
           fi
           : ${clean_depth:=1} ${kind:=all}
-          if [[ $command == clean2 ]]; then
+          if [[ $cell_command == clean2 ]]; then
             kind=data
-          elif [[ $command == clean0 ]]; then
+          elif [[ $cell_command == clean0 ]]; then
             kind=context
           fi
           clean_folder $bottom_cell || fail
@@ -264,12 +264,12 @@ handle_command() {
           local needs_update=${needs_update:-} \
             command_to_log="${original_cmd#* }" \
             top_level_command=t \
-            saved_command=$command
+            saved_command=$cell_command
 
           local command_successful=f trunk_cell=
-          execute_command $cell_path $command || fail
+          execute_command $cell_path $cell_command || fail
           if [[ $command_successful == f ]]; then
-            log_error "Command failed: $command"
+            log_error "Command failed: $cell_command"
             fail1
           fi
         ;;
@@ -362,15 +362,15 @@ handle_cell() {
       fail1
       }
 
-    local next
+    local next cell_command
     if (( ${#commands[*]} == 0 )); then
       show_cell_help $cell_path || fail
     else
-      begin_for command in ${commands[*]}; doo
+      begin_for cell_command in ${commands[*]}; doo
         if [[ $help_mode == t ]]; then
-          show_help_for_command $command || fail
+          show_help_for_command $cell_command || fail
         else
-          handle_command $command || fail
+          handle_command $cell_command || fail
         fi
         first_command=f
       end_for
@@ -545,7 +545,7 @@ show_usage() {
         short_desc=${short_desc%%$NL*}
         out "  $command_name $COL20$short_desc"
       else
-        out "  $command_name ${COL20}Please add a description to this command in $command"
+        out "  $command_name ${COL20}Please add a description to this command in $cell_command"
       fi
     end_for
   end_function
diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -2462,7 +2462,7 @@ execute_command_log_prep() {
     running_job_path=$job_path/running
 
     local link_target
-    begin_for link_target in $current_command-attempt attempt; doo
+    begin_for link_target in $cell_command-attempt attempt; doo
       if [[ -e "$job_path/last-$link_target" ]]; then
         mv $job_path/last-$link_target $job_path/prev-$link_target || fail
       fi
@@ -2496,7 +2496,7 @@ execute_command_internal_setup_params() {
 execute_command_internal() {
 
   local log_vars='cell_path' \
-    log_show_vars='short_cell current_command' 
+    log_show_vars='short_cell cell_command' 
   begin_function_hi
 
     local omni_log_fork_parent=${omni_log_fork_parent:-}-${omni_log_fork_child:-1} \
@@ -2518,20 +2518,20 @@ execute_command_internal() {
       eval "$localize_dims" || fail
     fi
 
-    if [[ " ${command_history:-}" == *" $current_command $short_cell "* ]]; then
-      log_fatal "Circular dependency found: arrived at $current_command $short_cell a second time."
+    if [[ " ${command_history:-}" == *" $cell_command $short_cell "* ]]; then
+      log_fatal "Circular dependency found: arrived at $cell_command $short_cell a second time."
       fail1
     fi
 
-    command_history+="$current_command $short_cell "
+    command_history+="$cell_command $short_cell "
 
     if [[ ${cell_is_leaf:-t} == t || $show_branches == t ]]; then
-      log_info "Executing cell command: $short_cell $current_command" || fail
+      log_info "Executing cell command: $short_cell $cell_command" || fail
     else
-      log_verbose "Executing cell command: $short_cell $current_command" || fail
+      log_verbose "Executing cell command: $short_cell $cell_command" || fail
     fi
 
-    local command_function=${current_command//-/_}_command
+    local command_function=${cell_command//-/_}_command
     if function_exists $command_function; then
       $command_function || fail
     else
@@ -2544,12 +2544,12 @@ execute_command_internal() {
 }
 
 execute_command() {
-  local cell_path=$(realpath $1) current_command=$2 \
-    log_show_vars='^cell_path current_command' \
+  local cell_path=$(realpath $1) cell_command=$2 \
+    log_show_vars='^cell_path cell_command' \
 
   begin_function_hi
 
-    case $current_command in
+    case $cell_command in
       dim-*|up-*)
         if [[ $cell_path == /seed/* ]]; then
           cell_path=/work${cell_path#/seed}
@@ -2583,7 +2583,7 @@ execute_command() {
       }
     fi
 
-    command_path=$path_to_commands/$current_command
+    command_path=$path_to_commands/$cell_command
     command_requires_resolved_dims=f
     command_allows_logs=f
     if [[ -e $command_path.info ]]; then
