.

diff --git a/bin/cell b/bin/cell
--- a/bin/cell
+++ b/bin/cell
@@ -320,11 +320,11 @@ show_cell_help() {
   local cell_path=$1
   begin_function
 
-    get_bottom_cell $cell_path || {
-      log_fatal "No cell found here: $cell_path"
-      fail1
-      }
-    local cell_path=$bottom_cell
+    # get_bottom_cell $cell_path || {
+    #   log_fatal "No cell found here: $cell_path"
+    #   fail1
+    #   }
+    # local cell_path=$bottom_cell
     can_create_cyto=f
     switch_context || fail
     if [[ $multi_cell == t ]]; then
