Make cell parameters execute commands sequentially against previously mentioned cell

diff --git a/bin/cell b/bin/cell
--- a/bin/cell
+++ b/bin/cell
@@ -91,9 +91,13 @@ show_usage() {
   handle_return
 }
 
-scan_commands() {
+get_help_depth() {
   begin_function
-    local parameter leftovers=() leftover_command
+    if [[ "${parameter_questions:-}" ]]; then
+      : ${help_depth:=2}
+    else
+      : ${help_depth:=0}
+    fi
     for parameter in ${parameters[*]}; do
       case $parameter in
         help|--help|-h|\?)
@@ -102,6 +106,46 @@ scan_commands() {
         \?\?)
           (( help_depth += 2 )) 
         ;;
+      esac
+    done
+  end_function
+  debug_return_vars=help_depth
+  handle_return
+}
+
+get_cells() {
+  begin_function
+    for (( ; current_parameter_index < ${#parameters[*]}; current_parameter_index++ )); do
+      local parameter=${parameters[$current_parameter_index]}
+      case $parameter in
+        help|--help|-h|\?|\?\?)
+          :
+        ;;
+        *)
+          if [[ $parameter == -* ]]; then
+            handle_flag $parameter || { fail_later; break 2; }
+          elif [[ ! -d $parameter ]]; then
+            # is a command
+            (( current_parameter_index-- ))
+            break
+          else
+            cells+=( $parameter )
+          fi
+        ;;
+      esac
+    done
+  end_function
+  handle_return
+}
+
+get_commands() {
+  begin_function
+    for (( ; current_parameter_index < ${#parameters[*]}; current_parameter_index++ )); do
+      local parameter=${parameters[$current_parameter_index]}
+      case $parameter in
+        help|--help|-h|\?|\?\?)
+          :
+        ;;
         *)
           leftover_command=
           if [[ "${leftovers:-}" ]]; then
@@ -109,21 +153,25 @@ scan_commands() {
             leftover_command=${leftover_command// /-}-$parameter
           fi
 
-          if [[ $parameter != */* && -f "$path_to_commands/$parameter.info" ]]; then
+          if [[ $parameter == -* ]]; then
+            handle_flag $parameter || { fail_later; break 2; }
+          elif [[ -f "$path_to_commands/$parameter.info" ]]; then
             commands+=( $parameter )
-          elif [[ $parameter != */* && -f "$path_to_commands/$leftover_command.info" ]]; then
+          elif [[ -f "$path_to_commands/$leftover_command.info" ]]; then
             commands+=( $leftover_command )
             leftovers=()
-          elif [[ -e $parameter/.dna ]]; then
-            cells+=( $parameter )
-          elif [[ $parameter == -* ]]; then
-            handle_flag $parameter || { fail_later; break 2; }
           else
             leftovers+=( $parameter )
           fi
         ;;
       esac
     done
+  end_function
+  handle_return
+}
+
+handle_leftovers() {
+  begin_function
     local leftover
     for leftover in "${leftovers[@]}"; do
       if (( help_depth > 0 )); then
@@ -139,53 +187,26 @@ scan_commands() {
           continue
         fi
       fi
-      if [[ -d "$leftover" ]]; then
-        local bottom_cell=
-        leftover=$(unrealpath $leftover)
-        get_bottom_cell $leftover
-        if [[ "$bottom_cell" ]]; then
-          cells+=( $bottom_cell )
-          continue
-        else
-          log_fatal "Not a valid cell: $leftover"
-        fi
-      else
-        log_fatal "Unidentified command: $leftover"
-      fi
       show_usage 
       fail_later1; break 2
     done
   end_function
-  local log_return_vars='cells commands'
   handle_return
 }
 
-show_help_for_command() {
-  local command=$1
+get_commands_and_cells() {
   begin_function
-    [[ $first_command == f ]] && out ''
-    out "Command: ${command//-/ }"
-    if [[ -f $path_to_commands/$command.info ]]; then
-      source $path_to_commands/$command.info || fail
-      indent=2 out_wrap "$command_description"
-      local name description default default_string choices_string i choices
-      if [[ "${parameter_names:-}" ]]; then
-        out "Parameters:"
-        begin_for ((i=0; i<${#parameter_names[*]}; i++)); doo
-          parameter="${parameter_names[$i]}"
-          description="${parameter_descriptions[$i]}"
-          choices="${parameter_choices[$i]}"
-          trim_ws description
-          default="${parameter_defaults[$i]}"
-          default_string=
-          choices_string=
-          [[ "$choices" ]] && choices_string="$NL    choices: $choices"
-          [[ "$default" ]] && default_string="$NL    default: $default"
-          out "  $parameter: $description$choices_string$default_string"
-        end_for
-      fi
+    local leftovers=() leftover_command
+
+    get_cells || fail
+    get_commands || fail
+    handle_leftovers || fail
+    if (( help_depth > 0 )); then
+      commands=( help )
     fi
+
   end_function
+  local log_return_vars='cells commands'
   handle_return
 }
 
@@ -373,97 +394,6 @@ handle_command() {
 
 }
 
-show_cell_help() {
-  local cell_path=$1
-  begin_function
-
-    command_requires_cell=t \
-    command_requires_resolved_dims=f \
-    trunk_changed=f \
-    command_allows_logs=f \
-      switch_context $cell_path || fail
-    indent=0
-
-    if [[ $multi_cell == t ]]; then
-      out "$hbar_equals"
-    fi
-
-    out_wrap "Cell: $short_cell"
-    (( indent += 2 ))
-    if [[ "${cell_description:-}" ]]; then
-      out_wrap "$cell_description"
-    else
-      out_wrap "No description for this cell. Set cell_description variable in context file."
-    fi
-
-    local required=()
-
-    if [[ "${trunk_dims:-}" ]]; then
-      out_wrap "${NL}Dimensions: (add {dim}=? to command to see details, or cell . ?? to show all details)"
-      dim_type=trunk_dims \
-      show_dimensions ${trunk_dims[*]} || fail
-    fi
-
-    if [[ "${sub_dims:-}" || "${data_props:-}" || "${control_props:-}" ]]; then
-      out_wrap "${NL}Other parameters:"
-      if [[ "${sub_dims:-}" ]]; then
-        dim_type=sub_dims \
-        show_dimensions ${sub_dims[*]} || fail
-      fi
-      if [[ "${control_props:-}" ]]; then
-        dim_type=control_props \
-        show_dimensions ${control_props[*]} || fail
-      fi
-      if [[ "${data_props:-}" ]]; then
-        dim_type=data_props \
-        show_dimensions ${data_props[*]} || fail
-      fi
-    fi
-
-    if [[ "${required:-}" ]]; then
-      out_wrap "${NL}Required parameters: ${required[*]}"
-    fi
-
-    if [[ "${trunk_dims:-}" ]]; then
-      out_wrap "${NL}Branch dimensions:"
-      local i pretty_form= member dim
-      #begin_for (( i = 0; i < ${#branch_dims[*]}; i++ )); doo
-      #  dim=${branch_dims[$i]}
-      #  eval "member=\${branch_members[$i]}"
-      #  local pretty_function_name=trunk_dims_${dim}_pretty
-      #  if function_exists $pretty_function_name; then
-      #    eval "$pretty_function_name member" || fail
-      #    pretty_form=" ($member)"
-      #  else
-      #    pretty_form=
-      #  fi
-      #  out "  $dim=${branch_members[$i]}$pretty_form"
-      #end_for
-      (( indent += 2 ))
-      begin_for (( i = 0; i < ${#trunk_dims[*]}; i++ )); doo
-        dim_var=${trunk_dims[$i]}
-        local -n dim=d_$dim_var
-        local pretty_function_name=trunk_dims_${dim_var}_pretty
-        if function_exists $pretty_function_name; then
-          eval "$pretty_function_name $dim_var" || fail
-          pretty_form=" ($value)"
-        else
-          pretty_form=
-        fi
-        local value=${dim:-}
-        if [[ "${value:-}" ]]; then
-          if [[ "$value" == $empty_member ]]; then
-            value='(empty)'
-          fi
-          out_wrap "$dim_var=$value$pretty_form"
-        fi
-      end_for
-    fi
-
-  end_function
-  handle_return
-}
-
 handle_cell() {
   local cell_path=$1
 
@@ -472,47 +402,37 @@ handle_cell() {
     local omni_log_job_id job_id_log=${home_job_path:-$HOME/.simpleton/job-log}
 
     cell_path=$(unrealpath $cell_path) || {
-      log_fatal "Failed to resolve path for $cell_path"
+      log_fatal "Invalid cell path: $cell_path"
       fail1
       }
 
-    local next cell_command
-    if [[ "${parameter_questions:-}" ]]; then
-
-      command_requires_resolved_dims=f \
-      trunk_changed=f \
-      command_allows_logs=f \
-        switch_context $cell_path || fail
-
-      if [[ -e $path_to_commands/all.info ]]; then
-        source $path_to_commands/all.info || fail
+    if [[ ! -d $cell_path/.dna ]]; then
+      if [[ $recursive_command == t ]]; then
+        local folder folders=$(find1 $cell_path -type d -not -name '.*') || fail
+        begin_for folder in $folders; doo
+          handle_cell $folder || fail
+        end_for
+      else
+        log_verbose "Skipping $cell_path because it is not a cell"
       fi
-      for cell_command in ${commands[*]}; do
-        command_path=$path_to_commands/$cell_command
-        if [[ -e $command_path.info ]]; then
-          source $command_path.info || fail
-        fi
-      done
-
-      local p
-      for p in ${parameter_questions[*]}; do
-        show_parameter_help $p  || fail
-      done
-    elif (( ${#commands[*]} == 0 )); then
-      show_cell_help $cell_path || fail
     else
-      begin_for cell_command in ${commands[*]}; doo
-        if (( help_depth > 0 )); then
-          show_help_for_command $cell_command || fail
-        else
-          handle_command $cell_command || fail
-        fi
-        first_command=f
-      end_for
+      if [[ $first_cell == t ]]; then
+        execute_commands $cell_path ${commands[*]} || fail
+      else
+        fork execute_commands $cell_path ${commands[*]} || fail
+      fi
+      first_cell=f
     fi
 
   end_function
   handle_return
+}
+
+reset_flags() {
+  trace_var_always=f
+  log=info
+  show_debug_id=n
+  recursive_command=f
 }
 
 top_level() {
@@ -523,51 +443,56 @@ top_level() {
     local cell_path \
       path_to_commands=$SIMPLETON_REPO/command \
       first_command=t \
+      first_cell=t \
       multi_cell=f \
       multi_commands=f \
-      commands=() \
       clean_cells=${clean_cells:-${clean_cell:-}} \
+
+    command="$original_cmd" omni_log_init || fail
 
     if [[ "$clean_cells" ]]; then
       clean_cells=" ${clean_cells} "
     fi
 
-    if [[ "${parameter_questions:-}" ]]; then
-      : ${help_depth:=2}
-    else
-      : ${help_depth:=0}
-    fi
+    get_help_depth || fail
 
-    if [[ "${cells:-}" ]]; then
-      cells=( $cells )
-    elif [[ "${cell:-}" ]]; then
-      cells=( $cell )
-    fi
+    local current_parameter_index=0
+    begin_while true; doo
 
-    command="$original_cmd" omni_log_init || fail
+      cells=() \
+      commands=() \
 
-    scan_commands || fail
+      reset_flags
 
-    if (( ${#commands[*]} > 1 )); then
-      multi_commands=t
-    fi
+      get_commands_and_cells || fail
+      if [[ ! "$commands" ]]; then
+        break
+      fi
 
-    if [[ ! "${cells:-}" && ! "${commands:-}" && ! "${parameter_questions:-}" ]]; then
-      show_usage
-      succeed
-    fi
+      if (( ${#commands[*]} > 1 )); then
+        multi_commands=t
+      fi
 
-    if [[ ! "${cells:-}" ]]; then
-      cells=( . )
-    fi
+      if (( ${#cells[*]} > 1 )); then
+        multi_cell=t
+      fi
 
-    if (( ${#cells[*]} > 1 )); then
-      multi_cell=t
-    fi
+      if [[ ! "${cells:-}" ]]; then
+        if [[ ! "${commands:-}" && ! "${parameter_questions:-}" || $help_depth -gt 0 ]]; then
+          show_usage
+          succeed
+        fi
+      fi
 
-    begin_for cell_path in ${cells[*]}; doo
-      handle_cell $cell_path || fail
-    end_for
+      if [[ ! "${cells:-}" ]]; then
+        cells=( . )
+      fi
+
+      begin_for cell_path in ${cells[*]}; doo
+        handle_cell $cell_path || fail
+      end_for
+
+    end_while
 
   end_function
 
diff --git a/command/mock b/command/mock
--- a/command/mock
+++ b/command/mock
@@ -31,20 +31,6 @@ mock_leaf() {
   handle_return
 }
 
-mock_branch() {
-  begin_function
-    local branch_cells=$(find1 $cell_path -name '*:*') || fail
-    local branch_cell
-    begin_for branch_cell in $branch_cells; doo
-      cell_path=$branch_cell
-      anchor_dims=
-      switch_context $cell_path || fail
-      mock_cell || fail
-    end_for
-  end_function
-  handle_return
-}
-
 mock_cell() {
   begin_function
     log_info "Checking $short_cell"
@@ -56,10 +42,26 @@ mock_cell() {
   handle_return
 }
 
+mock_branch() {
+  begin_function
+    local branch_cells=$(find1 $cell_path -name '*:*') || fail
+    local branch_cell
+    begin_for branch_cell in $branch_cells; doo
+      cell_path=$branch_cell
+      #anchor_dims=
+      #switch_context $cell_path || fail
+      load_branch_info $cell_path || fail
+      find_seed_path $cell_path || fail
+      mock_cell || fail
+    end_for
+  end_function
+  handle_return
+}
+
 mock_command() {
   begin_function
 
-    local mock=${mock:-}
+    local mock=${mock:-} ignore_missing=${ignore_missing:-t}
 
     if [[ ! "$mock" ]]; then
       if [[ -d $mock_path ]]; then
@@ -77,18 +79,22 @@ mock_command() {
     fi
 
     if [[ $mock != f && ! -d $mock_path/$mock ]]; then
-      log_fatal "Invalid mock: $mock"
-      if [[ -d $mock_path ]]; then
-        local options=( $(find1 $mock_path -printf "%f") )
-        if (( ${#options[*]} > 0 )); then
-          log_fatal "You must choose one of these mocks: ${options[*]} or use f to unmock this cell, or just leave the mock field blank to get a menu"
+      if [[ $ignore_missing == t ]]; then
+        log_verbose "Mock doesn't exist for this folder, skipping."
+      else
+        log_fatal "Invalid mock: $mock"
+        if [[ -d $mock_path ]]; then
+          local options=( $(find1 $mock_path -printf "%f") )
+          if (( ${#options[*]} > 0 )); then
+            log_fatal "You must choose one of these mocks: ${options[*]} or use f to unmock this cell, or just leave the mock field blank to get a menu"
+          else
+            log_fatal "There are no mocks available for this cell. To create one, create a folder here: $mock_path"
+          fi
         else
           log_fatal "There are no mocks available for this cell. To create one, create a folder here: $mock_path"
         fi
-      else
-        log_fatal "There are no mocks available for this cell. To create one, create a folder here: $mock_path"
+        fail1
       fi
-      fail1
     fi
 
     mock_cell || fail
diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -1132,7 +1132,6 @@ load_dna_contents_update_cell() {
     get_short_cell
 
     needs_update= \
-    top_level_command=f \
     fork execute_command "$cell_path" update || fail
 
     if [[ ! -f "$file" ]]; then
@@ -1542,6 +1541,7 @@ load_dna_contents() {
 
 get_short_cell() {
   short_cell=${cell_path#/work/*/}
+  debug_return_vars=short_cell
 }
 
 build_context_dna() {
@@ -1727,7 +1727,7 @@ init_context() {
   handle_return
 }
 
-branch_local_vars='branch_dims branch_members branch_hashes branch_dim_count trunk_cell short_cell'
+branch_local_vars='branch_dims branch_members branch_hashes branch_dim_count trunk_cell short_cell prev_branch_info_cell'
 load_branch_info() {
   local cell_path=${1:-$cell_path}
 
@@ -2616,48 +2616,53 @@ switch_context() {
         fail1
       fi
 
-      if [[ "$clean_cells" ]]; then
-        local cell_to_clean
-        begin_for cell_to_clean in $clean_cells; doo
-          if [[ /$cell_path/ == */$cell_to_clean/* ]]; then
-            if [[ -e $cyto_path ]]; then
-              log_info "Cleaning cell ${cell_to_clean#/work/*/} => $short_cell..."
-              rm -rf $cyto_path || fail
-            else
-              log_info "Cell already clean: $cell_to_clean => $short_cell"
+      if [[ $command_requires_cell == t ]]; then
+        if [[ "$clean_cells" ]]; then
+          local cell_to_clean
+          begin_for cell_to_clean in $clean_cells; doo
+            if [[ /$cell_path/ == */$cell_to_clean/* ]]; then
+              if [[ -e $cyto_path ]]; then
+                log_info "Cleaning cell ${cell_to_clean#/work/*/} => $short_cell..."
+                rm -rf $cyto_path || fail
+              else
+                log_info "Cell already clean: $cell_to_clean => $short_cell"
+              fi
+              remove_word_from_string clean_cells "$cell_to_clean" 
+              break
             fi
-            remove_word_from_string clean_cells "$cell_to_clean" 
-            break
-          fi
-        end_for
+          end_for
+        fi
       fi
 
       context_path=$cyto_path/context
       init_context || fail
 
       seed_path=
-      if [[ ! -f $context_path ]]; then
-        build_cyto $cell_path || fail
+      if [[ $command_requires_cell == t ]]; then
+        if [[ ! -f $context_path ]]; then
+          build_cyto $cell_path || fail
+        fi
+        source $context_path || fail
       fi
 
-      source $context_path || fail
+      if [[ $command_requires_cell == t ]]; then
+        if [[ $command_requires_resolved_dims == t ]]; then
+          setup_dims || fail
+        fi
+        load_child_dims || fail
 
-      if [[ $command_requires_resolved_dims == t ]]; then
-        setup_dims || fail
-      fi
-      load_child_dims || fail
-
-      local problem_found=f
-      broken_link_check || fail
-      if [[ $problem_found == t ]]; then
-        if [[ $rebuild_attempted == f ]]; then
-          log_verbose "Problem found, rebuilding context"
-          rm -rf $cyto_path/up* $context_path* || fail
-          rebuild_attempted=t
-          continue
-        else
-          log_fatal "Context rebuild failed to resolve problem"
-          fail1
+        local problem_found=f
+        broken_link_check || fail
+        if [[ $problem_found == t ]]; then
+          if [[ $rebuild_attempted == f ]]; then
+            log_verbose "Problem found, rebuilding context"
+            rm -rf $cyto_path/up* $context_path* || fail
+            rebuild_attempted=t
+            continue
+          else
+            log_fatal "Context rebuild failed to resolve problem"
+            fail1
+          fi
         fi
       fi
 
@@ -2672,26 +2677,6 @@ switch_context() {
   fi
 
   return 0
-}
-
-execute_command_internal_setup_params() {
-  begin_function
-    if [[ "${parameter_questions:-}" ]]; then
-      if [[ "$multi_commands" == t ]]; then
-        log_fatal "To use help, only choose one command"
-        fail1
-      fi
-      local p i pi 
-      begin_for pi in ${!parameter_questions[*]}; doo
-        p=${parameter_questions[$pi]}
-        if [[ " ${parameter_delayed_questions:-} " == *\ $p\ * ]]; then
-          continue
-        fi
-        show_parameter_help $p || fail
-      end_for
-    fi
-  end_function
-  handle_return
 }
 
 cell_open_log_file() {
@@ -2922,134 +2907,14 @@ show_dimensions() {
   handle_return
 }
 
-show_parameter_help() {
-  local name=$1 indent=${indent:-0}
-  begin_function
-
-    local found=f choices=()
-
-    # TODO this should go away and get replaced with props
-    begin_for i in ${!parameter_names[*]}; doo
-      if [[ "${parameter_names[$i]}" == $name ]]; then
-        out_wrap "Parameter: $name"
-        (( indent += 2 ))
-
-        if [[ -v parameter_descriptions[$i] && "${parameter_descriptions[$i]}" ]]; then
-          out "${parameter_descriptions[$i]}"
-        fi
-
-        if [[ -v parameter_defaults[$i] && "${parameter_defaults[$i]}" ]]; then
-          out_wrap "default: ${parameter_defaults[$i]}"
-        fi
-
-        local choices=
-        if [[ -v parameter_choices[$i] && "${parameter_choices[$i]}" ]]; then
-          eval "choices=( ${parameter_choices[$i]} )"
-        elif [[ -v ${name}_choices ]]; then
-          eval "choices=${name}_choices"
-        elif function_exists ${name}_get_choices; then
-          ${name}_get_choices || fail
-        fi
-        if [[ "$choices" ]]; then
-          out_wrap "choices: ${choices[*]}"
-        fi
-        found=t
-        break
-      fi
-    end_for
-
-    if [[ $found == f ]]; then
-      local dim_type dim
-      begin_for dim_type in trunk_dims sub_dims control_props data_props; doo
-        local -n dims=$dim_type
-        begin_for dim in ${dims[*]}; doo
-          if [[ $dim == $name ]]; then
-            show_dimension $dim || fail
-            found=t
-            break
-          fi
-        end_for
-      end_for
-    fi
-
-    if [[ $found != t ]]; then
-      log_warn "No description found for parameter $name" || fail
-    fi
-
-  end_function
-  handle_return
-}
-
-execute_command_internal() {
-
-  local log_vars='cell_path' \
-    log_show_vars='short_cell cell_command' 
-  begin_function_hi
-
-    local omni_log_fork_parent=${omni_log_fork_parent:-}-${omni_log_fork_child:-1} \
-      omni_log_fork_child=0
-    omni_log_fork_parent=${omni_log_fork_parent#-}
-
-    if [[ "${localize_dims:-}" ]]; then
-      eval "local $localize_dims" || fail
-    fi
-
-    if [[ $top_level_command == f ]]; then
-      unset anchor_dims
-    else
-      unset default_anchor_dims
-    fi
-
-    if [[ $command_requires_cell == t ]]; then
-      switch_context $cell_path || {
-        log_fatal "Context failed to load for $short_cell"
-        fail1
-      }
-    fi
-
-    if [[ $disable_log == t ]]; then
-      log_debug "Logging disabled." || fail
-    else
-      execute_command_log_prep || fail
-    fi
-
-    execute_command_internal_setup_params || fail
-
-    # This is in this function twice, because it changes after switch_context
-    if [[ "${localize_dims:-}" ]]; then
-      eval "local $localize_dims" || fail
-    fi
-
-    if [[ " ${command_history:-}" == *" $cell_command $short_cell "* ]]; then
-      log_fatal "Circular dependency found: arrived at $cell_command $short_cell a second time."
-      fail1
-    fi
-
-    command_history+="$cell_command $short_cell "
-
-    #if [[ ${cell_is_leaf:-t} == t || $show_branches == t ]]; then
-    #  log_info "Executing cell command: $short_cell $cell_command" || fail
-    #else
-    #  log_verbose "Executing cell command: $short_cell $cell_command" || fail
-    #fi
-
-    local command_function=${cell_command//-/_}_command
-    if function_exists $command_function; then
-      $command_function || fail
-    else
-      log_fatal "Missing command function $command_function which should be in $command_path"
-      fail1
-    fi
-
-  end_function
-  handle_return
-}
-
+# Inputs:
+#   $1    cell_path   should be real path
+#   $2    command
 execute_command() {
-  local cell_path=$(realpath $1) cell_command=$2 \
-    log_show_vars='^cell_path cell_command' \
+  local cell_path=$1 cell_command=$2 \
+    log_show_vars='short_cell cell_command' \
 
-  begin_function
+  begin_function_hi
 
     case $cell_command in
       dim-*|up-*)
@@ -3065,23 +2930,6 @@ execute_command() {
       ;;
     esac
 
-    local anchor_dims=${anchor_dims:-} \
-      disable_log=${disable_log:-} \
-      logging_to_file=${logging_to_file:-} \
-      omni_log_job_id=${omni_log_job_id:-} \
-      omni_log_fork_id=${omni_log_fork_id:-} \
-      previous_fork_id=${previous_fork_id:-} \
-      job_path=${job_path:-} \
-      log_path=${log_path:-} \
-      current_job_path=${current_job_path:-} \
-      job_start_time \
-      background_log \
-      running_job_path \
-      recursive_command=${recursive_command:-${recursive:-f}} \
-      short_cell
-
-    get_short_cell
-
     log_verbose "Executing cell command: $short_cell $cell_command" || fail
 
     if [[ ! -e "$cell_path" ]]; then
@@ -3091,10 +2939,11 @@ execute_command() {
       }
     fi
 
-    command_path=$path_to_commands/$cell_command \
-    command_requires_resolved_dims=f \
-    command_allows_logs=f \
-    command_requires_cell=t \
+    local \
+      command_path=$path_to_commands/$cell_command \
+      command_requires_resolved_dims=f \
+      command_allows_logs=f \
+      command_requires_cell=t \
 
     if [[ -e $path_to_commands/all.info ]]; then
       source $path_to_commands/all.info || fail
@@ -3108,6 +2957,15 @@ execute_command() {
 
     source $command_path || fail
 
+    if [[ $command_requires_cell == f ]]; then
+      command_requires_resolved_dims=f
+    fi
+
+    if [[ ! -e $cell_path/.dna && $command_requires_cell == t ]]; then
+      log_fatal "Invalid cell: $cell_path"
+      fail1
+    fi
+
     if [[ ! "${disable_log:-}" ]]; then
       if [[ $command_allows_logs == t ]]; then
         disable_log=f
@@ -3116,31 +2974,105 @@ execute_command() {
       fi
     fi
 
+    if [[ $disable_log == t ]]; then
+      log_debug "Logging disabled." || fail
+    else
+      execute_command_log_prep || fail
+    fi
+
+    if [[ $disable_log == f ]]; then
+      : ${omni_log_fork_child:=0}
+      (( omni_log_fork_child++ ))
+      previous_log_pos=$omni_log_pos
+      cell_open_log_file || fail
+      (( previous_log_pos++ ))
+    fi
+
+    local omni_log_fork_parent=${omni_log_fork_parent:-}-${omni_log_fork_child:-1} \
+      omni_log_fork_child=0
+    omni_log_fork_parent=${omni_log_fork_parent#-}
+
+    if [[ " ${command_history:-}" == *" $cell_command $short_cell "* ]]; then
+      log_fatal "Circular dependency found: arrived at $cell_command $short_cell a second time."
+      fail1
+    fi
+
+    command_history+="$cell_command $short_cell "
+
+    local command_function=${cell_command//-/_}_command
+    if function_exists $command_function; then
+      $command_function || fail
+    else
+      log_fatal "Missing command function $command_function which should be in $command_path"
+      fail1
+    fi
+
+    if [[ $disable_log == f ]]; then
+      cell_close_log_file || fail
+    fi
+
+  end_function
+  handle_return
+}
+
+# inputs:
+#   $1    cell_path   should be real path
+#   $2... commands
+execute_commands() {
+  local cell_path=$1; shift
+  local commands=$* command
+  begin_function
+
+    local anchor_dims=${anchor_dims:-} \
+      disable_log=${disable_log:-} \
+      logging_to_file=${logging_to_file:-} \
+      omni_log_job_id=${omni_log_job_id:-} \
+      omni_log_fork_id=${omni_log_fork_id:-} \
+      previous_fork_id=${previous_fork_id:-} \
+      job_path=${job_path:-} \
+      log_path=${log_path:-} \
+      current_job_path=${current_job_path:-} \
+      job_start_time \
+      background_log \
+      running_job_path \
+      recursive_command=${recursive_command:-${recursive:-f}} \
+      short_cell \
+      needs_context_reload=f \
+      top_level_command=${top_level_command_next:-t} \
+
+    # so top_level_command is set to t throughout this function, yet if it's called again, it will
+    #   be set to f
+    top_level_command_next=f
+
+    get_short_cell
+    eval "local $branch_local_vars" || fail
     load_branch_info || fail
 
-    local should_fork=f
-#    if [[ ${top_level_command:=t} == t ]]; then
-#      should_fork=f
-#    elif [[ "${prev_trunk_cell:-}" == "$trunk_cell" ]]; then
-#      should_fork=f
-#    fi
-    
-    # forking should be handled outside of execute_command, to improve performance
-    if [[ $should_fork == t ]]; then
-      fork execute_command_internal || fail_later
+    if [[ $top_level_command == f ]]; then
+      unset anchor_dims
     else
-      if [[ $disable_log == f ]]; then
-        : ${omni_log_fork_child:=0}
-        (( omni_log_fork_child++ ))
-        previous_log_pos=$omni_log_pos
-        cell_open_log_file || fail
-        (( previous_log_pos++ ))
-      fi
-      execute_command_internal || fail_later
-      if [[ $disable_log == f ]]; then
-        cell_close_log_file || fail
-      fi
+      unset default_anchor_dims
     fi
+
+    switch_context $cell_path || {
+      log_fatal "Context failed to load for $short_cell"
+      fail1
+    }
+
+    if [[ "${localize_dims:-}" ]]; then
+      eval "local $localize_dims" || fail
+    fi
+
+    begin_for command in $commands; doo
+      execute_command $cell_path $command || fail
+      if [[ $needs_context_reload == t ]]; then
+        switch_context $cell_path || {
+          log_fatal "Context failed to load for $short_cell"
+          fail1
+        }
+        needs_context_reload=f
+      fi
+    end_for
 
   end_function
   handle_return
