.

diff --git a/bin/cell b/bin/cell
--- a/bin/cell
+++ b/bin/cell
@@ -141,10 +141,29 @@ clean_cell() {
     fi
 
     local x
-    begin_for x in $cell_path/!(*.dna|.member|.|..); doo
-      log_verbose "Removing ${x#$cell_path/}"
-      rm -rf $x &>/dev/null
-    end_for
+    case $kind in
+      all)
+        begin_for x in $cell_path/!(*.dna|.member|.|..); doo
+          log_verbose "Removing ${x#$cell_path/}"
+          rm -rf $x &>/dev/null
+        end_for
+      ;;
+      cyto)
+        if [[ -e $cell_path/.cyto ]]; then
+          rm -rf $cell_path/.cyto || fail
+        fi
+      ;;
+      data)
+        begin_for x in $cell_path/!(*.dna|.cyto|.member|.|..); doo
+          log_verbose "Removing ${x#$cell_path/}"
+          rm -rf $x &>/dev/null
+        end_for
+      ;;
+      *)
+        log_fatal "Invalid clean kind ($kind). Must be one of: cyto, data, all"
+        fail1
+      ;;
+    esac
 
   end_function
   handle_return
@@ -175,7 +194,8 @@ handle_command() {
             log_fatal "Not a valid cell: $cell_path"
             fail1
           fi
-          clean_depth=${clean_depth:-1}
+          : ${clean_depth:=1}
+          : ${kind:=all}
           clean_cell $bottom_cell || fail
         ;;
         *)
diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -773,6 +773,30 @@ make_or_load_context_expand() {
   handle_return
 }
 
+load_delegated_dims() {
+  begin_function
+    local up_name original_cell=$cell_path
+    if [[ "${up:-}" ]]; then
+      begin_for up_name in ${up[*]}; doo
+        local up_name2=${up_name//-/_}
+        if [[ -v up_${up_name2}_choices ]]; then
+          local choice choices_var=up_${up_name2}_choices
+          local -n choices=$choices_var
+          begin_for choice in ${choices[*]}; doo
+            local choice2=${choice//-/_}
+            local path_var=up_${up_name2}_choices_${choice2}_path
+            local -n path=$path_var
+            # recursive
+            switch_context $path || fail
+          end_for
+        fi
+      end_for
+      switch_context $original_cell || fail
+    fi
+  end_function
+  handle_return
+}
+
 make_or_load_context() {
   local log_vars=cell_path log_show_vars=short_cell
   begin_function_hi
@@ -805,6 +829,9 @@ make_or_load_context() {
       log_vars=dna_path log_fatal "dna not found"
       fail1
     fi
+
+    delegated_dims=()
+    load_delegated_dims $cell_path || fail
 
     make_or_load_context_dims || fail
     make_or_load_context_expand || fail
@@ -1061,6 +1088,33 @@ make_cyto_up() {
   handle_return
 }
 
+git_commit_check() {
+  begin_function
+
+    local status_file=$status_path/git-commit-when-built \
+      changed=f \
+      repo_path=$(realpath $dna_path)
+    local new_hash=$(git $repo_path rev-list HEAD --max-count=1)
+
+    if [[ ! -f $status_file ]]; then
+      changed=t
+    else
+      local old_hash=$(<$status_file)
+      if [[ "$old_hash" != "$new_hash" ]]; then
+        changed=t
+      fi
+    fi
+
+    if [[ $changed == t ]]; then
+      rm -rf $cyto_path || fail
+      mkdir -p $status_path || fail
+      echo "$new_hash" >$status_file || fail
+    fi
+
+  end_function
+  handle_return
+}
+
 switch_context() {
 
   if [[ "${last_context_loaded:-}" != $cell_path ]]; then
@@ -1079,6 +1133,8 @@ switch_context() {
       init_context || fail
 
       if [[ $can_create_cyto == t ]]; then
+        git_commit_check || fail
+
         if [[ ! -e $cyto_path ]]; then
           mkdir $cyto_path || fail
         fi
