.

diff --git a/bin/cell b/bin/cell
--- a/bin/cell
+++ b/bin/cell
@@ -304,10 +304,12 @@ handle_cell() {
 
     local omni_log_job_id job_id_log=${home_job_path:-$HOME/.simpleton/job-log}
 
-    cell_path=$(unrealpath $cell_path) || {
-      log_fatal "Invalid cell path: $cell_path"
-      fail1
-      }
+    if [[ -e "$cell_path" ]]; then
+      cell_path=$(unrealpath $cell_path) || {
+        log_fatal "Invalid cell path: $cell_path"
+        fail1
+        }
+    fi
 
     if (( ${#commands[*]} > 0 )); then
       if [[ $multi_cell == f ]]; then
@@ -386,13 +388,19 @@ top_level() {
           fi
         fi
 
-        local potential_cell=$(realpath .)
+        local potential_cell=$(realpath .) seed_path=
         if [[ $potential_cell == /seed/* ]]; then
+          seed_path=$potential_cell
           potential_cell=/work${potential_cell#/seed}
         fi
         while [[ $potential_cell == */.* && $potential_cell == /*/*/* ]]; do
           potential_cell=${potential_cell%/*}
         done
+        if [[ "$seed_path" ]]; then
+          while [[ $seed_path == */.* && $seed_path == /seed/*/* ]]; do
+            seed_path=${seed_path%/*}
+          done
+        fi
 
         cells=( $potential_cell )
       fi
diff --git a/command/dim-add b/command/dim-add
--- a/command/dim-add
+++ b/command/dim-add
@@ -118,7 +118,7 @@ dim_add_get_next_ord() {
 dim_add_command() {
   begin_function
 
-    local shared_dim_folder= seed_path \
+    local shared_dim_folder= seed_path=${seed_path:-} \
       type=${type:-trunk_dim} \
       create_other=${create_other:-f} \
       create_each=${create_each:-f} \
@@ -145,8 +145,13 @@ dim_add_command() {
       ;;
     esac
 
-    load_branch_info || fail
-    switch_context $cell_path || fail
+    if [[ -e $cell_path/.dna && $cell_path == /work/* ]]; then
+      load_branch_info || fail
+      switch_context $cell_path || fail
+    elif [[ ! "${seed_path:-}" || ! -e $seed_path ]]; then
+      log_fatal "Couldn't find seed path. You must either run this command in a work cell, or in a seed cell"
+      fail1
+    fi
     dim_add_find_shared_dim || fail
 
     local dims=${dims:-${dim:-}} dim
diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -1627,16 +1627,18 @@ execute_command() {
 
     strong_log=t log_verbose "Executing cell command: $short_cell $cell_command" || fail
 
-    if [[ ! -e "$cell_path" ]]; then
-      plant_seed $cell_path || {
-        log_fatal "Not a cell: $cell_path"
-        fail1
-      }
-    fi
+    if [[ $command_requires_cell == t ]]; then
+      if [[ ! -e "$cell_path" ]]; then
+        plant_seed $cell_path || {
+          log_fatal "Not a cell: $cell_path"
+          fail1
+        }
+      fi
 
-    if [[ ! -e $cell_path/.dna && $command_requires_cell == t ]]; then
-      log_fatal "Invalid cell: $cell_path"
-      fail1
+      if [[ ! -e $cell_path/.dna ]]; then
+        log_fatal "Invalid cell: $cell_path"
+        fail1
+      fi
     fi
 
     if [[ $command_allows_logs == t ]]; then
