.

diff --git a/bin/cell b/bin/cell
--- a/bin/cell
+++ b/bin/cell
@@ -121,35 +121,26 @@ handle_command() {
           fi
         ;;
         *)
-          next=
-          if [[ $((i+1)) -lt ${#commands[*]} ]]; then
-            next=${commands[$((i+1))]}
+          get_bottom_cell $cell_path || fail
+          if [[ "$bottom_cell" ]]; then
+            cell_path=$bottom_cell
           fi
-          if [[ $next == --help || $next == -h || $next == help ]]; then
-            show_help_for_command $command
-            (( i++ ))
-          else
-            get_bottom_cell $cell_path || fail
-            if [[ "$bottom_cell" ]]; then
-              cell_path=$bottom_cell
-            fi
-            local omni_log_job_id job_id_log=${home_job_path:-$HOME/.simpleton/job-log}
+          local omni_log_job_id job_id_log=${home_job_path:-$HOME/.simpleton/job-log}
 
-            if [[ ! -d ${job_id_log%/*} ]]; then
-              mkdir -p ${job_id_log%/*} || fail
-            fi
+          if [[ ! -d ${job_id_log%/*} ]]; then
+            mkdir -p ${job_id_log%/*} || fail
+          fi
 
-            local needs_update=${needs_update:-} \
-              command_to_log="${original_cmd#* }" \
-              top_level_command=t \
-              saved_command=$command
+          local needs_update=${needs_update:-} \
+            command_to_log="${original_cmd#* }" \
+            top_level_command=t \
+            saved_command=$command
 
-            local command_successful=f
-            execute_command $cell_path $command || fail
-            if [[ $command_successful == f ]]; then
-              log_error "Command failed: $command"
-              fail1
-            fi
+          local command_successful=f
+          execute_command $cell_path $command || fail
+          if [[ $command_successful == f ]]; then
+            log_error "Command failed: $command"
+            fail1
           fi
         ;;
       esac
@@ -265,7 +256,7 @@ show_dimensions() {
 
         eval "value=all ${dim}_expand" &>/dev/null
         if [[ ! "$problem" ]]; then
-          out "    members: ${values[*]}"
+          out "    choices: ${values[*]}"
         fi
 
         if [[ -v ${dim}_examples ]]; then
