Fix upstream promotion

diff --git a/bin/cell b/bin/cell
--- a/bin/cell
+++ b/bin/cell
@@ -13,272 +13,272 @@ source $SIMPLETON_REPO/lib/omni-navigator || exit 1
 source $SIMPLETON_REPO/lib/cell-lib || exit 1
 
 handle_command() {
-local subject_type=$0
-subject_type=${subject_type##*/}
-local commands=( "$@" )
-local cells=${cells:-${cell:-.}}
-local multi_cell=f
-[[ "$cells" == *\ * ]] && multi_cell=t
+  local subject_type=$0
+  subject_type=${subject_type##*/}
+  local commands=( "$@" )
+  local cells=${cells:-${cell:-.}}
+  local multi_cell=f
+  [[ "$cells" == *\ * ]] && multi_cell=t
 
-begin_function_flat
+  begin_function_flat
 
-  debugger_init || fail
-  command="$original_cmd" omni_log_init || fail
-  omni_navigator_init || fail
+    debugger_init || fail
+    command="$original_cmd" omni_log_init || fail
+    omni_navigator_init || fail
 
-  local cell_path
-  begin_for cell_path in $cells; doo
+    local cell_path
+    begin_for cell_path in $cells; doo
 
-    cell_path=$(unrealpath $cell_path) || {
-      fatal "Failed to resolve path for $cell_path"
-      fail1
-      }
-
-    local command i next
-    begin_for ((i=0; i<${#commands[*]}; i++)); doo
-
-      command=${commands[$i]}
-
-      if [[ "$cell_path" == */.dna/sub/* && $command == update ]]; then
-        fatal "Don't run update cell commands within sub cell dna folders. Run in the real cell folders."
+      cell_path=$(unrealpath $cell_path) || {
+        fatal "Failed to resolve path for $cell_path"
         fail1
-      fi
+        }
 
-      if [[ $command == */* && -d $command/.dna ]]; then
-        cell_path=$(unrealpath $command/.dna)
-        continue
-      fi
+      local command i next
+      begin_for ((i=0; i<${#commands[*]}; i++)); doo
 
-      case $command in
-        help|?|--help)
-          handle_help_command "${commands[@]:$((i+1))}"
-          succeed
-        ;;
-        shell)
-          export prompt_name='cell shell'
-          bash --init-file <(
-            cat \
-            /etc/profile \
-            $SIMPLETON_REPO/lib/bash-lib \
-            $SIMPLETON_REPO/lib/omni-log \
-            $SIMPLETON_REPO/lib/omni-navigator \
-            $SIMPLETON_REPO/lib/bash-debugger \
-            $SIMPLETON_REPO/lib/cell-lib \
-            $SIMPLETON_REPO/lib/cell-shell-prep \
-            )
-        ;;
-        clean)
-          get_bottom_cell $cell_path || fail
-          if [[ ! "$bottom_cell" ]]; then
-            fatal "Not a valid cell: $cell_path"
-            fail1
-          fi
-          local cell_path=$bottom_cell
-          log_info "Cleaning $cell_path..." 
-          local clean_file=$cell_path/.dna/op/clean.bash
-          if [[ -f $clean_file ]]; then
-            source $clean_file || fail
-            clean || fail
-          else
-            local dir
-            begin_for dir in out build .dim; doo
-              if [[ -d $cell_path/$dir ]]; then
-                rm -rf $cell_path/$dir &>/dev/null
-              fi
-            end_for
-          fi
-          if [[ -e "$cell_path/.cyto" ]]; then
-            rm -rf $cell_path/.cyto || fail
-            log_info "Cleaned."
-          else
-            log_info "Already clean."
-          fi
-        ;;
-        *)
-          next=
-          if [[ $((i+1)) -lt ${#commands[*]} ]]; then
-            next=${commands[$((i+1))]}
-          fi
-          if [[ $next == --help || $next == -h || $next == help ]]; then
-            show_help_for_command $command
-            fail1
-          else
+        command=${commands[$i]}
+
+        if [[ "$cell_path" == */.dna/sub/* && $command == update ]]; then
+          fatal "Don't run update cell commands within sub cell dna folders. Run in the real cell folders."
+          fail1
+        fi
+
+        if [[ $command == */* && -d $command/.dna ]]; then
+          cell_path=$(unrealpath $command/.dna)
+          continue
+        fi
+
+        case $command in
+          help|?|--help)
+            handle_help_command "${commands[@]:$((i+1))}"
+            succeed
+          ;;
+          shell)
+            export prompt_name='cell shell'
+            bash --init-file <(
+              cat \
+              /etc/profile \
+              $SIMPLETON_REPO/lib/bash-lib \
+              $SIMPLETON_REPO/lib/omni-log \
+              $SIMPLETON_REPO/lib/omni-navigator \
+              $SIMPLETON_REPO/lib/bash-debugger \
+              $SIMPLETON_REPO/lib/cell-lib \
+              $SIMPLETON_REPO/lib/cell-shell-prep \
+              )
+          ;;
+          clean)
             get_bottom_cell $cell_path || fail
-            cell_path=$bottom_cell
-            local omni_log_job_id job_id_log=${home_job_path:-$HOME/.simpleton/job-log}
-
-            if [[ ! -d ${job_id_log%/*} ]]; then
-              mkdir -p ${job_id_log%/*} || fail
+            if [[ ! "$bottom_cell" ]]; then
+              fatal "Not a valid cell: $cell_path"
+              fail1
             fi
+            local cell_path=$bottom_cell
+            log_info "Cleaning $cell_path..." 
+            local clean_file=$cell_path/.dna/op/clean.bash
+            if [[ -f $clean_file ]]; then
+              source $clean_file || fail
+              clean || fail
+            else
+              local dir
+              begin_for dir in out build .dim; doo
+                if [[ -d $cell_path/$dir ]]; then
+                  rm -rf $cell_path/$dir &>/dev/null
+                fi
+              end_for
+            fi
+            if [[ -e "$cell_path/.cyto" ]]; then
+              rm -rf $cell_path/.cyto || fail
+              log_info "Cleaned."
+            else
+              log_info "Already clean."
+            fi
+          ;;
+          *)
+            next=
+            if [[ $((i+1)) -lt ${#commands[*]} ]]; then
+              next=${commands[$((i+1))]}
+            fi
+            if [[ $next == --help || $next == -h || $next == help ]]; then
+              show_help_for_command $command
+              fail1
+            else
+              get_bottom_cell $cell_path || fail
+              cell_path=$bottom_cell
+              local omni_log_job_id job_id_log=${home_job_path:-$HOME/.simpleton/job-log}
 
-            local needs_update= \
-              command_to_log="$(realpath $cell_path)"
-            execute_command $cell_path $command || fail
-          fi
-        ;;
-      esac
+              if [[ ! -d ${job_id_log%/*} ]]; then
+                mkdir -p ${job_id_log%/*} || fail
+              fi
+
+              local needs_update= \
+                command_to_log="$(realpath $cell_path)"
+              execute_command $cell_path $command || fail
+            fi
+          ;;
+        esac
+
+      end_for
 
     end_for
 
-  end_for
-
-end_function_flat
-handle_return
+  end_function_flat
+  handle_return
 }
 
 handle_help_command() {
-local commands=( "$@" ) command first_command=t
-begin_function_flat
-  if [[ "${commands:-}" ]]; then
-    begin_for command in "${commands[@]}"; doo
-      show_help_for_command $command || fail
-      first_command=f
-    end_for
-  else
-    show_cell_help
-  fi
-end_function_flat
-handle_return
+  local commands=( "$@" ) command first_command=t
+  begin_function_flat
+    if [[ "${commands:-}" ]]; then
+      begin_for command in "${commands[@]}"; doo
+        show_help_for_command $command || fail
+        first_command=f
+      end_for
+    else
+      show_cell_help
+    fi
+  end_function_flat
+  handle_return
 }
 
 show_cell_help() {
-begin_function_flat
+  begin_function_flat
 
-  get_bottom_cell $cell_path || {
-    fatal "No cell found here: $cell_path"
-    fail1
-    }
-  cell_path=$bottom_cell \
-    cell_context_load || fail
-  if [[ $multi_cell == t ]]; then
-    out "===================================================================================================="
-    out "Cell: $short_cell"
-  fi
-
-  if [[ "${cell_description:-}" ]]; then
-    out "Description: $cell_description"
-  else
-    out "No description for this cell. Set cell_description variable in context file."
-  fi
-
-  local required=()
-
-  if [[ "${leaf_dims:-}" ]]; then
-    out "Dimension parameters:"
-    show_dimensions ${leaf_dims[*]} || fail
-  fi
-
-  if [[ "${sub_dims:-}" || "${props:-}" ]]; then
-    out "Other parameters:"
-    if [[ "${sub_dims:-}" ]]; then
-      show_dimensions ${sub_dims[*]} || fail
+    get_bottom_cell $cell_path || {
+      fatal "No cell found here: $cell_path"
+      fail1
+      }
+    cell_path=$bottom_cell \
+      cell_context_load || fail
+    if [[ $multi_cell == t ]]; then
+      out "===================================================================================================="
+      out "Cell: $short_cell"
     fi
-    if [[ "${props:-}" ]]; then
-      show_dimensions ${props[*]} || fail
+
+    if [[ "${cell_description:-}" ]]; then
+      out "Description: $cell_description"
+    else
+      out "No description for this cell. Set cell_description variable in context file."
     fi
-  fi
 
-  if [[ "${required:-}" ]]; then
-    out "Required parameters: ${required[*]}"
-  fi
+    local required=()
 
-end_function_flat
-handle_return
+    if [[ "${leaf_dims:-}" ]]; then
+      out "Dimension parameters:"
+      show_dimensions ${leaf_dims[*]} || fail
+    fi
+
+    if [[ "${sub_dims:-}" || "${props:-}" ]]; then
+      out "Other parameters:"
+      if [[ "${sub_dims:-}" ]]; then
+        show_dimensions ${sub_dims[*]} || fail
+      fi
+      if [[ "${props:-}" ]]; then
+        show_dimensions ${props[*]} || fail
+      fi
+    fi
+
+    if [[ "${required:-}" ]]; then
+      out "Required parameters: ${required[*]}"
+    fi
+
+  end_function_flat
+  handle_return
 }
 
 show_dimensions() {
-local dims=( $* ) dim description values is_required
-begin_for dim in ${dims[*]}; doo
-  eval "description=\$${dim}_description" || fail
-  out "  $dim: $description"
-  if type -t ${dim}_member_expand >/dev/null; then
-    values=
-    is_required=f
-    eval "value='' ${dim}_member_expand" &>/dev/null || is_required=t
-    if [[ "$values" ]]; then
-      if [[ "$values" == $empty_member ]]; then
-        out "    default: (empty)"
-      else
-        out "    default: ${values[*]}"
-      fi
-    elif [[ $is_required == f ]]; then
-      out "    optional"
-    else
-      required+=( $dim )
-    fi
-    if [[ -v ${dim}_examples ]]; then
-      eval "local examples=( \"\${${dim}_examples[@]}\" )"
-      local example_count=${#examples[*]} i index_string=
-      for ((i=0; i<example_count; i++)); do
-        if [[ example_count -gt 1 ]]; then
-          index_string=" #$((i+1))"
+  local dims=( $* ) dim description values is_required
+  begin_for dim in ${dims[*]}; doo
+    eval "description=\$${dim}_description" || fail
+    out "  $dim: $description"
+    if type -t ${dim}_member_expand >/dev/null; then
+      values=
+      is_required=f
+      eval "value='' ${dim}_member_expand" &>/dev/null || is_required=t
+      if [[ "$values" ]]; then
+        if [[ "$values" == $empty_member ]]; then
+          out "    default: (empty)"
+        else
+          out "    default: ${values[*]}"
         fi
-        out "    example$index_string: ${examples[$i]}"
-      done
+      elif [[ $is_required == f ]]; then
+        out "    optional"
+      else
+        required+=( $dim )
+      fi
+      if [[ -v ${dim}_examples ]]; then
+        eval "local examples=( \"\${${dim}_examples[@]}\" )"
+        local example_count=${#examples[*]} i index_string=
+        for ((i=0; i<example_count; i++)); do
+          if [[ example_count -gt 1 ]]; then
+            index_string=" #$((i+1))"
+          fi
+          out "    example$index_string: ${examples[$i]}"
+        done
+      fi
     fi
-  fi
-end_for
+  end_for
 }
 
 show_help_for_command() {
-local command=$1
-begin_function_flat
-  get_bottom_cell $cell_path || fail
-  if [[ "$bottom_cell" ]]; then
-    local cell_path=$bottom_cell
-    cell_context_load || fail
-    [[ $first_command == f ]] && out ''
-    out "command: $command"
-    if [[ -f $command_path/$command.info ]]; then
-      source $command_path/$command.info || fail
-      out "  $command_description"
-      local name description default default_string i
-      if [[ "${parameter_names:-}" ]]; then
-        out "parameters:"
-        begin_for ((i=0; i<${#parameter_names[*]}; i++)); doo
-          parameter="${parameter_names[$i]}"
-          description="${parameter_descriptions[$i]}"
-          default="${parameter_defaults[$i]}"
-          default_string=
-          [[ "$default" ]] && default_string=" default: $default"
-          out "  $parameter: $description$default_string"
-        end_for
+  local command=$1
+  begin_function_flat
+    get_bottom_cell $cell_path || fail
+    if [[ "$bottom_cell" ]]; then
+      local cell_path=$bottom_cell
+      cell_context_load || fail
+      [[ $first_command == f ]] && out ''
+      out "command: $command"
+      if [[ -f $command_path/$command.info ]]; then
+        source $command_path/$command.info || fail
+        out "  $command_description"
+        local name description default default_string i
+        if [[ "${parameter_names:-}" ]]; then
+          out "parameters:"
+          begin_for ((i=0; i<${#parameter_names[*]}; i++)); doo
+            parameter="${parameter_names[$i]}"
+            description="${parameter_descriptions[$i]}"
+            default="${parameter_defaults[$i]}"
+            default_string=
+            [[ "$default" ]] && default_string=" default: $default"
+            out "  $parameter: $description$default_string"
+          end_for
+        fi
       fi
     fi
-  fi
-end_function_flat
-handle_return
+  end_function_flat
+  handle_return
 }
 
 show_usage() {
-warn "Usage: ${0##*/} {command(s)}"
-local command
-if [[ -d "$cell_path/.cyto" ]]; then
-  warn "commands:"
-  for command in $(find1 $cell_path/.cyto/command | sort); do
-    if [[ -f $command ]]; then
-      source $command || fail
-    elif [[ -d $command ]]; then
-      local first_file=$(find1 $command -type f | sort -g | head -n 1)
-      if [[ "$first_file" ]]; then
-        source $first_file || fail
+  warn "Usage: ${0##*/} {command(s)}"
+  local command
+  if [[ -d "$cell_path/.cyto" ]]; then
+    warn "commands:"
+    for command in $(find1 $cell_path/.cyto/command | sort); do
+      if [[ -f $command ]]; then
+        source $command || fail
+      elif [[ -d $command ]]; then
+        local first_file=$(find1 $command -type f | sort -g | head -n 1)
+        if [[ "$first_file" ]]; then
+          source $first_file || fail
+        fi
       fi
-    fi
-    local command_name=${command##*/}
-    local command_description=describe_${command_name}
-    command_description=${!command_description:-}
-    if [[ "$command_description" ]]; then
-      warn "  $command_name $COL20$command_description"
-    else
-      warn "  $command_name ${COL20}Please add a description to this command in $command"
-    fi
-  done
-else
-  warn "  either run this command inside of a cell folder, or specify"
-  warn "  the cell variable with the path to a cell. "
-  warn "  example: cell cell=/some/cell update"
-fi
-return 0
+      local command_name=${command##*/}
+      local command_description=describe_${command_name}
+      command_description=${!command_description:-}
+      if [[ "$command_description" ]]; then
+        warn "  $command_name $COL20$command_description"
+      else
+        warn "  $command_name ${COL20}Please add a description to this command in $command"
+      fi
+    done
+  else
+    warn "  either run this command inside of a cell folder, or specify"
+    warn "  the cell variable with the path to a cell. "
+    warn "  example: cell cell=/some/cell update"
+  fi
+  return 0
 }
 
 handle_command "$@"
diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -22,6 +22,7 @@ show_branches=${show_branches:-f}
 downstream_cell_stack=( ) 
 
 disable_log=${disable_log:-f}
+export debug_ignore=${debug_ignore:- apad begin_fork change_log_file debug_start defer echo_align find1 fork get_new_reply_file get_shell_quoted_value load_log_vars log_debug log_error log_fatal log_info log_trace log_warn out parallel_loop pause_tee safe_link save_log_vars snapshot_source_location tee_output_to_log unpause_tee unrealpath untee_output write_to_log }
 
 setup_cyto_out() {
   local from=$1 to=$2
@@ -814,7 +815,7 @@ parallel_loop() {
 
     local size=${#array[*]}
     if (( size > 1 )); then
-      log_debug "looping over $size values$extra. body: $body2"
+      log_debug "Looping over $size values$extra. body: $body2"
     fi
 
     begin_for value in "${array[@]}"; doo
@@ -1195,7 +1196,7 @@ promote_dep_cell() {
 
     begin_for dep_dim in ${dims[*]}; doo
 
-      log_debug "Promoting $dep_dim"
+      log_debug "Considering promotion of $dep_dim"
 
       # is this dim already promoted?
       if [[ $already_promoted_path == */.dim/* ]]; then
@@ -1206,6 +1207,8 @@ promote_dep_cell() {
 
       local branch_dim found_branch_dim=f
       # upstream prep script can add extra_dims as needed
+      # branch_dims here is the full set of dims for the subject cell, whereas 
+      #   dims is the full set of dims for the upstream cell being promoted
       begin_for branch_dim in ${branch_dims[*]} ${extra_dims[*]}; doo
         if [[ $branch_dim == $dep_dim ]]; then
           log_debug "Found branch dim for $dep_dim"
@@ -1215,15 +1218,22 @@ promote_dep_cell() {
       end_for
 
       if [[ $found_branch_dim == f ]]; then
-        debug_start
-        if [[ $cell_is_leaf == t ]]; then
-          value= ${dim}_member_expand || return 0
-
-        fi
-
         # can't promote if dep dim doesn't exist on the branch 
-        log_debug "Dim not found on branch: $dep_dim"
-        break
+        log_debug "Upstream dim not found in base branch dims: $dep_dim"
+        if [[ $cell_is_leaf == t ]]; then
+          if type -t ${dep_dim}_member_expand >/dev/null; then
+            value= ${dep_dim}_member_expand 
+            if [[ "$values" ]]; then
+              log_debug "Found default for $dep_dim = $values"
+            fi
+          fi
+          if [[ ! "$values" ]]; then
+            log_fatal "Leaf cell was unable to resolve upstream dep to a leaf also. Missing dim $dep_dim"
+            fail1
+          fi
+        else
+          break
+        fi
       fi
 
       local dep_dim_var=d_$dep_dim
@@ -1231,10 +1241,9 @@ promote_dep_cell() {
 
       if [[ -v $dep_dim_var ]]; then
         values=${!dep_dim_var}
-      fi
-
-      if type -t ${dep_dim}_member_expand >/dev/null; then
-        eval "value=\$values ${dep_dim}_member_expand" &>/dev/null || is_required=t
+        if type -t ${dep_dim}_member_expand >/dev/null; then
+          value=$values ${dep_dim}_member_expand
+        fi
       fi
 
       values=( $values )
@@ -1249,12 +1258,14 @@ promote_dep_cell() {
         get_sane_value "$values" || fail
         local old_from=$from
         from=$from/.dim/$sane_value
+        log_debug "Promoted $dep_dim"
         if [[ ! -d $from ]]; then
           eval "$dep_dim_var=\"$values\""
           log_debug "Creating sub for $from"
           fork "load_context_and_create_sub $old_from $from" || fail
         fi
       else
+        log_debug "Did not promote $dep_dim because no value is found for it yet"
         break
       fi
 
@@ -2327,30 +2338,30 @@ return 0
 #   trunk_dims
 #   trunk_dim_count
 setup_branch_dims() {
-local cell_path=$1 \
-  trunk_cell dims
+  local cell_path=$1 \
+    trunk_cell dims
 
-get_trunk_cell $cell_path || return 1
-get_dims $trunk_cell || return 1
-trunk_dims=( ${dims[*]} )
-trunk_dim_count=${#trunk_dims[*]}
+  get_trunk_cell $cell_path || return 1
+  get_dims $trunk_cell || return 1
+  trunk_dims=( ${dims[*]} )
+  trunk_dim_count=${#trunk_dims[*]}
 
-branch_dims=() 
-local dim
-for dim in ${dims[*]}; do
-  if [[ $cell_path =~ .dim ]]; then
-    cell_path=${cell_path%/.dim/*}
-    branch_dims+=( $dim )
-  else
-    break
+  branch_dims=() 
+  local dim
+  for dim in ${dims[*]}; do
+    if [[ $cell_path =~ .dim ]]; then
+      cell_path=${cell_path%/.dim/*}
+      branch_dims+=( $dim )
+    else
+      break
+    fi
+  done
+  branch_dim_count=${#branch_dims[*]}
+  if [[ "${branch_dims:-}" ]]; then
+    log_debug "Branch dims found: ${branch_dims[*]}"
   fi
-done
-branch_dim_count=${#branch_dims[*]}
-if [[ "${branch_dims:-}" ]]; then
-  log_debug "Branch dims found: ${branch_dims[*]}"
-fi
 
-return 0
+  return 0
 }
 
 # returns array of dims, which may be empty if there are no dims
