Fix cell_path bugs

diff --git a/bin/cell b/bin/cell
--- a/bin/cell
+++ b/bin/cell
@@ -26,11 +26,11 @@ begin_function_flat
   command="$original_cmd" omni_log_init || fail
   omni_navigator_init || fail
 
-  local cell 
-  begin_for cell in $cells; doo
+  local cell_path
+  begin_for cell_path in $cells; doo
 
-    cell=$(unrealpath $cell) || {
-      fatal "Failed to resolve path for $cell"
+    cell_path=$(unrealpath $cell_path) || {
+      fatal "Failed to resolve path for $cell_path"
       fail1
       }
 
@@ -39,13 +39,13 @@ begin_function_flat
 
       command=${commands[$i]}
 
-      if [[ "$cell" == */.dna/sub/* && $command == update ]]; then
+      if [[ "$cell_path" == */.dna/sub/* && $command == update ]]; then
         fatal "Don't run update cell commands within sub cell dna folders. Run in the real cell folders."
         fail1
       fi
 
       if [[ $command == */* && -d $command/.dna ]]; then
-        cell=$(unrealpath $command/.dna)
+        cell_path=$(unrealpath $command/.dna)
         continue
       fi
 
@@ -68,9 +68,9 @@ begin_function_flat
             )
         ;;
         clean)
-          get_bottom_cell $cell || fail
+          get_bottom_cell $cell_path || fail
           if [[ ! "$bottom_cell" ]]; then
-            fatal "Not a valid cell: $cell"
+            fatal "Not a valid cell: $cell_path"
             fail1
           fi
           local cell_path=$bottom_cell
@@ -103,8 +103,8 @@ begin_function_flat
             show_help_for_command $command
             fail1
           else
-            get_bottom_cell $cell || fail
-            cell=$bottom_cell
+            get_bottom_cell $cell_path || fail
+            cell_path=$bottom_cell
             local omni_log_job_id job_id_log=${home_job_path:-$HOME/.simpleton/job-log}
 
             if [[ ! -d ${job_id_log%/*} ]]; then
@@ -112,8 +112,8 @@ begin_function_flat
             fi
 
             local needs_update= \
-              command_to_log="$(realpath $cell)"
-            execute_command $cell $command || fail
+              command_to_log="$(realpath $cell_path)"
+            execute_command $cell_path $command || fail
           fi
         ;;
       esac
@@ -144,12 +144,12 @@ handle_return
 show_cell_help() {
 begin_function_flat
 
-  get_bottom_cell $cell || {
-    fatal "No cell found here: $cell"
+  get_bottom_cell $cell_path || {
+    fatal "No cell found here: $cell_path"
     fail1
     }
-  cell=$bottom_cell
-  cell_context_load || fail
+  cell_path=$bottom_cell \
+    cell_context_load || fail
   if [[ $multi_cell == t ]]; then
     out "===================================================================================================="
     out "Cell: $short_cell"
@@ -223,9 +223,9 @@ end_for
 show_help_for_command() {
 local command=$1
 begin_function_flat
-  get_bottom_cell $cell || fail
+  get_bottom_cell $cell_path || fail
   if [[ "$bottom_cell" ]]; then
-    local cell=$bottom_cell
+    local cell_path=$bottom_cell
     cell_context_load || fail
     [[ $first_command == f ]] && out ''
     out "command: $command"
@@ -253,9 +253,9 @@ handle_return
 show_usage() {
 warn "Usage: ${0##*/} {command(s)}"
 local command
-if [[ -d "$cell/.cyto" ]]; then
+if [[ -d "$cell_path/.cyto" ]]; then
   warn "commands:"
-  for command in $(find1 $cell/.cyto/command | sort); do
+  for command in $(find1 $cell_path/.cyto/command | sort); do
     if [[ -f $command ]]; then
       source $command || fail
     elif [[ -d $command ]]; then
diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -181,6 +181,7 @@ handle_return
 
 cell_context_load() {
 
+	get_short_cell $cell_path
   local log_vars=cell_path log_show_vars=short_cell
   begin_function
 
@@ -1475,7 +1476,7 @@ get_job_id() {
       fail1
     fi
 
-    echo "$omni_log_job_id $cell $command_to_log" >>$job_id_log || fail
+    echo "$omni_log_job_id $cell_path $command_to_log" >>$job_id_log || fail
 
     fd_unlock
 
@@ -1546,6 +1547,17 @@ execute_command() {
   handle_return
 }
 
+get_dna_command() {
+local cell_path=$cell_path command=$command
+local parent=${cell_path%/*}
+if [[ -e $cell_path/.dna/command/$command ]]; then
+  dna_command=$cell_path/.dna/command/$command
+elif [[ $parent != $cell_path ]]; then
+  cell=$parent get_dna_command || return 1
+fi
+return 0
+}
+
 # is run in a subshell since it loads the context
 execute_command_internal() {
 
@@ -1556,7 +1568,7 @@ begin_function
   if [[ $current_command != edit ]]; then
 
     cell_context_load || {
-      log_fatal "Context failed to load for $cell"
+      log_fatal "Context failed to load for $cell_path"
       fail1
       }
 
@@ -1579,11 +1591,11 @@ begin_function
 
   fi
 
-  local command_path=$cell/.cyto/command/$current_command
+  local command_path=$cell_path/.cyto/command/$current_command
 
-  if [[ ! -e $command_path && ! -e $cell/.cyto ]]; then
+  if [[ ! -e $command_path && ! -e $cell_path/.cyto ]]; then
     local dna_command=
-    cell=$cell command=$current_command get_dna_command || fail
+    command=$current_command get_dna_command || fail
     if [[ "$dna_command" ]]; then
       command_path=$dna_command
     fi
@@ -1623,17 +1635,6 @@ begin_function
 
 end_function
 handle_return
-}
-
-get_dna_command() {
-local cell=$cell command=$command
-local parent=${cell%/*}
-if [[ -e $cell/.dna/command/$command ]]; then
-  dna_command=$cell/.dna/command/$command
-elif [[ $parent != $cell ]]; then
-  cell=$parent get_dna_command || return 1
-fi
-return 0
 }
 
 execute_command_step_file() {
