Fix dim-add command

diff --git a/command/dim-add b/command/dim-add
--- a/command/dim-add
+++ b/command/dim-add
@@ -18,7 +18,7 @@ dim_add_choose_dim() {
     if [[ "$shared_dim_folder" ]]; then
       echo "Choose a dim to add to this cell:" >&2
       echo "(to create a new one, you'll need to specify the dim parameter directly)" >&2
-      choose "dim: " dims \
+      choose "$type: " dims \
         $(find $shared_dim_folder -maxdepth 1 -mindepth 1 -type d -printf "%f\n" | sort)
       if [[ ! "$dims" ]]; then
         log_fatal "Invalid dim selected"
@@ -127,13 +127,13 @@ dim_add_command() {
       trunk_dim|control_prop|data_prop|sub_dim)
         :
       ;;
-      t|d|dim)
+      t)
         type=trunk_dim
       ;;
-      dp)
+      d|dp)
         type=data_prop
       ;;
-      cp)
+      c|cp)
         type=control_prop
       ;;
       s|sub)
@@ -145,8 +145,11 @@ dim_add_command() {
       ;;
     esac
 
-    setup_cell_path_vars $cell_path || fail
-    find_seed_path $cell_path || fail
+    switch_context $cell_path || {
+      log_fatal "Context failed to load for $short_cell"
+      fail1
+    }
+
     dim_add_find_shared_dim || fail
 
     local dims=${dims:-${dim:-}} dim
