Fix setup_cell_path for when inside of seed

diff --git a/command/dim-add b/command/dim-add
--- a/command/dim-add
+++ b/command/dim-add
@@ -1,35 +1,46 @@
 #!/usr/bin/env bash
 
+dim_add_find_shared_dim() {
+  while [[ ${#d} -gt 3 ]]; do
+    if [[ -d $d/.dna/shared/dim ]]; then
+      shared_dim_folder=$d/.dna/shared/dim
+      break
+    fi
+    d=${d%/*}
+  done
+}
+
+dim_add_choose_dim() {
+  begin_function
+    if [[ "$shared_dim_folder" ]]; then
+      echo "Choose a dim to add to this cell:" >&2
+      echo "(to create a new one, you'll need to specify the dim parameter directly)" >&2
+      local PS3="dim: " 
+      select dims in \
+        $(find $shared_dim_folder -maxdepth 1 -mindepth 1 -type d -printf "%f\n" | sort)
+        do break; done
+      if [[ ! "$dims" ]]; then
+        log_fatal "Invalid dim selected"
+        fail1
+      fi
+    else
+      log_fatal "Must specify a dim parameter containing the dim to add."
+      fail1
+    fi
+  end_function
+  handle_return
+}
+
 dim_add_command() {
   begin_function
     local shared_dim_folder= d=$cell_path
     setup_cell_path_vars $cell_path || fail
 
-    while [[ ${#d} -gt 3 ]]; do
-      if [[ -d $d/.dna/shared/dim ]]; then
-        shared_dim_folder=$d/.dna/shared/dim
-        break
-      fi
-      d=${d%/*}
-    done
+    dim_add_find_shared_dim
 
     local dims=${dims:-${dim:-}} dim
     if [[ ! "${dim:-}" ]]; then
-      if [[ "$shared_dim_folder" ]]; then
-        echo "Choose a dim to add to this cell:" >&2
-        echo "(to create a new one, you'll need to specify the dim parameter directly)" >&2
-        local PS3="dim: " 
-        select dims in \
-          $(find $shared_dim_folder -maxdepth 1 -mindepth 1 -type d -printf "%f\n" | sort)
-          do break; done
-        if [[ ! "$dims" ]]; then
-          log_fatal "Invalid dim selected"
-          fail1
-        fi
-      else
-        log_fatal "Must specify a dim parameter containing the dim to add."
-        fail1
-      fi
+      dim_add_choose_dim || fail
     fi
 
     begin_for dim in $dims; doo
@@ -37,53 +48,15 @@ dim_add_command() {
       log_info "Adding dim $dim"
 
       if [[ -d $shared_dim_folder/$dim ]]; then
-        local dim_name= head_part tail_part description_found=f expand_found=f file
-        begin_for d in $(find1 $shared_dim_folder/$dim -type f); doo
-
-          file=${d##*/}
-          head_part=${file%%_*}
-          tail_part=${file#*_}
-
-          if [[ ! "$dim_name" ]]; then
-            dim_name=$head_part
-          elif [[ $dim_name != $head_part ]]; then
-            log_warn "Found inconsistent dim name in $shared_dim_folder/$dim: $dim_name != $head_part"
-            log_warn "Will ignore"
-            continue
-          fi
-
-          case $tail_part in
-            description|examples)
-              description_found=t
-              if [[ ! -d $dim_all_path/var ]]; then
-                mkdir -p $dim_all_path/var || fail
-              fi
-              force=t safe_link $d $dim_all_path/var/ || fail
-            ;;
-            expand)
-              expand_found=t
-              if [[ ! -d $dim_all_path/fun ]]; then
-                mkdir -p $dim_all_path/fun || fail
-              fi
-              force=t safe_link $d $dim_all_path/fun/ || fail
-            ;;
-            *)
-              log_warn "Unknown dim file type: $tail_part found in $shared_dim_folder/dim. Ignoring"
-            ;;
-          esac
-          
-        end_for
-
-        if [[ ! -d $var_path ]]; then
-          mkdir -p $var_path || fail
-        fi
-
-        if [[ -e $var_path/dims ]] && \
-           grep "$dim_name" $var_path/dims &>/dev/null; then
-          log_fatal "dim $dim_name has already been added here: $var_path/dims"
+        local dim_name= head_part tail_part file base_dim
+        base_dim=${dim%%-*}
+        if [[ -e $seed_path/.dna/${base_dim}_ || -e $seed_path/$base_dim:all ]]; then
+          log_fatal "Dim $dim has already been added to this cell"
           fail1
         fi
-        echo "$dim_name" >>$var_path/dims || fail
+        mkdir -p $seed_path/$base_dim:all/.dna || fail
+        safe_link $seed_path/.dna/* $seed_path/$base_dim:all/.dna/ || fail
+        safe_link $shared_dim_folder/$dim $seed_path/.dna/${base_dim}_ || fail
 
         log_info "Added $dim_name"
       else
