.

diff --git a/command/dim-add b/command/dim-add
--- a/command/dim-add
+++ b/command/dim-add
@@ -146,7 +146,7 @@ dim_add_command() {
     begin_for dim in $dims; doo
 
       local base_dim=${dim%%-*}
-      log_info "Adding $type $dim"
+      log_info "Adding $type $base_dim"
 
       local added_something=f \
         dim_path=$shared_dim_folder/$dim
@@ -155,13 +155,12 @@ dim_add_command() {
         local var_path=$cell_path/.dna/${type}s.var
         local vals=
         if [[ -f $var_path ]]; then
-          vals=$(<var_path) || fail
+          vals=$(<$var_path) || fail
         fi
-        if [[ " $vals " == *" $dim "* ]]; then
-          log_fatal "$type $dim has already been added to this cell."
-          fail1
+        if [[ " $vals " != *" $base_dim "* ]]; then
+          echo "$base_dim" >>$var_path || fail
+          added_something=t
         fi
-        echo "$base_dim" >>$var_path || fail
       fi
 
       if [[ ! -e $seed_path/.dna/${base_dim}_ ]]; then
@@ -188,7 +187,7 @@ dim_add_command() {
       fi
 
       if [[ $added_something == f ]]; then
-        log_warn "Dim $dim already added, nothing to do."
+        log_warn "Dim $base_dim already added, nothing to do."
       fi
 
     end_for
