.

diff --git a/command/dim-rm b/command/dim-rm
--- a/command/dim-rm
+++ b/command/dim-rm
@@ -82,9 +82,20 @@ dim_rm_command() {
   begin_function
 
     local seed_path trunk_seed_path
-    load_branch_info || fail
-    find_seed_path $cell_path || fail
-    trunk_seed_path=$seed_path
+    if [[ ! "${seed_path:-}" ]]; then
+      load_branch_info || fail
+      find_seed_path $cell_path || fail
+    else
+      cell_path=/work${seed_path#/seed}
+    fi
+
+    if [[ ! "${seed_path:-}" || ! -e $seed_path ]]; then
+      log_fatal "Couldn't find seed path. You must either run this command in a work cell, or in a seed cell"
+      fail1
+    fi
+
+    local dna_path=$seed_path/.dna
+    local trunk_seed_path=$seed_path
 
     local trunk_dims_path=$seed_path/.dna/trunk_dims \
       cprops_path=$seed_path/.dna/control_props \
