Fix get command sorting bug

diff --git a/command/get b/command/get
--- a/command/get
+++ b/command/get
@@ -430,7 +430,7 @@ handle_sorting() {
 
     local single_column result
     get_single_column $sort_field_index || fail
-    result=$(echo -n "$single_column" | sort -gu $sort_flags) || fail
+    result=$(echo -n "$single_column" | sort -g $sort_flags | uniq) || fail
     local from_data=( "${output_table_data[@]}" ) 
 
     output_table_data=( )
@@ -450,6 +450,11 @@ handle_sorting() {
       end_for
     end_for
     IFS=$OIFS
+
+    if (( ${#from_data[*]} != ${#output_table_data[*]} )); then
+      log_fatal "Internal error: sorting changed table size ${#from_data[*]} -> ${#output_table_data[*]}"
+      fail1
+    fi
   end_function
   handle_return
 }
