.

diff --git a/command/get b/command/get
--- a/command/get
+++ b/command/get
@@ -499,9 +499,9 @@ get_command() {
       fail1
     }
     setup_dims || fail
-    calc_coords || fail
+    #calc_coords || fail
 
-    local out_form=${out_form:-${form:-${default_out_form:-simple}}} \
+    local out_form=${out_form:-${form:-${default_out_form:-table}}} \
       out_fields=${out_fields:-${fields:-${field:-}}} \
       out_sort=${out_sort:-${sort:-${default_sort:-}}} \
       table_data=() \
