Make get command filter faster

diff --git a/command/get b/command/get
--- a/command/get
+++ b/command/get
@@ -1,18 +1,53 @@
 #!/usr/bin/env bash
 
+get_formatted_data_row() {
+  begin_function
+    o=
+    (( row_begin = field_count * row ))
+    if function_exists each_field; then
+      begin_for (( c = 0; c < selected_count; c++ )); doo
+
+        i=${selected_field_indices[$c]}
+        field=${output_table_fields[$i]}
+        value=${output_table_data[$((i + row_begin))]}
+
+        if [[ $pretty == t ]]; then
+          if [[ -v pretty_function[$field] ]]; then
+            local pretty_value
+            ${pretty_function[$field]} "$value" || fail
+            value=$pretty_value
+          elif [[ -v pretty_form[$field] ]]; then
+            format_var ${pretty_form[$field]} value
+          fi
+        fi
+
+        each_field || fail
+      end_for
+    fi
+    if [[ ! -v rows_already_output[$o] ]]; then
+      execute_if_exists after_row || fail
+      rows_already_output[$o]=1
+    fi
+  end_function
+  handle_return
+}
+
 get_formatted_data() {
   begin_function
 
     local i field value o c row row_type row_begin \
       pretty=${pretty:-t}
-    local -A pretty_function pretty_form
+
+    local -A pretty_function \
+      pretty_form \
+      rows_already_output=() \
 
     o=
     row_type=header
     if function_exists each_field; then
       begin_for (( c = 0; c < selected_count; c++ )); doo
         i=${selected_field_indices[$c]}
-        field=${table_fields[$i]}
+        field=${output_table_fields[$i]}
         value=$field
 
         local pretty_function_name=dim_${field}_pretty_function
@@ -34,43 +69,11 @@ get_formatted_data() {
       row_count=$out_limit
     fi
 
-    local -A rows_already_output=()
     begin_for (( row = 0; row < row_count; row++ )); doo
-      o=
-      (( row_begin = field_count * row ))
-      local is_valid
-      offset=$row_begin \
-      check_table_row || fail
-      if [[ $is_valid == t ]]; then
-        if function_exists each_field; then
-          begin_for (( c = 0; c < selected_count; c++ )); doo
-
-            i=${selected_field_indices[$c]}
-            field=${table_fields[$i]}
-            value=${table_data[$((i + row_begin))]}
-
-            if [[ $pretty == t ]]; then
-              if [[ -v pretty_function[$field] ]]; then
-                local pretty_value
-                ${pretty_function[$field]} "$value" || fail
-                value=$pretty_value
-              elif [[ -v pretty_form[$field] ]]; then
-                format_var ${pretty_form[$field]} value
-              fi
-            fi
-
-            each_field || fail
-          end_for
-        fi
-        if [[ ! -v rows_already_output[$o] ]]; then
-          execute_if_exists after_row || fail
-          rows_already_output[$o]=1
-        fi
-      fi
+      get_formatted_data_row || fail
     end_for
 
   end_function
-  local log_return_vars=formatted_data
   handle_return
 }
 
@@ -218,7 +221,7 @@ display_data_table() {
     local c i f bar="+" length pad
     begin_for (( c = 0; c < selected_count; c++ )); doo
       i=${selected_field_indices[$c]}
-      f="${table_fields[$i]}"
+      f="${output_table_fields[$i]}"
       length=${apad_size[$f]}
       printf -v pad %$((length-1))s
       pad=${pad// /-}
@@ -298,7 +301,7 @@ get_selected_field_indices() {
     local field i found
 
     out_fields=" $out_fields "
-    out_fields=${out_fields// all / ${table_fields[*]} }
+    out_fields=${out_fields// all / ${output_table_fields[*]} }
     out_fields=${out_fields# }
     out_fields=${out_fields% }
 
@@ -308,7 +311,7 @@ get_selected_field_indices() {
 
       found=f
       begin_for (( i = 0; i < field_count; i++ )); doo
-        local remaining_name=${table_fields[$i]}
+        local remaining_name=${output_table_fields[$i]}
         while true; do
 
           if [[ "$remaining_name" == "$field" ]]; then
@@ -329,7 +332,7 @@ get_selected_field_indices() {
         done
       end_for
       if [[ $found == f ]]; then
-        log_fatal "Field not found: $field. Must be one of: ${table_fields[*]}"
+        log_fatal "Field not found: $field. Must be one of: ${output_table_fields[*]}"
         fail1
       fi
     end_for
@@ -352,7 +355,7 @@ get_single_column() {
     single_column=
     begin_for (( row = 0; row < row_count; row++ )); doo
       (( t = row * field_count + field_index ))
-      value=${table_data[$t]}
+      value=${output_table_data[$t]}
       single_column+="$value$NL"
     end_for
 
@@ -362,12 +365,43 @@ get_single_column() {
 }
 
 # inputs:
+#   output_table_data
+# outputs:
+#   output_table_data
+handle_filtering() {
+  begin_function
+
+    local -A matching_rows=() \
+
+    matching_rows[all]=1
+
+    full_table=output_table \
+    extract_from_derive_table_find_row_indexes || fail
+
+    if [[ ! -v matching_rows[all] ]]; then
+      local from_data=( "${output_table_data[@]}" ) \
+        row_indexes=() beginning_of_row=0
+      output_table_data=()
+      set_to_array matching_rows row_indexes
+      sort_array row_indexes
+      begin_for row in ${row_indexes[*]}; doo
+        (( beginning_of_row = row * field_count ))
+        output_table_data+=( "${from_data[@]:beginning_of_row:field_count}" )
+      end_for
+    fi
+
+    row_count=$((${#output_table_data[*]} / field_count))
+  end_function
+  handle_return
+}
+
+# inputs:
 #   row_count
 #   field_count
 #   out_sort
-#   table_data
+#   output_table_data
 # outputs:
-#   table_data
+#   output_table_data
 handle_sorting() {
   begin_function
     local sort_flags=
@@ -377,45 +411,45 @@ handle_sorting() {
     fi
 
     if [[ "$out_sort" == *" "* ]]; then
-      log_fatal "Can't yet sort by multiple fields. Choose only one for now"
+      log_fatal "can't yet sort by multiple fields. choose only one for now"
       fail1
     fi
 
     local i sort_field_index=
     begin_for (( i = 0; i < field_count; i++ )); doo
-      if [[ "${table_fields[$i]}" == "$out_sort" ]]; then
+      if [[ "${output_table_fields[$i]}" == "$out_sort" ]]; then
         sort_field_index=$i
         break
       fi
     end_for
 
     if [[ ! "$sort_field_index" ]]; then
-      log_fatal "Invalid sort field: $out_sort"
+      log_fatal "invalid sort field: $out_sort"
       fail1
     fi
 
     local single_column result
     get_single_column $sort_field_index || fail
     result=$(echo -n "$single_column" | sort -u $sort_flags) || fail
-    local from_data=( "${table_data[@]}" ) 
+    local from_data=( "${output_table_data[@]}" ) 
 
-    table_data=( )
-    OIFS=$IFS
-    IFS="$NL"
+    output_table_data=( )
+    oifs=$ifs
+    ifs="$nl"
     local v sort_field_value row t beginning_of_row
     begin_for v in ${result}; doo
-      IFS=$OIFS
+      ifs=$oifs
       local from_data_size=${#from_data[*]}
       begin_for (( row = 0; row < row_count; row++ )); doo
         (( beginning_of_row = row * field_count ))
         (( t = beginning_of_row + sort_field_index ))
         sort_field_value=${from_data[$t]}
         if [[ "$sort_field_value" == "$v" ]]; then
-          table_data+=( "${from_data[@]:beginning_of_row:field_count}" )
+          output_table_data+=( "${from_data[@]:beginning_of_row:field_count}" )
         fi
       end_for
     end_for
-    IFS=$OIFS
+    ifs=$oifs
   end_function
   handle_return
 }
@@ -423,7 +457,7 @@ handle_sorting() {
 get_command_output() {
   begin_function
 
-    log_verbose "Preparing output..."
+    log_debug "Preparing output..."
     if [[ "$get_show_file" && -f "$out_path/$get_show_file" ]]; then
       if [[ "$out_limit" ]]; then
         cat $out_path/$get_show_file | head -n $out_limit || fail
@@ -431,21 +465,24 @@ get_command_output() {
         cat $out_path/$get_show_file || fail
       fi
     else
-      if is_array table_data; then
+      if is_array output_table_data; then
 
         local selected_field_indices=() \
-          field_count=${#table_fields[*]} \
+          field_count=${#output_table_fields[*]} \
           selected_count \
-          row_count=${#table_data[*]} \
+          row_count=${#output_table_data[*]} \
 
         if (( field_count == 0 )); then
           log_fatal "field_count can't be 0."
           fail1
         fi
 
-        log_verbose "Indexing and sorting..."
+        log_debug "Indexing and sorting..."
         (( row_count /= field_count ))
         get_selected_field_indices || fail
+
+        handle_filtering || fail
+
         if [[ "$out_sort" ]]; then
           handle_sorting || fail
         fi
@@ -456,7 +493,7 @@ get_command_output() {
           formatted_data+="$o$NL"
         }
 
-        log_verbose "Displaying data in $out_form form..."
+        log_debug "Displaying data in $out_form form..."
         case $out_form in 
           c|csv)
             display_data_csv || fail
@@ -488,8 +525,8 @@ get_command_output() {
             fail1
           ;;
         esac
-      elif [[ -v table_data ]]; then
-        out "$table_data"
+      elif [[ -v output_table_data ]]; then
+        out "$output_table_data"
       else
         out "No data"
       fi
@@ -503,7 +540,8 @@ get_command_load_data_branch() {
 
     local short_cell
     get_short_cell
-    log_verbose "Loading branch $short_cell..."
+    log_debug "Loading branch $short_cell..."
+    progress_bar_nudge .
     local subs
     subs=$(find1 $cell_path -type d -not -name '.*' | sort -g) || fail1
     local cell_path=
@@ -526,22 +564,23 @@ get_command_load_data_leaf() {
 
     local short_cell
     get_short_cell
-    log_verbose "Loading leaf data for $short_cell"
+    log_debug "Loading leaf data for $short_cell"
     local context_type= output_data output_fields
 
     local tabs=( $cell_path/output.*tab )
     if [[ -f $tabs ]]; then
 
+      progress_bar_nudge +
       load_dna_item $tabs || fail
 
-      if (( ${#table_fields[*]} == 0 )); then
-        table_fields=( ${output_fields[*]} )
-      elif [[ "${table_fields[*]}" != "${output_fields[*]}" ]]; then
+      if (( ${#output_table_fields[*]} == 0 )); then
+        output_table_fields=( ${output_fields[*]} )
+      elif [[ "${output_table_fields[*]}" != "${output_fields[*]}" ]]; then
         log_fatal "Fields are different across sub cells. This should not be possible. Try clean updating."
         fail1
       fi
 
-      table_data+=( "${output_data[@]}" )
+      output_table_data+=( "${output_data[@]}" )
 
     fi
 
@@ -557,7 +596,15 @@ get_command_load_data() {
       original_anchor_dims=$anchor_dims \
       original_cell_path=$cell_path \
       extra_fields=${extra_fields:-} \
+      cache_path=$out_path/output.tab.cache \
 
+    if [[ -f $cache_path ]]; then
+      source $cache_path || fail
+      abort
+    fi
+
+    log_info "Generating cache $cache_path"
+    progress_bar_start
     localize
     if [[ "${localize_dims:-}" ]]; then
       eval "local $localize_reverse_dims" || fail
@@ -569,6 +616,33 @@ get_command_load_data() {
     else
       get_command_load_data_branch || fail
     fi
+
+    if [[ -f $cache_path.new ]]; then
+      rm $cache_path.new || fail
+    fi
+
+    progress_bar_nudge I
+
+    grip_fence
+    table=output_table \
+    ignore_unknown_dims=t \
+    include_implicit_dims=t \
+    make_table_index || fail
+
+    grip_fence
+    progress_bar_nudge .
+    local context_file=$cache_path.new
+    write_table_to_context output_table || fail
+
+    grip_fence
+    progress_bar_nudge .
+    table=output_table \
+    expand_values=f \
+    write_index_to_context || fail
+
+    grip_fence
+    mv $cache_path.new $cache_path || fail
+    progress_bar_stop
 
   end_function
   handle_return
@@ -585,15 +659,12 @@ get_command() {
     switch_context $cell_path || fail
     grip_fence
 
-    setup_dims || fail
-    grip_fence
-
     local out_form=${out_form:-${form:-${default_out_form:-simple}}} \
       out_fields=${out_fields:-${fields:-${field:-}}} \
       out_sort=${out_sort:-${sort:-${default_out_sort:-}}} \
       out_limit=${out_limit:-${limit:-}} \
-      table_data=() \
-      table_fields=() \
+      output_table_data=() \
+      output_table_fields=() \
       used_default_fields=f \
 
     out_fields=${out_fields,,}
@@ -624,7 +695,7 @@ get_command() {
       get_command_load_data || fail
       grip_fence
 
-      if (( ${#table_fields[*]} > 0 )); then
+      if (( ${#output_table_fields[*]} > 0 )); then
         local get_show_file=${get_show_file:-}
         get_command_output
       else
diff --git a/lib/bash-debugger b/lib/bash-debugger
--- a/lib/bash-debugger
+++ b/lib/bash-debugger
@@ -1557,8 +1557,8 @@ debug_command_loop() {
         echo "   prefix with ! to show declare output for this var" >&$fd_original_err
         echo "   prefix with * to show declare output for all set variables matching that" >&$fd_original_err
         echo "   prefix with $ to use a raw variable expression which is fed into echo" >&$fd_original_err
-        echo "   prefix with @ to show an array in long view, with one element per row" >&$fd_original_err
-        echo "   prefix with @@ to show an array in table form, requiring a {var}_data and {var}_fields variables" >&$fd_original_err
+        echo "   prefix with @ to show an array in long view, with one element per row. Can use [...] after to select an element." >&$fd_original_err
+        echo "   prefix with @@ to show an array in table form, requiring a {var}_data and {var}_fields variables. Can use [...] after to select a row." >&$fd_original_err
         echo "   prefix with ^ to show all dim forms of that var" >&$fd_original_err
         echo "   you can also display the result of a test, example: [[ -v index ]]   or   (( x > 3 ))" >&$fd_original_err
         echo "D  repeat last display command" >&$fd_original_err
@@ -2124,18 +2124,31 @@ show_array() {
 }
 
 show_table() {
-  local -n fields=$1_fields data=$1_data
+  local table_with_row=$1
+
+  local table_var=${table_with_row%%\[*} \
+    row_index=${table_with_row##*\[} \
+
+  row_index=${row_index%\]}
+  if [[ $row_index == $table_var ]]; then
+    row_index=
+  fi
+
+  local -n fields=${table_var}_fields data=${table_var}_data
   if [[ -v fields && -v data ]]; then
 
     set +T
     {
     echo "${fields[*]}"
-    local line= field_count=${#fields[*]} f
+    local line= field_count=${#fields[*]} f row
 
     for (( i = 0; i <= ${#data[*]}; i++ )); do
       (( f = i % field_count ))
+      (( row = i / field_count - 1 ))
       if (( f == 0 )) && [[ "$line" ]]; then
-        echo "$line"
+        if [[ ! "$row_index" ]] || (( row_index == row )); then
+          echo "$line"
+        fi
         line=
       fi
       if (( i < ${#data[*]} )); then
@@ -2146,7 +2159,7 @@ show_table() {
     set -T
 
   else
-    echo "Invalid table variable: $1" >&$fd_original_err
+    echo "Invalid table variable: $table_var" >&$fd_original_err
   fi
 }
 
