Fix local .* fail bug

diff --git a/command/get b/command/get
--- a/command/get
+++ b/command/get
@@ -262,9 +262,9 @@ handle_sorting() {
       fail1
     fi
 
-    local single_column
+    local single_column result
     get_single_column $sort_field_index || fail
-    local result=$(echo -n "$single_column" | sort -u $sort_flags) || fail
+    result=$(echo -n "$single_column" | sort -u $sort_flags) || fail
     local from_data=( "${table_data[@]}" ) 
 
     table_data=( )
@@ -395,8 +395,8 @@ get_command_load_data() {
       fi
 
       if [[ $execute_inner != n && "${inner:-}" ]]; then
-        local i_path
-        local inners=$(find1 $inner_path -type d -not -name '.*') || fail
+        local i_path inners
+        inners=$(find1 $inner_path -type d -not -name '.*') || fail
         begin_for i_path in $inners; doo
           parent_cell=$cell_path cell_path=$i_path get_command_load_data || fail
         end_for
diff --git a/lib/update-lib b/lib/update-lib
--- a/lib/update-lib
+++ b/lib/update-lib
@@ -301,14 +301,16 @@ update_upstream_get_locks() {
     local -r export_path=$upstream/chosen/export
     if [[ -d $export_path ]]; then
 
-      local shared_locks=$(find1 $export_path -not -name ".*" -name "shared-lock-*" | sort -g) || fail
+      local shared_locks
+      shared_locks=$(find1 $export_path -not -name ".*" -name "shared-lock-*" | sort -g) || fail
       begin_for lock in $shared_locks; doo
         write_lock=f \
           timeout=$lock_timeout \
           cell_lock $lock || fail
       end_for
 
-      local exclusive_locks=$(find1 $export_path -not -name ".*" -name "lock-*" | sort -g) || fail
+      local exclusive_locks
+      exclusive_locks=$(find1 $export_path -not -name ".*" -name "lock-*" | sort -g) || fail
       begin_for lock in $exclusive_locks; doo
         write_lock=t \
           timeout=$lock_timeout \
@@ -393,7 +395,8 @@ update_upstream() {
 
     if [[ "$needs_update" != f ]]; then
 
-      local up_cell=$(realpath $chosen) || fail
+      local up_cell
+      up_cell=$(realpath $chosen) || fail
 
       downstream_cell_name=${short_cell//\//_} \
       fork execute_commands "$up_cell" update || fail
@@ -583,7 +586,8 @@ already_in_dep_stack() {
 propagate_change_to_downstream2() {
   begin_function
 
-    local cell=$(realpath $value) || fail
+    local cell
+    cell=$(realpath $value) || fail
 
     local t1 t2 trunk_cell
     get_trunk_cell $cell
@@ -726,7 +730,8 @@ create_outer_links() {
       fi
       safe_link $outer_cell_path $outer_link || fail
     else
-      local link_target=$(readlink $outer_link) || fail
+      local link_target
+      link_target=$(readlink $outer_link) || fail
       if [[ $link_target != $outer_cell_path ]]; then
         log_fatal "Link conflict: A link already exists but doesn't point to the same place."
         log_fatal "  source:   $outer_link"
@@ -756,7 +761,8 @@ create_downstream_links() {
 
 #      let's just replace this each time for now
 #    if [[ -e $down_link ]]; then
-#      local link_target=$(readlink $down_link) || fail
+#      local link_target
+#      link_target=$(readlink $down_link) || fail
 #      if [[ $link_target != $down_cell_path ]]; then
 #        log_fatal "Link conflict: A link already exists but doesn't point to the same place."
 #        log_fatal "  source:   $down_link"
@@ -773,7 +779,8 @@ create_downstream_links() {
 link_dim_parts() {
   local from_path=$from_path to_path=$to_path
   begin_function
-    local contents=$(find1 $from_path -not -name '.*') || fail
+    local contents
+    contents=$(find1 $from_path -not -name '.*') || fail
     begin_for part in $contents; doo
       if [[ "$part" == */up \
          || "$part" == */down \
@@ -1282,8 +1289,8 @@ get_dep_member() {
 
 update_inners() {
   begin_function
-    local i_path needs_update=
-    local inners=$(find1 $inner_path -type d -not -name '.*') || fail
+    local i_path needs_update= inners
+    inners=$(find1 $inner_path -type d -not -name '.*') || fail
     begin_for i_path in $inners; doo
       outer_cell_name=${short_cell//\//_} \
       inner_cell_link=$i_path \
