Allow mock command to work recursively

diff --git a/command/mock b/command/mock
--- a/command/mock
+++ b/command/mock
@@ -1,14 +1,75 @@
 #!/usr/bin/env bash
 
+mock_leaf() {
+  begin_function
+    local mock_changed=f
+    if [[ $current_mock == f ]]; then
+      if [[ $mock != f ]]; then
+        mock_changed=t
+      else # both are f
+        log_warn "Keeping previous unmocked state"
+      fi
+    else # current_mock != f
+      if [[ $mock != f ]]; then
+        if [[ $mock != $current_mock ]]; then
+          mock_changed=t
+        else
+          log_warn "Keeping previous mock: $mock"
+        fi
+      else # current_mock != f && mock == f
+        log_warn "Removing mock"
+        rm $cyto_path/current_mock || fail
+        kind=data clean_cell $cell_path || fail
+      fi
+    fi
+
+    if [[ $mock_changed == t ]]; then
+      kind=data clean_cell $cell_path || fail
+      echo "$mock" >$cyto_path/current_mock || fail
+
+      deep=t plant_seed_internal "$seed_path" "$cell_path" || fail
+    fi
+
+  end_function
+  handle_return
+}
+
+mock_branch() {
+  begin_function
+    local branch_cells=$(find1 $cell_path -name '*:*') || fail
+    local branch_cell
+    begin_for branch_cell in $branch_cells; doo
+      cell_path=$branch_cell
+      anchor_dims=
+      switch_context || fail
+
+      if [[ $cell_is_leaf == f ]]; then
+        mock_leaf || fail
+      else
+        mock_branch || fail
+      fi
+
+    end_for
+  end_function
+  handle_return
+}
+
+mock_cell() {
+  begin_function
+    log_info "Mocking $short_cell"
+    if [[ $cell_is_leaf == f ]]; then
+      mock_leaf || fail
+    else
+      mock_branch || fail
+    fi
+  end_function
+  handle_return
+}
+
 mock_command() {
   begin_function
 
     local mock=${mock:-}
-
-    if [[ $cell_is_leaf == f ]]; then
-      log_fatal "This command can only be run on leaf cells"
-      fail1
-    fi
 
     if [[ ! "$mock" ]]; then
       if [[ -d $mock_path ]]; then
@@ -40,33 +101,7 @@ mock_command() {
       fail1
     fi
 
-    local mock_changed=f
-    if [[ $current_mock == f ]]; then
-      if [[ $mock != f ]]; then
-        mock_changed=t
-      else # both are f
-        log_warn "Keeping previous unmocked state"
-      fi
-    else # current_mock != f
-      if [[ $mock != f ]]; then
-        if [[ $mock != $current_mock ]]; then
-          mock_changed=t
-        else
-          log_warn "Keeping previous mock: $mock"
-        fi
-      else # current_mock != f && mock == f
-        log_warn "Removing mock"
-        rm $cyto_path/current_mock || fail
-        kind=data clean_cell $cell_path || fail
-      fi
-    fi
-
-    if [[ $mock_changed == t ]]; then
-      kind=data clean_cell $cell_path || fail
-      echo "$mock" >$cyto_path/current_mock || fail
-
-      deep=t plant_seed_internal "$seed_path" "$cell_path" || fail
-    fi
+    mock_cell || fail
 
     command_successful=t
 
