Add mock=disabled option

diff --git a/command/mock b/command/mock
--- a/command/mock
+++ b/command/mock
@@ -65,28 +65,23 @@ mock_command() {
     mock_path=$seed_path/.mock
 
     if [[ ! "$mock" ]]; then
+      local options=()
       if [[ -d $mock_path ]]; then
-        local options=( $(find1 $mock_path -not -name export -printf "%f ") )
-        if (( ${#options[*]} > 0 )); then
-          choose "Which mock? " mock "${options[@]}" f || fail
-        else
-          log_fatal "There are no mocks available for this cell. To create one, create a folder here: $mock_path"
-          fail1
-        fi
-      else
-        log_fatal "There are no mocks available for this cell. To create one, create a folder here: $mock_path"
-        fail1
+        options=( $(find1 $mock_path -not -name export -printf "%f ") ) || fail
       fi
+      options+=( disabled f )
+      choose "Which mock? " mock "${options[@]}" || fail
     fi
 
-    if [[ $mock != f && ! -d $mock_path/$mock ]]; then
+    if [[ $mock != f && $mock != disabled && ! -d $mock_path/$mock ]]; then
       if [[ $ignore_missing == t ]]; then
         log_verbose "Mock doesn't exist for this folder, skipping."
         succeed
       else
         log_fatal "Invalid mock: $mock"
         if [[ -d $mock_path ]]; then
-          local options=( $(find1 $mock_path -printf "%f") )
+          local options
+          options=( $(find1 $mock_path -not -name export -printf "%f ") disabled ) || fail
           if (( ${#options[*]} > 0 )); then
             log_fatal "You must choose one of these mocks: ${options[*]} or use f to unmock this cell, or just leave the mock field blank to get a menu"
           else
diff --git a/lib/update-lib b/lib/update-lib
--- a/lib/update-lib
+++ b/lib/update-lib
@@ -699,9 +699,10 @@ pre_update() {
       rm $status_path/last-good-update-end || fail
     fi
 
-    if [[ $current_mock != f ]]; then
-      kind=data clean_cell $cell_path || fail
-    fi
+    # This should have already happened when the mock was set in the first place
+    #if [[ $current_mock != f ]]; then
+    #  kind=data clean_cell $cell_path || fail
+    #fi
 
     # This already happens in switch_context
     #if [[ $cell_is_leaf == t ]]; then
@@ -1317,6 +1318,11 @@ update_command() {
       log_fatal "Context failed to load for $short_cell"
       fail1
     }
+
+    if [[ $current_mock == disabled ]]; then
+      log_fatal "Cell is disabled. Use mock command to change it if this is not intended."
+      fail1
+    fi
 
     if [[ ${branches_only:-f} == t && $cell_is_leaf == t ]]; then
       update_successful=t
