.

diff --git a/command/mock b/command/mock
--- a/command/mock
+++ b/command/mock
@@ -18,13 +18,13 @@ mock_leaf() {
         fi
       else # current_mock != f && mock == f
         log_warn "Removing mock"
-        rm $cyto_path/current_mock || fail
+        rm $cell_path/.mock || fail
         kind=data clean_cell $cell_path || fail
       fi
     fi
 
     if [[ $mock_changed == t ]]; then
-      echo "$mock" >$cyto_path/current_mock || fail
+      echo "$mock" >$cell_path/.mock || fail
     fi
 
   end_function
