.

diff --git a/command/mock b/command/mock
--- a/command/mock
+++ b/command/mock
@@ -35,9 +35,9 @@ mock_cell() {
   begin_function
     log_info "Checking $short_cell"
     mock_leaf || fail
-    if [[ $cell_is_leaf == f ]]; then
-      mock_branch || fail
-    fi
+    #if [[ $cell_is_leaf == f ]]; then
+    #  mock_branch || fail
+    #fi
   end_function
   handle_return
 }
@@ -97,7 +97,7 @@ mock_command() {
       fi
     fi
 
-    mock_cell || fail
+    mock_leaf || fail
 
     command_successful=t
 
