Improve mock ls command

diff --git a/command/mock-ls b/command/mock-ls
--- a/command/mock-ls
+++ b/command/mock-ls
@@ -3,6 +3,11 @@
 mock_ls_command() {
   begin_function
 
+    switch_context $cell_path || {
+      log_fatal "Context failed to load for $short_cell"
+      fail1
+    }
+
     local seed_path mock_path
     find_seed_path $cell_path || fail
     mock_path=$seed_path/.mock
@@ -18,7 +23,7 @@ mock_ls_command() {
         fi
         echo "$output"
       done
-      } | column -t
+      } | column -t -l2
     else
       out "No mocks have been defined for this cell."
     fi
