Abstract out walk command to make it more reuable

diff --git a/command/up-rm b/command/up-rm
--- a/command/up-rm
+++ b/command/up-rm
@@ -1,17 +1,20 @@
 #!/usr/bin/env bash
 
 select_upstream() {
-  local starting_folder=$1
   begin_function
+    upstream=
+    local current_folder=$1 \
+      hidden_choices choices \
+      choice path i real_stack=() \
+      filter_mode=f walk_filter= \
 
-    echo "Choose upstream to add."
+    local -A code_set
+    echo "Choose upstream to add. Press enter or space to accept selection, ? for more help, or q to quit"
+    begin_while true; doo
 
-    walk_init || fail
-
-    show_selection() {
       local extra=
-      if [[ -f $current_selection/.member ]]; then
-        extra=" $(<$current_selection/.member)"
+      if [[ -f $current_folder/.member ]]; then
+        extra=" $(<$current_folder/.member)"
         if (( ${#extra} > 60 )); then
           extra=" ${extra:0:60}..."
         fi
@@ -19,45 +22,68 @@ select_upstream() {
 
       local highlight=$'\033[1;33m' \
         reset=$'\033[0m'
-      echo "$highlight$hbar_equals$NL$(short_path $current_selection)$reset$extra"
-    }
+      echo "$highlight$hbar_equals$NL$(short_path $current_folder)$reset$extra"
 
-    adjust_choices() {
-      if [[ -d $current_selection/.. ]]; then
-        hidden=f walk_add_choice "." "$current_selection/.." ".."
+      code_set=()
+      hidden_choices=(
+        "enter accept"
+        "q quit"
+        "? help"
+        "/ filter"
+        )
+      choices=()
+      i=0
+
+      if [[ -d .. ]]; then
+        hidden=f walk_add_choice "." ".."
       fi
 
-      if [[ $current_selection == *:* ]]; then
-        path=${current_selection%%:*}
+      if [[ $current_folder == *:* ]]; then
+        path=${current_folder%%:*}
         path=${path%/*}
         walk_add_choice "t" "$path" "trunk"
       fi
 
-      walk_add_dirs $current_selection || return 1
-      return 0
-    }
+      walk_add_dirs $current_folder || fail
 
-    handle_walk_responses() {
-      if [[ -d "$response" ]]; then
-        current_selection="$(unrealpath $response)"
+      local prompt="Choose an upstream cell (press enter to accept current choice): "
+      walk_menu || break
+      if [[ $filter_mode == f ]]; then
+        if [[ "$result" == help ]]; then
+          echo "Press one of the characters in the menu to go to the corrosponding folders, enter or space to accept the upstream choice, or q to quit/abort this command."
+          echo "You can also use / to enter filter mode and narrow down results."
+          echo "Using / again after a filter is applied will remove the filter."
+          # later
+        elif [[ "$result" == quit ]]; then
+          exit 0
+        elif [[ "$result" == accept ]]; then
+          upstream=$current_folder
+          break
+        elif [[ "$result" == filter ]]; then
+          if [[ "$walk_filter" ]]; then
+            echo "Removed filter."
+            walk_filter=
+          else
+            filter_mode=t
+          fi
+        elif [[ -d "$result" ]]; then
+          current_folder="$(unrealpath $result)"
+        else
+          echo "Invalid selection, try again."
+          continue
+        fi
+      else # filter_mode == t
+        if [[ "$result" == accept ]]; then
+          filter_mode=f
+        fi
       fi
-    }
 
-    local result= \
-      prompt="Choose an upstream cell (press enter to accept current choice): " \
-
-    walk $starting_folder || fail
-    if [[ "$result" ]]; then
-      upstream=$result
-    else 
-      fail1
-    fi
-
+    end_while
   end_function
   handle_return
 }
 
-up_add_command() {
+up_rm_command() {
   begin_function
 
     local choices=${choices:-${choice:-}} name=${name:-}
diff --git a/lib/help-lib b/lib/help-lib
--- a/lib/help-lib
+++ b/lib/help-lib
@@ -52,7 +52,10 @@ walk_menu() {
 
   local input
 
-  result=
+  response=
+  if [[ "$walk_filter" ]]; then
+    echo "${CYAN}Current filter:${RESET} $walk_filter"
+  fi
   if [[ $filter_mode == t ]]; then
     read -sp "Filtering results (press enter or space to accept filter): " -n1 input || return 1
     if [[ "$input" == $'\x7f' ]]; then
@@ -62,7 +65,7 @@ walk_menu() {
       walk_filter+=$input
       echo "$walk_filter"
     else
-      result=accept
+      response=accept
       echo "Accept filter"
     fi
   else
@@ -70,11 +73,11 @@ walk_menu() {
     for choice in "${choices[@]}" "${hidden_choices[@]}"; do
       walk_split_choice
       if [[ $key == $input || $key == enter && $input == '' ]]; then
-        result=$code
+        response=$code
         break
       fi
     done
-    if [[ "$result" ]]; then
+    if [[ "$response" ]]; then
       echo "${message%% *}"
     else
       echo
@@ -99,8 +102,8 @@ walk_add_choice() {
 }
 
 walk_add_dirs() {
-  local dirs d extra current_folder=$1
-  dirs=$(find -L $current_folder -mindepth 1 -maxdepth 1 -type d -not -name ".*" | sort -g) || return 1
+  local dirs d extra current_selection=$1
+  dirs=$(find -L $current_selection -mindepth 1 -maxdepth 1 -type d -not -name ".*" | sort -g) || return 1
   if [[ "$dirs" ]]; then
     for d in $dirs; do
       if [[ "${walk_filter:-}" ]]; then
@@ -119,6 +122,76 @@ walk_add_dirs() {
       walk_add_choice "$i" "${d#./}" "${d##*/}$extra"
     done
   fi
+}
+
+walk_init() {
+  show_selection() { :; }
+  adjust_choices() { :; }
+  handle_walk_responses() { :; }
+}
+
+walk() {
+  begin_function
+    echo "Choose upstream to add."
+
+    upstream=
+    local current_selection=$1 \
+      hidden_choices choices \
+      choice path i real_stack=() \
+      filter_mode=f walk_filter= \
+      prompt=${prompt:-Choose: } \
+
+    local -A code_set
+    begin_while true; doo
+
+      show_selection || fail
+
+      code_set=()
+      hidden_choices=(
+        "enter accept"
+        "q quit"
+        "? help"
+        "/ filter"
+        )
+      choices=()
+      i=0
+      adjust_choices || fail
+
+      walk_menu || break
+      if [[ $filter_mode == f ]]; then
+        if [[ "$response" == help ]]; then
+          echo "Press one of the characters in the menu to select one of the choices, enter or space to accept the choice, or q to quit/abort this command."
+          echo "You can also use / to enter filter mode and narrow down results."
+          echo "Using / again after a filter is applied will remove the filter."
+        elif [[ "$response" == quit ]]; then
+          exit 0
+        elif [[ "$response" == accept ]]; then
+          result=$current_selection
+          break
+        elif [[ "$response" == filter ]]; then
+          if [[ "$walk_filter" ]]; then
+            echo "Removed filter."
+            walk_filter=
+          else
+            filter_mode=t
+          fi
+        else
+          local invalid_response=f
+          handle_walk_responses || fail
+          if [[ $invalid_response == t ]]; then
+            echo "Invalid selection, try again."
+            continue
+          fi
+        fi
+      else # filter_mode == t
+        if [[ "$response" == accept ]]; then
+          filter_mode=f
+        fi
+      fi
+
+    end_while
+  end_function
+  handle_return
 }
 
 # inputs:
