.

diff --git a/command/update b/command/update
--- a/command/update
+++ b/command/update
@@ -119,26 +119,6 @@ update_upstream_prep() {
       mkdir $cyto_up_path || fail
     fi
 
-    if [[ -d $up_cyto ]]; then
-
-      if [[ $previous_upstream_changed == t ]]; then
-        log_debug "Previous upstream changed, removing cyto upstream"
-        rm -r "$up_cyto" || fail
-      else
-        # cyto already exists, don't need to update it here since it will be updated later anyway
-        succeed
-      fi
-
-    fi
-
-    local needs_update
-    mkdir $up_cyto || fail
-
-    if [[ ! -e $up_cyto ]]; then
-      log_debug "Cyto upstream is missing, will need to update"
-      needs_update=t
-    fi
-
     # This may be overridden by upstream prep file to customize how failure of this upstream is handled
     handle_upstream_result() {
       if [[ $update_successful == f ]]; then
@@ -146,7 +126,23 @@ update_upstream_prep() {
       fi
     }
 
-    prep_upstream || fail
+    if [[ -d $up_cyto ]]; then
+
+      if [[ $previous_upstream_changed == t ]]; then
+        log_debug "Previous upstream changed, removing cyto upstream"
+        rm -r "$up_cyto" || fail
+      fi
+
+    fi
+
+    if [[ ! -d $up_cyto ]]; then
+
+      log_debug "Cyto upstream is missing, will need to update"
+      mkdir $up_cyto || fail
+      local needs_update=t
+      prep_upstream || fail
+
+    fi
 
   end_function
   handle_return
