.

diff --git a/command/update b/command/update
--- a/command/update
+++ b/command/update
@@ -536,29 +536,17 @@ create_sub_branch() {
 
     mkdir $sub_var $sub_fun $sub_dim || fail
 
-    echo "${super_dims[*]:1}" >$sub_var/leaf_dims || fail
-
-    local dim
-    begin_for dim in ${super_dims[*]:1}; doo
-      local from_fun=$fun_path/${dim}_member_expand
-      local to_fun=$sub_fun/${dim}_member_expand
-      if [[ -e "$from_fun" ]]; then
-        safe_link $(realpath $from_fun) $to_fun || fail
-      else
-        log_fatal "Missing ${dim}_member_expand which should be in $fun_path"
-        fail1
-      fi
-    end_for
+    echo "${super_dims[*]:1}" >$sub_var/dims || fail
 
     local all_path=$dim_path/_all
     if [[ -d $all_path ]]; then
       from_path=$all_path to_path=$sub_dna_path link_dim_parts || fail
-      safe_link $(realpath $all_path) $to_path/ || fail
+      safe_link $(realpath $all_path) $sub_dim/ || fail
     fi
 
     local leaf_path=$dim_path/_leaf
     if [[ -d $leaf_path ]]; then
-      safe_link $(realpath $leaf_path) $sub_dim/ || fail
+      safe_link $(realpath $leaf_path) $sub_dim/_leaf || fail
     fi
 
   end_function
@@ -991,9 +979,11 @@ create_sub_cell_with_seed() {
 
 create_sub_cell() {
   local sub_cell=$1
-  find_seed $sub_cell || return 1
-  create_sub_cell_with_seed $seed $sub_cell || return 1
-  return 0
+  begin_function
+    find_seed $sub_cell || fail
+    create_sub_cell_with_seed $seed $sub_cell || fail
+  end_function
+  handle_return
 }
 
 update_member() {
@@ -1422,7 +1412,7 @@ setup_cyto_out() {
   handle_return
 }
 
-update() {
+update_command() {
   begin_function
 
     local leave_loop=0 something_changed=f
