.

diff --git a/command/update b/command/update
--- a/command/update
+++ b/command/update
@@ -334,43 +334,63 @@ find_seed() {
   handle_return
 }
 
-create_sub_branch() {
-  local log_show_vars=^sub_dna_path
-  begin_function
-
-    mkdir $sub_dna_path/dim || fail
-
-    local from_dim
-    begin_for from_dim in ${super_dims[*]:1}; doo
-      local to_dim=$sub_dna_path/dim/${from_dim##*/}
-      safe_link $(realpath $from_dim) $to_dim || fail
-    end_for
-
-    local contents=$(find1 $dna_path -not -name '.*') || fail
+link_dim_parts() {
+  local from_path=$from_path to_path=$to_path
+  begin_function_flat
+    local contents=$(find1 $from_path -not -name '.*') || fail
     begin_for part in $contents; doo
-      if [[ "$part" == */dim \
-         || "$part" == */context* \
-         || "$part" == */up \
+      if [[ "$part" == */up \
          || "$part" == */down \
-         || "$part" == */leaf \
-         || "$part" == */cyto-template \
          ]]; then
         continue
-      fi
-      safe_link $(realpath $part) $sub_dna_path/ || fail
-    end_for 
-
-    if [[ -d $dna_path/leaf ]]; then
-      local contents=$(find1 $dna_path/leaf -not -name '.*') || fail
-      mkdir $sub_dna_path/leaf || fail
-      begin_for part in $contents; doo
-        if [[ "$part" == */up \
-           || "$part" == */down \
+      elif [[ "$part" == */var \
+           || "$part" == */fun \
            ]]; then
-          continue
-        fi
-        safe_link $(realpath $part) $sub_dna_path/leaf/ || fail
-      end_for 
+        contents=$(find1 $part -not -name '.*') || fail
+        local folder=${part##*/} part2
+        begin_for part2 in $contents; doo
+          safe_link $(realpath $part2) $to_path/$folder/ || fail
+        end_for
+      else
+        safe_link $(realpath $part) $to_path/ || fail
+      fi
+    end_for 
+  end_function
+  handle_return
+}
+
+create_sub_branch() {
+  local log_show_vars=^sub_dna_path
+  begin_function_flat
+
+    local sub_var=$sub_dna_path/var \
+      sub_fun=$sub_dna_path/fun \
+      sub_dim=$sub_dna_path/dim 
+    mkdir $sub_var $sub_fun $sub_dim || fail
+
+    echo "${super_dims[*]:1}" >$sub_var/leaf_dims || fail
+
+    local dim
+    begin_for dim in ${super_dims[*]:1}; doo
+      local from_fun=$fun_path/${dim}_member_expand
+      local to_fun=$sub_fun/${dim}_member_expand
+      if [[ -e "$from_fun" ]]; then
+        safe_link $(realpath $from_fun) $to_fun || fail
+      else
+        log_fatal "Missing ${dim}_member_expand which should be in $fun_path"
+        fail1
+      fi
+    end_for
+
+    local all_path=$dna_path/dim/_all
+    if [[ -d $all_path ]]; then
+      from_path=$all_path to_path=$sub_dna_path link_dim_parts || fail
+      safe_link $(realpath $all_path) $to_path/ || fail
+    fi
+
+    local leaf_path=$dna_path/dim/_leaf
+    if [[ -d $leaf_path ]]; then
+      safe_link $(realpath $leaf_path) $sub_dim/ || fail
     fi
 
   end_function
@@ -379,23 +399,20 @@ create_sub_branch() {
 
 create_sub_leaf() {
   local log_show_vars=^sub_dna_path
-  begin_function
+  begin_function_flat
 
-    if [[ -d $dna_path/leaf ]]; then
-      local contents=$(find1 $dna_path/leaf -not -name '.*') || fail
-      local part
-      begin_for part in $contents; doo
-        if [[ "$part" == */up \
-           || "$part" == */down \
-           ]]; then
-          continue
-        fi
-        safe_link $(realpath $part) $sub_dna_path/ || fail
-      end_for 
+    local sub_var=$sub_dna_path/var \
+      sub_fun=$sub_dna_path/fun
+    mkdir $sub_var $sub_fun || fail
+
+    local all_path=$dna_path/dim/_all
+    if [[ -d $all_path ]]; then
+      from_path=$all_path to_path=$sub_dna_path link_dim_parts || fail
     fi
 
-    if [[ -d $dna_path/key ]]; then
-      safe_link $(realpath $dna_path/key) $sub_dna_path/ || fail
+    local leaf_path=$dna_path/dim/_leaf
+    if [[ -d $leaf_path ]]; then
+      from_path=$leaf_path to_path=$sub_dna_path link_dim_parts || fail
     fi
 
   end_function
@@ -427,7 +444,7 @@ create_sub_branch_or_leaf() {
       
       local sub_dna_path=$cell/.dna 
       mkdir $sub_dna_path || fail
-      local -r super_dims=( $(find1 $dna_path/dim -not -name '.*' | sort -g) ) || fail
+      local -r super_dims=( ${leaf_dims[*]} ) || fail
       local -r super_dim_count=${#super_dims[*]}
       if [[ "$super_dims" ]]; then
         local is_branch=f
