.

diff --git a/command/update b/command/update
--- a/command/update
+++ b/command/update
@@ -442,7 +442,7 @@ update_self() {
         fi
       fi
 
-      tee_output_to_log || fail
+      #tee_output_to_log || fail
       execute_op update || fail
       completion_time=$EPOCHSECONDS
       untee_output || fail
