.

diff --git a/command/update b/command/update
--- a/command/update
+++ b/command/update
@@ -854,11 +854,8 @@ append_dim_var_to_context() {
     if [[ "$value" == $empty_member ]]; then
       value=
     fi
-    debug_start
-    echo "$value" >$sub_var/$ddim || fail
-    echo "$ddim=\${$ddim:-\${$dim:-}} $ddims=\${$ddims:-\${$dims:-\${$ddim:-\${$dim:-}}}}" \
-      >$sub_var/localize_dims || fail
-    log_debug "Appending dim $ddim=$value to $sub_dna_path/context-before"
+    echo "$value" >$sub_var/$dim || fail
+    log_debug "Appending dim $dim=$value to $sub_var/$dim"
   end_function
   handle_return
 }
