.

diff --git a/command/update b/command/update
--- a/command/update
+++ b/command/update
@@ -743,16 +743,16 @@ update_self() {
 
     local reuse_existing_out=${reuse_existing_out:-t}
 
-    local out_path=$cell_path
+    local original_out_path=$out_path out_path=$out_path
+    debug_start
     if [[ $reuse_existing_out == f ]]; then
-      out_path=$cell_path.new
-      if [[ -d $out_path ]]; then
-        rm -rf $out_path || fail
+      if [[ -d $out_path.new ]]; then
+        rm -rf $out_path.new || fail
       fi
-      if [[ ! -d $out_path ]] && ! mkdir $out_path 2>/dev/null; then
-        log_debug "Could not make dir $out_path, falling back to $cell_path"
-        out_path=$cell_path
+      if [[ ! -d $out_path.new ]] && ! mkdir $out_path.new 2>/dev/null; then
+        log_debug "Could not make dir $out_path.new, falling back to $out_path"
       fi
+      out_path=$out_path.new
     else
       # allow update code to set this, since we can't compare when changes are made in place
       something_changed=
@@ -770,8 +770,8 @@ update_self() {
       update_successful=${update_successful:-f}
     fi
 
-    if [[ $reuse_existing_out == f && -d $cell_path.new ]]; then
-      out_path=$cell_path
+    if [[ $reuse_existing_out == f && -d $out_path ]]; then
+      out_path=$original_out_path
       if [[ $update_successful == t ]]; then
         local changed
         compare_files_or_dirs $out_path $out_path.new || fail
