.

diff --git a/command/update b/command/update
--- a/command/update
+++ b/command/update
@@ -1199,13 +1199,17 @@ update_command() {
     pre_update || fail
     update_upstreams || fail
     if [[ $update_successful == t ]]; then
-      if [[ "${leaf_dims:-}" ]]; then
-        update_members || fail
-      fi
       if [[ $cell_is_leaf == t ]]; then
         update_successful=
         update_self_retry_loop || fail
         check_results || fail
+      else
+        if [[ "${leaf_dims:-}" ]]; then
+          update_members || fail
+        else
+          log_fatal "Internal error: cell is not a leaf, yet it doesn't have leaf dims?"
+          fail1
+        fi
       fi
     fi
     post_update || fail
