.

diff --git a/command/update b/command/update
--- a/command/update
+++ b/command/update
@@ -363,9 +363,6 @@ create_sub_branch() {
   local log_show_vars=^sub_dna_path
   begin_function_flat
 
-    local sub_var=$sub_dna_path/var \
-      sub_fun=$sub_dna_path/fun \
-      sub_dim=$sub_dna_path/dim 
     mkdir $sub_var $sub_fun $sub_dim || fail
 
     echo "${super_dims[*]:1}" >$sub_var/leaf_dims || fail
@@ -401,8 +398,6 @@ create_sub_leaf() {
   local log_show_vars=^sub_dna_path
   begin_function_flat
 
-    local sub_var=$sub_dna_path/var \
-      sub_fun=$sub_dna_path/fun
     mkdir $sub_var $sub_fun || fail
 
     local all_path=$dna_path/dim/_all
@@ -443,6 +438,10 @@ create_sub_branch_or_leaf() {
       branch_dims+=( ${trunk_dims[$branch_dim_count]} )
       
       local sub_dna_path=$cell/.dna 
+      local sub_var=$sub_dna_path/var \
+        sub_fun=$sub_dna_path/fun \
+        sub_dim=$sub_dna_path/dim 
+
       mkdir $sub_dna_path || fail
       local -r super_dims=( ${leaf_dims[*]} ) || fail
       local -r super_dim_count=${#super_dims[*]}
@@ -855,9 +854,10 @@ append_dim_var_to_context() {
     if [[ "$value" == $empty_member ]]; then
       value=
     fi
-    echo "# Generated by create_sub_branch from $cell_path
-$ddim='$value'
-localize_dims+=' $ddim=\${$ddim:-\${$dim:-}} $ddims=\${$ddims:-\${$dims:-\${$ddim:-\${$dim:-}}}}'" >$sub_dna_path/context-before || fail
+    debug_start
+    echo "$value" >$sub_var/$ddim || fail
+    echo "$ddim=\${$ddim:-\${$dim:-}} $ddims=\${$ddims:-\${$dims:-\${$ddim:-\${$dim:-}}}}" \
+      >$sub_var/localize_dims || fail
     log_debug "Appending dim $ddim=$value to $sub_dna_path/context-before"
   end_function
   handle_return
