Fix anchor_dims bug

diff --git a/command/update b/command/update
--- a/command/update
+++ b/command/update
@@ -268,6 +268,7 @@ update_upstream_choose_single() {
     fi
     upstream_cell_link=$chosen
     cell_path=$(realpath $chosen)
+    anchor_dims= \
     switch_context
     get_needs_update || fail
   end_function
@@ -281,6 +282,7 @@ update_upstream_choose_multi() {
       if [[ -e "$chosen/.dna" ]]; then
         upstream_cell_link=$chosen
         cell_path=$(realpath $chosen)
+        anchor_dims= \
         switch_context
         get_needs_update || fail
       else
@@ -301,6 +303,7 @@ update_upstream_choose_multi() {
       begin_for choice in $choices; doo
         needs_update=
         cell_path=$(realpath $choice)
+        anchor_dims= \
         switch_context
         get_needs_update || fail
         if [[ $needs_update == f ]]; then
@@ -350,6 +353,7 @@ update_upstream_choose() {
     fi
 
     cell_path=$original_cell_path
+    anchor_dims=$original_anchor_dims
     switch_context || fail
 
   end_function
@@ -494,6 +498,7 @@ update_upstreams() {
     if [[ -d "${up_path:-}" ]]; then
 
       local previous_upstream_changed=f upstream upstreams 
+      local original_anchor_dims=${anchor_dims[*]}
 
       upstreams=$(find1 $up_path -not -name '.*' | sort -g) || fail
       begin_for upstream in $upstreams; doo
@@ -502,6 +507,8 @@ update_upstreams() {
           break
         fi
       end_for
+
+      anchor_dims=$original_anchor_dims
       switch_context || fail
 
     fi
@@ -666,7 +673,6 @@ update_member() {
     log_vars=member log_show_vars=member \
     upstream_cell_link=${upstream_cell_link:-} \
     original_cell_path=$cell_path \
-    anchor_dims \
 
   begin_function_hi
 
@@ -699,7 +705,6 @@ update_member() {
         log_debug "Only one member found, passing upstream_cell_link: $upstream_cell_link"
       fi
 
-      anchor_dims=${anchor_dims:-} \
       top_level_command=f \
       downstream_cell_name=${short_cell//\//_} \
       execute_command $member_path update || fail
@@ -716,23 +721,30 @@ update_member() {
       upstream_cell_link=
     fi
 
-    cell_path=$original_cell_path
-    switch_context || fail
+    #   This shouldn't be needed since we restore anchor_dims at end of update_members
+    # cell_path=$original_cell_path
+    # anchor_dims=$original_anchor_dims
+    # switch_context || fail
   end_function
   handle_return
 }
 
 update_members() {
   begin_function_hi
+
     local dim=${anchor_dims[0]}
-    local anchor_dims=( ${anchor_dims[*]:1} )
+    local original_anchor_dims=${anchor_dims[*]}
+    local anchor_dims=${anchor_dims[*]:1}
     update_successful=
     par=t fork=f function=update_member for_each_member $dim || fail
+
+    anchor_dims=$original_anchor_dims
     switch_context || fail
     if [[ ${update_successful:=t} == f ]]; then
       log_fatal "Failed to update some member(s)"
       fail1
     fi
+
   end_function
   handle_return
 }
