.

diff --git a/command/update b/command/update
--- a/command/update
+++ b/command/update
@@ -1,20 +1,26 @@
 #!/usr/bin/env bash
 
-update() {
-  begin_function_flat
-    local leave_loop=0
-    break_if_not_changed || fail
-    if (( leave_loop > 0 )); then
-      break
+create_cyto_for_upstream() {
+  local upstream=$1
+  begin_function
+  end_function
+  handle_return
+}
+
+create_cyto_up() {
+  begin_function
+
+    if [[ -d "${dna_up_path:-}" ]]; then
+      upstreams=( $(find1 $dna_up_path -not -name '.*' | sort -g) )
+    else
+      upstreams=
     fi
-    pre_update || fail
-    create_downstream_links || fail
-    update_upstreams || fail
-    update_members || fail
-    create_sub_cells || fail
-    update_self_retry_loop || fail
-    check_results || fail
-    post_update || fail
+
+    local upstream
+    begin_for upstream in $upstreams; doo
+      create_cyto_for_upstream $upstream || fail
+    end_for
+
   end_function
   handle_return
 }
@@ -101,30 +107,132 @@ update_upstreams() {
   begin_function
 
     if [[ -d "${dna_up_path:-}" && ! "$update_successful" ]]; then
-      upstreams=( $(find1 $dna_up_path \
-        -not -name '.*' \
-        -not -name '*.prep' \
-        -not -regex '.*/\([0-9]+-\)?\(before\|after\|choose\)-.*' \
-        | sort -g \
-        ) )
-      previous_upstream_changed=f
-    else
-      upstreams=
-    fi
+      local upstreams=( $(find1 $dna_up_path -not -name '.*' | sort -g) ) || fail
+      local previous_upstream_changed=f
 
-    local upstream
-    begin_for upstream in $upstreams; doo
-      update_upstream || fail
-    end_for
+      local upstream
+      begin_for upstream in $upstreams; doo
+        update_dna_upstream || fail
+      end_for
+
+      upstreams=( $(find1 $cyto_up_path -not -name '.*' | sort -g) )
+      begin_for upstream in $upstreams; doo
+        update_cyto_upstream || fail
+      end_for
+
+    fi
 
   end_function
   handle_return
 }
 
-update_upstream() {
+update_dna_upstream_choice() {
+  begin_function
+
+    if [[ "${localize_dim_vars:-}" ]]; then
+      eval "$localize_dim_vars"
+    fi
+
+    if [[ $needs_update == t ]]; then
+      downstream_ref_path=$up_cyto \
+        execute_command "$(realpath $up_dna)" update || fail
+
+      previous_upstream_changed=t
+      handle_upstream_result || fail
+    fi
+    
+  end_function
+  handle_return
+}
+
+# inputs: 
+#   upstream: a folder in .dna/up
+update_dna_upstream() {
 
   local required_freshness=$required_freshness fresh=$fresh \
     default_freshness=$default_freshness up_dna=$upstream
+
+  local log_show_vars=^up_dna 
+  begin_function
+
+    local up_part=${up_dna##*/}
+    local up_cyto=$cyto_up_path/$up_part
+
+    if [[ -d $up_cyto ]]; then
+
+      if [[ $previous_upstream_changed == t ]]; then
+        log_debug "Previous upstream changed, removing cyto upstream"
+        rm -r "$up_cyto" || fail
+      else
+        # cyto already exists, don't need to update it here since it will be updated later anyway
+        succeed
+      fi
+
+    fi
+
+    # This may be overridden by upstream prep file to customize how failure of this upstream is handled
+    handle_upstream_result() {
+      if [[ $update_successful == f ]]; then
+        log_error "Failed to update upstream cell $up_dna"
+      else 
+        update_successful=
+      fi
+    }
+
+    local needs_update
+    mkdir "$up_cyto" || fail
+
+    if [[ ! -e $up_cyto ]]; then
+      log_debug "Cyto upstream is missing, will need to update"
+      if [[ -e $up_dna/prep && ! -e $up_cyto/prep ]]; then
+        safe_link $up_dna/prep $up_cyto/prep || fail
+      fi
+      needs_update=t
+    fi
+
+    prep_upstream $up_cyto || fail
+
+    local choices=$(find1 $up_dna/choices -not -name ".*" | sort -g) || fail
+
+    begin_for choice in $choices; doo
+
+      needs_update=
+      if [[ ! "$needs_update" ]]; then
+        get_needs_update $choice || fail
+      fi
+
+      downstream_ref_path=$up_cyto \
+        update_dna_upstream_choice $choice || fail
+      handle_upstream_result || fail
+
+      if [[ $cell_output_changed == t ]]; then
+        previous_upstream_changed=t
+      fi
+
+      if
+      then
+        succeed
+      fi
+
+    end_for
+
+    write_lock=f \
+    timeout=$lock_timeout \
+      cell_lock $up_cyto || fail
+
+    touch $status_path/deps-up-to-date || return 1
+    touch $status_path/up-to-date || return 1
+
+  end_function
+  handle_return
+}
+
+# inputs: 
+#   upstream: a cyto upstream folder
+update_cyto_upstream() {
+
+  local required_freshness=$required_freshness fresh=$fresh \
+    default_freshness=$default_freshness up_cyto=$upstream
 
   local log_show_vars=^up_dna 
   begin_function
@@ -144,9 +252,9 @@ update_upstream() {
 
     local needs_update=
     local up_part=${up_dna##*/}
-    local up_cyto=$up_path/$up_part
-    if [[ ! -d "$up_path" ]]; then
-      mkdir "$up_path" || fail
+    local up_cyto=$cyto_up_path/$up_part
+    if [[ ! -d "$cyto_up_path" ]]; then
+      mkdir "$cyto_up_path" || fail
     fi
 
     if [[ $previous_upstream_changed == t && -e "$up_cyto" ]]; then
@@ -430,3 +538,24 @@ post_update() {
   end_function
   handle_return
 }
+
+update() {
+  begin_function_flat
+    local leave_loop=0
+    break_if_not_changed || fail
+    if (( leave_loop > 0 )); then
+      break
+    fi
+    pre_update || fail
+    create_downstream_links || fail
+    create_cyto_up || fail
+    update_upstreams || fail
+    update_members || fail
+    create_sub_cells || fail
+    update_self_retry_loop || fail
+    check_results || fail
+    post_update || fail
+  end_function
+  handle_return
+}
+
