Auto create data.tab when possible

diff --git a/command/update b/command/update
--- a/command/update
+++ b/command/update
@@ -774,6 +774,15 @@ update_self() {
       update_successful=${update_successful:-f}
     fi
 
+    if [[ -d $out_path/export && ! -f $out_path/export/data.tab ]]; then
+      local exported_files=( $(find1 $out_path/export -type f -not -name '.*') ) || fail
+      if (( ${#exported_files[*]} == 1 )); then
+        local var_name=${exported_files##*/}
+        var_name=${var_name%.*}
+        echo "$var_name" | cat - $exported_files >$out_path/export/data.tab || fail
+      fi
+    fi
+
     if [[ $reuse_existing_out == f && -d $out_path ]]; then
       out_path=$original_out_path
       if [[ $update_successful == t ]]; then
