.

diff --git a/command/update b/command/update
--- a/command/update
+++ b/command/update
@@ -292,18 +292,20 @@ update_upstream_choose() {
         fail1
       fi
 
-      # are any already updated?
-      local choice
-      begin_for choice in $choices; doo
+      if [[ "$choices" == *$NL* ]]; then
+        # are any already updated?
+        local choice
+        begin_for choice in $choices; doo
 
-        needs_update= \
-        get_needs_update $choice || fail
-        if [[ $needs_update == f ]]; then
-          chosen=$choice
-          break
-        fi
+          needs_update= \
+          get_needs_update $choice || fail
+          if [[ $needs_update == f ]]; then
+            chosen=$choice
+            break
+          fi
 
-      end_for
+        end_for
+      fi
 
       if [[ ! "$chosen" ]]; then
         chosen=${choices%% *}
@@ -519,10 +521,10 @@ create_sub_cell() {
       fail1
     fi
 
-    if [[ -e $sub_cell ]]; then
-      log_fatal "sub_cell already exists: $sub_cell"
-      fail1
-    fi
+    # if [[ -e $sub_cell ]]; then
+    #   log_fatal "sub_cell already exists: $sub_cell"
+    #   fail1
+    # fi
 
     if [[ "$parent_cell" == "$sub_cell" ]]; then
       log_fatal "Can't create sub cells in a cell without parents: $sub_cell"
@@ -534,6 +536,7 @@ create_sub_cell() {
     parent_path=$parent_cell \
     seed_path=$parent_seed \
     member=$member \
+    repair=t \
     plant_member || fail
 
   end_function
@@ -551,7 +554,7 @@ update_member() {
     member_path=$cell_path/$dim:$sane_value
 
     local needs_update=
-    if [[ ! -d $member_path ]]; then
+    if [[ ! -d $member_path/.dna ]]; then
       parent_cell=$cell_path \
       parent_seed=$seed_path \
       sub_cell=$member_path \
