.

diff --git a/command/update b/command/update
--- a/command/update
+++ b/command/update
@@ -627,7 +627,7 @@ append_dim_var_to_context() {
     if [[ "$value" == $empty_member ]]; then
       value=
     fi
-    echo "$value" >$sub_var/$dim || fail
+    echo "$value" >$sub_var/$ddim || fail
   end_function
   handle_return
 }
@@ -1026,7 +1026,7 @@ update_member() {
       execute_command $member_path update || fail
 
       if [[ $update_successful == f ]]; then
-        error "Failed to update member cell $member"
+        log_error "Failed to update member cell $member"
         reply_to_caller "update_successful=f" || fail
       else 
         update_successful=
