.

diff --git a/command/update b/command/update
--- a/command/update
+++ b/command/update
@@ -189,21 +189,22 @@ create_downstream_links() {
     down_cell_path=$bottom_cell
 
     local down_link=$down_path/$downstream_cell_name
-    if [[ ! -e $down_link ]]; then
-      if [[ ! -d $down_path ]]; then
-        mkdir $down_path || fail
-      fi
-      safe_link $down_cell_path $down_link || fail
-    else
-      local link_target=$(readlink $down_link) || fail
-      if [[ $link_target != $down_cell_path ]]; then
-        log_fatal "Link conflict: A link already exists but doesn't point to the same place."
-        log_fatal "  source:   $down_link"
-        log_fatal "  target 1: $down_cell_path"
-        log_fatal "  target 2: $link_target"
-        fail1
-      fi
+    if [[ ! -d $down_path ]]; then
+      mkdir $down_path || fail
     fi
+    force=t safe_link $down_cell_path $down_link || fail
+
+#      let's just replace this each time for now
+#    if [[ -e $down_link ]]; then
+#      local link_target=$(readlink $down_link) || fail
+#      if [[ $link_target != $down_cell_path ]]; then
+#        log_fatal "Link conflict: A link already exists but doesn't point to the same place."
+#        log_fatal "  source:   $down_link"
+#        log_fatal "  target 1: $down_cell_path"
+#        log_fatal "  target 2: $link_target"
+#        fail1
+#      fi
+#    fi
 
   end_function
   handle_return
