Fix migrate prep bug

diff --git a/command/update b/command/update
--- a/command/update
+++ b/command/update
@@ -661,6 +661,130 @@ localize_dim_vars+=' $ddim=\${$ddim:-\${$dim:-}} $ddims=\${$ddims:-\${$dims:-\${
   handle_return
 }
 
+promote_dep_cell() {
+  local log_show_vars=^from
+  begin_function
+
+    local trunk_cell=
+    get_trunk_cell $from || fail
+
+    local dims= last_cell_dims_loaded
+    load_dims $trunk_cell/.dna/dim || fail
+
+    local dep_dim already_promoted_path=$from
+
+    # We don't need to promote all dims in target, but only the dims in the source
+    # e1 -> e1, not e1 -> e1/ods
+    # only promote what is in source + provided by prep
+    #   can't just promote because a var exists, only if it's actually used at that point
+
+    begin_for dep_dim in ${dims[*]}; doo
+
+      log_debug "Considering promotion of $dep_dim"
+
+      # is this dim already promoted?
+      if [[ $already_promoted_path == */.dim/* ]]; then
+        already_promoted_path=${already_promoted_path%/.dim/*}
+        log_debug "Already promoted: $dep_dim"
+        continue
+      fi
+
+      local branch_dim found_branch_dim=f
+      # upstream prep script can add extra_dims as needed
+      # branch_dims here is the full set of dims for the subject cell, whereas 
+      #   dims is the full set of dims for the upstream cell being promoted
+      begin_for branch_dim in ${branch_dims[*]} ${extra_dims[*]}; doo
+        if [[ $branch_dim == $dep_dim ]]; then
+          log_debug "Found branch dim for $dep_dim"
+          found_branch_dim=t
+          break
+        fi
+      end_for
+
+      local values=
+      if [[ $found_branch_dim == f ]]; then
+        # can't promote if dep dim doesn't exist on the branch 
+        log_debug "Upstream dim not found in base branch dims: $dep_dim"
+        if [[ $cell_is_leaf == t ]]; then
+          if type -t ${dep_dim}_member_expand >/dev/null; then
+            value= ${dep_dim}_member_expand 
+            if [[ "$values" ]]; then
+              log_debug "Found default for $dep_dim = $values"
+            fi
+          fi
+          if [[ ! "$values" ]]; then
+            log_fatal "Leaf cell was unable to resolve upstream dep to a leaf also. Missing dim $dep_dim"
+            fail1
+          fi
+        else
+          break
+        fi
+      fi
+
+      local dep_dim_var=d_$dep_dim
+
+      if [[ -v $dep_dim_var ]]; then
+        values=${!dep_dim_var}
+        if type -t ${dep_dim}_member_expand >/dev/null; then
+          value=$values ${dep_dim}_member_expand
+        fi
+      fi
+
+      values=( $values )
+
+      if [[ "${#values[*]}" -gt 1 ]]; then
+        log_fatal "Multiple values in dependency dims not yet supported (dim=$dep_dim)"
+        fail1
+      fi
+
+      if [[ "${values:-}" ]]; then
+        local sane_value
+        get_sane_value "$values" || fail
+        local old_from=$from
+        from=$from/.dim/$sane_value
+        log_debug "Promoted $dep_dim"
+        if [[ ! -d $from ]]; then
+          eval "$dep_dim_var=\"$values\""
+          log_debug "Creating sub for $from"
+          fork_fg "load_context_and_create_sub $old_from $from" || fail
+        fi
+      else
+        log_debug "Did not promote $dep_dim because no value is found for it yet"
+        break
+      fi
+
+    end_for
+  end_function
+  handle_return
+}
+
+# should be forked because dims will be altered
+# from and to are paths to up/choices/{upstream} which must be a cell
+migrate_cell() {
+  local -r dep_link=$1 to=$2
+  local from=$(realpath $dep_link) 
+  local log_vars=from log_show_vars="^dep_link ^to"
+  begin_function
+
+    if [[ "$from" == */.dna/sub/* ]]; then
+      local fixed_from=${from//.dna\/sub\//}
+      if [[ -d $fixed_from ]]; then
+        rm $dep_link || fail
+        safe_link $fixed_from $dep_link || fail
+        from=$fixed_from
+      else
+        log_fatal "Dependencies must link to planted cells, not seeds: $from"
+        fail1
+      fi
+    fi
+
+    promote_dep_cell || fail
+    safe_link $from $to || fail
+
+  end_function
+  handle_return
+}
+
 # from and to are paths to cells
 migrate_dep2() {
   local from=$1 to=$2
@@ -705,6 +829,10 @@ migrate_dep() {
           mkdir $to/$dep_name || fail
         fi
 
+        if [[ -f $dep/prep ]]; then
+          safe_link $dep/prep $to/$dep_name/prep || fail
+        fi
+
         if [[ -d $dep/cell ]]; then
           migrate_dep2 $dep/cell $to/$dep_name/cell || fail 
         elif [[ -d $dep/choices ]]; then
@@ -717,8 +845,6 @@ migrate_dep() {
             local choice_name=${choice##*/}
             migrate_dep2 $choice $to/$dep_name/choices/$choice_name || fail
           end_for
-#        elif [[ -d $dep/.dna ]]; then
-#          migrate_dep2 $dep $to/$dep_name || fail 
         else
           log_fatal "Dependency is missing choices or cell folder: $dep"
           fail1
