Fix branch dim propagation bug

diff --git a/command/update b/command/update
--- a/command/update
+++ b/command/update
@@ -443,7 +443,7 @@ update_upstream() {
 }
 
 update_upstreams() {
-  begin_function_hi
+  begin_function
 
     if [[ "$update_successful" == f ]]; then
       succeed
@@ -611,7 +611,7 @@ find_seed_dna() {
 }
 
 append_dim_var_to_context() {
-  local dim=$1
+  local -r dim=$dim target_folder=$target_folder
   begin_function
     local ddim=d_$dim
     if [[ ! -v $ddim ]]; then
@@ -622,7 +622,7 @@ append_dim_var_to_context() {
     if [[ "$value" == $empty_member ]]; then
       value=
     fi
-    echo "$value" >$sub_var/$ddim || fail
+    echo "$value" >$target_folder/$ddim || fail
   end_function
   handle_return
 }
@@ -920,10 +920,15 @@ create_sub_branch_or_leaf() {
         if (( super_dim_count > 1 )); then
           is_branch=t
           create_sub_branch || fail
+          local target_folder=$sub_dim/_all/var
+          if [[ ! -d $target_folder ]]; then
+            mkdir $target_folder || fail
+          fi
+          target_folder=$target_folder dim=${super_dims[0]} append_dim_var_to_context  || fail
         else
           create_sub_leaf || fail
+          target_folder=$sub_var dim=${super_dims[0]} append_dim_var_to_context  || fail
         fi
-        append_dim_var_to_context ${super_dims[0]} || fail
         migrate_deps || fail
       fi
     fi
@@ -1152,7 +1157,7 @@ update_self() {
       fi
 
       tee_output_to_log || fail
-      execute_op update || fail
+      ignore_missing=t execute_op update || fail
       completion_time=$EPOCHSECONDS
       untee_output || fail
 
