.

diff --git a/command/update b/command/update
--- a/command/update
+++ b/command/update
@@ -1,5 +1,173 @@
 #!/usr/bin/env bash
 
+get_upstream_needs_update() {
+
+  local cell_path=$1
+  local short_cell \
+    cyto_up_path=$cell_path/.cyto/up \
+    dna_up_path=$cell_path/.dna/up 
+  get_short_cell $cell_path
+
+  local log_show_vars=short_cell log_vars=cell_path
+  begin_function_hi
+    if [[ "${dna_up_path:-}" && -d "$dna_up_path" ]] \
+       && (( check_upstream_depth > 0 )); then
+      #log_debug "Checking upstream of $short_cell"
+      local -r upstream_cells=( 
+        $(find1 $dna_up_path -not -name '.*' | sort -g) 
+        ) || fail
+      local up up_part
+      begin_for up in ${upstream_cells[*]}; doo
+
+        up_part=${up##*/}
+        log_debug "Checking $up_part"
+        up_cyto=$cyto_up_path/$up_part/chosen
+        if [[ ! -e $up_cyto ]]; then
+          log_debug "Cyto up is missing, needs update"
+          needs_update=t
+          break
+        fi
+
+        # recursive
+        check_upstream_depth=$((check_upstream_depth-1)) get_needs_update $up_cyto || fail
+
+        if [[ $needs_update == t ]]; then
+          break
+        fi
+
+      end_for
+    fi
+
+    # restore context
+    load_context || fail
+
+  end_function
+  handle_return
+
+}
+
+get_leaf_needs_update() {
+  needs_update=
+  if [[ ! "${leaf_path:-}" ]]; then
+    log_fatal "leaf_path is missing"
+    return 1
+  fi
+  local leaf_cell_path=$cell_path$leaf_path
+
+  if [[ -d $leaf_cell_path ]]; then
+    # recursive
+    get_needs_update $leaf_cell_path || return 1
+  else
+    needs_update=t
+  fi
+
+  if [[ $needs_update == t ]]; then
+    leave_loop=1
+  fi
+  return 0
+}
+
+# returns needs_update
+get_needs_update() {
+  if [[ ! -e $1 ]]; then
+    log_fatal "Cell doesn't exist: $1"
+    stack_trace
+    return 1
+  fi
+
+  local cell_path=$(realpath $1) short_cell
+
+  local log_show_vars=^cell_path
+  begin_function_hi
+
+    local localize_dims=${localize_dims:-} $dim_vars
+
+    load_context || fail
+
+    local status_path=$cell_path/.cyto/status \
+      cyto_up_path=$cell_path/.cyto/up \
+      log_message="No update needed" \
+      check_upstream_depth=${check_upstream_depth:-1}
+
+    if [[ "$needs_update" ]]; then
+      # needs_update is already known, don't need to compute it again
+      log_message="needs_update is already set."
+      succeed
+    fi
+
+    if [[ ! -d $cell_path/.dna ]]; then
+      log_fatal "Attempted to run get_needs_update on folder that is not a cell: $cell_path"
+      fail1
+    fi
+
+    if [[ "$out_file" && ! -e "$out_path/$out_file" ]]; then
+      needs_update=t
+      log_message="Needs update because output file doesn't exist"
+    elif (( refresh_less_than > update_cost ))
+    then
+      needs_update=t
+      log_message="Needs update because update_cost ($update_cost) < refresh_less_than ($refresh_less_than)"
+    elif [[ ! -e $status_path/last-good-update-end ]]
+    then
+      needs_update=t
+      log_message="Needs update because cell has never been updated successfully"
+    elif [[ ! -e $status_path/up-to-date ]]
+    then
+      needs_update=t
+      log_message="Needs update because something changed"
+    elif get_prop_changed $cell_path || fail
+         [[ $prop_changed == t ]]
+    then
+      needs_update=t
+      log_message="Needs update because properties have changed"
+    elif get_is_stale $status_path || fail
+         [[ $is_stale == t ]]
+    then
+      needs_update=t
+      log_message="Needs update because cell is stale"
+    elif [[ -v leaf_dims ]] \
+         && { 
+           function=get_leaf_needs_update \
+             for_each_leaf_flat ${leaf_dims[*]} || fail 
+         } \
+         && { 
+           load_context || fail
+         } \
+         && [[ $needs_update == t ]]
+    then
+      log_message="Needs update because at least one leaf cell is out of date"
+    elif [[ -v dna_up_path ]] \
+         && { get_upstream_needs_update $cell_path || fail; } \
+         && [[ $needs_update == t ]]
+    then
+      log_message="Needs update because at least one upstream cell is out of date"
+    elif local data_valid=t
+      ignore_missing=t execute_op check || fail
+      [[ $data_valid == f ]]
+    then
+      needs_update=t
+      log_message="Needs update because current value does not match intended value"
+    fi
+
+  end_function
+
+  if succeeded; then
+    local level=log_verbose
+    if [[ ${cell_is_leaf:-t} == t || $show_branches == t || $top_level_command == t ]]; then
+      level=log_info
+    fi
+    action=update_check $level "$log_message ($short_cell)"
+  else
+    action=update_check log_fatal "Failed to check update need"
+  fi
+
+  if [[ ! "$needs_update" ]]; then
+    needs_update=f
+  fi
+
+  handle_return
+}
+
 break_if_not_changed() {
   begin_function
     if [[ ! "${needs_update:-}" ]]; then
@@ -1117,10 +1285,6 @@ post_update() {
           from_cell=$cell_path \
             propagate_change_to_downstream || fail
         fi
-        if [[ "${downstream_ref_path:-}" ]]; then
-          log_debug "Linking upstream cell to it's downstream cell cyto up folder"
-          force=t safe_link $cell_path $downstream_ref_path/chosen || fail
-        fi
       else
         touch -d @$completion_time $status_path/last-bad-update-end || fail
         force=t safe_link $current_job_path $job_path/last-failure || fail
@@ -1263,12 +1427,18 @@ update() {
     local leave_loop=0 something_changed=f
     needs_update= 
 
+    create_downstream_links || fail
+    if [[ "${downstream_ref_path:-}" ]]; then
+      log_debug "Linking upstream cell to it's downstream cell cyto up folder"
+      force=t safe_link $cell_path $downstream_ref_path/chosen || fail
+    fi
+
     break_if_not_changed || fail
     if (( leave_loop > 0 )); then
       succeed
     fi
+
     pre_update || fail
-    create_downstream_links || fail
     update_upstreams || fail
     if [[ $update_successful == t ]]; then
       update_successful=
