Fix update bug

diff --git a/command/update b/command/update
--- a/command/update
+++ b/command/update
@@ -162,8 +162,8 @@ update_upstream_choose() {
       local choices=$(find1 $up_dna/choices -not -name ".*" | sort -g) || fail
 
       if [[ ! "$choices" ]]; then
-        log_debug "No choices for upstream. Skipping."
-        succeed
+        log_fatal "No choices defined for upstream $up_dna"
+        fail1
       fi
 
       # are any already updated?
@@ -187,6 +187,7 @@ update_upstream_choose() {
       fail1
     fi
 
+    local log_show_vars=chosen
   end_function
   handle_return
 }
@@ -248,6 +249,11 @@ update_upstream() {
     local chosen=
     update_upstream_choose || fail
 
+    if [[ ! "$chosen" ]]; then
+      log_fatal "chosen was not set."
+      fail1
+    fi
+
     if [[ ! -e $up_cyto/chosen ]]; then
       needs_update=t
     fi
@@ -297,7 +303,7 @@ update_upstreams() {
 
       local previous_upstream_changed=f upstream upstreams
 
-      upstreams=( $(find1 $dna_up_path -not -name '.*' | sort -g) ) || fail
+      upstreams=$(find1 $dna_up_path -not -name '.*' | sort -g) || fail
       begin_for upstream in $upstreams; doo
         update_upstream || fail
         if [[ $update_successful == f ]]; then
@@ -840,9 +846,13 @@ migrate_dep() {
           if [[ ! -d $to/$dep_name/choices ]]; then
             mkdir $to/$dep_name/choices || fail
           fi
-          choices=$(find1 $dep/choices -type d -not -name '.*') || fail
+          choices=$(find1 $dep/choices -not -name '.*') || fail
           begin_for choice in $choices; doo
             local choice_name=${choice##*/}
+            if [[ ! -d "$choice" ]]; then
+              log_fatal "Invalid config for $dep: $choice_name is not a folder"
+              fail1
+            fi
             migrate_dep2 $choice $to/$dep_name/choices/$choice_name || fail
           end_for
         else
