Updated the init script to always update our modules when run on remote-server

diff --git a/docker/init b/docker/init
--- a/docker/init
+++ b/docker/init
@@ -35,6 +35,19 @@ main() {
   for bin_folder in ${bin_folders[*]}; do
     ln -sf $bin_folder/* /usr/bin/ || return 1
   done
+  
+  if [[ ${run_context:=local} == remote ]]; then
+    # Clean and pull latest changes for modules
+    local module_repos=$(find -L /repo -mindepth 1 -maxdepth 1 -type d -not -name '.*' -not -name 'simpleton') || return 1
+    for repo in $module_repos; do
+      git -C $repo checkout main >/dev/null 2>&1 || { echo 'failed to checkout main'; return 1; }
+      if [[ ! -z "$(git -C $repo status --porcelain)" ]]; then
+        git -C $repo reset --hard HEAD >/dev/null 2>&1
+        git -C $repo clean -ffdx >/dev/null 2>&1
+      fi
+      git -C $repo pull >/dev/null 2>&1 || { echo 'failed to pull latest changes'; return 1; }
+    done
+  fi
 
   cd /work || return 1
   local modules=( $(find -L /work -mindepth 1 -maxdepth 1 -type d -not -name '.*') ) || return 1 
@@ -42,6 +55,12 @@ main() {
     source /etc/profile.d/shell-start-0.sh || return 1
     export SIMPLETON_LIB=$SIMPLETON_REPO/lib
     cell plant || echo "Failed to plant cells." >&2
+  else
+    if [[ $run_context == remote ]]; then
+      for module in ${modules[*]}; do
+        (cd $module; clean-all >/clean-results 2>&1)
+      done
+    fi
   fi
 
   if [[ "${COMMAND:-}" ]]; then
