Minor change

diff --git a/docker/init b/docker/init
--- a/docker/init
+++ b/docker/init
@@ -42,11 +42,11 @@ main() {
     for repo in $module_repos; do
       git -C $repo checkout main >/dev/null 2>&1 || { echo 'failed to checkout main'; return 1; }
       if [[ ! -z "$(git -C $repo status --porcelain)" ]]; then
-        git -C "$repo" fetch --prune origin >/dev/null 2>&1
-        git -C "$repo" reset --hard origin/main >/dev/null 2>&1
-        git -C "$repo" clean -ffdx >/dev/null 2>&1
+        git -C "$repo" fetch --prune origin &>/dev/null
+        git -C "$repo" reset --hard origin/main &>/dev/null
+        git -C "$repo" clean -ffdx &>/dev/null
       fi
-      git -C $repo pull >/dev/null 2>&1 || { echo 'failed to pull latest changes'; return 1; }
+      git -C $repo pull &>/dev/null || { echo 'failed to pull latest changes'; return 1; }
     done
   fi
 
@@ -59,7 +59,7 @@ main() {
   else
     if [[ $run_context == remote ]]; then
       for module in ${modules[*]}; do
-        (cd $module; clean-all >/clean-results 2>&1)
+        (cd $module; rm -rf ${module:-/work/one-data}/* &>/clean-results; plant)
       done
     fi
   fi
