Fixed issue with rm not removing derive-cache and .lib folder

diff --git a/docker/init b/docker/init
--- a/docker/init
+++ b/docker/init
@@ -60,8 +60,9 @@ main() {
     cell plant || echo "Failed to plant cells." >&2
   else
     if [[ $run_context == remote ]]; then
-      rm -rf /work/one-data/* &>/dev/null
-      (cd /work/one-data; clean-cache &>/dev/null; cell plant || echo "Failed to plant cells." >&2)
+      rm -rf /work/one-data/* /work/one-data/.lib || return 1
+      cd /work/one-data || return 1
+      cell plant || echo "Failed to plant cells." >&2
     fi
   fi
 
