minor patch

diff --git a/docker/init b/docker/init
--- a/docker/init
+++ b/docker/init
@@ -59,7 +59,7 @@ main() {
   else
     if [[ $run_context == remote ]]; then
       rm -rf /work/one-data/* &>/dev/null
-      (cd /work/one-data; cell plant || echo "Failed to plant cells." >&2)
+      (cd /work/one-data; clean-cache; cell plant || echo "Failed to plant cells." >&2)
     fi
   fi
 
