added simp_plant check

diff --git a/docker/init b/docker/init
--- a/docker/init
+++ b/docker/init
@@ -52,17 +52,19 @@ main() {
     unset GIT_TERMINAL_PROMPT
   fi
 
-  cd /work || return 1
-  local modules=( $(find -L /work -mindepth 1 -maxdepth 1 -type d -not -name '.*') ) || return 1 
-  if (( ${#modules[*]} == 0 )); then
-    source /etc/profile.d/shell-start-0.sh || return 1
-    export SIMPLETON_LIB=$SIMPLETON_REPO/lib
-    cell plant || echo "Failed to plant cells." >&2
-  else
-    if [[ $run_context == remote && ${work_refresh:-t} == t ]]; then
-      rm -rf /work/one-data/* /work/one-data/.lib || return 1
-      cd /work/one-data || return 1
+  if [[ ${simp_plant:-t} == t ]]; then
+    cd /work || return 1
+    local modules=( $(find -L /work -mindepth 1 -maxdepth 1 -type d -not -name '.*') ) || return 1 
+    if (( ${#modules[*]} == 0 )); then
+      source /etc/profile.d/shell-start-0.sh || return 1
+      export SIMPLETON_LIB=$SIMPLETON_REPO/lib
       cell plant || echo "Failed to plant cells." >&2
+    else
+      if [[ $run_context == remote && ${work_refresh:-t} == t ]]; then
+        rm -rf /work/one-data/* /work/one-data/.lib || return 1
+        cd /work/one-data || return 1
+        cell plant || echo "Failed to plant cells." >&2
+      fi
     fi
   fi
 
