minor patch

diff --git a/docker/init b/docker/init
--- a/docker/init
+++ b/docker/init
@@ -58,9 +58,8 @@ main() {
     cell plant || echo "Failed to plant cells." >&2
   else
     if [[ $run_context == remote ]]; then
-      for module in ${modules[*]}; do
-        (cd $module; rm -rf ${module:-/work/one-data}/* &>/clean-results; plant)
-      done
+      rm -rf /work/one-data/* &>/dev/null
+      (cd /work/one-data; cell plant || echo "Failed to plant cells." >&2)
     fi
   fi
 
