Fixed git issue

diff --git a/docker/init b/docker/init
--- a/docker/init
+++ b/docker/init
@@ -39,15 +39,19 @@ main() {
   if [[ ${run_context:=local} == remote ]]; then
     # Clean and pull latest changes for modules
     local module_repos=$(find -L /repo -mindepth 1 -maxdepth 1 -type d -not -name '.*' -not -name 'simpleton') || return 1
+    export GIT_TERMINAL_PROMPT=0
     for repo in $module_repos; do
-      git -C $repo checkout main >/dev/null 2>&1 || { echo 'failed to checkout main'; return 1; }
-      if [[ ! -z "$(git -C $repo status --porcelain)" ]]; then
-        git -C "$repo" fetch --prune origin &>/dev/null
-        git -C "$repo" reset --hard origin/main &>/dev/null
-        git -C "$repo" clean -ffdx &>/dev/null
+      if git -C "$repo" rev-parse --is-inside-work-tree &>/dev/null; then
+        git -C "$repo" checkout -q main &>/dev/null
+        if [[ -n "$(git -C "$repo" status --porcelain 2>/dev/null)" ]]; then
+          git -C "$repo" fetch -q --prune origin &>/dev/null
+          git -C "$repo" reset -q --hard origin/main &>/dev/null
+          git -C "$repo" clean -ffdxq &>/dev/null
+        fi
+        git -C "$repo" pull -q &>/dev/null
       fi
-      git -C $repo pull &>/dev/null || { echo 'failed to pull latest changes'; return 1; }
     done
+    unset GIT_TERMINAL_PROMPT
   fi
 
   cd /work || return 1
@@ -59,7 +63,7 @@ main() {
   else
     if [[ $run_context == remote ]]; then
       rm -rf /work/one-data/* &>/dev/null
-      (cd /work/one-data; clean-cache; cell plant || echo "Failed to plant cells." >&2)
+      (cd /work/one-data; clean-cache &>/dev/null; cell plant || echo "Failed to plant cells." >&2)
     fi
   fi
 
