Add cell flags for shortcuts to common parameters

diff --git a/docker/init b/docker/init
--- a/docker/init
+++ b/docker/init
@@ -37,7 +37,7 @@ main() {
   if (( ${#modules[*]} == 0 )); then
     source /etc/profile.d/shell-start-0.sh || return 1
     export SIMPLETON_LIB=$SIMPLETON_REPO/lib
-    cell plant || return 1
+    cell plant || echo "Failed to plant cells." >&2
   fi
 
   if [[ "${COMMAND:-}" ]]; then
