Improve background replay management

diff --git a/lib/background-process-lib b/lib/background-process-lib
--- a/lib/background-process-lib
+++ b/lib/background-process-lib
@@ -6,7 +6,6 @@ background_process_lib_loaded=t
 update_replay_hash() {
   pipe_replay_hash_command=$command
   pipe_replay_hash=$(echo -n "$command" | sha1sum | awk '{print $1}')
-  zombie_log "update_replay_hash: $command -> $pipe_replay_hash"
   debug_return_vars=pipe_replay_hash
 }
 
@@ -21,18 +20,22 @@ prep_background_communication() {
 
       if [[ $pipe_replay == t ]]; then
         pipe_replay_state=replaying
+      elif [[ $pipe_replay == m ]]; then
+        pipe_replay_state=replay_unless_missing
       else
         pipe_replay_state=${pipe_replay_state:-recording}
       fi
 
       pipe_replay_hash=none
+      update_replay_hash "$command" || fail
       case $pipe_replay_state in
         recording)
-          update_replay_hash "$command" || fail
           log_debug "Recording $command responses" || fail
         ;;
+        replay_unless_missing)
+          log_verbose "Replaying pre-recorded $command responses, unless they are missing" || fail
+        ;;
         replaying)
-          update_replay_hash "$command" || fail
           log_verbose "Replaying pre-recorded $command responses" || fail
         ;;
         disabled)
@@ -55,7 +58,7 @@ start_background_process() {
   begin_function
     prep_background_communication "$command" || fail
     case $pipe_replay_state in
-      recording|disabled)
+      recording|disabled|replay_unless_missing)
         log_and_run "$command" || fail
       ;;
     esac
@@ -89,13 +92,14 @@ to_background_process_single() {
         echo -n "$YELLOW$masked_command$RESET" >>$background_log || fail
       fi
 
-      case $pipe_replay_state in recording|replaying)
+      case $pipe_replay_state in recording|replaying|replay_unless_missing)
         update_replay_hash "$command" || fail
       esac
+      get_replay_file || fail
 
-      if [[ $pipe_replay_state != replaying ]]; then
+      case $effective_replay_state in recording|disabled)
         echo -n "$command" >$pipe_in || fail
-      fi
+      esac
     else
 
       local pid \
@@ -112,12 +116,12 @@ to_background_process_single() {
         echo -n "$YELLOW$masked_command$RESET" >>$background_log || fail
       fi
 
-      case $pipe_replay_state in recording|replaying)
+      case $pipe_replay_state in recording|replaying|replay_unless_missing)
         update_replay_hash "$command" || fail
       esac
+      get_replay_file || fail
 
-      if [[ $pipe_replay_state != replaying ]]; then
-
+      case $effective_replay_state in recording|disabled)
         echo -n "$command" >$pipe_in &
         pid=$!
 
@@ -145,7 +149,7 @@ to_background_process_single() {
         local wait_time_s=$(dc -e "$wait_time 1000 / p")
         log_debug "Finished waiting. Took ${wait_time_s}s." || fail
 
-      fi
+      esac
 
     fi
 
@@ -201,11 +205,10 @@ from_background_process__record_line() {
   [[ "$no_newline" == f ]] && result=$result$NL
   to+=$result
 
-  case $pipe_replay_state in
+  case $effective_replay_state in
     recording)
       echo "$line" >>$current_replay_file-out || return 1
       log_debug "Recording line to replay file: $line" || fail
-      zombie_log "Recording line to replay file: $line -> $current_replay_file-out" || fail
     ;;
     replaying)
       log_debug "Replaying line: $line" || fail
@@ -222,6 +225,7 @@ from_background_process__record_line() {
 get_replay_file() {
   begin_function
     replay_changed=f
+    effective_replay_state=$pipe_replay_state
     if [[ "${replay_pipe:-}" ]]; then
       if [[ ! "${current_replay_file:-}" ]]; then
         if [[ -p $replay_pipe ]]; then
@@ -240,7 +244,15 @@ get_replay_file() {
         replay_changed=t
       fi
 
-      if [[ $pipe_replay_state == recording ]]; then
+      if [[ $pipe_replay_state == recording 
+         || $pipe_replay_state == replay_unless_missing
+         && ! -f "$current_replay_file-out"
+         ]]; then
+
+        if [[ $pipe_replay_state == replay_unless_missing ]]; then
+          log_warn "Replay file doesn't yet exist, so recording new file: $current_replay_file"
+          effective_replay_state=recording
+        fi
 
         if [[ ! -d $replay_path ]]; then
           mkdir -p $replay_path || fail
@@ -265,6 +277,11 @@ get_replay_file() {
         fi
       fi
     fi
+
+    if [[ $effective_replay_state == replay_unless_missing ]]; then
+      effective_replay_state=replaying
+    fi
+
   end_function
   debug_return_vars=current_replay_file
   handle_return
@@ -303,7 +320,7 @@ from_background_process__check_line() {
           from_var=output to_background_process || fail
           interacted=t
           get_replay_file || fail
-          if [[ $pipe_replay_state == replaying && $replay_changed == t ]]; then
+          if [[ $effective_replay_state == replaying && $replay_changed == t ]]; then
             undefer "exec $back_fd>&-" || fail
             exec {back_fd}<>$current_replay_file-out || fail
             defer "exec $back_fd>&-"
@@ -411,7 +428,7 @@ flush_background_process() {
 
     get_replay_file || fail
 
-    if [[ $pipe_replay_state == replaying ]]; then
+    if [[ $effective_replay_state == replaying ]]; then
       if [[ $replay_changed == t || ! "${back_fd:-}" ]]; then
         local back_fd
         log_debug "Replaying background interaction from $current_replay_file-out" || fail
@@ -428,7 +445,6 @@ flush_background_process() {
 
     if [[ ! "${back_fd:-}" ]]; then
       log_fatal "Interal error: back_fd not defined in flush_background_process"
-      zombie_debug
       fail1
     fi
 
@@ -682,12 +698,14 @@ from_background_process() {
       succeed_after_count=0 interact_count=0 s \
       requirement_met=f
 
+    timed_out=f
+
     from_background_process__prep || fail
 
     get_replay_file || fail
 
-    if [[ $pipe_replay_state == replaying ]]; then
-      if [[ $replay_changed == t ]]; then
+    if [[ $effective_replay_state == replaying ]]; then
+      if [[ $replay_changed == t || ! "${back_fd:-}" ]]; then
         local back_fd
         log_debug "Replaying background interaction from $current_replay_file-out" || fail
         exec {back_fd}<>$current_replay_file-out || fail
@@ -774,9 +792,10 @@ run_pipe_command() {
   local log_show_vars=command log_vars='pipe shell_prompt buffering'
   begin_function_hi
 
+    timed_out=f failed=f command_successful=f
+
     timeout=$flush_time buffering=char flush_background_process || fail
 
-    timed_out=f failed=f command_successful=f
     from_var=command \
       to_background_process || fail
 
