Fix background bug

diff --git a/lib/background-process-lib b/lib/background-process-lib
--- a/lib/background-process-lib
+++ b/lib/background-process-lib
@@ -275,6 +275,16 @@ get_replay_file() {
 from_background_process__check_line() {
   begin_function
 
+    if [[ "$succeed_after" ]]; then
+      begin_for ((i=0; i < succeed_after_count; i++)); doo
+        if [[ "$line" =~ ${succeed_after[$i]} ]]; then
+          log_debug "Succeeded after [${succeed_after[$i]}]" || fail
+          succeeded=t
+          abort
+        fi
+      end_for
+    fi
+
     if [[ "$fail_after" ]]; then
       begin_for ((i=0; i < succeed_after_count; i++)); doo
         if [[ "$line" =~ ${fail_after[$i]} ]]; then
@@ -301,16 +311,6 @@ from_background_process__check_line() {
           fi
           unset interact_in[$i]
           break
-        fi
-      end_for
-    fi
-
-    if [[ "$succeed_after" ]]; then
-      begin_for ((i=0; i < succeed_after_count; i++)); doo
-        if [[ "$line" =~ ${succeed_after[$i]} ]]; then
-          log_debug "Succeeded after [${succeed_after[$i]}]" || fail
-          succeeded=t
-          abort
         fi
       end_for
     fi
