Allow dim and up commands to work inside seed

diff --git a/lib/bash-debugger b/lib/bash-debugger
--- a/lib/bash-debugger
+++ b/lib/bash-debugger
@@ -429,6 +429,29 @@ cooked_stack_trace() {
   return 0
 }
 
+debug_shell() {
+  if [[ ! -v debugging ]]; then
+    debugger_init || return 1
+  fi
+  local c
+  echo "Debug shell started. " >&$fd_original_err
+  echo "Use q to exit debug shell and resume execution of the script. " >&$fd_original_err
+  echo "Use 'exit' to abort all further code execution. " >&$fd_original_err
+  echo "You have access to the full execution environment (variables and functions). " >&$fd_original_err
+  while true; do
+    read -u $fd_original_in -e -p "debug ${CYAN}\$${RESET} " c >&$fd_original_err
+    case $c in
+      q|quit)
+        echo "Leaving debug shell." >&$fd_original_err
+        break
+        ;;
+      *)
+        eval "$c" || { rc=$?; echo; echo "Command failed ($rc)"; }
+        ;;
+    esac
+  done
+}
+
 debug_command_loop() {
   local debug_c no_follow_once=f
 
@@ -1775,29 +1798,6 @@ debug() {
   else
     debug_start
   fi
-}
-
-debug_shell() {
-  if [[ ! -v debugging ]]; then
-    debugger_init || return 1
-  fi
-  local c
-  echo "Debug shell started. " >&$fd_original_err
-  echo "Use q to exit debug shell and resume execution of the script. " >&$fd_original_err
-  echo "Use 'exit' to abort all further code execution. " >&$fd_original_err
-  echo "You have access to the full execution environment (variables and functions). " >&$fd_original_err
-  while true; do
-    read -u $fd_original_in -e -p "debug ${CYAN}\$${RESET} " c >&$fd_original_err
-    case $c in
-      q|quit)
-        echo "Leaving debug shell." >&$fd_original_err
-        break
-        ;;
-      *)
-        eval "$c" || { rc=$?; echo; echo "Command failed ($rc)"; }
-        ;;
-    esac
-  done
 }
 
 debug_setup() {
