Fix debugger display bug

diff --git a/lib/bash-debugger b/lib/bash-debugger
--- a/lib/bash-debugger
+++ b/lib/bash-debugger
@@ -116,23 +116,23 @@ is_set() {
 }
 
 get_var_value() {
-  local var_name=$1 val_name=${2:-value}
+  local __var_name=$1 __val_name=${2:-value}
 
-  if [[ ! "$var_name" =~ ^[a-zA-Z0-9_]+$ ]]; then
-    echo "Invalid variable name: $var_name" >&$fd_original_err
+  if [[ ! "$__var_name" =~ ^[a-zA-Z0-9_]+$ ]]; then
+    echo "Invalid variable name: $__var_name" >&$fd_original_err
     return 1
   fi
 
-  if [[ ! "$val_name" =~ ^[a-zA-Z0-9_]+$ ]]; then
-    echo "Invalid variable name: $val_name" >&$fd_original_err
+  if [[ ! "$__val_name" =~ ^[a-zA-Z0-9_]+$ ]]; then
+    echo "Invalid variable name: $__val_name" >&$fd_original_err
     return 1
   fi
 
-  local -n _var=$var_name _val=$val_name || return 1
+  local -n _var=$__var_name _val=$__val_name || return 1
   _val='(unset)'
-  if [[ "$var_name" == *\[* ]]; then
-    if is_set ${var_name%%\[*} && [[ -v $var_name ]]; then
-      eval "_val=\${$var_name}"
+  if [[ "$__var_name" == *\[* ]]; then
+    if is_set ${__var_name%%\[*} && [[ -v $__var_name ]]; then
+      eval "_val=\${$__var_name}"
     fi
   elif is_set _var; then
     local c=0 k v
