Fix duplicate op bug

diff --git a/lib/bash-lib b/lib/bash-lib
--- a/lib/bash-lib
+++ b/lib/bash-lib
@@ -108,26 +108,26 @@ ansi_filter_var() {
 }
 
 plural() {
-local count=$1 word=$2
-if [[ $count -eq 1 ]]; then
-  echo "$count $word"
-else
-  echo "$count ${word}s"
-fi
+  local count=$1 word=$2
+  if [[ $count -eq 1 ]]; then
+    echo "$count $word"
+  else
+    echo "$count ${word}s"
+  fi
 }
 
 find1() {
-if [[ ! -d "${1:-}" ]]; then
-  echo "find1: directory missing: ${1:-}" >&$fd_original_err
-  if [[ "${debug_id_current:-}" ]]; then
-    echo "debug_id=$debug_id_current" >&$fd_original_err
+  if [[ ! -d "${1:-}" ]]; then
+    echo "find1: directory missing: ${1:-}" >&$fd_original_err
+    if [[ "${debug_id_current:-}" ]]; then
+      echo "debug_id=$debug_id_current" >&$fd_original_err
+    fi
+    stack_trace
+    return 1
   fi
-  stack_trace
-  return 1
-fi
-local path=$1; shift
-find -L "$path" -mindepth 1 -maxdepth 1 "$@"
-return 0
+  local path=$1; shift
+  find -L "$path" -mindepth 1 -maxdepth 1 "$@"
+  return 0
 }
 
 NL=$'\n'
@@ -172,12 +172,12 @@ COL170=$'\n\e[A\e[170G' COL180=$'\n\e[A\e[180G' COL190=$'\n\e[A\e[190G'
 COL200=$'\n\e[A\e[200G'
 
 hydrate_template() {
-if [[ "$line" =~ \$ ]]; then
-  line="${line//\"/\\\"}"
-  eval "echo \"$line\"" || return 1
-else
-  echo "$line"
-fi
+  if [[ "$line" =~ \$ ]]; then
+    line="${line//\"/\\\"}"
+    eval "echo \"$line\"" || return 1
+  else
+    echo "$line"
+  fi
 }
 
 # prompt_ynsq {message} {var to save result into}
@@ -221,7 +221,6 @@ defer() {
 # usage: random {p=number of possibilities}
 #   sets r={random number between 0 and p-1}
 #   it will be fairly evenly distributed below about 1000, but will become more biased as it gets higher
-unset random
 random() {
   local p=$1
   r=$((RANDOM % p))
@@ -229,7 +228,6 @@ random() {
 
 # usage: random_sleep {min} {max}
 #   will sleep for a random interval between min and max
-unset random_sleep
 random_sleep() {
   local min=$1; shift
   local max=$1
