.

diff --git a/lib/bash-debugger b/lib/bash-debugger
--- a/lib/bash-debugger
+++ b/lib/bash-debugger
@@ -41,11 +41,19 @@ CLEAR_SCREEN=$'\033[2J\r\033[H'
 tmp_folder=${tmp_folder:-/tmp}
 debug_state_file=$tmp_folder/debug-state-$$
 
+# debug_cleanup='
+#   if [[ $BASH_SUBSHELL -eq 0 ]]; then
+#     rm "$debug_state_file" &>/dev/null || true
+#   fi
+#   '
+
+rm $tmp_folder/debug-state-* &>/dev/null || true
 debug_cleanup='
-  if [[ $BASH_SUBSHELL -eq 0 ]]; then
-    rm "$debug_state_file" &>/dev/null || true
+  if [[ -f $debug_state_file ]]; then
+    echo "debug state is stored here: $debug_state_file"
   fi
   '
+
 if type defer &>/dev/null; then
   defer "$debug_cleanup"
 else
diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -235,21 +235,72 @@ local vars=cell; begin_function
     if [[ -d $cell.new ]]; then
       rm -rf $cell.new || fail
     fi
-    local parent_part=${cell%/*}
-    parent_part=${parent_part##*/}
+    local parent=${cell%/*}
+    local parent_part=${parent##*/}
     if [[ "$parent_part" == .dim ]]; then
       create_sub_branch_or_leaf $cell.new || fail
     else
       mkdir -p $cell.new || fail
-      link_dna_from_seed $cell.new || {
-        err "Failed to link dna from seed for $cell"
-        fail1
-        }
+      find_seed_dna $parent ${cell#$parent/} || fail
+      if [[ "$seed_dna" ]]; then
+        ln -sf $seed_dna $cell.new/.dna || fail
+      fi
     fi
     mv $cell.new $cell || fail
   fi
 end_function
 handle_return
+}
+
+link_dna_from_seed() {
+local subject=$1
+local parent=${subject%/*}
+local seed_dna
+if [[ "${#parent}" -gt 1 ]]; then
+  find_seed_dna $parent ${subject#$parent/} || {
+    err "Could not find seed dna for $subject"
+    return 1
+    }
+  if [[ "$seed_dna" ]]; then
+    return 0
+  fi
+fi
+return 1
+}
+
+# returns seed_dna
+find_seed_dna() {
+local subject=$1
+local parent=${subject%/*}
+local path_to_cell=$2
+path_to_cell=${path_to_cell%.new}
+seed_dna=$subject/.dna/sub/$path_to_cell/.dna
+if [[ ! -e $seed_dna ]]; then
+  seed_dna=
+  if [[ -d $subject/.dna/sub ]]; then
+    seed_dna=$subject/.dna/sub
+    local path_array=( ${path_to_cell//\// } ) \
+      failed=f
+    for path_part in "${path_array[@]}"; do
+      if [[ -d $seed_dna/$path_part ]]; then
+        seed_dna+=/$path_part
+      elif [[ -d $seed_dna/$wild_sub_path ]]; then
+        seed_dna+=/$wild_sub_path
+      else
+        failed=t
+        break
+      fi
+    done
+    seed_dna+=/.dna
+    if [[ $failed == t || ! -d $seed_dna ]]; then
+      seed_dna=
+    fi
+  elif [[ ${#parent} -gt 1 ]]; then
+    # recursive
+    find_seed_dna $parent ${subject#$parent/}/$path_to_cell || return 1
+  fi
+fi
+return 0
 }
 
 create_sub_branch_or_leaf() {
@@ -850,9 +901,6 @@ return 0
 get_top_cell2() {
 local subject=$1
 local parent=${subject%/*}
-if [[ ! -e $subject/.dna ]]; then
-  link_dna_from_seed $subject || true
-fi
 if [[ -e $subject/.dna ]]; then
   top_cell=$subject
 fi
@@ -874,66 +922,11 @@ return 0
 get_bottom_cell2() {
 local subject=$1
 local parent=${subject%/*}
-if [[ ! -e $subject/.dna ]]; then
-  link_dna_from_seed $subject || true
-fi
 if [[ -e $subject/.dna ]]; then
   bottom_cell=$subject
 elif [[ ${#parent} -gt 1 ]]; then
   # recursive
   get_bottom_cell2 $parent || return 1
-fi
-return 0
-}
-
-link_dna_from_seed() {
-local subject=$1
-local parent=${subject%/*}
-local seed_dna
-if [[ "${#parent}" -gt 1 ]]; then
-  find_seed_dna $parent ${subject#$parent/} || {
-    err "Could not find seed dna for $subject"
-    return 1
-    }
-  if [[ "$seed_dna" ]]; then
-    ln -sf $seed_dna $subject/.dna || return 1
-    return 0
-  fi
-fi
-return 1
-}
-
-# returns seed_dna
-find_seed_dna() {
-local subject=$1
-local parent=${subject%/*}
-local path_to_cell=$2
-path_to_cell=${path_to_cell%.new}
-seed_dna=$subject/.dna/sub/$path_to_cell/.dna
-if [[ ! -e $seed_dna ]]; then
-  seed_dna=
-  if [[ -d $subject/.dna/sub ]]; then
-    seed_dna=$subject/.dna/sub
-    local path_array=( ${path_to_cell//\// } ) \
-      failed=f
-    for path_part in "${path_array[@]}"; do
-      if [[ -d $seed_dna/$path_part ]]; then
-        seed_dna+=/$path_part
-      elif [[ -d $seed_dna/$wild_sub_path ]]; then
-        seed_dna+=/$wild_sub_path
-      else
-        failed=t
-        break
-      fi
-    done
-    seed_dna+=/.dna
-    if [[ $failed == t || ! -d $seed_dna ]]; then
-      seed_dna=
-    fi
-  elif [[ ${#parent} -gt 1 ]]; then
-    # recursive
-    find_seed_dna $parent ${subject#$parent/}/$path_to_cell || return 1
-  fi
 fi
 return 0
 }
