adding omni-navigator

diff --git a/lib/bash-lib b/lib/bash-lib
--- a/lib/bash-lib
+++ b/lib/bash-lib
@@ -1,6 +1,20 @@
 #!/bin/bash
 
-fd_trace=${fd_trace:-3}
+type -t bash_lib_loaded >/dev/null && return 0
+bash_lib_loaded=t
+
+set -ue +H
+shopt -s expand_aliases   # make sure aliases are expanded even for non-interactive scripts
+shopt -s extglob
+
+umask 0077  # to make created files readable only by the user by default
+
+if [[ ! -v fd_original_in ]]; then
+  exec {fd_original_in}<&0
+  exec {fd_original_out}>&1
+  exec {fd_original_err}>&2
+  exec {fd_original_trace}>&${fd_trace:-2}
+fi
 
 # some required defaults
 export tmp_folder="${tmp_folder:-/tmp}"
@@ -158,7 +172,7 @@ prompt_ynq() {
         echo "Quit" >&2 
         ;;
       *)
-        fatal "Pick one of: (y)es (n)o (q)uit"
+        log_fatal "Pick one of: (y)es (n)o (q)uit"
         continue
         ;;
     esac
@@ -232,18 +246,6 @@ trim_stream() {
   sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' | grep -v '^$'
 }
 
-to_lower() {
-  tr '[:upper:]' '[:lower:]'
-}
-
-to_upper() {
-  tr '[:lower:]' '[:upper:]'
-}
-
-spaces_to_minus() {
-  sed 's/  */-/g'
-}
-
 upper_first_char() {
   local string=$1
   local first=${string:0:1}
@@ -278,7 +280,7 @@ convert_to_seconds() {
         # default to seconds
         eval "$to=$from"
       else
-        fatal "Unknown time format, use something like: 4h, 3d, 5m"
+        log_fatal "Unknown time format, use something like: 4h, 3d, 5m"
         return 1
       fi
     ;;
@@ -465,36 +467,6 @@ get_overlap() {
 }
 
 # usage: convert_to_seconds {from time period} {to var name}
-convert_to_seconds() {
-  local from=$1; shift
-  local to=$1
-  case "$from" in
-    *s)
-      eval "$to=${from%s}"
-      ;;
-    *m)
-      eval "$to=$((${from%m}*60))"
-      ;;
-    *h)
-      eval "$to=$((${from%h}*60*60))"
-      ;;
-    *d)
-      eval "$to=$((${from%d}*24*60*60))"
-      ;;
-    *w)
-      eval "$to=$((${from%w}*7*24*60*60))"
-      ;;
-    *y)
-      eval "$to=$((${from%y}*365*24*60*60))"
-      ;;
-    *)
-      fatal "Unknown time format, use something like: 4h, 3d, 5m"
-      return 1
-      ;;
-  esac
-  return 0
-}
-
 # inputs: folder_to_lock timeout pid_file
 # if timeout is not given, then attempt will immediately fail if it can't get the lock right away
 #   otherwise it will keep trying until the timeout is reached or the lock is obtained.
@@ -508,13 +480,13 @@ vars='folder_to_lock timeout'; begin_function
 
   if [[ -d "$folder_to_lock" ]]; then
 
-    debug "Lock folder exists already: $folder_to_lock"
+    log_debug "Lock folder exists already: $folder_to_lock"
     local pid=
 
     if [[ -f "$pid_file" ]]; then
       pid=$(<"$pid_file")
       if [[ "$pid" == $$ ]]; then
-        debug "This process already owns the lock, so we are done."
+        log_debug "This process already owns the lock, so we are done."
         succeed
       fi
     fi
@@ -522,7 +494,7 @@ vars='folder_to_lock timeout'; begin_function
     # check to see if the process is still running
     if [[ ! "$pid" ]] || ! ps $pid &>/dev/null; then
       rm -rf "$folder_to_lock" || fail
-      debug "Removed stale lock: $folder_to_lock with pid: $pid"
+      log_debug "Removed stale lock: $folder_to_lock with pid: $pid"
     fi
 
   fi
@@ -545,23 +517,23 @@ vars='folder_to_lock timeout'; begin_function
       fi
 
       local seconds_to_wait=$(dc -e "2 k $delay 1000 / p")
-      debug "Failed to obtain lock. Waiting $seconds_to_wait seconds before trying again."
+      log_debug "Failed to obtain lock. Waiting $seconds_to_wait seconds before trying again."
       sleep $seconds_to_wait
       timeleft=$((timeleft-delay))
       let delay*=2
       if [ "$timeleft" -le 0 ]; then
-        warn "Timeout reached. Couldn't obtain the lock in time."
+        log_warn "Timeout reached. Couldn't obtain the lock in time."
         break
       fi
     end_while
   else
-    fatal "Attempting to obtain a folder lock when it's parent doesn't exist: $parent"
+    log_fatal "Attempting to obtain a folder lock when it's parent doesn't exist: $parent"
     stack_trace
     fail1
   fi
 
   if [[ $success == f ]]; then
-    debug "Failed to obtain lock."
+    log_debug "Failed to obtain lock."
     fail1
   fi
 
@@ -570,7 +542,7 @@ vars='folder_to_lock timeout'; begin_function
   fi
 
   # lock obtained
-  debug "Succeeded in obtaining lock."
+  log_debug "Succeeded in obtaining lock."
 
 end_function
 handle_return
@@ -598,7 +570,7 @@ local pid_file=${pid_file:-$folder_to_unlock/pid}
 local remove_folder_when_unlocked=${remove_folder_when_unlocked:-f}
 
 if [[ ! "$folder_to_unlock" ]]; then
-  fatal "Usage: folder_to_unlock=... folder_unlock "
+  log_fatal "Usage: folder_to_unlock=... folder_unlock "
   return 1
 fi
 
@@ -614,41 +586,30 @@ return 0
 }
 
 fd_read_lock() {
-local lock_path=$1
-local timeout=${2:-$lock_timeout}
+local lock_path=$lock_path timeout=$timeout
+exec {lock_fd}<>$lock_path
 flock -s -w $timeout $lock_fd || {
-  fatal "Failed to get read lock for $lock_path within $timeout seconds"
+  log_fatal "Failed to get read lock for $lock_path within $timeout seconds"
   return 1
   }
 }
 
 fd_write_lock() {
-local lock_path=$1
-local timeout=${2:-$lock_timeout}
+local lock_path=$lock_path timeout=$timeout
+exec {lock_fd}<>$lock_path
 flock -e -w $timeout $lock_fd || {
-  fatal "Failed to get write lock for $lock_path within $timeout seconds"
+  log_fatal "Failed to get write lock for $lock_path within $timeout seconds"
   return 1
   }
 }
 
 fd_unlock() {
-flock -u $1
+flock -u $lock_fd
 }
 
 get_next_fd() {
 next_fd=$(ls -1 /proc/self/fd | tail -n1)
 let next_fd++
-}
-
-update_modify_times() {
-local from_inclusive=$1; shift
-local to_exclusive=$1
-local current=$from_inclusive
-while [[ ${#current} > 1 && $current =~ / && $current != $to_exclusive ]]; do
-  touch $current || return 1
-  current=${current%/*}
-done
-return 0
 }
 
 is_dir_empty() {
@@ -702,13 +663,13 @@ case $pretend in
     esac
   ;;
   *)
-    fatal "Invalid pretend setting: $pretend. Must be one of: t f ask"
+    log_fatal "Invalid pretend setting: $pretend. Must be one of: t f ask"
     return 1
   ;;
 esac
 
 if [[ $execute == t ]]; then
-  info "Executing: $command_to_execute"
+  log_info "Executing: $command_to_execute"
   eval "$command_to_execute" || return $?
 fi
 
@@ -746,7 +707,7 @@ if [[ $to != */ && -L "$to" ]]; then
   rm "$to" || return 1
 fi
 if [[ ! -e "$from" ]]; then
-  fatal "Internal error: Source of link doesn't exist: $from"
+  log_fatal "Internal error: Source of link doesn't exist: $from"
   stack_trace
   return 1
 fi
@@ -764,7 +725,7 @@ unrealpath() {
 local p=$PWD x=$1
 cd / || return 1
 realpath -s "$p/$x" || {
-  fatal "Internal error: could not resolve $p/$x"
+  log_fatal "Internal error: could not resolve $p/$x"
   return 1 
   }
 return 0
@@ -779,3 +740,31 @@ if [[ -v $from_var ]]; then
   eval "$from_var=\"\$left \$right\""
 fi
 }
+
+cooked_stack_trace() {
+echo "Cooked call stack:" >&$fd_original_err
+local count=${#cooked_stack[*]} n
+for ((n = 0; n < count; n++)); do
+  echo " ${cooked_stack[$n]}" >&$fd_original_err
+done
+return 0
+}
+
+stack_trace() {
+local start_frame=${start_frame:-1}
+local count=${#FUNCNAME[*]}
+local p n
+
+if [ ${tracing_midline:-f} == t ]; then
+  tracing_midline=f
+  echo >&$fd_original_err
+fi
+
+echo "Raw call stack:" >&$fd_original_err
+for ((n = count - 1; n >= start_frame; n--)) ; do
+  let p=n-1
+  echo "  ${BASH_SOURCE[$n]} ${FUNCNAME[$n]} ${BASH_LINENO[$p]}" >&$fd_original_err
+done
+return 0
+}
+
diff --git a/lib/omni-log b/lib/omni-log
--- a/lib/omni-log
+++ b/lib/omni-log
@@ -1,8 +1,6 @@
 #!/bin/bash
 
-# This library of aliases and functions follows the standard hi-shell
-# output interface but changes the implementation to always output trace info
-# but with additional info to allow easy filtering or browsing of that info.
+type -t init_omni_log >/dev/null && return 0
 
 # if log_file is set, trace output will be sent to this file
 
@@ -14,91 +12,123 @@
 #   handle_return
 # }
 
-debug_at_log_id=
-if [[ "${log_id:-}" ]]; then
-  echo "${CYAN}Will debug starting at log_id $log_id or later${RESET}" >&2
-  debug_at_log_id=$log_id
-fi
+get_next_fork_id() {
+  local base_log_file=$base_log_file
+  timeout=3 lock_path=$fork_log fd_write_lock || {
+    echo "Failed to get lock on $fork_log" >&2
+    return 1
+  }
+  local last_id=$(tail -n1 $fork_log | awk '{print $1}')
+  let fork_id=last_id+1 || true
+  new_log_file=$base_log_file-$fork_id.olog
+  echo "$fork_id $new_log_file" >>$fork_log || return 1
+  fd_unlock
+  return 0
+}
 
-first_log=t
-log_depth_current=0
-log_id=0
-trace_var=${trace_var:-}
-declare -A trace_var_value=()
-log=${log:-file}
-log_to_file=t
-log_to_out=f
-log_action=${log_action:-}
-log_depth=${log_depth:-}
-log_function=${log_function:-}
-log_level=${log_level:-info}
-log_format=${log_format:-default}
-cooked_stack=( ${cooked_stack[*]:-} )
+init_omni_log() {
+  local command="$*"  
+  # local exported_vars=$(export | grep '^declare -x [a-z]' | cut -d' ' -f3-)
+  # exported_vars=${exported_vars//$NL/ }
+  # command="$command $exported_vars"
+  fork_log=${fork_log:-~/fork-log/$$}
+  if [[ ! -d ${fork_log%/*} ]]; then
+    mkdir ${fork_log%/*} || return 1
+  fi
+  fork_id=0
+  # echo "$fork_id $command" >>$fork_log || return 1
 
-case $log in
-  off|fatal|error|warn|info|debug|trace|all)
-    log_level=$log
-    log=file
+  if [[ "${debugger_available:-f}" == t ]]; then
+    debug_at_log_id=
+    if [[ "${log_id:-}" ]]; then
+      echo "${CYAN}Will debug starting at log_id $log_id or later${RESET}" >&2
+      debug_at_log_id=$log_id
+    fi
+  fi
+
+  first_log_file=
+  first_log=t
+  log_depth_current=0
+  log_pos=0
+  trace_var=${trace_var:-}
+  declare -A trace_var_value=()
+  log=${log:-file}
+  log_to_file=t
+  log_to_out=f
+  log_action=${log_action:-}
+  log_depth=${log_depth:-}
+  log_function=${log_function:-}
+  log_level=${log_level:-info}
+  log_format=${log_format:-default}
+  cooked_stack=( ${cooked_stack[*]:-} )
+
+  case $log in
+    off|fatal|error|warn|info|debug|trace|all)
+      log_level=$log
+      log=file
+      ;;
+    file)
+      # default behavior
+      ;;
+    out)
+      log_to_out=t
+      log_level=warn
+      if [[ "$log_format" == default ]]; then
+        log_format='$level_color$message$RESET'
+      fi
+      ;;
+    both)
+      log_to_file=t
+      log_to_out=t
+      ;;
+    *)
+      log_to_file=t
+      log_to_out=t
+      log_action=$log
+      ;;
+  esac
+
+  case $log_level in
+    none)
+      log_format=
     ;;
-  file)
-    # default behavior
+    fatal|error|warn|info)
+      if [[ "$log_format" == default ]]; then
+        log_format='$level_color$message$RESET'
+      fi
     ;;
-  out)
-    log_to_out=t
-    log_level=warn
-    if [[ "$log_format" == default ]]; then
+    debug)
+      if [[ "$log_format" == default ]]; then
+        log_format='$log_id$level_color$message$RESET'
+      fi
+    ;;
+    trace|all)
+      if [[ "$log_format" == default ]]; then
+        log_format='$time$pid$log_id$COL40$level_color$action$COL55$function$COL85$log_vars$message$RESET'
+      fi
+    ;;
+    *)
+      log_fatal "Invalid log_level value. Must be one of: none, error, warn, info, trace, debug"
+      exit 1
+    ;;
+  esac
+
+  case $log_format in
+    tiny)
       log_format='$level_color$message$RESET'
-    fi
     ;;
-  both)
-    log_to_file=t
-    log_to_out=t
+    short)
+      log_format='$level_color$action$COL15$function$COL45$log_vars$message$RESET'
     ;;
-  *)
-    log_to_file=t
-    log_to_out=t
-    log_action=$log
+    compact)
+      log_format='$level_color$action$function$log_vars$message$RESET'
     ;;
-esac
+  esac
 
-case $log_level in
-  none)
-    log_format=
-  ;;
-  fatal|error|warn|info)
-    if [[ "$log_format" == default ]]; then
-      log_format='$level_color$message$RESET'
-    fi
-  ;;
-  debug)
-    if [[ "$log_format" == default ]]; then
-      log_format='$log_id$level_color$message$RESET'
-    fi
-  ;;
-  trace|all)
-    if [[ "$log_format" == default ]]; then
-      log_format='$time$pid$log_id$COL40$level_color$action$COL55$function$COL85$log_vars$message$RESET'
-    fi
-  ;;
-  *)
-    fatal "Invalid log_level value. Must be one of: none, error, warn, info, trace, debug"
-    exit 1
-  ;;
-esac
+  var_stack=( )
+  log_file=
+}
 
-case $log_format in
-  tiny)
-    log_format='$level_color$message$RESET'
-  ;;
-  short)
-    log_format='$level_color$action$COL15$function$COL45$log_vars$message$RESET'
-  ;;
-  compact)
-    log_format='$level_color$action$function$log_vars$message$RESET'
-  ;;
-esac
-
-var_stack=( )
 alias begin_function='
   local return_value=0 break_out=f
   write_to_log trace call
@@ -119,27 +149,26 @@ alias end_function='
 #   change_log_file {log file base}   point to new log file
 #   change_log_file                   point to same base but new pid (forked)
 #   change_log_file -                 stop logging
-log_file=
 change_log_file() {
 begin_function_flat
 
-  local new_base=${1:-} new_log_file old_log_file
+  local new_base=${1:-} new_log_file old_log_file old_fork_id=$fork_id
 
   if [[ "$new_base" == - ]]; then
     new_log_file=
   elif [[ "$new_base" ]]; then
     base_log_file=$new_base
-    new_log_file=$base_log_file-$BASHPID.olog
+    get_next_fork_id || fail
     local first_log=$base_log_file-first.olog
     if [[ -e "$first_log" ]]; then
-      fatal "Log already exists: $first_log" 
+      log_fatal "Log already exists: $first_log" 
       stack_trace
       fail1
     fi
     ln -s $new_log_file $first_log || fail
   else
     [[ ! "${base_log_file:-}" ]] && succeed
-    new_log_file=$base_log_file-$BASHPID.olog
+    get_next_fork_id || fail
   fi
 
   if [[ "${log_file:-}" == "$new_log_file" ]]; then
@@ -159,7 +188,7 @@ begin_function_flat
     log_file=$new_log_file
 
     if [[ -f $log_file ]]; then
-      fatal "log file already exists: $log_file"
+      log_fatal "log file already exists: $log_file"
       fail1
     fi
 
@@ -173,7 +202,7 @@ end_function_flat
 handle_return
 }
 
-trace() {
+log_trace() {
 begin_no_tracing_zone
 local message="$*"
 log_function=${FUNCNAME[1]} write_to_log trace "${action:-}" "$message"
@@ -181,35 +210,35 @@ end_no_tracing_zone
 return 0
 }
 
-debug() {
+log_debug() {
 begin_no_tracing_zone
 log_function=${FUNCNAME[1]} write_to_log debug "${action:-}" "$*"
 end_no_tracing_zone
 return 0
 }
 
-info() {
+log_info() {
 begin_no_tracing_zone
 log_function=${FUNCNAME[1]} write_to_log info "${action:-}" "$*"
 end_no_tracing_zone
 return 0
 }
 
-warn() {
+log_warn() {
 begin_no_tracing_zone
 log_function=${FUNCNAME[1]} write_to_log warn "${action:-}" "$*"
 end_no_tracing_zone
 return 0
 }
 
-error() {
+log_error() {
 begin_no_tracing_zone
 log_function=${FUNCNAME[1]} write_to_log error "${action:-}" "$*"
 end_no_tracing_zone
 return 0
 }
 
-fatal() {
+log_fatal() {
 begin_no_tracing_zone
 log_function=${FUNCNAME[1]} write_to_log fatal "${action:-}" "$*"
 end_no_tracing_zone
@@ -218,7 +247,7 @@ return 0
 
 # zombie logs are used to output temporary debugging logs
 # they should be removed from the code after the issue is resolved
-zombie() {
+log_zombie() {
 begin_no_tracing_zone
 echo "$CYAN$*$RESET" >&$fd_original_err
 end_no_tracing_zone
@@ -326,12 +355,13 @@ done
 
 local time="$EPOCHREALTIME"
 local pid="$BASHPID"
-local to_log="= $time pid=$pid"
+local to_log="= ts=$time pid=$pid"
 
 if [[ "${debug_id:-}" ]]; then
   to_log+=" debug_id=$debug_id_current"
 fi
 
+log_id=$fork_id:$log_pos
 to_log+=" log_id=$log_id depth=$log_depth_current level=$level"
 
 if [[ "$action" ]]; then
@@ -404,19 +434,24 @@ fi
 
 unpause_tee
 
-if [[ "$debug_at_log_id" && $log_id -ge "$debug_at_log_id" ]]; then
-  debug_at_log_id=
-  if [[ ! "${debug_id:-}" ]]; then
-    debug_immediate=t
-  else
-    echo "${CYAN}Will debug starting at debug_id $debug_id or later${RESET}" >&2
-    debug_subshell=t
-    debug_stepping=f
-    debug_immediate=f
+if [[ "$debug_at_log_id" ]]; then
+  local debug_at_fork_id=${debug_at_log_id%:*}
+  local debug_at_log_pos=${debug_at_log_id#*:}
+  if [[ $fork_id == $debug_at_fork_id \
+     && $log_pos -ge $debug_at_log_pos ]]; then
+    debug_at_log_id=
+    if [[ ! "${debug_id:-}" ]]; then
+      debug_immediate=t
+    else
+      echo "${CYAN}Will debug starting at debug_id $debug_id or later${RESET}" >&2
+      debug_subshell=t
+      debug_stepping=f
+      debug_immediate=f
+    fi
+    debug_start
   fi
-  debug_start
 fi
-let log_id++ || true
+let log_pos++ || true
 
 end_no_tracing_zone
 }
