Improve unrealpath

diff --git a/lib/bash-lib b/lib/bash-lib
--- a/lib/bash-lib
+++ b/lib/bash-lib
@@ -748,9 +748,11 @@ read -p "${1:-Press any key}" -n 1 none || true
 # normal usage: x=$(unrealpath "$some_path")
 unrealpath() {
 local p=$PWD x=$1
-cd / || return 1
-realpath -s "$p/$x" || {
-  log_fatal "Internal error: could not resolve $p/$x"
+if [[ "$x" != /* ]]; then
+  x="$p/$x"
+fi
+realpath -s "$x" || {
+  log_fatal "Internal error: could not resolve $x"
   return 1 
   }
 return 0
