omni-log: Add auto_shorten function

diff --git a/lib/bash-lib b/lib/bash-lib
--- a/lib/bash-lib
+++ b/lib/bash-lib
@@ -405,7 +405,7 @@ local to=$to
 local timeout=${timeout:-}
 local pid_file=${pid_file:-$to/pid}
 
-vars='from to timeout'
+local log_vars='from to timeout'
 begin_function
 
   if [[ ! -e "$from" ]]; then
@@ -516,7 +516,8 @@ local timeout=${timeout:-$lock_timeout}
 local pid_file=${pid_file:-$folder_to_lock/pid}
 local remove_folder_when_unlocked=${remove_folder_when_unlocked:-f}
 
-vars='folder_to_lock timeout'; begin_function
+local log_vars='folder_to_lock timeout'
+begin_function
 
   if [[ -d "$folder_to_lock" ]]; then
 
@@ -757,19 +758,23 @@ done
 
 safe_link() {
 local from=$1 to=$2 force=${force:-f} from_must_exist=${from_must_exist:-t}
-if [[ $to != */ && -L "$to" ]]; then
-  rm "$to" || return 1
-fi
-if [[ $from_must_exist == t && ! -e "$from" ]]; then
-  log_fatal "Internal error: Source of link doesn't exist: $from"
-  stack_trace
-  return 1
-fi
-if [[ $force == t ]]; then
-  ln -sfn "$from" "$to" || return 1
-else
-  ln -sn "$from" "$to" || return 1
-fi
+local log_show_vars="from to" log_vars="force from_must_exist"
+begin_function
+  if [[ $to != */ && -L "$to" ]]; then
+    rm "$to" || fail
+  fi
+  if [[ $from_must_exist == t && ! -e "$from" ]]; then
+    log_fatal "Internal error: Source of link doesn't exist: $from"
+    stack_trace
+    fail1
+  fi
+  if [[ $force == t ]]; then
+    ln -sfn "$from" "$to" || fail
+  else
+    ln -sn "$from" "$to" || fail
+  fi
+end_function
+handle_return
 }
 
 pause() {
