Fix support dims calculation bug

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -532,9 +532,6 @@ init_context() {
     shuffle_chance=100 \
     sub_dims=() \
     sub_dims_expanded=() \
-    support_dims=() \
-    support_dims_expanded=() \
-    support_dims_one_expanded=() \
     trunk_dims=() \
     trunk_dims_expanded=() \
     up=() \
@@ -546,6 +543,9 @@ init_context() {
       update_op \
       get_op \
       aggregate_op \
+      support_dims \
+      support_dims_expanded \
+      support_dims_one_expanded \
 
     context_path=$cyto_path/context \
     context_path=$cyto_path/context \
@@ -5432,7 +5432,6 @@ calc_coordinates_next_unknown_dim() {
         for dim in $unknown_dims; do
 
           grip_fence
-          needs_narrowing=t
 
           local -n dim_type=${dim}_dim_type
           get_plural $dim dims
@@ -5471,17 +5470,18 @@ calc_coordinates_next_unknown_dim() {
             deriving= \
             attempt_derive || fail
             needs_narrowing=f
-          elif [[ $derive_exactly_one == f \
-               || $target_form == seed ]]; then
-            local value=all
-            expand_dim value values || fail
-            already_expanded=t
           elif [[ $phase == narrow ]]; then
             derive_exactly_one=f \
             deriving= \
             use_narrow_from=t \
             attempt_derive || fail
             needs_narrowing=f
+#  not sure this is needed, since narrowing phase should already handle this
+#          elif [[ $derive_exactly_one == f \
+#               || $target_form == seed ]]; then
+#            local value=all
+#            expand_dim value values || fail
+#            already_expanded=t
           else
             log_fatal "Internal error: invalid phase: $phase"
             fail1
