Add save_dna_tab function

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -952,6 +952,69 @@ load_dna_vtab() {
   handle_return
 }
 
+# writes a table to a file
+# inputs:
+#   tab_var       name of the table variable (without the _data or _fields)
+#   target_file   full path of file to write to
+save_dna_tab() {
+  local tab_var=$tab_var target_file=$target_file
+
+  begin_function
+
+    if [[ -f $target_file ]]; then
+      log_fatal "Target file $target_file already exists. It must be deleted before calling this function."
+      fail1
+    fi
+
+    local value field_index data_offset row_index field
+
+    local -n c_data=${tab_var}_data \
+      c_fields=${tab_var}_fields \
+
+    local c_fields_count=${#c_fields[*]} \
+      c_count=${#c_data[*]} \
+
+    local c_rows=$(( c_count / c_fields_count ))
+
+    if [[ ! "{c_fields:-}" ]]; then
+      log_fatal "No fields are defined for $coord_type coordinates"
+      fail1
+    fi
+
+    local line=
+
+    for (( field_index = 0; field_index < c_fields_count; field_index++ )); do
+      field=${c_fields[$field_index]}
+      if [[ ! "$keep_dims" || " $keep_dims " == *" $field "* ]]; then
+        if [[ " $skip_dims " != *" $field "* ]]; then
+          line+="$field "
+        fi
+      fi
+    done
+    echo "${line% }" >>$target_file || fail
+
+    for (( row_index = 0; row_index < c_rows; row_index++ )); do
+      line=
+      for (( field_index = 0; field_index < c_fields_count; field_index++ )); do
+        (( data_offset = row_index * c_fields_count + field_index ))
+        field=${c_fields[$field_index]}
+        if [[ ! "$keep_dims" || " $keep_dims " == *" $field "* ]]; then
+          if [[ " $skip_dims " != *" $field "* ]]; then
+            value=${c_data[$data_offset]}
+            shell_quote_var value
+            line+="$value "
+          fi
+        fi
+      done
+
+      echo "${line% }" >>$target_file || fail
+    done
+
+  end_function
+  handle_return
+}
+
+
 # Will load the given derive table if not already loaded
 # Will not load indexes (those should have already been loaded from the table cache)
 # Will not calculate cardinality or key fields
