Remove foundation check

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -7375,7 +7375,7 @@ switch_context() {
       seed_path=
       if [[ $dna_exists == t ]]; then
 
-        check_foundation || fail
+        #check_foundation || fail
 
         if [[ ! -f $context_path ]]; then
           fork build_cyto $cell_path || fail
