.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -657,10 +657,10 @@ local -r from=$1 to=$2
 begin_function_flat
   if [[ -e $from && ! -e $to ]]; then
 
-    if [[ -f $from ]]; then
+    if [[ -f $from || -f $from/.dna ]]; then
       safe_link $(realpath $from) $to || fail
-    elif [[ -e $from/.dna ]]; then
-      fork to_dims=${leaf_dims[*]} migrate_cell $from $to || fail
+    elif [[ -d $from/.dna ]]; then
+      fork "to_dims=( ${leaf_dims[*]} ) migrate_cell $from $to" || fail
     elif [[ -d $from ]]; then
       mkdir $to || fail
       local item item_name \
@@ -684,41 +684,44 @@ migrate_cell() {
 local -r from=$1 to=$2 to_dims=$to_dims
 begin_function_flat
 
-  local sub_dim
-  get_sub_dim || fail
+  local dep_dims= dep_dim branch_dim branch_member
+  get_dep_dims || fail
 
-  local sub_member
-  get_sub_member || fail
+  local found_match i branch_dim_count=${#branch_dims[*]}
+  begin_for dep_dim in ${dep_dims[*]}; doo
+    found_match=f
 
-  local dep_dim
-  get_dep_dim || fail
+    begin_for ((i=0; i<branch_dim_count; i++)); doo 
+      branch_dim=${branch_dims[$i]}
+      sane_branch_member=${sane_branch_members[$i]}
+      if [[ $dep_dim == $branch_dim ]]; then
+        found_match=t
+        break
+      fi
+    end_for
+    
+    if [[ $found_match == t ]]; then
+      promote_dep $dep_dim $sane_branch_member || fail
+    else
+      break
+    fi
 
-  local dep_member=$member
-
-  local sane_value
-  get_sane_value "$sub_member" || fail
-  local -r sub_member_sane=$sane_value
-  get_sane_value "$dep_member" || fail
-  local -r dep_member_sane=$sane_value
-
-  if [[ $sub_dim == $dep_dim ]]; then
-    safe_link $from/$dep_member_sane $to/$sub_member_sane || fail
+  end_for
+  
+  if is_leaf_cell $from && is_leaf_cell $to; then
+    safe_link $from $to || fail
   else
-    safe_link $from $to/$sub_member_sane || fail
+    fatal "Unable to match leaf cells between $from and $to."
+    fatal "This means dimension mapping is not properly set up between these cells," 
+    fatal "so the dependency can't be resolved."
+    fail1
   fi
 
 end_function_flat
 handle_return
 }
 
-get_sub_dim() {
-local first_dim
-get_first_dim $cell_path || return 1
-sub_dim=$first_dim
-return 0
-}
-
-get_dep_dim() {
+get_dep_dims() {
 local -r prep_file=$from.prep
 if [[ -f $prep_file ]]; then
   source $prep_file || return 1
@@ -730,19 +733,25 @@ if [[ ${dep_cell_parent##*/} == .dim ]]; then
   dep_cell_parent=${dep_cell_parent%/*}
 fi
 
-local first_dim
-get_first_dim $dep_cell_parent || return 1
+if [[ -d $dep_cell_parent/.dna/dim ]]; then
+  local first_dim
+  get_first_dim $dep_cell_parent || return 1
+  dep_dim=$first_dim
+else
+  dep_dim=
+fi
 
-dep_dim=$first_dim
 return 0
 }
 
-get_first_dim() {
+get_dims() {
 local -r cell=$1
-first_dim=$( \
-  find $cell/.dna/dim -not '.*' \
-  | sort -g | head -n 1) || return 1
-if [[ ! "$first_dim" ]]; then
+dims=$( \
+  find1 $cell/.dna/dim \
+  -not -name '.*' \
+  printf '%f\n' \
+  | sort -g) || return 1
+if [[ ! "$dims" ]]; then
   fatal "Could not find dim of $cell"
   return 1
 fi
