.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -206,12 +206,29 @@ handle_return
 
 create_sub_cell() {
 local cell=$1
-begin_function_flat
+vars=cell; begin_function
   if [[ ! -d $cell ]]; then
-    mkdir -p $cell || fail
-    link_dna_from_seed $cell || fail
+    local parent_part=${cell%/*}
+    parent_part=${parent_part##*/}
+    if [[ "$parent_part" == .dim ]]; then
+      local trunk_cell
+      find_trunk_cell || {
+        err "Could not find trunk cell for $cell"
+        fail1
+        }
+    else
+      if [[ -d $cell.new ]]; then
+        rm -rf $cell.new || fail
+      fi
+      mkdir -p $cell.new || fail
+      link_dna_from_seed $cell.new || {
+        err "Failed to link dna from seed for $cell"
+        fail1
+        }
+    fi
+    mv $cell.new $cell || fail
   fi
-end_function_flat
+end_function
 handle_return
 }
 
@@ -246,7 +263,10 @@ handle_return
 execute_command() {
 local cell=$(realpath $1) command=$2
 vars='cell command'; begin_function
-  cell_context_load || fail
+  cell_context_load || {
+    err "Context failed to load for $cell"
+    fail1
+    }
   local function_exists=$(type -t $command &>/dev/null && echo true)
   if [[ "$function_exists" ]]; then
     $command || fail
@@ -319,7 +339,7 @@ handle_return
 }
 
 execute_command_step_file() {
-begin_function_flat
+vars=step; begin_function
   case $base in
     *.py)
       err "Python steps not implemented yet"
@@ -361,7 +381,7 @@ begin_function_flat
       fail1
     ;;
   esac
-end_function_flat
+end_function
 handle_return
 }
 
@@ -490,7 +510,6 @@ begin_function_flat
     files=( ${contents[$i]} )
     if [[ $files =~ ([0-9]+)-[^/]*$ ]]; then
       file_index=${BASH_REMATCH[1]}
-      # does next file have same index?
     else
       file_index=-1
     fi
@@ -692,7 +711,7 @@ get_top_cell2() {
 local subject=$1
 local parent=${subject%/*}
 if [[ ! -e $subject/.dna ]]; then
-  link_dna_from_seed $subject || return 1
+  link_dna_from_seed $subject || true
 fi
 if [[ -e $subject/.dna ]]; then
   top_cell=$subject
@@ -716,7 +735,7 @@ get_bottom_cell2() {
 local subject=$1
 local parent=${subject%/*}
 if [[ ! -e $subject/.dna ]]; then
-  link_dna_from_seed $subject || return 1
+  link_dna_from_seed $subject || true
 fi
 if [[ -e $subject/.dna ]]; then
   bottom_cell=$subject
@@ -732,7 +751,10 @@ local subject=$1
 local parent=${subject%/*}
 local seed_dna
 if [[ "${#parent}" -gt 1 ]]; then
-  find_seed_dna $parent ${subject#$parent/} || return 1
+  find_seed_dna $parent ${subject#$parent/} || {
+    err "Could not find seed dna for $subject"
+    return 1
+    }
   if [[ "$seed_dna" ]]; then
     ln -sf $seed_dna $subject/.dna || return 1
     return 0
@@ -746,6 +768,7 @@ find_seed_dna() {
 local subject=$1
 local parent=${subject%/*}
 local path_to_cell=$2
+path_to_cell=${path_to_cell%.new}
 seed_dna=$subject/.dna/sub/$path_to_cell/.dna
 if [[ ! -e $seed_dna ]]; then
   seed_dna=
@@ -763,7 +786,8 @@ if [[ ! -e $seed_dna ]]; then
         break
       fi
     done
-    if [[ $failed == t ]]; then
+    seed_dna+=/.dna
+    if [[ $failed == t || ! -d $seed_dna ]]; then
       seed_dna=
     fi
   elif [[ ${#parent} -gt 1 ]]; then
