Refactor get_trunk_cell get_short_cell load_branch_dims into load_branch_info

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -43,7 +43,6 @@ cell_lib_init() {
     get_bottom_cell
     get_new_fork_id
     get_new_reply_file
-    get_short_cell
     get_top_cell
     load_log_vars
     load_log_vars_and_write_to_log
@@ -427,8 +426,10 @@ load_vars() {
   handle_return
 }
 
-load_branch_dims() {
+branch_local_vars='branch_dims branch_members branch_hashes branch_dim_count trunk_cell short_cell'
+load_branch_info() {
   local cell_path=${1:-$cell_path}
+
   begin_function
 
     branch_dims=() \
@@ -456,12 +457,34 @@ load_branch_dims() {
       c=${c%/*}
     end_while
 
+    trunk_cell=$c
     branch_dim_count=${#branch_dims[*]}
 
     if [[ "${branch_dims:-}" ]]; then
       log_debug "Branch dims found: ${branch_dims[*]}"
     fi
 
+    local x y dim_string= 
+    if [[ "${branch_hashes:-}" ]]; then
+      dim_string="${branch_hashes[*]}"
+      dim_string=:${dim_string// /\/}
+    fi
+    local short_trunk=$trunk_cell
+    if   y=${short_trunk%/*/*/*} 
+         x=${short_trunk#$y/}
+         [[ $x != $short_trunk && ${#x} -gt 0 ]]; then
+      short_trunk=$x
+    elif y=${short_trunk%/*/*} 
+         x=${short_trunk#$y/}
+         [[ $x != $short_trunk && ${#x} -gt 0 ]]; then
+      short_trunk=$x
+    elif x=${short_trunk##*/} 
+         [[ $x != $short_trunk && ${#x} -gt 0 ]]; then
+      short_trunk=$x
+    fi
+    short_cell="$short_trunk$dim_string"
+
+    log_return_vars=short_cell
   end_function
   handle_return
 }
@@ -777,10 +800,6 @@ make_or_load_context() {
   local log_vars=cell_path log_show_vars=short_cell
   begin_function_hi
 
-    if [[ ! "${short_cell:-}" ]]; then
-      get_short_cell $cell_path
-    fi
-
     log_debug "Loading context for $short_cell"
     local item_name last_part dna_full_item suffix \
       context_make=$context_make \
@@ -828,47 +847,12 @@ make_context() {
   context_make=t make_or_load_context 
 }
 
-get_trunk_cell() {
-  trunk_cell=$1
-  while [[ $trunk_cell == */*:* ]]; do
-    trunk_cell=${trunk_cell%/*}
-  done
-  debug_return_vars=trunk_cell
-}
-
-get_short_cell() {
-  local x y cell_path=$1 dim_string= branch_dims=
-  load_branch_dims $cell_path || fail
-  if [[ "${branch_hashes:-}" ]]; then
-    dim_string="${branch_hashes[*]}"
-    dim_string=:${dim_string// /\/}
-  fi
-  get_trunk_cell $cell_path
-  if   y=${trunk_cell%/*/*/*} 
-       x=${trunk_cell#$y/}
-       [[ $x != $trunk_cell && ${#x} -gt 0 ]]; then
-    trunk_cell=$x
-  elif y=${trunk_cell%/*/*} 
-       x=${trunk_cell#$y/}
-       [[ $x != $trunk_cell && ${#x} -gt 0 ]]; then
-    trunk_cell=$x
-  elif x=${trunk_cell##*/} 
-       [[ $x != $trunk_cell && ${#x} -gt 0 ]]; then
-    trunk_cell=$x
-  fi
-  short_cell="$trunk_cell$dim_string"
-  debug_return_vars=short_cell
-}
-
 find_seed_path() {
   local work_path=$1 d s= i h dim dim_count
   begin_function
     seed_path=
 
     s=/seed${work_path#/work}
-
-    local branch_dims branch_members branch_hashes branch_dim_count
-    load_branch_dims $work_path || fail
 
     begin_while [[ ! -d $s && $s == *:* ]]; doo
       s=${s%/*}
@@ -929,7 +913,6 @@ setup_cell_path_vars() {
       cell_path=/work${cell_path#/seed}
     fi
 
-    load_branch_dims || fail
     find_seed_path $cell_path || fail
 
     if [[ ! "${top_cell:-}" ]]; then
@@ -942,6 +925,7 @@ setup_cell_path_vars() {
     context_path=$cyto_path/context \
     dna_key_path=$dna_path/key \
     down_path=$cyto_path/down \
+    job_path=$cyto_path/job \
     key_path=$cyto_path/key \
     lock_path=$cyto_path/context \
     req_path=$cyto_path/req \
@@ -1177,9 +1161,6 @@ switch_context() {
         localize_dims=
       fi
 
-      get_short_cell $cell_path
-      : ${anchor_dims:=${trunk_dims[*]}}
-
     end_function
     handle_return
 
@@ -1195,6 +1176,43 @@ setup_dep_defaults() {
   # Make this go back to default for any further contexts loaded
   # fresh passed in by user should only apply to top level cell, not to deps or subs
   fresh=
+  return 0
+}
+
+# inputs: log_id_part
+# outputs: new_fork_id
+get_new_fork_id() {
+  # old way
+#  if [[ ! "${fork_id_log:-}" ]]; then
+#    log_fatal "Missing fork_id_log"
+#    stack_trace
+#    return 1
+#  fi
+#  timeout=5 lock_path=$fork_id_log fd_write_lock || {
+#    echo "Failed to get lock on $fork_id_log" >&2
+#    return 1
+#  }
+#  local last_id=$(tail -n1 $fork_id_log | awk '{print $1}')
+#  (( new_fork_id = last_id + 1 ))
+#  echo $new_fork_id >>$fork_id_log || return 1
+#  fd_unlock
+  : ${ancestor_fork_id:=}
+
+  if [[ "$ancestor_fork_id" ]]; then
+    new_fork_id=$ancestor_fork_id-
+  else
+    new_fork_id=
+  fi
+
+  if [[ "$ancestor_fork_id" ]]; then
+    ancestor_fork_id+=-$log_id_part
+  else
+    ancestor_fork_id+=$log_id_part
+  fi
+
+  new_fork_id+=$log_id_part
+  log_id_part=0
+
   return 0
 }
 
@@ -1298,6 +1316,15 @@ after_fork() {
   return 0
 }
 
+get_new_reply_file() {
+  reply_file=$tmp_folder/reply.$BASHPID
+  if [[ -f $reply_file ]]; then
+    log_fatal "reply_file already exists: $reply_file"
+    return 1
+  fi
+  return 0
+}
+
 # usage: fork {command to execute}
 #  background=f (whether to run as a background process)
 #  change_log=f (whether to change the log)
@@ -1312,6 +1339,9 @@ fork() {
   if [[ $background == t ]]; then
     change_log=t
   fi
+
+  : ${log_id_part:=0}
+  (( log_id_part++ ))
 
   get_new_reply_file || return 1
   defer "rm $reply_file"
@@ -1710,15 +1740,6 @@ reply_to_caller() {
 
 reply_file=
 
-get_new_reply_file() {
-  reply_file=$tmp_folder/reply.$BASHPID
-  if [[ -f $reply_file ]]; then
-    log_fatal "reply_file already exists: $reply_file"
-    return 1
-  fi
-  return 0
-}
-
 # input: parallel processes
 wait_for_sub_processes() {
 if [[ "$processes" ]]; then
@@ -1822,13 +1843,18 @@ parallel_loop() {
   handle_return
 }
 
+get_trunk_cell() {
+  trunk_cell=$1
+  while [[ $trunk_cell == */*:* ]]; do
+    trunk_cell=${trunk_cell%/*}
+  done
+  debug_return_vars=trunk_cell
+}
+
 propagate_change_to_downstream2() {
   begin_function
 
     local cell=$(realpath $value)
-
-    local short_cell
-    get_short_cell $cell || fail
 
     local t1 t2 trunk_cell
     get_trunk_cell $cell
@@ -1870,18 +1896,18 @@ propagate_change_to_downstream2() {
 propagate_change_to_downstream() {
   begin_function
 
-  local from_cell=$from_cell \
-    down_path=$from_cell/.cyto/down down_folder folders
+    local from_cell=$from_cell \
+      down_path=$from_cell/.cyto/down down_folder folders
 
-  if [[ -d $down_path ]]; then
-    local dep_stack=( ${downstream_cell_stack[*]} )
-    folders=( $(find1 $down_path -not -name '.*' -type d) ) || fail
-    loop_over_var=folders \
-    background=f \
-      par=${par:-t} fork=f \
-      body=propagate_change_to_downstream2 \
-      parallel_loop || fail
-  fi
+    if [[ -d $down_path ]]; then
+      local dep_stack=( ${downstream_cell_stack[*]} )
+      folders=( $(find1 $down_path -not -name '.*' -type d) ) || fail
+      loop_over_var=folders \
+      background=f \
+        par=f fork=f \
+        body=propagate_change_to_downstream2 \
+        parallel_loop || fail
+    fi
 
   end_function
   handle_return
@@ -1948,25 +1974,6 @@ execute_op() {
 
   end_function
   handle_return
-}
-
-# inputs: fork_id_log 
-# outputs: new_fork_id
-get_new_fork_id() {
-  if [[ ! "${fork_id_log:-}" ]]; then
-    log_fatal "Missing fork_id_log"
-    stack_trace
-    return 1
-  fi
-  timeout=5 lock_path=$fork_id_log fd_write_lock || {
-    echo "Failed to get lock on $fork_id_log" >&2
-    return 1
-  }
-  local last_id=$(tail -n1 $fork_id_log | awk '{print $1}')
-  (( new_fork_id = last_id + 1 ))
-  echo $new_fork_id >>$fork_id_log || return 1
-  fd_unlock
-  return 0
 }
 
 get_job_id() {
@@ -2131,6 +2138,57 @@ execute_command_internal_setup_params() {
   handle_return
 }
 
+execute_command_log_prep() {
+  begin_function
+    cyto_path=$cell_path/.cyto
+    if [[ ! -d $cyto_path ]]; then
+      mkdir $cyto_path || fail
+    fi
+
+    if [[ ! -d $job_path ]]; then
+      mkdir $job_path || fail
+    fi
+
+    if [[ ! "${omni_log_job_id:-}" ]]; then
+      job_start_time=${EPOCHREALTIME//./}
+      command_to_log="${original_cmd#* }" \
+        get_job_id || fail
+    fi
+
+    current_job_path=$job_path/$omni_log_job_id
+    if [[ ! -d $current_job_path ]]; then
+      mkdir $current_job_path || fail
+    fi
+
+    # only set this for the first cell in the job, all other cells should 
+    #   use the same fork_id log so that they all have unique ids across the job
+    if [[ ! "${fork_id_log:-}" ]]; then
+      fork_id_log=$current_job_path/fork-id-log
+    fi
+
+    log_path=$current_job_path/log
+    if [[ ! -d $log_path ]]; then
+      mkdir $log_path || fail
+    fi
+
+    previous_log_pos=$omni_log_pos
+    cell_open_log_file || fail
+    (( previous_log_pos++ ))
+
+    local running_job_path=$job_path/running
+
+    local link_target
+    begin_for link_target in $current_command-attempt attempt; doo
+      if [[ -e "$job_path/last-$link_target" ]]; then
+        mv $job_path/last-$link_target $job_path/prev-$link_target || fail
+      fi
+      safe_link $current_job_path $job_path/last-$link_target || fail
+    end_for
+
+  end_function
+  handle_return
+}
+
 execute_command_internal() {
 
   local log_vars='cell_path' \
@@ -2141,6 +2199,7 @@ execute_command_internal() {
       omni_log_job_id=${omni_log_job_id:-} \
       omni_log_fork_id=${omni_log_fork_id:-} \
       previous_fork_id=${previous_fork_id:-} \
+      job_path log_path current_job_path \
 
     if [[ "${localize_dims:-}" ]]; then
       eval "$localize_dims" || fail
@@ -2161,18 +2220,10 @@ execute_command_internal() {
 
     command_history+="$current_command $short_cell "
 
-    if [[ $disable_log == f ]]; then
-
-      local running_job_path=$job_path/running
-
-      local link_target
-      begin_for link_target in $current_command-attempt attempt; doo
-        if [[ -e "$job_path/last-$link_target" ]]; then
-          mv $job_path/last-$link_target $job_path/prev-$link_target || fail
-        fi
-        safe_link $current_job_path $job_path/last-$link_target || fail
-      end_for
-
+    if [[ $disable_log == t ]]; then
+      log_debug "Logging disabled."
+    else
+      execute_command_log_prep || fail
     fi
 
     # if [[ ${cell_is_leaf:-t} == t || $show_branches == t ]]; then
@@ -2349,48 +2400,9 @@ plant_seed() {
   handle_return
 }
 
-execute_command_log_prep() {
-  begin_function
-    cyto_path=$cell_path/.cyto
-    if [[ ! -d $cyto_path ]]; then
-      mkdir $cyto_path || fail
-    fi
-
-    if [[ ! -d $job_path ]]; then
-      mkdir $job_path || fail
-    fi
-
-    if [[ ! "${omni_log_job_id:-}" ]]; then
-      job_start_time=${EPOCHREALTIME//./}
-      command_to_log="${original_cmd#* }" \
-        get_job_id || fail
-    fi
-
-    current_job_path=$job_path/$omni_log_job_id
-    if [[ ! -d $current_job_path ]]; then
-      mkdir $current_job_path || fail
-    fi
-
-    # only set this for the first cell in the job, all other cells should 
-    #   use the same fork_id log so that they all have unique ids across the job
-    if [[ ! "${fork_id_log:-}" ]]; then
-      fork_id_log=$current_job_path/fork-id-log
-    fi
-
-    log_path=$current_job_path/log
-    if [[ ! -d $log_path ]]; then
-      mkdir $log_path || fail
-    fi
-  end_function
-  handle_return
-}
-
 execute_command() {
-
   local cell_path=$(realpath $1) current_command=$2 \
-    short_cell disable_log=${disable_log:-}
-
-  local log_show_vars='^cell_path current_command' 
+    log_show_vars='^cell_path current_command' 
   begin_function
 
     if [[ $cell_path != /work* ]]; then
@@ -2405,9 +2417,12 @@ execute_command() {
       }
     fi
 
-    local anchor_dims=${anchor_dims:-}
+    local anchor_dims=${anchor_dims:-} \
+      prev_trunk_cell=${trunk_cell:-} \
+      disable_log=${disable_log:-} \
+      $branch_local_vars \
 
-    get_short_cell $cell_path
+    load_branch_info || fail
 
     case $current_command in log|edit|dim-*|up-*|plant|get)
       disable_log=${disable_log:-t}
@@ -2415,21 +2430,18 @@ execute_command() {
 
     : ${disable_log:=f}
 
-    local job_path omni_log_job_id log_path current_job_path cyto_path
-
-    job_path=$cell_path/.cyto/job
-
-    if [[ $disable_log == t ]]; then
-      log_debug "Logging disabled."
-    else
-      execute_command_log_prep || fail
+    local should_fork=t 
+    if [[ $top_level_command == t ]]; then
+      should_fork=f
+    elif [[ "$prev_trunk_cell" == "$trunk_cell" ]]; then
+      should_fork=f
     fi
 
-    previous_log_pos=$omni_log_pos
-    cell_open_log_file || fail
-    (( previous_log_pos++ ))
-
-    execute_command_internal || fail_later
+    if [[ $should_fork == t ]]; then
+      fork execute_command_internal || fail_later
+    else
+      execute_command_internal || fail_later
+    fi
 
     cell_close_log_file || fail
 
@@ -3031,15 +3043,6 @@ unpause_tee() {
     paused_tee_file=
   fi
   return 0
-}
-
-get_cell_name() {
-  local cell_path=$1
-  local short_cell
-  get_short_cell $cell_path || fail
-  cell_name=${short_cell//\//_}
-  cell_name=${cell_name// /:}
-  debug_return_vars=cell_name
 }
 
 # locks the given cell, or fails if it can't obtain a lock
