Flip yolo default and avoid duplicate coordinates

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -3264,6 +3264,7 @@ find_path_to_dim_required_dims() {
 
       if [[ $resolved == f ]]; then
 
+        # recursive
         find_path_to_dim $required_dim || fail
 
         if [[ $path_found == f ]]; then
@@ -3423,53 +3424,56 @@ get_support_dims() {
 
     log_debug "Finding support dims for $target_dims"
 
-    local dim path_found
-    begin_for dim in $target_dims; doo
-      
-      if [[ ! -v resolved_dims[$dim] ]]; then
+# OLD WAY
+#    local dim path_found
+#    begin_for dim in $target_dims; doo
+#      
+#      if [[ ! -v resolved_dims[$dim] ]]; then
+#
+#        grip_fence
+#
+#        if any_dim_is_set $dim; then
+#          resolve_dim $dim
+#          continue
+#        fi
+#
+#        #  this doesn't work because all_if_blank prevents
+#        #  support dims needed to derive non-blank results
+#        #if any_dim_is_set $dim \
+#        #  || [[ " ${all_if_blank:-} " == *" $dim "* ]]; then
+#        #  resolved_dims[$dim]=1
+#        #  continue
+#        #fi
+#
+#        extra_dims_needed=()
+#        local history= loop_found=f unresolved_log=
+#        find_path_to_dim $dim || fail
+#        if [[ $path_found == t ]]; then
+#          if (( "${#extra_dims_needed[*]}" > 0 )); then
+#            log_debug "Support dims needed for $dim: ${!extra_dims_needed[*]}"
+#            add_to_set extra_dims_needed support_dims_set || fail
+#          fi
+#        elif [[ " ${all_if_blank:-} " != *" $dim "* ]]; then
+#          log_fatal "Could not resolve dim $dim." \
+#            "Either provide this dim value or other dims which can be used" \
+#            "to derive this. Or add it to the all_if_blank var."
+#          if [[ "$unresolved_log" ]] && log_level_at_least debug; then
+#            echo "Dim dependencies: (red dims are missing) " >&$fd_original_err
+#            echo "$unresolved_log" >&$fd_original_err
+#          fi
+#          fail1
+#        fi
+#      fi
+#
+#      if [[ " ${trunk_dims_expanded[*]} " != *" $dim "* ]]; then
+#        support_dims_set[$dim]=1
+#      else
+#        unset support_dims_set[$dim]
+#      fi
+#
+#    end_for
 
-        grip_fence
-
-        if any_dim_is_set $dim; then
-          resolve_dim $dim
-          continue
-        fi
-
-        #  this doesn't work because all_if_blank prevents
-        #  support dims needed to derive non-blank results
-        #if any_dim_is_set $dim \
-        #  || [[ " ${all_if_blank:-} " == *" $dim "* ]]; then
-        #  resolved_dims[$dim]=1
-        #  continue
-        #fi
-
-        extra_dims_needed=()
-        local history= loop_found=f unresolved_log=
-        find_path_to_dim $dim || fail
-        if [[ $path_found == t ]]; then
-          if (( "${#extra_dims_needed[*]}" > 0 )); then
-            log_debug "Support dims needed for $dim: ${!extra_dims_needed[*]}"
-            add_to_set extra_dims_needed support_dims_set || fail
-          fi
-        elif [[ " ${all_if_blank:-} " != *" $dim "* ]]; then
-          log_fatal "Could not resolve dim $dim." \
-            "Either provide this dim value or other dims which can be used" \
-            "to derive this. Or add it to the all_if_blank var."
-          if [[ "$unresolved_log" ]] && log_level_at_least debug; then
-            echo "Dim dependencies: (red dims are missing) " >&$fd_original_err
-            echo "$unresolved_log" >&$fd_original_err
-          fi
-          fail1
-        fi
-      fi
-
-      if [[ " ${trunk_dims_expanded[*]} " != *" $dim "* ]]; then
-        support_dims_set[$dim]=1
-      else
-        unset support_dims_set[$dim]
-      fi
-
-    end_for
+    array_to_set related_dims_expanded support_dims_set
 
     local d
     for d in ${trunk_dims_expanded[*]:-} ${sub_dims_expanded[*]:-} ${control_props_expanded[*]:-} ${data_props_expanded[*]:-}; do
@@ -6273,13 +6277,18 @@ calc_coordinates_add_row() {
           fail1
         fi
         new_coords+=( "" )
-        coord_added_string+="'' "
+        if [[ -v required_dims[$dim_var] ]]; then
+          coord_added_string+="'' "
+        fi
       else
         new_coords+=( "$dim_value" )
-        coord_added_string+="$dim_value "
+        if [[ -v required_dims[$dim_var] ]]; then
+          coord_added_string+="$dim_value "
+        fi
       fi
     done
 
+    log_debug "${coord_type}_coordinate_data+=( ${new_coords[*]} )"
     if [[ ! -v coordinates_added[$coord_added_string] ]]; then
       coordinates_added[$coord_added_string]=1
       new_coordinate_data+=( "${new_coords[@]}" )
@@ -6287,8 +6296,8 @@ calc_coordinates_add_row() {
       progress_bar_nudge +
     else
       progress_bar_nudge -
+      log_debug "Duplicate coordinate skipped"
     fi
-    log_debug "${coord_type}_coordinate_data+=( ${new_coords[*]} )"
 
   end_function
   handle_return
@@ -6578,6 +6587,17 @@ calc_coordinates_next_unknown_dim_found() {
   local needs_narrowing=${needs_narrowing:-t} \
     interesting_vars=dim
   begin_function
+
+    local -n member_type=dim_${dim}_effective_member_type
+    if [[ $values == all && $member_type == dynamic ]]; then
+      if [[ -v required_dims[$dim] ]]; then
+        log_fatal "Missing required dim: $dim"
+        fail1
+      else
+        already_expanded=t
+        values=( none )
+      fi
+    fi
 
     resolved_dims+=" $dim"
 
@@ -7725,15 +7745,15 @@ build_context() {
       rm $context_path.new || fail
     fi
 
-    local dim_cache derive_cache
-
-    begin_for dim_cache in ${dim_caches:-}; doo
-      cat $dim_cache >>$context_path.new || fail
-    end_for
-
-    begin_for derive_cache in ${derive_caches:-}; doo
-      cat $derive_cache >>$context_path.new || fail
-    end_for
+#    local dim_cache derive_cache
+#
+#    begin_for dim_cache in ${dim_caches:-}; doo
+#      cat $dim_cache >>$context_path.new || fail
+#    end_for
+#
+#    begin_for derive_cache in ${derive_caches:-}; doo
+#      cat $derive_cache >>$context_path.new || fail
+#    end_for
 
     if [[ -e $context_path-trunk ]]; then
       cat $context_path-trunk >>$context_path.new || fail
