Improve update

diff --git a/lib/cell-common b/lib/cell-common
--- a/lib/cell-common
+++ b/lib/cell-common
@@ -141,13 +141,7 @@ return 0
 init_update_context() {
 # this should write to out.new or out/{row}.new
 execute_update() { 
-  if [ -d "$current_cell/in" ]; then
-    local from="$current_cell/in"
-    if [ -d "$current_cell/in$row_path" ]; then
-      from="$current_cell/in$row_path"
-    fi
-    rsync -a "$from/" "$out_path.new/" || return 1
-  fi
+  rsync -a "$in_path/" "$out_path.new/" || return 1
   return 0
 }
 }
@@ -177,5 +171,38 @@ local parent=${f%/*}
 [ -f "$f/update-context-after" ] && source "$f/update-context-after"
 [ "${#parent}" -gt 1 ] && { load_update_context_after "$parent" || return 1; }
 return 0
+}
+
+decrypt_file() {
+
+local from=$1; shift
+local to=$1; shift
+
+trace 0 "Decrypting $from"
+begin_function
+
+  mkdir -p "$tmp_path" || fail
+
+  if [ ! -f "$current_cell/key/key.$USER" ]; then
+    err "You don't have a key for this cell ($USER). Ask someone who does to add you. Existing keys:" 
+    find $current_cell/key -name "key.*" >&2
+    fail
+  fi
+
+  # extract the master key
+  openssl pkeyutl -decrypt -inkey ~/.ssh/id_rsa -in "$current_cell/key/key.$USER" -out $tmp_path/master || {
+    err "Failed to decrypt master key." 
+    fail
+  }
+
+  # decrypt the secret file
+  openssl enc -aes256 -in $from -out $to -d -pass file:$tmp_path/master || {
+    err "Failed to decrypt secret file." 
+    fail
+  }
+
+end_function
+handle_return
+
 }
 
diff --git a/lib/cell-update b/lib/cell-update
--- a/lib/cell-update
+++ b/lib/cell-update
@@ -180,10 +180,10 @@ begin_function
     fi
 
     if [ $parallel == t ]; then
-      cell_update_row "$dep" &
+      called_from=$short_cell/up cell_update_row "$dep" &
       processes+=" $!"
     else
-      cell_update_row "$dep" || fail
+      called_from=$short_cell/up cell_update_row "$dep" || fail
     fi
   end_for
 
@@ -287,9 +287,32 @@ begin_function
   new_status load-update-context || fail
   init_and_load_update_context_a
 
-  new_status execute-update || fail
+  local in_path="$current_cell/in"
+  [ -n "$row_path" ] && [ -d "$current_cell/in$row_path" ] && in_path="$current_cell/in$row_path"
+
+  local tmp_path="$current_cell/tmp$row_path"
 
   mkdir -p "$out_path.new" || fail
+
+  local need_decrypt file
+  begin_for file in $(find "$in_path" -name '*.crypt' -type f); doo
+    file=${file#$in_path}
+    file=${file%.crypt}
+    if [ -f "$out_path/$file" ]; then
+      cp "$out_path/$file" "$out_path.new/$file" || fail
+    else
+      need_decrypt+="$file "
+    fi
+  end_for
+
+  if [ "$need_decrypt" ]; then
+    new_status decrypt || fail
+    begin_for file in $need_decrypt; doo
+      decrypt_file "$in_path/$file.crypt" "$out_path.new/$file" || fail
+    end_for
+  fi
+
+  new_status execute-update || fail
 
   local start_time=$EPOCHSECONDS
   local update_successful=f
@@ -297,7 +320,7 @@ begin_function
   local duration_of_update=$((EPOCHSECONDS-start_time))
   local success_string=good
   [ $update_successful == f ] && success_string=bad
-  echo "$start_time $duration_of_update $success_string" >>$log_path/history || fail
+  echo "start:$start_time duration:$duration_of_update from:$called_from result:$success_string" >>$log_path/history || fail
 
   if [ $update_successful == t ]; then
 
@@ -339,8 +362,8 @@ begin_function
 
   fi
 
-  if [ -d "$current_cell/tmp$row_path" ]; then
-    rm -rf "$current_cell/tmp$row_path" || fail
+  if [ -d "$tmp_path" ]; then
+    rm -rf "$tmp_path" || fail
   fi
 
 end_function
