.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -2915,7 +2915,7 @@ execute_command() {
       ;;
     esac
 
-    log_info "Executing cell command: $short_cell $cell_command" || fail
+    strong_log=t log_info "Executing cell command: $short_cell $cell_command" || fail
 
     if [[ ! -e "$cell_path" ]]; then
       plant_seed $cell_path || {
