Make trace_stack

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -5879,7 +5879,12 @@ switch_context() {
         if [[ "$derive_caches" ]]; then
           local derive_cache
           for derive_cache in $derive_caches; do
-            source $derive_cache || fail
+            if [[ -f $derive_caches ]]; then
+              source $derive_cache || fail
+            else
+              log_fatal "Internal error: Derive cache is expected to exist at this point but is missing."
+              fail1
+            fi
           done
         fi
 
