Fix log command bugs

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -65,7 +65,6 @@ cell_lib_init() {
     fork_inside
     function_exists
     get_bottom_cell
-    get_new_fork_id
     get_new_reply_file
     get_top_cell
     load_log_vars
@@ -1372,7 +1371,7 @@ switch_context_prep_dims() {
         is_optional=${is_optional:-f}
         sdim=${sdim:-${pdim:-${dim:-}}}
         sdims=${sdims:-${pdims:-${dims:-}}}
-        if [[ ! "$sdims" && ! "$sdim" && ! "$ddim" && ! "$ddims" ]]; then
+        if [[ ! "${sdims:-}" && ! "${sdim:-}" && ! "${ddim:-}" && ! "${ddims:-}" ]]; then
           if [[ $is_optional == f ]]; then
             missing_dims+=( $dim_var )
           fi
@@ -2077,19 +2076,23 @@ cell_open_log_file() {
       fail1
     fi
      
-    if [[ "${omni_log_job_id:-0}" != 0 && $disable_log == f ]]; then
+    if [[ "${omni_log_job_id:-0}" != 0 ]]; then
+
       cell_log_file_stack+=( $logging_to_file )
-      previous_fork_id=$omni_log_fork_id
-      get_new_fork_id || fail
-      local new_log_file=$log_path/$omni_log_job_id:$new_fork_id.olog
+
+      omni_log_fork_id=${omni_log_fork_parent:-}-${omni_log_fork_child}
+      omni_log_fork_id=${omni_log_fork_id#-}
+
+      local new_log_file=$log_path/$omni_log_job_id:$omni_log_fork_id.olog
       local first_log_path=${new_log_file%/*}/first.olog
       if [[ ! -f $first_log_path ]]; then
         from_must_exist=f \
           safe_link $new_log_file $first_log_path || fail
       fi
-      omni_log_fork_id=$new_fork_id
+
       log_function=${FUNCNAME[1]} \
         change_log_file || fail
+
     fi
   end_function
   handle_return
@@ -2099,7 +2102,6 @@ cell_close_log_file() {
   begin_function
     if [[ "${cell_log_file_stack:-}" ]]; then
       local previous_log=${cell_log_file_stack[-1]}
-      omni_log_fork_id=$previous_fork_id
       unset cell_log_file_stack[-1]
       log_function=${FUNCNAME[1]} \
         new_log_file=$previous_log \
@@ -2140,6 +2142,7 @@ get_job_id() {
 
     fd_unlock
 
+    log_return_vars=omni_log_job_id
   end_function
   handle_return
 }
@@ -2200,6 +2203,10 @@ execute_command_internal() {
     log_show_vars='short_cell current_command' 
   begin_function_hi
 
+    local omni_log_fork_parent=${omni_log_fork_parent:-}-${omni_log_fork_child:-1} \
+      omni_log_fork_child=0
+    omni_log_fork_parent=${omni_log_fork_parent#-}
+
     if [[ "${localize_dims:-}" ]]; then
       eval "$localize_dims" || fail
     fi
@@ -2219,7 +2226,7 @@ execute_command_internal() {
     command_history+="$current_command $short_cell "
 
     if [[ ${cell_is_leaf:-t} == t || $show_branches == t ]]; then
-      log_info "Executing cell command: $short_cell $current_command"
+      log_info "Executing cell command: $short_cell $current_command" || fail
     else
       log_verbose "Executing cell command: $short_cell $current_command" || fail
     fi
@@ -2357,6 +2364,8 @@ execute_command() {
       fork execute_command_internal || fail_later
     else
       if [[ $disable_log == f ]]; then
+        : ${omni_log_fork_child:=0}
+        (( omni_log_fork_child++ ))
         previous_log_pos=$omni_log_pos
         cell_open_log_file || fail
         (( previous_log_pos++ ))
@@ -2430,19 +2439,6 @@ setup_dep_defaults() {
   return 0
 }
 
-# inputs: omni_log_fork_id child_log_id
-# outputs: new_fork_id
-get_new_fork_id() {
-  : ${child_log_id:=0}
-  (( child_log_id++ ))
-  if [[ "${omni_log_fork_id:-}" ]]; then
-    new_fork_id=$omni_log_fork_id-$child_log_id
-  else
-    new_fork_id=$child_log_id
-  fi
-  return 0
-}
-
 reply_to_caller() {
   if [[ "${reply_file:-}" ]]; then
     echo "$*" >>$reply_file || return 1
@@ -2459,7 +2455,7 @@ fork_inside() {
     # Prevents this variable from bleeding through to lower called functions
     change_log=
 
-    if [[ $change_log2 == t ]]; then
+    if [[ $change_log2 == t && $disable_log == f ]]; then
       previous_log_pos=$omni_log_pos
       cell_open_log_file || fail
       (( previous_log_pos++ ))
@@ -2550,8 +2546,8 @@ fork() {
     change_log=t
   fi
 
-  : ${log_id_part:=0}
-  (( log_id_part++ ))
+  : ${omni_log_fork_child:=0}
+  (( omni_log_fork_child++ ))
 
   get_new_reply_file || return 1
   defer "rm $reply_file"
