.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -3394,7 +3394,7 @@ cell_unlock() {
 #   
 to_background_shell_single() {
   local command=$1
-  begin_function
+  begin_function_flat
 
     if [[ "${timeout:-}" ]]; then
       local timeout_ms=$((timeout*1000))
@@ -3416,16 +3416,30 @@ to_background_shell_single() {
       echo -n "$command" >$pipe_in & 
       pid=$!
 
-      timed_out=f
+      timed_out=f wait_time=0
+      set -x
       begin_while ps $pid &>/dev/null; doo
+
+        log_debug "Sleeping for $seconds_to_wait seconds"
         sleep $seconds_to_wait || fail
-        (( time_left -= $delay_ms ))
+
+        (( time_left -= delay_ms 
+         , wait_time += delay_ms ))
+
         if (( time_left <= 0 )); then
           log_debug "Timed out trying to execute: $command"
           timed_out=t
+          kill $pid || log_warn "Failed to kill $pid"
           break
         fi
+
+        if (( wait_time > 2 )); then
+          out "${NL}Waiting for pipe to be open"
+        fi
+
       end_while
+      set +x
+      log_debug "Finished waiting. Took $wait_time seconds."
 
     fi
 
@@ -3574,21 +3588,29 @@ from_background_shell__prep() {
 # input:
 #   pipe      path to pipe to receive commands from
 #   to_var    var to write result to
+#   timeout   0=never timeout, >0=timeout after that many seconds (may be fractional)
 # output:
 #   timed_out 
 #   failed
 from_background_shell() {
   local pipe_in=${pipe}_in pipe_out=${pipe}_out \
     buffering=${buffering:-line} \
-    timeout=${timeout:-2} \
     stop_after=${stop_after:-} \
     fail_after=${fail_after:-} \
     interact=${interact:-} \
     secret=${secret:-none}
+
+  if [[ "${timeout:-}" ]]; then
+    local timeout_ms=$((timeout*1000))
+  else
+    local timeout_ms=${timeout_ms:-0}
+  fi
+  local timeout_s=$(dc -e "2 k $timeout_s 1000 / p") || fail
+
   local -n to=$to_var
 
   local log_show_vars='pipe' \
-    log_vars='timeout stop_after fail_after interact'
+    log_vars='timeout_s stop_after fail_after interact'
   begin_function
 
     timed_out=f
@@ -3604,7 +3626,7 @@ from_background_shell() {
     if [[ $buffering == line ]]; then
       while true; do
 
-        IFS= read -r -t $timeout line <$pipe_out
+        IFS= read -r -t $timeout_ms line <$pipe_out
 
         if (( $? > 128 )); then 
           timed_out=t
@@ -3696,28 +3718,41 @@ run_pipe_command() {
 flush_background_shell() {
   local pipe_in=${pipe}_in pipe_out=${pipe}_out \
     buffering=${buffering:-line} \
-    timeout=${timeout:-1} line char
+    line char
   local log_show_vars=pipe
+
+  if [[ "${timeout:-}" ]]; then
+    local timeout_ms=$((timeout*1000))
+  else
+    local timeout_ms=${timeout_ms:-1000}
+  fi
+  local seconds_to_wait=$(dc -e "2 k $timeout_ms 1000 / p") || fail
+
   begin_function
 
+    log_debug "Flushing background output with timeout of ${seconds_to_wait}s"
     line=
-    if [[ $buffering == char ]]; then
-      while IFS= read -n1 -r -t $timeout -r char || [[ "$line" ]]; do
-        if [ "$char" ]; then
-          line+=$char
-        else
+    case "$buffering" in
+      char)
+        while IFS= read -n1 -r -t $seconds_to_wait -r char || [[ "$line" ]]; do
+          if [ "$char" ]; then
+            line+=$char
+          else
+            log_debug "Flushing: $line"
+            line=
+          fi
+        done <$pipe_out
+        ;;
+      line)
+        while IFS= read -r -t $seconds_to_wait -r line; do
           log_debug "Flushing: $line"
-          line=
-        fi
-      done <$pipe_out
-    elif [[ $buffering == line ]]; then
-      while IFS= read -r -t $timeout -r line; do
-        log_debug "Flushing: $line"
-      done <$pipe_out
-    else
-      log_fatal "Invalid buffering type: $buffering. Should be char or line"
-      fail1
-    fi
+        done <$pipe_out
+        ;;
+      *)
+        log_fatal "Invalid buffering type: $buffering. Should be char or line"
+        fail1
+        ;;
+    esac
 
   end_function
   handle_return
