Fix member loading bug

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -1598,7 +1598,7 @@ load_branch_info() {
 
         local member_var_path=$c/.member
         if [[ -f $member_var_path ]]; then
-          m=$(<$member_var_path) || fail
+          IFS= read -r -d '' m <$member_var_path
         fi
         branch_members=( "$m" "${branch_members[@]}" )
 
@@ -2835,11 +2835,6 @@ calc_coordinates_next_unknown_dim() {
           fence
           log_debug "Finding values for $dim in phase $phase"
 
-          if [[ " $trace_dims " == *" $dim "* ]]; then
-            var= \
-            show_trace_dim_message "Value is unknown"
-          fi
-
           local values= already_expanded=f
           if [[ $phase == derive ]]; then
             attempt_derive $dim || fail
@@ -3119,11 +3114,6 @@ calc_coordinates_next_known_dim_member() {
     fi
 
     if [[ $is_valid == t ]]; then
-
-      if [[ " $trace_dims " == *" $dim "* && "$member" ]]; then
-        var=member \
-        show_trace_dim_message "Value is known"
-      fi
 
       conflict=
       if [[ ${is_cross_dim:-f} == t ]]; then
@@ -4833,7 +4823,7 @@ plant_member() {
 
       mkdir $new_path || fail
       if [[ "$member" != "$sane_value" ]]; then
-        echo "$member" >$new_path/.member || fail
+        echo -n "$member" >$new_path/.member || fail
       fi
 
       plant_seed $member_path $new_path || fail
@@ -5277,7 +5267,7 @@ get_sane_value() {
   if [[ ${#value} -lt 40 && "$value" =~ ^[A-Za-z0-9_\.:\-]+$ ]]; then
     _s=$value
   else
-    hash=$(echo "$value" | sha1sum | awk '{ print $1 }')
+    hash=$(echo -n "$value" | sha1sum | awk '{ print $1 }')
     _s=${hash:0:8}
   fi
   debug_return_vars=_s
