.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -2587,13 +2587,25 @@ load_post_context_dynamic_vars() {
 
     mock_path=$seed_path/.mock
 
-    if [[ -f $cell_path/.mock ]]; then
-      current_mock=$(<$cell_path/.mock)
+    current_mock=f
+    if [[ -e $cell_path/.mock ]]; then
+      current_mock=$(<$cell_path/.mock) || fail
+    fi
+
+    if [[ "${force_mock:-}" && -d $mock_path/$force_mock && $current_mock != $force_mock ]]; then
+      log_debug "Changing mock: $current_mock -> $force_mock (because of force_mock parameter)"
+      current_mock=$force_mock
+      echo "$force_mock" >$cell_path/.mock || fail
+    elif [[ -f $cell_path/.mock ]]; then
+      :
     elif [[ -f $trunk_cell/.mock ]]; then
-      current_mock=$(<$trunk_cell/.mock)
       local trunk_seed
       find_seed_path $trunk_cell trunk_seed || fail
-      mock_path=$trunk_seed/.mock
+      #mock_path=$trunk_seed/.mock
+    elif [[ "${mock:-}" && -d $mock_path/$mock && $current_mock != $mock ]]; then
+      log_debug "Changing mock: $current_mock -> $mock (because of mock parameter)"
+      current_mock=$mock
+      echo "$mock" >$cell_path/.mock || fail
     else
       current_mock=f
     fi
