.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -2719,32 +2719,72 @@ load_child_dims() {
 find_path_to_dim() {
   local target_dim=$1
   begin_function
+    local -A new_extra_dims_needed=()
     local -n derived_from=dim_${target_dim}_derived_from
-    local row_array derived_from_row target type
+    local row_array derived_from_row target type required_dims optional_dims
     begin_for derived_from_row in "${derived_from[@]}"; doo
+
       row_array=( $derived_from_row )
       target=$row_array
-      type=${target##*.}
-      case $type in
-        fun)
-          local derive_fun=${target%.*}
-          local f_name=derive_function_$derive_fun
-          local action=check values=() can_derive=f target_dim=$dim
-          $f_name || fail
-        ;;
-        tab)
-          local derive_table=${target%.*}
-          derive_found=t
-          extract_from_derive_table || fail
-        ;;
-        *)
-          log_fatal "Unknown derived_from type: $type"
-          fail1
-        ;;
-      esac
-      if (( ${#value_set[*]} == 0 )); then
-        break
+      required_dims=${row_array[1]}
+      required_dims=( ${required_dims//,/ } )
+      optional_dims=${row_array[2]}
+      optional_dims=( ${optional_dims//,/ } )
+
+      local required_dim all_required_set=t resolved
+      for required_dim in ${required_dims[*]}; do
+
+        resolved=f
+
+        if [[ -v ${resolved_dims[$required_dim]} ]]; then
+          resolved=t
+        elif any_dim_is_set $required_dim; then
+          resolved_dim[$required_dim]=1
+          resolved=t
+        fi
+
+        if [[ $resolved == f ]]; then
+          # TODO attempt recursion
+          all_required_set=f
+          # TODO if failed, add to potentials
+        fi
+
+      done
+
+      # TODO handle optional dims
+
+      if [[ $all_required_set == t ]]; then
+        path_found=t
+        # TODO this is a set
+        extra_dims_needed+="${required_dims[*]} ${optional_dims[*]}"
+
+        # TODO move new_extra_dims_needed to extra_dims_needed
+        succeed
+      else
+        # TODO
+        extra_dims_needed=()
       fi
+
+      #  don't think we need this
+      #type=${target##*.}
+      #case $type in
+      #  fun)
+      #    local derive_fun=${target%.*}
+      #    local f_name=derive_function_$derive_fun
+      #    local action=check values=() can_derive=f target_dim=$dim
+      #    $f_name || fail
+      #  ;;
+      #  tab)
+      #    local derive_table=${target%.*}
+      #    derive_found=t
+      #    extract_from_derive_table || fail
+      #  ;;
+      #  *)
+      #    log_fatal "Unknown derived_from type: $type"
+      #    fail1
+      #  ;;
+      #esac
+
     end_for
   end_function
   handle_return
@@ -2759,8 +2799,11 @@ get_support_dims() {
   begin_function
 
     local -A support_dims_set \
-      resolved_dims
+      resolved_dims \
+      extra_dims_needed \
+      potentials \
 
+    local dim path_found
     begin_for dim in $target_dims; doo
       
       if [[ ! -v resolved_dims[$dim] ]]; then
@@ -2769,7 +2812,21 @@ get_support_dims() {
           continue
         fi
 
+        extra_dims_needed=()
+        potentials=()
+        path_found=f
         find_path_to_dim $dim || fail
+        if [[ $path_found == t ]]; then
+          add_to_set extra_dims_needed support_dims_set || fail
+        else
+          log_fatal "Could not resolve dim $dim."
+          if (( ${#potentials} > 0 )); then
+            log_fatal "Either provide this dim value or other dims which can be used to derive this, such as one of these: ${!potentials[*]}"
+          else
+            log_fatal "No other dims were found which could be used to derive this, so either the user needs to provide this dim value or another cell."
+          fi
+          fail1
+        fi
       fi
 
     end_for
@@ -6248,6 +6305,21 @@ any_dim_is_set() {
     local -n ddim=d_${dim} ddims=d_${dims}
     if [[ "${ddim:-}" || "${ddims:-}" ]]; then
       is_set=t
+      break
+    fi
+  done
+  [[ $is_set == t ]]
+}
+
+# inputs:
+#   $*   the dims to check, must use short dims (like trunk_dims, etc)
+all_dims_are_set() {
+  local dim dims is_set=t
+  for dim in $*; do
+    get_plural $dim dims
+    local -n ddim=d_${dim} ddims=d_${dims}
+    if [[ ! "${ddim:-}" && ! "${ddims:-}" ]]; then
+      is_set=f
       break
     fi
   done
