Make 'each' folder step run sub steps in parallel

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -54,9 +54,9 @@ begin_function
   to=$to/$folder_name
   begin_for lib in $(find1 -not -name '.*' $from); doo
     if [[ -f $lib ]]; then
-      local source_path=${lib%/*} target_file=${lib##*/} base index
+      local source_path=${lib%/*} target_file=${lib##*/} base prefix
       if [[ ! $target_file =~ ([0-9]+)-(.*) ]]; then
-        index=000
+        prefix=000
         base=$target_file
         found=( $(find1 $to -regex '[0-9]+-'$base'$' | sort -g) ) || fail
         if [[ "$found" ]]; then
@@ -64,8 +64,6 @@ begin_function
           if [[ "${#found[*]}" -gt 1 ]]; then
             warn "Found more than one match for $lib in $to. Will use $target_file."
           fi
-        else
-          target_file=$index-$base
         fi
       fi
       ln -sf $lib $to/$target_file || fail
@@ -105,71 +103,33 @@ handle_return
 execute_command_step() {
 local step=$1
 vars=step; begin_function
-  local step_name=${step##*/}
+  local step_name=${step##*/} prefix=
+
+  if [[ $target_file =~ ([0-9]+)-(.*) ]]; then
+    prefix=${BASH_REMATCH[1]}
+    base=${BASH_REMATCH[2]}
+  fi
+  
+  if [[ ! "$prefix" ]]; then
+    succeed # only execute steps that have a numeric prefix
+  fi
+
   if [[ -d $step/.dna ]]; then
     # recursive
     execute_command $step update || fail
   elif [[ -d $step ]]; then
-    if [[ $step_name =~ ^choose-.* ]]; then
+    if [[ $base =~ ^choose-.* ]]; then
       # TODO ...
       incomplete
-    elif [[ $step_name =~ ^each-.* ]]; then
-      local ref ref_group
-      if [[ $step_name =~ ^each-([^-]+)-in-([^-]+) ]]; then
-        ref=${BASH_REMATCH[1]}
-        ref_group=${BASH_REMATCH[2]}
-      elif [[ $step_name =~ ^each-([^-]+) ]]; then
-        ref=${BASH_REMATCH[1]}
-        ref_group=${ref}s
-      fi
-      if [[ ! -v $ref_group ]]; then
-        err "var doesn't exist: $ref_group"
-        fail1
-      fi
-      local v a
-      eval "a=( \"$ref_group[@]}\" )"
-      begin_for v in "${a[@]}"; doo
-        let "$ref=\$v"
-        execute_command_step_plain_folder $step || fail
-      end_for
+    elif [[ $base =~ ^serial-each-.* ]]; then
+      serial=t execute_command_step_each || fail
+    elif [[ $base =~ ^each-.* ]]; then
+      serial=f execute_command_step_each || fail
     else
       execute_command_step_plain_folder $step || fail
     fi
   elif [[ -f $step ]]; then
-    case $step in
-      *.py)
-        err "Python steps not implemented yet"
-        fail1
-      ;;
-      *.js)
-        err "JavaScript steps not implemented yet"
-        fail1
-      ;;
-      *.go)
-        err "GoLang steps not implemented yet"
-        fail1
-      ;;
-      *.java)
-        err "Java steps not implemented yet"
-        fail1
-      ;;
-      *.bash)
-        source $step || fail
-        local function_name=${step%.bash}
-        function_name=${function_name##*/}
-        local function_exists=`type -t $function_name &>/dev/null && echo true`
-        if [[ "$function_exists" ]]; then
-          $function_name || fail
-        else
-          err "Step $step requires that a function named $function_name be defined in that file."
-          fail1
-        fi
-      ;;
-      *)
-        err "Unknown file format for $step. Can't execute."
-        fail1
-      ;;
-    esac
+    execute_command_step_file $step || fail
   else 
     err "I don't know how to process this step: $step"
     fail1
@@ -178,9 +138,94 @@ end_function
 handle_return
 }
 
+execute_command_step_file() {
+begin_function_flat
+  case $step in
+    *.py)
+      err "Python steps not implemented yet"
+      fail1
+    ;;
+    *.js)
+      err "JavaScript steps not implemented yet"
+      fail1
+    ;;
+    *.go)
+      err "GoLang steps not implemented yet"
+      fail1
+    ;;
+    *.java)
+      err "Java steps not implemented yet"
+      fail1
+    ;;
+    *.bash)
+      source $step || fail
+      local function_name=${step%.bash}
+      function_name=${function_name##*/}
+      local function_exists=`type -t $function_name &>/dev/null && echo true`
+      if [[ "$function_exists" ]]; then
+        $function_name || fail
+      else
+        err "Step $step requires that a function named $function_name be defined in that file."
+        fail1
+      fi
+    ;;
+    *)
+      err "Unknown file format for $step. Can't execute."
+      fail1
+    ;;
+  esac
+end_function_flat
+handle_return
+}
+
+execute_command_step_each() {
+local serial=$serial
+begin_function_flat
+  local ref ref_group
+  if [[ $base =~ each-([^-]+)-in-([^-]+) ]]; then
+    ref=${BASH_REMATCH[1]}
+    ref_group=${BASH_REMATCH[2]}
+  elif [[ $base =~ each-([^-]+) ]]; then
+    ref=${BASH_REMATCH[1]}
+    ref_group=${ref}s
+  fi
+  if [[ ! -v $ref_group ]]; then
+    err "var doesn't exist: $ref_group"
+    fail1
+  fi
+  local v a
+  eval "a=( \"$ref_group[@]}\" )"
+
+  local parallel=f processes=
+  if [[ "${#a[*]}" -gt 1 ]]; then
+    if [[ "$parallel_execution" == t && $serial == f ]]; then
+      parallel=t
+      wait_for_low_load || fail
+    fi
+  fi
+
+  begin_for v in "${a[@]}"; doo
+    let "$ref=\$v"
+    if [[ $parallel == t ]]; then
+      execute_command_step_plain_folder $step &
+      processes+=" $!"
+    else
+      execute_command_step_plain_folder $step || fail
+    fi
+  end_for
+
+  wait_for_sub_processes || fail
+
+end_function_flat
+handle_return
+}
+
+# may be run in a subshell
 execute_command_step_plain_folder() {
 local step=$1
 begin_function_flat
+
+  change_log_file || fail
 
   local contents=$(find1 -not -name ".*" $step | sort -g) || fail
   local files i=0 file_index
