.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -839,6 +839,63 @@ dim_${dim}_expand() {
 # inputs:
 #   $1          full path of file to write to
 #   skip_dims   (optional) dims to skip
+write_coordinates_to_shell_file() {
+  local coord_type=$coord_type target_file=$1 skip_dims=${skip_dims:-}
+  begin_function
+
+    if [[ -f $target_file ]]; then
+      log_fatal "Target file $target_file already exists. It must be deleted before calling this function."
+      fail1
+    fi
+
+    local value field_index data_offset row_index field
+
+    local -n c_data=${coord_type}_coordinate_data \
+      c_fields=${coord_type}_coordinate_fields \
+
+    local c_fields_count=${#c_fields[*]} \
+      c_count=${#c_data[*]} \
+
+    local c_rows=$(( c_count / c_fields_count ))
+
+    if [[ ! "{c_fields:-}" || c_rows -eq 0 ]]; then
+      log_fatal "There must be at least one ${coord_type} coord row to call write_coordinates_to_tab_file"
+      fail1
+    fi
+
+    echo "${coord_type}_coordinate_fields=( ${c_fields[*]} )" >$target_file || fail
+    echo "${coord_type}_coordinate_data=(" >>$target_file || fail
+
+    local line=
+    for (( row_index = 0; row_index < c_rows; row_index++ )); do
+
+      line="  "
+
+      for (( field_index = 0; field_index < c_fields_count; field_index++ )); do
+        (( data_offset = row_index * c_fields_count + field_index ))
+        field=${c_fields[$field_index]}
+        if [[ " $skip_dims " != *" $field "* ]]; then
+          value=${c_data[$data_offset]}
+          shell_quote_var value
+          line+="$value "
+        fi
+      done
+
+      echo "${line% }" >>$target_file || fail
+
+    done
+
+    echo ")" >>$target_file || fail
+
+  end_function
+  handle_return
+}
+
+# writes $coord_type coords to a file, skipping dims specified in skip_dims
+# also assumes that there is 1 or more sub coord rows
+# inputs:
+#   $1          full path of file to write to
+#   skip_dims   (optional) dims to skip
 write_coordinates_to_tab_file() {
   local coord_type=$coord_type target_file=$1 skip_dims=${skip_dims:-}
   begin_function
@@ -2484,10 +2541,6 @@ build_context_trunk() {
     build_context_gather_derive_tables || fail
 
     build_context_trunk_dna || fail
-
-    coord_type=branch \
-    target_form=seed \
-    calc_coordinates || fail
 
     if [[ ! -d $status_path ]]; then
       mkdir -p $status_path || fail
@@ -4196,6 +4249,26 @@ build_context() {
       source $context_path-branch || fail
     fi
     fence_grip
+
+    if [[ ! -f $context_path-coords ]]; then
+      debug_start
+
+      local parent_coord_path=${cell_path%/*}/.cyto/context-coords \
+        clear_existing_coords=t \
+
+      if [[ -f $parent_coord_path ]]; then
+        source $parent_coord_path || fail
+        clear_existing_coords=f
+      fi
+
+      coord_type=branch \
+      target_form=seed \
+      calc_coordinates || fail
+
+      coord_type=branch \
+      write_coordinates_to_shell_file $context_path-coords || fail
+
+    fi
 
     if [[ $cell_is_leaf == t ]]; then
       if [[ ! -f $context_path-leaf ]]; then
