Improve needs_update check

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -84,57 +84,16 @@ handle_return
 
 # returns needs_update
 get_needs_update() {
-needs_update=f
-local log_message="No update needed"
-begin_function_flat
-
-  get_node_needs_update $cell_path || fail
-  [[ $needs_update == t ]] && succeed
-
-  if [[ -v leaf_dims ]]; then
-    fork=f par=f function=get_leaf_needs_update for_each_leaf ${leaf_dims[*]} || fail
-    if [[ $needs_update == t ]]; then
-      log_message="Needs update because at least one leaf cell is out of date"
-    fi
-    [[ $needs_update == t ]] && succeed
-  fi
-
-  if [[ -d $up_path ]]; then
-    local -r upstream_cells=( $(find1 $up_path -not -name '.*' | sort -g) ) || fail
-    local up
-    begin_for up in ${upstream_cells[*]}; doo
-      get_node_needs_update $up || fail
-      if [[ $needs_update == t ]]; then
-        log_message="Needs update because at least one upstream cell is out of date"
-        break
-      fi
-    end_for
-    [[ $needs_update == t ]] && succeed
-  fi
-
-end_function_flat
-
-if [[ $needs_update == t ]]; then
-  action=update_check debug "$log_message"
-else
-  action=update_check info "$log_message"
-fi
-
-handle_return
-}
-
-get_leaf_needs_update() {
-local cell_path=$cell_path
-local leaf_path=$leaf_path
-get_node_needs_update $cell_path$leaf_path
-}
-
-get_node_needs_update() {
 local cell_path=$1
-local status_path=$cell_path/.cyto/status
+local status_path=$cell_path/.cyto/status \
+  log_message="No update needed"
+
 begin_function_flat
-  
+
+  debug_start
   needs_update=f
+  get_short_cell $(realpath $cell_path)
+  debug "Does $short_cell need to be updated?"
 
   if [[ ! -e $status_path/up-to-date ]]; then
     needs_update=t
@@ -142,18 +101,22 @@ begin_function_flat
   elif [[ ! -e $status_path/last-good-update-end ]]; then
     needs_update=t
     log_message="Needs update because cell has never been updated successfully"
-  else
-    get_prop_changed $cell_path || fail
-    if [[ $prop_changed == t ]]; then
-      needs_update=t
-      log_message="Needs update because properties have changed"
-    else
-      get_is_stale $status_path || fail
-      if [[ $is_stale == t ]]; then
-        needs_update=t
-        log_message="Needs update because cell is stale"
-      fi
-    fi
+  elif get_prop_changed $cell_path || fail; \
+       [[ $prop_changed == t ]]; then
+    needs_update=t
+    log_message="Needs update because properties have changed"
+  elif get_is_stale $status_path || fail; \
+       [[ $is_stale == t ]]; then
+    needs_update=t
+    log_message="Needs update because cell is stale"
+  elif [[ -v leaf_dims ]]; \
+       get_leaf_needs_update || fail; \
+       [[ $needs_update == t ]]; then
+    log_message="Needs update because at least one leaf cell is out of date"
+  elif [[ -d $up_path ]]; \
+       get_upstream_needs_update || fail; \
+       [[ $needs_update == t ]]; then
+    log_message="Needs update because at least one upstream cell is out of date"
   fi
 
   if [[ $needs_update=t && ${pre_validate:-f} == t ]]; then
@@ -171,7 +134,37 @@ begin_function_flat
   fi
 
 end_function_flat
+
+if succeeded; then
+  if [[ $needs_update == t ]]; then
+    action=update_check debug "$log_message"
+  else
+    action=update_check info "$log_message"
+  fi
+else
+  action=update_check fatal "Failed to check update need"
+fi
+
 handle_return
+}
+
+get_upstream_needs_update() {
+debug_start
+local -r upstream_cells=( $(find1 $up_path -not -name '.*' | sort -g) ) || return 1
+local up
+for up in ${upstream_cells[*]}; do
+  get_needs_update $up || return 1
+  if [[ $needs_update == t ]]; then
+    break
+  fi
+done
+return 0
+}
+
+get_leaf_needs_update() {
+debug_start
+fork=f par=f function='get_needs_update $cell_path$leaf_path' for_each_leaf ${leaf_dims[*]} || return 1
+return 0
 }
 
 get_prop_changed() {
@@ -1470,7 +1463,6 @@ init_context() {
 #     update and set something_changed=t accordingly. 
 
 default_freshness= \
-needs_update= \
 retry_max=1 \
 retry_delay=1 \
 retry_scale=2 \
@@ -1949,7 +1941,7 @@ local dim=${dim_array[0]} \
   leaf_path=${leaf_path:-}
 
 local vars='dim fork par function'
-begin_function
+begin_function_flat
 
   expand_values || fail
 
@@ -1959,7 +1951,7 @@ begin_function
 
   local loop_function=$leaf_function
   if [[ "${remaining_dims:-}" ]]; then
-    loop_function="function=$leaf_function for_each_leaf ${remaining_dims[*]}"
+    loop_function="function=\"$leaf_function\" for_each_leaf ${remaining_dims[*]}"
   fi
 
   branch_values+=()
@@ -1980,7 +1972,7 @@ begin_function
       ' \
     parallel_loop || fail
 
-end_function
+end_function_flat
 handle_return
 }
 
@@ -2466,6 +2458,8 @@ local x y top_cell=${top_cell:-} trunk_cell=$1 dim_string=
 if [[ "$trunk_cell" =~ .dim ]]; then
   x=${trunk_cell//\/.dim\// }
   dim_string=" ${x#* }"
+  dim_string=${dim_string/ /:}
+  dim_string=${dim_string// /\/}
   trunk_cell=${x%% *}
 fi
 if x=${trunk_cell#$PWD/}
