Fix fork logging

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -202,7 +202,8 @@ vars=step; begin_function
   
   if [[ -d $step/.dna ]]; then
     # recursive
-    ( execute_command $step update ) || fail
+    ( change_log_file; execute_command $step update ) || { after_fork; fail; }
+    after_fork
     ln -sf $step $batch_source_path/$base || fail
   elif [[ -d $step ]]; then
     if [[ $base =~ ^choose-.* ]]; then
@@ -303,13 +304,13 @@ begin_function_flat
       fi
     fi
 
-    if [[ "$ref_group" && ! "${!ref_group:-}" ]]; then
-      err "Problem executing step $step"
-      err "Could not find ref group for $ref. Should be named either ${ref}s, ${ref}es, or ${ref%?}ies, "
-      err "or override it with a different folder name."
-      err "Or if this is a custom loop with a before-block file in it, set ref_group= (to nothing) in that file."
-      fail1
-    fi
+    # if [[ "$ref_group" && ! "${!ref_group:-}" ]]; then
+    #   err "Problem executing step $step"
+    #   err "Could not find ref group for $ref. Should be named either ${ref}s, ${ref}es, or ${ref%?}ies, "
+    #   err "or override it with a different folder name."
+    #   err "Or if this is a custom loop with a before-block file in it, set ref_group= (to nothing) in that file."
+    #   fail1
+    # fi
 
   fi
 
@@ -338,7 +339,12 @@ setup_default_each_handler() {
       fail1
     fi
     local v a
-    eval "a=( \"\${$ref_group[@]}\" )"
+    eval "a=( \"\${$ref_group[@]:-}\" )"
+
+    if [[ ! "$a" ]]; then
+      # nothing to do if there are no values
+      succeed
+    fi
 
     local parallel=f
     if [[ "${#a[*]}" -gt 1 ]]; then
@@ -353,6 +359,7 @@ setup_default_each_handler() {
       eval "$ref=\$v" || fail
       if [[ $parallel == t ]]; then
         execute_command_step_plain_folder &
+        after_fork
         processes+=" $!"
       else
         execute_command_step_plain_folder || fail
@@ -405,6 +412,7 @@ begin_function_flat
       if [[ $parallel == t ]]; then
         # recursive
         execute_command_step $step &
+        after_fork
         processes+=" $!"
       else
         # recursive
@@ -602,6 +610,11 @@ begin_function_flat
     fi
 
     op_path=$dna_path/op
+
+    stem_up_path=$dna_path/up
+    if [[ ! -d $stem_up_path ]]; then
+      stem_up_path=
+    fi
 
   fi
 
@@ -1137,7 +1150,8 @@ if [[ "${remaining_batch_dims:-}" ]]; then
 else
   if [[ "$leaf_function" ]]; then
     if [[ $fork_leaves == t ]]; then
-      ( $leaf_function ) || return 1
+      ( $leaf_function ) || { after_fork; return 1; }
+      after_fork
     else
       $leaf_function || return 1
     fi
@@ -1306,6 +1320,7 @@ begin_function_flat
       if [[ $parallel == t ]]; then
         # recursive
         batch_pivot "${remaining_batch_dims[@]:1}" &
+        after_fork
         processes+=" $!"
       else
         # recursive
@@ -1317,10 +1332,12 @@ begin_function_flat
       if [[ "$leaf_function" ]]; then
         if [[ $parallel == t ]]; then
           $leaf_function &
+          after_fork
           processes+=" $!"
         else
           if [[ $fork_leaves == t ]]; then
-            ( $leaf_function ) || fail
+            ( $leaf_function ) || { after_fork; fail; }
+            after_fork
           else
             $leaf_function || fail
           fi
@@ -1499,5 +1516,9 @@ local name=$name description=$description default=${default:-}
 parameter_names+=( "$name" ) 
 parameter_descriptions+=( "$description" ) 
 parameter_defaults+=( "$default" ) 
+}
+
+after_fork() {
+let log_id+=100 || true
 }
 
