.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -714,8 +714,8 @@ migrate_dep() {
             local choice_name=${choice##*/}
             migrate_dep2 $choice $to/$dep_name/choices/$choice_name || fail
           end_for
-        elif [[ -d $dep/.dna ]]; then
-          migrate_dep2 $dep $to/$dep_name || fail 
+#        elif [[ -d $dep/.dna ]]; then
+#          migrate_dep2 $dep $to/$dep_name || fail 
         else
           log_fatal "Dependency is missing choices or cell folder: $dep"
           fail1
