Make command folder not get broken so often

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -85,9 +85,23 @@ begin_function_flat
 
   record_context $cell || fail
 
-  mkdir -p $new_cyto/command || fail
-  mkdir -p $new_cyto/lib || fail
-  inherit_lib $cell || fail
+  get_top_cell $cell || fail
+  if [[ "$top_cell" != $cell ]]; then
+    if [[ $top_cell/.dna/command ]]; then
+      ln -s $top_cell/.dna/command $new_cyto/command || fail
+    else
+      err "Top cell doesn't have a command folder ($top_cell/.dna/command missing)"
+      fail1
+    fi
+    if [[ $top_cell/.dna/lib ]]; then
+      ln -s $top_cell/.dna/lib $new_cyto/lib || fail
+    fi
+  fi
+
+  #   older more powerful, but more fragile way
+  # mkdir -p $new_cyto/command || fail
+  # mkdir -p $new_cyto/lib || fail
+  # inherit_lib $cell || fail
 
   local context_path=$new_cyto/context
   if [[ -f "$context_path" ]]; then
