.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -2203,133 +2203,133 @@ handle_secure_edit() {
 
 handle_insecure_edit() {
 
-local log_vars= old_file=$file new_file=$file.new
-begin_function
+  local log_vars= old_file=$file new_file=$file.new
+  begin_function
 
-  if [[ -f $old_file ]]; then
-    cp $old_file $new_file || fail 
-  fi
-
-  if [[ "${content:-}" ]]; then
-    echo "$content" | trim_nl >$new_file || fail
-  else
-    $EDITOR $new_file || fail
-  fi
-
-  if [[ -f $old_file ]]; then
-    if files_are_different $old_file $new_file >/dev/null; then
-      changed=t
-    else
-      log_debug "No change"
-      rm $new_file || fail
+    if [[ -f $old_file ]]; then
+      cp $old_file $new_file || fail 
     fi
-  else
-    changed=t
-  fi
 
-  if [[ $changed == t ]]; then
-    mv $new_file $old_file || fail
-    update_modify_times $new_file || fail
-  fi
+    if [[ "${content:-}" ]]; then
+      echo "$content" | trim_nl >$new_file || fail
+    else
+      $EDITOR $new_file || fail
+    fi
 
-end_function
-handle_return
+    if [[ -f $old_file ]]; then
+      if files_are_different $old_file $new_file >/dev/null; then
+        changed=t
+      else
+        log_debug "No change"
+        rm $new_file || fail
+      fi
+    else
+      changed=t
+    fi
+
+    if [[ $changed == t ]]; then
+      mv $new_file $old_file || fail
+      update_modify_times $new_file || fail
+    fi
+
+  end_function
+  handle_return
 }
 
 update_modify_times() {
-local file=$1
-if [[ "$status_path" && -f "$status_path/up-to-date" ]]; then
-  rm $status_path/up-to-date || return 1
-fi
-return 0
+  local file=$1
+  if [[ "$status_path" && -f "$status_path/up-to-date" ]]; then
+    rm $status_path/up-to-date || return 1
+  fi
+  return 0
 }
 
 # will set top_cell, which will be empty if no cell cells are found
 get_top_cell() {
-local subject=$1
-top_cell=
-get_top_cell2 $subject || return 1
-return 0
+  local subject=$1
+  top_cell=
+  get_top_cell2 $subject || return 1
+  return 0
 }
 
 get_top_cell2() {
-local subject=$1
-local parent=${subject%/*}
-if [[ -e $subject/.dna ]]; then
-  top_cell=$subject
-fi
-if [[ ${#parent} -gt 1 ]]; then
-  # recursive
-  get_top_cell2 $parent || return 1
-fi
-return 0
+  local subject=$1
+  local parent=${subject%/*}
+  if [[ -e $subject/.dna ]]; then
+    top_cell=$subject
+  fi
+  if [[ ${#parent} -gt 1 ]]; then
+    # recursive
+    get_top_cell2 $parent || return 1
+  fi
+  return 0
 }
 
 # will set bottom_cell, which will be empty if no cell cells are found
 get_bottom_cell() {
-local subject=$1
-bottom_cell=
-get_bottom_cell2 $subject || return 1
-return 0
+  local subject=$1
+  bottom_cell=
+  get_bottom_cell2 $subject || return 1
+  return 0
 }
 
 get_bottom_cell2() {
-local subject=$1
-local parent=${subject%/*}
-if [[ -e $subject/.dna ]]; then
-  bottom_cell=$subject
-elif [[ ${#parent} -gt 1 ]]; then
-  # recursive
-  get_bottom_cell2 $parent || return 1
-fi
-return 0
+  local subject=$1
+  local parent=${subject%/*}
+  if [[ -e $subject/.dna ]]; then
+    bottom_cell=$subject
+  elif [[ ${#parent} -gt 1 ]]; then
+    # recursive
+    get_bottom_cell2 $parent || return 1
+  fi
+  return 0
 }
 
 setup_context_defaults() {
-setup_dep_defaults || return 1
-return 0
+  setup_dep_defaults || return 1
+  return 0
 }
 
 init_context() {
-# required_freshness:
-#   inf means infinite (never refresh based on time). 30s means refresh if it is older than 30 seconds.
-#   1w means refresh if it's older than a week.
-# shuffle_chance:
-#   chance out of 1000 of not following the computed strategy order
-# min_pause:
-#   number of ms to wait between cycles
-#   this number doubles each time there is nothing to do, until it reaches max_pause
-# reuse_existing_out:
-#   if set to t: 
-#   new output folder won't be created when updating, but the existing one will be used
-#   should set to true when creating a new output folder would be expensive
-#   these cells must detect for themselves whether a change has happened in an
-#     update and set something_changed=t accordingly. 
+  # required_freshness:
+  #   inf means infinite (never refresh based on time). 30s means refresh if it is older than 30 seconds.
+  #   1w means refresh if it's older than a week.
+  # shuffle_chance:
+  #   chance out of 1000 of not following the computed strategy order
+  # min_pause:
+  #   number of ms to wait between cycles
+  #   this number doubles each time there is nothing to do, until it reaches max_pause
+  # reuse_existing_out:
+  #   if set to t: 
+  #   new output folder won't be created when updating, but the existing one will be used
+  #   should set to true when creating a new output folder would be expensive
+  #   these cells must detect for themselves whether a change has happened in an
+  #     update and set something_changed=t accordingly. 
 
-localize_dim_vars=local \
-default_freshness= \
-retry_max=1 \
-retry_delay=1 \
-retry_scale=2 \
-cell_expiration= \
-cell_is_persistent=f \
-cell_is_external=f \
-default_strategies=crl \
-shuffle_chance=100 \
-lock_timeout=30 \
-pre_validate=f \
-post_validate=f \
-min_pause=250 \
-current_pause=250 \
-max_pause=60000 \
-reuse_existing_out=f \
-branch_dims= \
-props= \
-leaf_dims= \
-sub_dims= \
-in_path= \
-out_path=out 
-return 0
+  localize_dim_vars=local \
+  default_freshness= \
+  retry_max=1 \
+  retry_delay=1 \
+  retry_scale=2 \
+  cell_expiration= \
+  cell_is_persistent=f \
+  cell_is_external=f \
+  default_strategies=crl \
+  shuffle_chance=100 \
+  lock_timeout=30 \
+  pre_validate=f \
+  post_validate=f \
+  min_pause=250 \
+  current_pause=250 \
+  max_pause=60000 \
+  reuse_existing_out=f \
+  branch_dims= \
+  props= \
+  leaf_dims= \
+  sub_dims= \
+  in_path= \
+  out_path=out 
+  return 0
 }
 
 # returns:
