Fix bug in save_dna_tab

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -952,6 +952,36 @@ load_dna_vtab() {
   handle_return
 }
 
+save_dna_tab_inner() {
+  local write_to=${write_to:-}
+  begin_function
+    for (( field_index = 0; field_index < c_fields_count; field_index++ )); do
+      field=${c_fields[$field_index]}
+      apad line $field "$field "
+    done
+
+    if [[ "$write_to" ]]; then
+      echo "${line% }" >>$write_to || fail
+    fi
+
+    for (( row_index = 0; row_index < c_rows; row_index++ )); do
+      line=
+      for (( field_index = 0; field_index < c_fields_count; field_index++ )); do
+        (( data_offset = row_index * c_fields_count + field_index ))
+        field=${c_fields[$field_index]}
+        value=${c_data[$data_offset]}
+        shell_quote_var value
+        apad line $field "$value "
+      done
+
+      if [[ "$write_to" ]]; then
+        echo "${line% }" >>$write_to || fail
+      fi
+    done; maybe_break
+  end_function
+  handle_return
+}
+
 # writes a table to a file
 # inputs:
 #   tab_var       name of the table variable (without the _data or _fields)
@@ -981,32 +1011,18 @@ save_dna_tab() {
       fail1
     fi
 
-    local line=
+    local line
 
-    for (( field_index = 0; field_index < c_fields_count; field_index++ )); do
-      field=${c_fields[$field_index]}
-      line+="$field "
-    done
+    line=
+    save_dna_tab_inner || fail
 
-    echo "${line% }" >>$target_file || fail
-
-    for (( row_index = 0; row_index < c_rows; row_index++ )); do
-      line=
-      for (( field_index = 0; field_index < c_fields_count; field_index++ )); do
-        (( data_offset = row_index * c_fields_count + field_index ))
-        field=${c_fields[$field_index]}
-        value=${c_data[$data_offset]}
-        shell_quote_var value
-        line+="$value "
-      done
-
-      echo "${line% }" >>$target_file || fail
-    done
+    # done twice so we calculate width of each column before forming the final result
+    line=
+    write_to=$target_file save_dna_tab_inner || fail
 
   end_function
   handle_return
 }
-
 
 # Will load the given derive table if not already loaded
 # Will not load indexes (those should have already been loaded from the table cache)
