Add .arr dna object type

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -130,6 +130,19 @@ make_or_load_cyto_var() {
   handle_return
 }
 
+make_or_load_cyto_arr() {
+  begin_function
+    local var_full_path=$1 var=$prefix$2 content 
+    load_var $var_full_path content
+    if [[ $make_or_load == make ]]; then
+      echo "${NL}$var=( $content )" >>$context_path || fail
+    else
+      eval "$var=( $content )" || fail
+    fi
+  end_function
+  handle_return
+}
+
 make_or_load_cyto_raw() {
   begin_function
     local full_path=$1 name=$2 content 
@@ -163,6 +176,9 @@ make_or_load_dna_contents() {
         case $suffix in
           var)
             make_or_load_cyto_var $dna_full_item $item_name || fail
+          ;;
+          arr)
+            make_or_load_cyto_arr $dna_full_item $item_name || fail
           ;;
           fun)
             make_or_load_cyto_fun $dna_full_item $item_name || fail
