.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -117,7 +117,8 @@ write_to_context() {
        || $last_type == var && $new_type == fun ]]; then
       echo >>$context_path-$context_type.new || fail
     fi
-    echo "$content" >>$context_path-$context_type.new || fail
+    trim_ws content
+    echo "${content}" >>$context_path-$context_type.new || fail
     last_type=$new_type
     eval "$content" || {
       if [[ "${var_full_path:-}" ]]; then
@@ -1065,11 +1066,11 @@ build_context_dna() {
       if [[ ! "${default_anchor_dims:-}" ]]; then
         calculate_default_anchors || fail
       fi
-      write_to_context var default_anchor_dims || fail
+      write_vars_to_context default_anchor_dims || fail
 
       mv $context_path-$context_type.new $context_path-$context_type.new2 || fail
       echo "#!/usr/env bash
-  # This file is generated from $dna_path$NL" >$context_path-$context_type.new || fail
+# This file is generated from $dna_path$NL" >$context_path-$context_type.new || fail
       local v
       for v in ${!append_vars[*]}; do
         echo "$v=" >>$context_path-$context_type.new || fail
@@ -2193,7 +2194,7 @@ build_context_branch() {
     mock_path=$seed_path/.mock
     write_vars_to_context seed_path mock_path || fail
 
-    local dim assignment member i members_string= context_type=trunk
+    local dim assignment member i members_string=
     begin_for ((i = 0; i < branch_dim_count; i++)); doo
       dim=${branch_dims[$i]}
       member=${branch_members[$i]}
