.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -1697,13 +1697,15 @@ execute_command_internal_prep() {
         }
 
         if [[ "${anchor_dims:-}" ]]; then
-          local dim=$anchor_dims
-          dim_type=trunk_dims \
-          expand_values || fail
-          get_plural $dim || fail
-          eval "unset $dim" || fail
-          eval "unset d_$dim" || fail
-          eval "d_$plural=\${values[*]}" || fail
+          #   This is already happening in for_each_member
+          :
+          # local dim=$anchor_dims
+          # dim_type=trunk_dims \
+          # expand_values || fail
+          # get_plural $dim || fail
+          # eval "unset $dim" || fail
+          # eval "unset d_$dim" || fail
+          # eval "d_$plural=\${values[*]}" || fail
         else
           local prop plural
           begin_for prop in ${props[*]}; doo
