.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -890,8 +890,10 @@ load_dna_vtab() {
 }
 
 # inputs:
-#   $1     full path to vtab file. It is assumed existence check has already happened.
-#   $2     target var to store data in (includes prefix)
+#   $1            full path to vtab file. It is assumed existence check has already happened.
+#   $2            target var to store data in (includes prefix)
+#   context_type
+#   context_file
 write_dna_vtab_to_context() {
 
   begin_function_lo
@@ -915,8 +917,9 @@ write_dna_vtab_to_context() {
 }
 
 # inputs:
-#   $1     full path to tab file. It is assumed existence check has already happened.
-#   $2     target var to store data in (includes prefix)
+#   $1            full path to tab file. It is assumed existence check has already happened.
+#   $2            target var to store data in (includes prefix)
+#   context_file
 write_dna_tab_to_context() {
 
   begin_function_lo
@@ -932,7 +935,7 @@ write_dna_tab_to_context() {
       ' $full_path
     ) || fail
 
-    echo "$content" >>$context_path-$context_type.new || fail
+    echo "$content" >>$context_file || fail
 
   end_function
   handle_return
@@ -975,11 +978,18 @@ extract_simple_name_across_array() {
 #   $1             full path to dna file
 #   prefix         optional prefix
 #   context_type   if empty, only loads the variable, if set, records to context
+#   context_file
 load_dna_item() {
   begin_function
     local var_full_path=$1 prefix=${prefix:-} \
       suffix= \
       file_name \
+      context_file=${context_file:-} \
+      context_type=${context_type:-} \
+
+    if [[ ! "$context_file" && $context_type ]]; then
+      context_file=$context_path-$context_type.new
+    fi
 
     last_type=${last_type:-var}
 
@@ -1037,7 +1047,7 @@ load_dna_item() {
     esac
 
     if [[ "$code" ]]; then
-      if [[ "${context_type:-}" ]]; then
+      if [[ "${context_type:-}${context_file:-}" ]]; then
         write_to_context $load_type code || fail
       else
         eval "$code" || fail
