.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -347,6 +347,184 @@ make_array_assignment() {
   handle_return
 }
 
+# finds the nearest ancestor of the given path which has .dna in it
+# will set bottom_cell, which will be empty if no cell cells are found
+get_bottom_cell() {
+  local subject=$1
+  bottom_cell=
+  while [[ -d "$subject" && "$subject" == /*/* ]]; do
+    if [[ -e $subject/.dna ]]; then
+      bottom_cell=$subject
+      break
+    fi
+    subject=${subject%/*}
+  done
+  debug_return_vars=bottom_cell
+  return 0
+}
+
+plant_seed_internal() {
+  local from=$1 to=$2 contents x x_part deep=${deep:-t} plant_branches=${plant_branches:-f}
+  begin_function
+
+    log_debug "Planting seed from $from to $to"
+
+    if [[ ! -d $to ]]; then
+
+      if [[ $from == /seed/* && -d $from ]]; then
+        plant_seed_internal ${from%/*} ${to%/*} || fail
+      else
+        log_fatal "Seed doesn't exist for $to"
+        fail1
+      fi
+
+    else
+
+      contents=( $(find1 $from | sort -g) ) || fail
+      local dim_found= target
+      begin_for x in ${contents[*]}; doo
+        x_part=${x##*/}
+        target=$to/$x_part
+        if [[ ! -e $target ]]; then
+          if [[ -f $x || $x_part == .dna ]]; then
+            safe_link $(realpath $x) $to/ || fail
+          elif [[ $x_part == .* ]]; then
+            : # ignore this
+          elif [[ $x_part == *:* ]]; then
+            local new_dim=${x_part%%:*}
+            if [[ ! "$dim_found" ]]; then
+              dim_found=${x_part%%:*}
+            elif [[ $dim_found != $new_dim ]]; then
+              log_fatal "Seed has two different dims defined, which is not allowed: $dim_found and $new_dim in $from"
+              fail1
+            fi
+          elif [[ -L $x ]]; then
+            cp -a $x $to/ || fail
+          elif [[ -d $x ]]; then
+            mkdir $target || fail
+            if [[ $deep == t ]]; then
+              plant_seed_internal $x $target || fail
+            fi
+          fi
+        fi
+      end_for
+
+      if [[ "$dim_found" && $plant_branches == t ]]; then
+        load_context $to || fail
+        parent_path=$to \
+        seed_path=$from \
+        par=f fork=f \
+        function=plant_member \
+        for_each_member $dim_found || fail
+      fi
+
+    fi
+  end_function
+  handle_return
+}
+
+# should make sure load_branch_info was run before calling this
+# inputs: $1  work path to target folder, which may be a cell or a folder of a cell
+# outputs: seed_path cell_path
+find_seed_path() {
+  local work_path=$1 d s= i h dim dim_count
+  begin_function
+    seed_path=
+
+    s=/seed${work_path#/work}
+
+    begin_while [[ ! -d $s && $s == *:* ]]; doo
+      s=${s%/*}
+    end_while
+
+    if [[ $ignore_nonexistent == t ]]; then
+      begin_while [[ ! -d $s && $s == */*/*/* ]]; doo
+        s=${s%/*}
+      end_while
+    fi
+
+    if [[ ! -d $s ]]; then
+      log_fatal "Couldn't find seed for $work_path"
+      fail1
+    fi
+
+    # go through each seed folder and find matching dim
+    local found_branch=t
+    begin_while [[ $found_branch == t ]]; doo
+      found_branch=f
+      local dim_folder=$(find1 $s -name "*:*" -type d | head -n1) || fail
+      if [[ "$dim_folder" ]]; then
+
+        local seed_dim=${dim_folder##*/}
+        seed_dim=${seed_dim%%:*}
+
+        begin_for (( i = 0; i < branch_dim_count; i++ )); doo
+
+          dim=${branch_dims[$i]}
+          if [[ $dim == $seed_dim ]]; then
+            h=${branch_hashes[$i]}
+            if [[ -d $s/$dim:$h ]]; then
+              s+=/$dim:$h
+              found_branch=t
+            elif [[ -d $s/$dim:_other ]]; then
+              s+=/$dim:_other
+              found_branch=t
+            fi
+            break
+          fi
+
+        end_for
+
+      fi
+
+    end_while
+
+  end_function
+
+  if [[ "$s" && -d $s ]]; then
+    seed_path=$s
+  fi
+
+  local log_return_vars=seed_path
+  handle_return
+}
+
+# inputs: $1  work path to the cell
+plant_seed() {
+  local seed_path cell_path to=$1 \
+    deep=${deep:-t} plant_branches=${plant_branches:-f} \
+    ignore_nonexistent=${ignore_nonexistent:-f}
+  begin_function
+
+    # TODO
+    #   to needs to be adjusted if its inside of a cell
+    #   alse need to return new cell path
+    find_seed_path $to || fail
+    if [[ ! "$seed_path" ]]; then
+      log_fatal "No seed is associated with this path: $cell_path"
+      fail1
+    fi
+
+    plant_seed_internal $seed_path $cell_path || fail
+
+  end_function
+  handle_return
+}
+
+make_or_load_dna_contents_update_cell() {
+  local file=$1
+  begin_function
+    local bottom_cell cell_path parent=${file%/*}
+    get_bottom_cell $parent
+    if [[ ! "$bottom_cell" ]]; then
+      plant_seed $parent || fail
+    else
+      cell_path=$bottom_cell
+    fi
+  end_function
+  handle_return
+}
+
 make_or_load_dna_contents() {
   local folder=$1 prefix=${prefix:-} pass_thru=${pass_thru:-f}
   begin_function
@@ -398,8 +576,13 @@ make_or_load_dna_contents() {
       else # is a file
 
         if [[ -L $item && ! -e $item ]]; then
-          log_fatal "Broken link found: $item"
-          fail1
+          local unlinked_item=$((realpath -m $item)) || fail
+          if [[ $unlinked_item == /work/* ]]; then
+            make_or_load_dna_contents_update_cell $unlinked_item || fail
+          else
+            log_fatal "Broken link found: $item"
+            fail1
+          fi
         fi
 
         prefix=$new_prefix make_or_load_dna_item $item || fail
@@ -845,64 +1028,6 @@ load_context() {
 
 make_context() {
   context_make=t make_or_load_context 
-}
-
-# should make sure load_branch_info was run before calling this
-find_seed_path() {
-  local work_path=$1 d s= i h dim dim_count
-  begin_function
-    seed_path=
-
-    s=/seed${work_path#/work}
-
-    begin_while [[ ! -d $s && $s == *:* ]]; doo
-      s=${s%/*}
-    end_while
-
-    if [[ ! -d $s ]]; then
-      log_fatal "Couldn't find seed for $work_path"
-      fail1
-    fi
-
-    # go through each seed folder and find matching dim
-    local found_branch=t
-    begin_while [[ $found_branch == t ]]; doo
-      found_branch=f
-      local dim_folder=$(find1 $s -name "*:*" -type d | head -n1) || fail
-      if [[ "$dim_folder" ]]; then
-
-        local seed_dim=${dim_folder##*/}
-        seed_dim=${seed_dim%%:*}
-
-        begin_for (( i = 0; i < branch_dim_count; i++ )); doo
-
-          dim=${branch_dims[$i]}
-          if [[ $dim == $seed_dim ]]; then
-            h=${branch_hashes[$i]}
-            if [[ -d $s/$dim:$h ]]; then
-              s+=/$dim:$h
-              found_branch=t
-            elif [[ -d $s/$dim:_other ]]; then
-              s+=/$dim:_other
-              found_branch=t
-            fi
-            break
-          fi
-
-        end_for
-
-      fi
-
-    end_while
-
-  end_function
-
-  if [[ "$s" && -d $s ]]; then
-    seed_path=$s
-  fi
-
-  local log_return_vars=seed_path
-  handle_return
 }
 
 # input must be a folder
@@ -2282,66 +2407,6 @@ for_each_member() {
   handle_return
 }
 
-plant_seed_internal() {
-  local from=$1 to=$2 contents x x_part deep=${deep:-t} plant_branches=${plant_branches:-f}
-  begin_function
-
-    log_debug "Planting seed from $from to $to"
-
-    if [[ ! -d $to ]]; then
-
-      if [[ $from == /seed/* && -d $from ]]; then
-        plant_seed_internal ${from%/*} ${to%/*} || fail
-      else
-        log_fatal "Seed doesn't exist for $to"
-        fail1
-      fi
-
-    else
-
-      contents=( $(find1 $from | sort -g) ) || fail
-      local dim_found= target
-      begin_for x in ${contents[*]}; doo
-        x_part=${x##*/}
-        target=$to/$x_part
-        if [[ ! -e $target ]]; then
-          if [[ -f $x || $x_part == .dna ]]; then
-            safe_link $(realpath $x) $to/ || fail
-          elif [[ $x_part == .* ]]; then
-            : # ignore this
-          elif [[ $x_part == *:* ]]; then
-            local new_dim=${x_part%%:*}
-            if [[ ! "$dim_found" ]]; then
-              dim_found=${x_part%%:*}
-            elif [[ $dim_found != $new_dim ]]; then
-              log_fatal "Seed has two different dims defined, which is not allowed: $dim_found and $new_dim in $from"
-              fail1
-            fi
-          elif [[ -L $x ]]; then
-            cp -a $x $to/ || fail
-          elif [[ -d $x ]]; then
-            mkdir $target || fail
-            if [[ $deep == t ]]; then
-              plant_seed_internal $x $target || fail
-            fi
-          fi
-        fi
-      end_for
-
-      if [[ "$dim_found" && $plant_branches == t ]]; then
-        load_context $to || fail
-        parent_path=$to \
-        seed_path=$from \
-        par=f fork=f \
-        function=plant_member \
-        for_each_member $dim_found || fail
-      fi
-
-    fi
-  end_function
-  handle_return
-}
-
 # inputs: parent_path seed_path member
 plant_member() {
   begin_function
@@ -2377,23 +2442,6 @@ plant_member() {
       mv $new_path $member_path || fail
 
     fi
-  end_function
-  handle_return
-}
-
-# inputs: $1  work path to the cell
-plant_seed() {
-  local seed_path to=$1 deep=${deep:-t} plant_branches=${plant_branches:-f}
-  begin_function
-
-    find_seed_path $to || fail
-    if [[ ! "$seed_path" ]]; then
-      log_fatal "No seed is associated with this path: $cell_path"
-      fail1
-    fi
-
-    plant_seed_internal $seed_path $to || fail
-
   end_function
   handle_return
 }
@@ -2730,22 +2778,6 @@ get_top_cell() {
     subject=${subject%/*}
   done
   debug_return_vars=top_cell
-  return 0
-}
-
-# finds the nearest ancestor of the given path which has .dna in it
-# will set bottom_cell, which will be empty if no cell cells are found
-get_bottom_cell() {
-  local subject=$1
-  bottom_cell=
-  while [[ -d "$subject" && "$subject" == /*/* ]]; do
-    if [[ -e $subject/.dna ]]; then
-      bottom_cell=$subject
-      break
-    fi
-    subject=${subject%/*}
-  done
-  debug_return_vars=bottom_cell
   return 0
 }
 
