.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -5244,43 +5244,43 @@ execute_auto_load_add_constraints() {
   handle_return
 }
 
-execute_auto_load_tab() {
-  local table_name=$1 prefix=${prefix:-}
-  begin_function
-    local -n table_fields=${table_name}_fields table_data=${table_name}_data
-    if [[ ! -v table_fields || ! -v table_data ]]; then
-      log_fatal "Missing expected vars: ${table_name}_fields or ${table_name}_data"
-      fail1
-    fi
-    local row \
-      field_count=${#table_fields[*]} data_count=${#table_data[*]}
-    local row_count=$((data_count/field_count))
-    local -A keys
-    begin_for (( row = 0; row < row_count; row++ )); doo
-      check_table_row || fail
-      if [[ $is_valid == t ]]; then
-        execute_auto_load_add_constraints || fail
-      fi
-    end_for
-
-    local value key key_field field value
-    begin_for field in "${table_fields[@]}"; doo
-      local -n target_field=$field
-      if [[ "${target_field:-}" ]]; then
-        continue
-      fi
-      begin_for key in "${!keys[@]}"; doo
-        key_field=${key%% *}
-        if [[ "$key_field" != "$field" ]]; then
-          continue
-        fi
-        value=${key#$key_field }
-        target_field+=( "$value" )
-      end_for
-    end_for
-  end_function
-  handle_return
-}
+#execute_auto_load_tab() {
+#  local table_name=$1 prefix=${prefix:-}
+#  begin_function
+#    local -n table_fields=${table_name}_fields table_data=${table_name}_data
+#    if [[ ! -v table_fields || ! -v table_data ]]; then
+#      log_fatal "Missing expected vars: ${table_name}_fields or ${table_name}_data"
+#      fail1
+#    fi
+#    local row \
+#      field_count=${#table_fields[*]} data_count=${#table_data[*]}
+#    local row_count=$((data_count/field_count))
+#    local -A keys
+#    begin_for (( row = 0; row < row_count; row++ )); doo
+#      check_table_row || fail
+#      if [[ $is_valid == t ]]; then
+#        execute_auto_load_add_constraints || fail
+#      fi
+#    end_for
+#
+#    local value key key_field field value
+#    begin_for field in "${table_fields[@]}"; doo
+#      local -n target_field=$field
+#      if [[ "${target_field:-}" ]]; then
+#        continue
+#      fi
+#      begin_for key in "${!keys[@]}"; doo
+#        key_field=${key%% *}
+#        if [[ "$key_field" != "$field" ]]; then
+#          continue
+#        fi
+#        value=${key#$key_field }
+#        target_field+=( "$value" )
+#      end_for
+#    end_for
+#  end_function
+#  handle_return
+#}
 
 execute_auto_loads() {
   local auto_loads=( "$@" )
@@ -5288,8 +5288,11 @@ execute_auto_loads() {
     local table_name prefix i
     begin_for item in "${auto_loads[@]}"; doo
       case $item in
-        *.tab)
-          execute_auto_load_tab ${item%.tab} || fail
+# OLD CODE, should remove if not used soon
+#        *.tab)
+#          execute_auto_load_tab ${item%.tab} || fail
+#        ;;
+        *.var)
         ;;
         *)
           log_fatal "Can't auto load $item"
