Remove seeding for now

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -2355,6 +2355,7 @@ attempt_derive() {
     stop_after_first_match=${stop_after_first_match:-f} \
     deriving=${deriving:-} \
     derive_deep=${derive_deep:-t} \
+    derive_exactly_one=${derive_exactly_one:-t} \
 
   log_show_vars='dim from_dim'
   begin_function
@@ -2378,14 +2379,12 @@ attempt_derive() {
       values=()
     fi
 
-    if [[ ! "${values:-}" ]]; then
-      log_debug "Derive of $dim failed"
-#    elif (( ${#values[*]} == 1 )); then
-#      value_found=t
-#      log_debug "Derive of $dim successful: ${values[*]:0:30}"
+    if [[ $derive_exactly_one == t && ${#values[*]} -gt 1 ]]; then
+      log_debug "Derive of $dim failed, too many possibilities"
+      values=()
+    elif [[ ! "${values:-}" ]]; then
+      log_debug "Derive of $dim failed, no possibilities found"
     else
-#      value_found=f
-#      log_debug "Derive of $dim found too many values: ${#values[*]}, not accepting result"
       log_debug "Derive of $dim successful: ${values[*]:0:30}"
     fi
 
@@ -5255,12 +5254,13 @@ calc_coordinates() {
 
     if [[ $clear_existing_coords == t ]]; then
       coordinate_data=()
-      if [[ $target_form == tree && -v ${coord_type}_seed_coordinate_fields ]]; then
-        seed_table=${coord_type}_seed_coordinate \
-        seed_coordinates || fail
-        make_coord_index || fail
-        seed_already_expanded=t
-      fi
+      # Skipping seeding as a test for now
+      #if [[ $target_form == tree && -v ${coord_type}_seed_coordinate_fields ]]; then
+      #  seed_table=${coord_type}_seed_coordinate \
+      #  seed_coordinates || fail
+      #  make_coord_index || fail
+      #  seed_already_expanded=t
+      #fi
     fi
 
     if [[ ! "${coordinate_fields:-}" ]]; then
@@ -5561,13 +5561,14 @@ build_context() {
       source $context_path-branch || fail
     fi
 
-    if [[ "${trunk_dims_expanded:-}" ]]; then
-      if [[ ! -f $context_path-branch-coords ]]; then
-        build_branch_seed_coords || fail
-      else
-        source $context_path-branch-coords || fail
-      fi
-    fi
+    #  disabling seeding for now
+    #if [[ "${trunk_dims_expanded:-}" ]]; then
+    #  if [[ ! -f $context_path-branch-coords ]]; then
+    #    build_branch_seed_coords || fail
+    #  else
+    #    source $context_path-branch-coords || fail
+    #  fi
+    #fi
 
     #  unused at the moment
     #if [[ $cell_is_leaf == t ]]; then
