.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -1563,40 +1563,33 @@ load_dna_contents() {
   handle_return
 }
 
-# inputs: up_path up_name 
-link_choices() {
-  begin_function
-    local choice_var choice_name o
-    mkdir -p $dep_path/choices || fail
-    begin_for choice_name in ${choices[*]}; doo
-      extract_simple_name choice_name o choice_var
-      local -n choice_path=up_${up_var}_choices_${choice_var}_path
-      if [[ ! -v choice_path ]]; then
-        log_fatal "Missing choice path var"
-        fail1
-      fi
-      if [[ ! -d $choice_path ]]; then
-        log_fatal "Missing choice path"
-        fail1
-      fi
-      safe_link $choice_path $dep_path/choices/$choice_name || fail
-    end_for
-  end_function
-  handle_return
-}
-
 link_single() {
   begin_function
-    mkdir -p $dep_path/choices || fail
+    extract_simple_name choice_name o choice_var
+    local -n choice_path=up_${up_var}_choices_${choice_var}_path
     if [[ ! -v choice_path ]]; then
       log_fatal "Missing choice path var"
       fail1
     fi
     if [[ ! -d $choice_path ]]; then
-      log_fatal "Invalid choice path: $choice_path"
+      log_fatal "Missing choice path"
       fail1
     fi
     safe_link $choice_path $dep_path/choices/$choice_name || fail
+  end_function
+  handle_return
+}
+
+# inputs: dep_path up_name 
+link_choices() {
+  begin_function
+    local choice_var choice_name o
+    if [[ ! -d $dep_path/choices ]]; then
+      mkdir -p $dep_path/choices || fail
+    fi
+    begin_for choice_name in ${choices[*]}; doo
+      link_single $choice_name || fail
+    end_for
   end_function
   handle_return
 }
@@ -1636,7 +1629,7 @@ make_cyto_up_single() {
     else
       local -n choice_path=up_${up_var}_path
       local choice_name=$up_name
-      link_single || fail
+      link_single $choice_name || fail
     fi
   end_function
   handle_return
@@ -2947,7 +2940,7 @@ load_dna_contents_update_cell() {
 
     needs_update= \
     top_level_command=f \
-    execute_command "$cell_path" update || fail
+    fork execute_command "$cell_path" update || fail
 
     if [[ ! -f "$file" ]]; then
       log_fatal "Cell $cell_path did not produce file at $file as required by dna of $original_cell_path"
@@ -4114,5 +4107,13 @@ execute_auto_loads() {
     end_for
   end_function
   handle_return
+}
+
+get_trunk_cell() {
+  trunk_cell=$1
+  while [[ $trunk_cell == */*:* ]]; do
+    trunk_cell=${trunk_cell%/*}
+  done
+  debug_return_vars=trunk_cell
 }
 
diff --git a/lib/update-lib b/lib/update-lib
--- a/lib/update-lib
+++ b/lib/update-lib
@@ -204,7 +204,6 @@ update_upstream_choose_multi() {
       if [[ -e "$chosen/.dna" ]]; then
         upstream_cell_link=$chosen
         cell_path=$(realpath $chosen) || fail
-        switch_context $cell_path
         get_needs_update $cell_path || fail
       else
         needs_update=t
@@ -221,7 +220,6 @@ update_upstream_choose_multi() {
         maybe_fix_choice $choice || fail
         needs_update=
         cell_path=$(realpath $choice) || fail
-        switch_context $cell_path
         get_needs_update $cell_path || fail
         if [[ $needs_update == f ]]; then
           chosen=$choice
@@ -254,7 +252,6 @@ update_upstream_choose() {
   local log_show_vars=^upstream problem=
   begin_function_hi
 
-    local choice
     local choices
     if [[ -d $upstream/choices ]]; then
       choices=( $(find1 $upstream/choices -not -name ".*" | sort -g) ) || fail
@@ -286,15 +283,8 @@ update_upstream_choose() {
     fi
     upstream_cell_link=$chosen
     cell_path=$(realpath $chosen) || fail
-    anchor_dims= \
-    switch_context $cell_path
+    anchor_dims=
     get_needs_update $cell_path || fail
-
-    if [[ $needs_update == f ]]; then
-      cell_path=$original_cell_path
-      anchor_dims=$original_anchor_dims
-      switch_context $cell_path || fail
-    fi
 
   end_function
   local log_return_vars=chosen
@@ -304,7 +294,7 @@ update_upstream_choose() {
 
 update_upstream_get_locks() {
   local log_show_vars=^upstream
-  begin_function_hi
+  begin_function
 
     local lock 
     local -r export_path=$upstream/chosen/export
@@ -369,11 +359,7 @@ repair_update_upstream() {
 #   upstream: a folder in .dna/up
 update_upstream() {
 
-  local required_freshness= fresh= \
-    default_freshness= \
-    risk_tolerance=$risk_tolerance \
-    command_history=${command_history:-} \
-    original_cell_path=${cell_path:-} \
+  local original_cell_path=${cell_path:-} \
     upstream=$1 \
 
   if [[ -e $upstream/.dna ]]; then
@@ -384,11 +370,25 @@ update_upstream() {
   local log_show_vars=^upstream 
   begin_function_hi
 
-    log_debug "Updating upstream ${upstream##*/.cyto/up/}"
-
     local needs_update= upstream_cell_link= \
       chosen= anchor_dims= \
       chosen_target_link \
+      required_freshness= fresh= \
+      default_freshness= \
+      risk_tolerance=$risk_tolerance \
+      command_history=${command_history:-} \
+
+    local upstream_name=${upstream##*/.cyto/up/}
+    local cell_path=${upstream%/.cyto/up/$upstream_name}
+    if [[ $cell_path == $upstream ]]; then
+      log_fatal "Invalid upstream: $upstream, it should be within .cyto/up"
+      fail1
+    fi
+
+    local cyto_path=$cell_path/.cyto
+    local up_path=$cyto_path/up up_chosen_path=$cyto_path/up-chosen
+
+    log_debug "Updating upstream $upstream_name"
 
     eval "local $localize_dims" || fail
 
@@ -953,7 +953,7 @@ update_member() {
 
       top_level_command=f \
       downstream_cell_name=${short_cell//\//_} \
-      execute_command $member_path update || fail
+      fork execute_command $member_path update || fail
 
       if [[ $update_successful == f ]]; then
         log_error "Failed to update member cell $member"
@@ -1303,7 +1303,7 @@ update_inners() {
       outer_cell_name=${short_cell//\//_} \
       inner_cell_link=$i_path \
       anchor_dims= \
-      execute_command $i_path update || fail
+      fork execute_command $i_path update || fail
     end_for
   end_function
   handle_return
