omni_nav: added log stack command

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -170,9 +170,9 @@ begin_function_flat
     mkdir $job_path || fail
   fi
 
-  if [[ "${job_id:-}" ]]; then
+  if [[ "${omni_log_job_id:-}" ]]; then
 
-    current_job_path=$job_path/$job_id
+    current_job_path=$job_path/$omni_log_job_id
     running_job_path=$job_path/running
 
     if [[ ! -d $current_job_path ]]; then
@@ -1262,7 +1262,7 @@ fi
 
 cell_change_log_file() {
   if [[ $current_command != log ]]; then
-    local new_log_file=$log_path/$job_id:$fork_id.olog
+    local new_log_file=$log_path/$omni_log_job_id:$omni_log_fork_id.olog
     if [[ ${is_first_log:-t} == t ]]; then
       from_must_exist=f \
         safe_link $new_log_file ${new_log_file%/*}/first.olog || return 1
@@ -1296,9 +1296,9 @@ get_job_id() {
 
     if [[ -f "$job_id_log" ]]; then
       local last_id=$(tail -n1 $job_id_log | awk '{print $1}')
-      (( job_id = last_id + 1 ))
+      (( omni_log_job_id = last_id + 1 ))
     else
-      job_id=1
+      omni_log_job_id=1
     fi
 
     if [[ ! "$command_to_log" ]]; then
@@ -1306,7 +1306,7 @@ get_job_id() {
       fail1
     fi
 
-    echo "$job_id $command_to_log" >>$job_id_log || fail
+    echo "$omni_log_job_id $command_to_log" >>$job_id_log || fail
 
     fd_unlock
 
@@ -1321,8 +1321,8 @@ get_fork_id() {
     return 1
   }
   local last_id=$(tail -n1 $fork_id_log | awk '{print $1}')
-  (( fork_id = last_id + 1 ))
-  echo $fork_id >>$fork_id_log || return 1
+  (( omni_log_fork_id = last_id + 1 ))
+  echo $omni_log_fork_id >>$fork_id_log || return 1
   fd_unlock
   return 0
 }
@@ -1348,7 +1348,7 @@ begin_function
       fi
     fi
 
-    if [[ ! "${job_id:-}" ]]; then
+    if [[ ! "${omni_log_job_id:-}" ]]; then
       command_to_log="${original_cmd#* }" \
         get_job_id || fail
     fi
