Make constellations manually chosen

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -4093,11 +4093,15 @@ build_context_trunk_dna() {
 find_constellations_of_dims() {
   local dims=$dims dim con
   for dim in $dims; do
-    grip_fence
-    if [[ ! -v is_breaker[$dim] ]]; then
-      con=${constellation_of[$dim]:-}
-      if [[ "$con" && " ${cons_found[*]} " != *" $con "* ]]; then
-        cons_found+=( $con )
+    local -n con=dim_${dim}_con
+    if [[ "${con:-}" && " ${cons_found[*]} " != *" $con "* ]]; then
+      cons_found+=( $con )
+      if [[ ! -v con_${con}_derive_tables ]]; then
+        declare -g con_${con}_derive_tables=
+      fi
+      local -n con_dt=con_${con}_derive_tables
+      if [[ " $con_dt " != *" $name "* ]]; then
+        con_dt+="$name "
       fi
     fi
   done
@@ -4220,12 +4224,7 @@ make_derive_cache_handle_table() {
     if [[ $dim_resolver == brute ]]; then
       local cons_found=() king_con=
       dims=${table_fields[*]} find_constellations_of_dims || fail
-      dims=${table_fields[*]} merge_dim_constellations || fail
-      if [[ ! -v con_${king_con}_derive_tables ]]; then
-        declare -g con_${king_con}_derive_tables=
-      fi
-      local -n con_dt=con_${king_con}_derive_tables
-      con_dt+="$name "
+#      dims=${table_fields[*]} merge_dim_constellations || fail
     fi
 
     table=derive_table_${name} \
@@ -5586,16 +5585,16 @@ make_derive_cache() {
     fi
 
     local context_file=$cache_path.new
-    local -A is_breaker
+    #local -A is_breaker
 
     for dim in ${!all_dims[*]}; do
       local -A members_of_$dim
       local -n members_of=members_of_$dim
       members_of=()
-      local -n breaker=dim_${dim}_constellation_breaker
-      if [[ ${breaker:-f} == t ]]; then
-        is_breaker[$dim]=t
-      fi
+      #local -n breaker=dim_${dim}_constellation_breaker
+      #if [[ ${breaker:-f} == t ]]; then
+      #  is_breaker[$dim]=t
+      #fi
     done
 
     make_derive_cache_tables || fail
