Allow cells to be part of foundation outside of foundation folder

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -3787,6 +3787,12 @@ setup_coord_fields() {
 
       for dim in ${coordinate_fields[*]}; do
         local -n member_type=dim_${dim}_member_type
+
+        if [[ ! -v member_type ]]; then
+          log_fatal "internal error: Missing member_type"
+          debug_start
+        fi
+
         if [[ $member_type == static ]]; then
           new_fields+=( $dim )
         fi
@@ -6024,9 +6030,18 @@ check_foundation() {
   begin_function
     local module_path=${cell_path#/*/*/}
     module_path=${cell_path%/$module_path}
+
+    debug_start
+    if [[ -f $dna_path/cell_is_foundation.var && ! -v cell_is_foundation ]]; then
+      context_type= \
+      prefix= \
+      load_dna_item $dna_path/cell_is_foundation.var || fail
+    fi
+
     if [[ $cell_path != */foundation/* 
        && -d $module_path/foundation/all 
        && ! -d $module_path/foundation/all/.cyto
+       && ${cell_is_foundation:-f} == f
        ]]; then
       log_fatal "Foundation cells have not been updated, so update can't proceed. Update $module_path/foundation/all before attempting to update other cells."
       fail1
