.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -351,15 +351,17 @@ begin_function_flat
       ln -s $(realpath $dna_path/$part) $sub_dna_path/ || fail
     fi
   end_for 
+  append_dim_var_to_context ${super_dims[0]} || fail
 end_function_flat
 handle_return
 }
 
 create_sub_leaf() {
+err "create_sub_leaf called"
 begin_function_flat
   begin_for part in op up context-local; doo
-    if [[ -e $dna_path/leaf/$part ]]; then
-      ln -s $(realpath $dna_path/leaf/$part) $sub_dna_path/ || fail
+    if [[ -e $dna_path/op/leaf/$part ]]; then
+      ln -s $(realpath $dna_path/op/leaf/$part) $sub_dna_path/ || fail
     fi
   end_for 
   if [[ -d $dna_path/.dna/up && ! -d $sub_dna_path/up ]]; then
@@ -375,6 +377,26 @@ begin_function_flat
       ln -s $(realpath $leaf_cell) $sub_dna_path/up/$upstream_name || fail
     end_for
   fi
+  append_dim_var_to_context ${super_dims[0]} || fail
+end_function_flat
+handle_return
+}
+
+append_dim_var_to_context() {
+local context_dim=$1
+begin_function_flat
+  context_dim=${context_dim##*/}
+  context_dim=${context_dim#*-}
+  if [[ ! -v $context_dim ]]; then
+    err "internal error: while trying to create a branch sub cell, required dim value $context_dim is missing."
+    fail1
+  fi
+  local value=${!context_dim}
+  if [[ "$value" == $empty_member ]]; then
+    value=
+  fi
+  echo "# Generated by create_sub_branch
+$context_dim='$value'" >>$sub_dna_path/context-before || fail
 end_function_flat
 handle_return
 }
@@ -714,7 +736,7 @@ setup_default_each_handler() {
 
   begin_function_flat
 
-    if [[ ! -v $ref_group ]]; then
+    if [[ ! -v ref_group || ! -v $ref_group ]]; then
       # nothing to do if there are no values
       succeed
     fi
@@ -1446,10 +1468,15 @@ begin_function_flat
   values=( ${!dim:-} )
   type -t ${dim}_member_expand >/dev/null && has_member_expand_function=t
 
+  local problem=
   if [[ ! "${values:-}" ]]; then
-    expand_values_plural || fail
+    expand_values_plural || true
   else
-    expand_values_single || fail
+    expand_values_single || true
+  fi
+  if [[ "$problem" ]]; then
+    err "$problem"
+    fail1
   fi
 
   values=( $new_value_list )
@@ -1754,7 +1781,9 @@ parameter_defaults+=( "$default" )
 
 after_fork() {
 let log_id+=100 || true
-let debug_id+=1000 || true
+if [[ "$debug_id" != t ]]; then
+  let debug_id+=1000 || true
+fi
 }
 
 dir_is_empty() {
