m

diff --git a/lib/cell-common b/lib/cell-common
--- a/lib/cell-common
+++ b/lib/cell-common
@@ -40,3 +40,100 @@ init_context() {
   return 0
 }
 
+init_status_context() {
+
+  # override this in cells to support aliases, dimension groups, and defaults
+  # should store values in plural form of var, and only plural form should be used after this
+  expand_dimension() {
+  local dimension_plural=$1; shift
+  local value=$1
+  eval "$dimension_plural=\$value"
+  return 0
+  }
+
+}
+
+normalize_dimensions() {
+trace -5 "Normalizing dimensions"
+begin_function
+
+  local dimension cell=$1 value dimension_plural
+  dimensions=( )
+  if [ -d "$cell/dimension" ]; then
+    for dimension in $(find "$cell/dimension" -mindepth 1 -maxdepth 1 -type d); do
+      dimension=${dimension##*/}
+      dimension_plural=${dimension}s
+      value=${!dimension_plural:-${!dimension:-}}
+      if [ "$value" ]; then
+        dimension+=( $dimension )
+        expand_dimension "$dimension_plural" "$value" || return 1
+      else
+        err "Missing value for dimension $dimension. You must set this in an env var."
+        return 1
+      fi
+    done
+  fi
+
+end_function
+handle_return
+}
+
+
+init_update_context() {
+return 0
+}
+
+load_status_context() {
+init_status_context || return 1
+local f=$1 
+local parent=${f%/*}
+[ "${#parent}" -gt 1 ] && { load_status_context_before "$parent" || return 1; }
+[ -f "$f/status-context" ] && source "$f/status-context"
+[ -f "$f/status-context-after" ] && source "$f/status-context-after"
+[ "${#parent}" -gt 1 ] && { load_status_context_after "$parent" || return 1; }
+return 0
+}
+
+load_status_context_before() {
+local f=$1 
+local parent=${f%/*}
+[ "${#parent}" -gt 1 ] && { load_status_context_before "$parent" || return 1; }
+[ -f "$f/status-context" ] && source "$f/status-context"
+return 0
+}
+
+load_status_context_after() {
+local f=$1 
+local parent=${f%/*}
+[ -f "$f/status-context-after" ] && source "$f/status-context-after"
+[ "${#parent}" -gt 1 ] && { load_status_context_after "$parent" || return 1; }
+return 0
+}
+
+load_update_context() {
+init_update_context || return 1
+local f=$1 
+local parent=${f%/*}
+[ "${#parent}" -gt 1 ] && { load_update_context_before "$parent" || return 1; }
+[ -f "$f/update-context" ] && source "$f/update-context"
+[ -f "$f/update-context-after" ] && source "$f/update-context-after"
+[ "${#parent}" -gt 1 ] && { load_update_context_after "$parent" || return 1; }
+return 0
+}
+
+load_update_context_before() {
+local f=$1 
+local parent=${f%/*}
+[ "${#parent}" -gt 1 ] && { load_update_context_before "$parent" || return 1; }
+[ -f "$f/update-context" ] && source "$f/update-context"
+return 0
+}
+
+load_update_context_after() {
+local f=$1 
+local parent=${f%/*}
+[ -f "$f/update-context-after" ] && source "$f/update-context-after"
+[ "${#parent}" -gt 1 ] && { load_update_context_after "$parent" || return 1; }
+return 0
+}
+
diff --git a/lib/cell-update b/lib/cell-update
--- a/lib/cell-update
+++ b/lib/cell-update
@@ -11,77 +11,34 @@ end_function
 handle_return
 }
 
-load_context() {
-local f=$1 
-local parent=${f%/*}
-[ "${#parent}" -gt 1 ] && { load_pre_context "$parent" || return 1; }
-[ -f "$f/pre-context" ] && source "$f/pre-context"
-[ -f "$f/post-context" ] && source "$f/post-context"
-[ "${#parent}" -gt 1 ] && { load_post_context "$parent" || return 1; }
-return 0
-}
-
-load_pre_context() {
-local f=$1 
-local parent=${f%/*}
-[ "${#parent}" -gt 1 ] && { load_pre_context "$parent" || return 1; }
-[ -f "$f/pre-context" ] && source "$f/pre-context"
-return 0
-}
-
-load_post_context() {
-local f=$1 
-local parent=${f%/*}
-[ -f "$f/post-context" ] && source "$f/post-context"
-[ "${#parent}" -gt 1 ] && { load_post_context "$parent" || return 1; }
-return 0
-}
-
-derive_row_id() {
-local dimension_count="${#dimensions[*]}" 
-if [ $dimension_count -gt 0 ]; then
-  local dimension default dimension_with_default
-  row_id=
-  for dimension_with_default in "${dimensions[@]}"; do
-    read dimension default <<<$dimension_with_default
-    local var_defined=t
-    declare -p "$dimension" &>/dev/null || var_defined=f
-    if [ $var_defined == f ]; then
-      if [ "$default" ]; then
-        eval "$dimension='$default'"
-      else
-        err "Required var $dimension not defined, and no default was provided."
-        fail
-      fi
-    fi
-    if [[ "${!dimension}" =~ [$TAB$NL\ :] ]]; then
-      err "Dimension $dimension contains invalid characters: [${!dimension}]. It must not contain white space or colons."
-      fail
-    fi
-    row_id+="${!dimension}:"
-  done
-  row_id=${row_id%:}
-  row_path="/$row_id"
-else
-  row_id="only"
-  row_path=""
-fi
-}
-
 cell_update_single() {
 local current_cell=$1
 trace "Updating $current_cell"
 begin_function
 
-  load_context "$current_cell" || fail
-  # todo: if there are multiple rows, need to parallelize them also
-  #   need to be able to compute member groups
-  derive_row_id || fail
+  if [ ! -d "$current_cell/status" ]; then
+    local folder
+    # check subfolders for cells
+    for folder in $(find $current_cell -mindepth 1 -maxdepth 1 -type d); do
+      cell_update_single "$folder" || fail
+    done
+  fi
+
+  load_status_context "$current_cell" || fail
+
+  if ! normalize_dimensions "$current_cell"; then
+    err "Dimension normalization failed. One of the dimensions must be invalid."
+    fail
+  fi
+
+  derive_row_ids || fail
   # todo: but we do need dep phase even if build phase is skipped
   # todo: cell needs update if update is possible AND something changed (including deps)
   #   so dep analysis must happen before determining if this cell needs to update
   #   do we need to lock the cell if we are doing dep analysis?
 
+  # each update needs the full dimension vars for each row, the row id for each won't work, 
+  #   need to loop over all possibilities
 
   local needs_update
   does_cell_need_update || fail
@@ -112,8 +69,42 @@ begin_function
       cell_update_after_write_lock || fail
     fi
   fi
+
 end_function
 handle_return
+
+}
+
+derive_row_ids() {
+# todo: needs to be fixed to support multiple rows and use plural dims
+local dimension_count="${#dimensions[*]}" 
+if [ $dimension_count -gt 0 ]; then
+  local dimension default dimension_with_default
+  row_id=
+  for dimension_with_default in "${dimensions[@]}"; do
+    read dimension default <<<$dimension_with_default
+    local var_defined=t
+    declare -p "$dimension" &>/dev/null || var_defined=f
+    if [ $var_defined == f ]; then
+      if [ "$default" ]; then
+        eval "$dimension='$default'"
+      else
+        err "Required var $dimension not defined, and no default was provided."
+        fail
+      fi
+    fi
+    if [[ "${!dimension}" =~ [$TAB$NL\ :] ]]; then
+      err "Dimension $dimension contains invalid characters: [${!dimension}]. It must not contain white space or colons."
+      fail
+    fi
+    row_id+="${!dimension}:"
+  done
+  row_id=${row_id%:}
+  row_path="/$row_id"
+else
+  row_id="only"
+  row_path=""
+fi
 }
 
 wait_for_low_load() {
@@ -149,6 +140,7 @@ eval "exec $fd_trace>&$fd_original_trace"
 cell_update_after_write_lock() {
 begin_function
 
+  load_update_context "$current_cell" || fail
   init_status || fail
   new_status begin_update || fail
   if [ -d "$current_cell/log" ]; then
