.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -131,8 +131,9 @@ load_arr() {
         quotes=single shell_quote_var line
       ;;
     esac
-    eval "$to_var+=( $line )"
+    eval "$to_var+=' $line'"
   done < <(cat "$from")
+  to_var=${to_var# }
 }
 
 make_or_load_cyto_var() {
@@ -154,22 +155,16 @@ make_or_load_cyto_var() {
 make_or_load_cyto_arr() {
   begin_function
 
-    local var_full_path=$1 var=$prefix$2 arr
-    load_arr $var_full_path arr || fail
-
-    local result= v
-    begin_for v in "${arr[@]}"; doo
-      result+="\"$v\" "
-    end_for
-    result=${result% }
+    local var_full_path=$1 var=$prefix$2 content
+    load_arr $var_full_path content || fail
 
     if [[ $make_or_load == make ]]; then
       if [[ $last_type == fun ]]; then
         echo >>$context_path || fail
       fi
-      echo "$var=( $result )" >>$context_path || fail
+      echo "$var=( $content )" >>$context_path || fail
     else
-      eval "$var=( $result )" || fail
+      eval "$var=( $content )" || fail
     fi
 
   end_function
