.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -4012,10 +4012,10 @@ calc_coordinates_next_unknown_dim_found() {
       ddim=d_$dim \
       ddims=d_$dims \
 
-    local -n derive_tables_loaded=dim_${dim}_derive_tables_loaded
-    if [[ "${derive_tables_loaded:-}" != t ]]; then
-      load_related_derive_tables $dim || fail
-    fi
+    #local -n derive_tables_loaded=dim_${dim}_derive_tables_loaded
+    #if [[ "${derive_tables_loaded:-}" != t ]]; then
+    #  load_related_derive_tables $dim || fail
+    #fi
 
     unset sdim ddim ddims sdims
     if [[ $already_expanded == f ]]; then
@@ -4026,10 +4026,10 @@ calc_coordinates_next_unknown_dim_found() {
     fi
 
     local unknown_dims=${unknown_dims% }
-    remove_word_from_string unknown_dims $dim
     if [[ "$unknown_dims" == *' '* ]]; then
       unknown_dims="${unknown_dims#* } ${unknown_dims%% *}"
     fi
+    remove_word_from_string unknown_dims $dim
 
     local member ms
     if [[ "${ddims:-}" ]]; then
@@ -4384,11 +4384,12 @@ calc_coordinates_next_dim() {
       local -n member=d_$dim \
         members=d_$dims
 
-      local -n derive_tables_loaded=dim_${dim}_derive_tables_loaded
+      # This should not be needed now that all derive tables are loaded always
+      #local -n derive_tables_loaded=dim_${dim}_derive_tables_loaded
 
-      if [[ "${derive_tables_loaded:-}" != t ]]; then
-        load_related_derive_tables $dim || fail
-      fi
+      #if [[ "${derive_tables_loaded:-}" != t ]]; then
+      #  load_related_derive_tables $dim || fail
+      #fi
 
       if [[ "${member:-}" || "${members:-}" ]]; then
         
