Improve error logging for dim expansion failures

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -1022,7 +1022,7 @@ build_context_expand_members() {
       _out=( \"\$_in\" )
     elif function_exists dim_${dim}_get_members; then
       values=()
-      dim_${dim}_get_members || return 1
+      dim_${dim}_get_members || { problem=\"Failed to get members of $dim dimension\"; return 1; }
       if array_contains values \"\$_in\"; then
         _out=( \"\$_in\" )
       else
@@ -1791,7 +1791,7 @@ expand_dims() {
         fi
 
         local value new_values
-        expand_dim_members members || fail
+        expand_dim_members members || { log_fatal "Failed to expand members of $dim_var dimension"; fail1; }
 
         if [[ $single == t ]]; then
           if (( ${#new_values[*]} > 1 )); then
@@ -4664,7 +4664,7 @@ set_cross_dims_no_conflict() {
       fi
     fi
 
-    if [[ "$field_dim" && " ${validated_dims:-} " != *" $field "* ]]; then
+    if [[ "${field_dim:-}" && " ${validated_dims:-} " != *" $field "* ]]; then
       validated_dims+=" $field"
     fi
 
@@ -7104,7 +7104,7 @@ calc_coordinates_slow() {
           extra="seed of "
         fi
         log_debug "Calculating $extra$coord_type cell coordinates for dims: ${coordinate_fields[*]}"
-        calc_coordinates_next_dim || fail
+        calc_coordinates_next_dim || { log_fatal "Failed to calculate coordinates."; fail1; }
       fi
 
       if (( primary_dim_count > 0 && secondary_dim_count > 0 )) && [[ -v coordinate_fields ]]; then
