Simplify upstream dna definition

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -1462,6 +1462,22 @@ link_choices() {
   handle_return
 }
 
+link_single() {
+  begin_function
+    mkdir -p $dep_path/choices || fail
+    if [[ ! -v choice_path ]]; then
+      log_fatal "Missing choice path var"
+      fail1
+    fi
+    if [[ ! -d $choice_path ]]; then
+      log_fatal "Invalid choice path: $choice_path"
+      fail1
+    fi
+    safe_link $choice_path $dep_path/choices/$choice_name || fail
+  end_function
+  handle_return
+}
+
 make_cyto_inner() {
   begin_function
     mkdir $inner_path || fail
@@ -1495,10 +1511,11 @@ make_cyto_up() {
       local -n choices=up_${up_var}_choices
       mkdir $dep_path || fail
       if [[ -v choices ]]; then
-        link_choices
+        link_choices || fail
       else
-        log_fatal "Invalid upstream config for $up_path: Missing choices folder."
-        fail1
+        local -n choice_path=up_${up_var}_path
+        local choice_name=$up_name
+        link_single || fail
       fi
     end_for
   end_function
