.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -2042,16 +2042,20 @@ calc_coordinates_next_unknown_dim() {
             log_debug "Resolved $dim with $phase: ${values[*]:0:30}"
             remove_word_from_string unknown_dims $dim
 
-            begin_for member in "${members[@]}"; doo
+            local m
+            begin_for m in "${members[@]}"; doo
 
-              #log_debug "Processing $dim=$current_member"
-              local is_valid=t
-              calc_coords_validate_member $dim "$member" || fail
+              member=$m
+              #log_debug "Processing $dim=$member"
 
-              if [[ $is_valid == t ]]; then
+              #  Don't need to validate members which have been derived from existing dims
+              #local is_valid=t
+              #calc_coords_validate_member $dim "$member" || fail
+
+              #if [[ $is_valid == t ]]; then
                 # recursive
                 calc_coordinates_next_unknown_dim || fail
-              fi
+              #fi
 
             end_for
             row_ended=t
