.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -1264,6 +1264,12 @@ init_context() {
       done
     done
 
+    branch_coordinate_count= \
+    branch_coordinate_data= \
+    branch_coordinate_fields= \
+    branch_coordinate_fields_count= \
+    branch_coordinate_fields_plural= \
+    branch_coordinate_rows= \
     cell_expiration= \
     cell_is_external=f \
     cell_is_persistent=f \
@@ -1273,6 +1279,12 @@ init_context() {
     default_anchor_dims= \
     default_freshness= \
     default_strategies=crl \
+    leaf_coordinate_count= \
+    leaf_coordinate_data= \
+    leaf_coordinate_fields= \
+    leaf_coordinate_fields_count= \
+    leaf_coordinate_fields_plural= \
+    leaf_coordinate_rows= \
     localize_dims= \
     localize_reverse_dims= \
     lock_timeout=2 \
@@ -2436,7 +2448,7 @@ switch_context() {
     handle_return
 
   else
-    log_debug "Context already loaded" || fail
+    log_debug "Context already loaded: $cell_path" || fail
   fi
 
   return 0
