.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -601,7 +601,6 @@ handle_return
 
 create_sub_branch() {
 begin_function_flat
-  debug_start
 
   mkdir $sub_dna_path/dim || fail
 
@@ -613,7 +612,11 @@ begin_function_flat
 
   local contents=$(find1 $dna_path -not -name '.*') || fail
   begin_for part in $contents; doo
-    if [[ "$part" == */dim || "$part" == */context* ]]; then
+    if [[ "$part" == */dim \
+       || "$part" == */context* \
+       || "$part" == */up \
+       || "$part" == */down \
+       ]]; then
       continue
     fi
     safe_link $(realpath $part) $sub_dna_path/ || fail
@@ -656,7 +659,7 @@ begin_function_flat
 
     if [[ -f $from ]]; then
       safe_link $(realpath $from) $to || fail
-    elif [[ -d $from/.dna ]]; then
+    elif [[ -e $from/.dna ]]; then
       fork to_dims=${leaf_dims[*]} migrate_cell $from $to || fail
     elif [[ -d $from ]]; then
       mkdir $to || fail
@@ -666,6 +669,7 @@ begin_function_flat
         | sort -g) || fail
       begin_for item in $items; doo
         item_name=${item##*/}
+        # recursive
         migrate_dep $item $to/$item_name || fail
       end_for
     fi
@@ -680,17 +684,90 @@ migrate_cell() {
 local -r from=$1 to=$2 to_dims=$to_dims
 begin_function_flat
 
-  local -r prep_file=$from.prep
-  if [[ -f $prep_file ]]; then
-    source $prep_file || fail
-  fi
+  local sub_dim
+  get_sub_dim || fail
 
-  local -r dep_cell=$(realpath $from)
-  dep_dim=
-  dep_value=
+  local sub_member
+  get_sub_member || fail
+
+  local dep_dim
+  get_dep_dim || fail
+
+  local dep_member=$member
+
+  local sane_value
+  get_sane_value "$sub_member" || fail
+  local -r sub_member_sane=$sane_value
+  get_sane_value "$dep_member" || fail
+  local -r dep_member_sane=$sane_value
+
+  if [[ $sub_dim == $dep_dim ]]; then
+    safe_link $from/$dep_member_sane $to/$sub_member_sane || fail
+  else
+    safe_link $from $to/$sub_member_sane || fail
+  fi
 
 end_function_flat
 handle_return
+}
+
+get_sub_dim() {
+local first_dim
+get_first_dim $cell_path || return 1
+sub_dim=$first_dim
+return 0
+}
+
+get_dep_dim() {
+local -r prep_file=$from.prep
+if [[ -f $prep_file ]]; then
+  source $prep_file || return 1
+fi
+
+local -r dep_cell=$(realpath $from)
+local dep_cell_parent=${dep_cell%/*}
+if [[ ${dep_cell_parent##*/} == .dim ]]; then
+  dep_cell_parent=${dep_cell_parent%/*}
+fi
+
+local first_dim
+get_first_dim $dep_cell_parent || return 1
+
+dep_dim=$first_dim
+return 0
+}
+
+get_first_dim() {
+local -r cell=$1
+first_dim=$( \
+  find $cell/.dna/dim -not '.*' \
+  | sort -g | head -n 1) || return 1
+if [[ ! "$first_dim" ]]; then
+  fatal "Could not find dim of $cell"
+  return 1
+fi
+return 0
+}
+
+get_dep_member() {
+
+if [[ -f $dep_cell/.dna/context-before ]]; then
+  source $dep_cell/.dna/context-before || return 1
+else
+  fatal "Missing context-before in $dep_cell/.dna."
+  fatal "Should have been generated by update of it's trunk."
+  fatal "Maybe try to run a clean on it and update again."
+  return 1
+fi
+
+if [[ ! -v $dep_dim ]]; then
+  fatal "Missing member for $dep_dim."
+  fatal "This should have been defined in $dep_cell/.dna/context-before"
+  return 1
+fi
+
+dep_member=${!dep_dim}
+return 0
 }
 
 # ??
