.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -587,6 +587,8 @@ switch_context() {
         fail1
       fi
 
+      load_branch_info $cell_path || fail
+
       last_context_loaded=$cell_path
 
       setup_cell_path_vars $cell_path || fail
@@ -854,6 +856,69 @@ execute_command_internal() {
   handle_return
 }
 
+branch_local_vars='branch_dims branch_members branch_hashes branch_dim_count trunk_cell short_cell'
+load_branch_info() {
+  local cell_path=${1:-$cell_path}
+
+  begin_function
+
+    branch_dims=() \
+    branch_members=() \
+    branch_hashes=() \
+
+    local c=$cell_path p d m
+    begin_while [[ $c == *:* ]]; doo
+      p=${c##*/}
+      if [[ $p == *:* ]]; then
+
+        d=${p%%:*}
+        branch_dims=( $d ${branch_dims[*]} )
+
+        m=${p#*:}
+        branch_hashes=( $m ${branch_hashes[*]} )
+
+        local member_var_path=$c/.member
+        if [[ -f $member_var_path ]]; then
+          m=$(<$member_var_path) || fail
+        fi
+        branch_members=( "$m" "${branch_members[@]}" )
+
+      fi
+      c=${c%/*}
+    end_while
+
+    trunk_cell=$c
+    branch_dim_count=${#branch_dims[*]}
+
+    if [[ "${branch_dims:-}" ]]; then
+      log_debug "Branch dims found: ${branch_dims[*]}" || fail
+    fi
+
+    local x y dim_string= 
+    if [[ "${branch_hashes:-}" ]]; then
+      dim_string="${branch_hashes[*]}"
+      dim_string=:${dim_string// /\/}
+    fi
+    local short_trunk=$trunk_cell
+    if   y=${short_trunk%/*/*/*} 
+         x=${short_trunk#$y/}
+         [[ $x != $short_trunk && ${#x} -gt 0 ]]; then
+      short_trunk=$x
+    elif y=${short_trunk%/*/*} 
+         x=${short_trunk#$y/}
+         [[ $x != $short_trunk && ${#x} -gt 0 ]]; then
+      short_trunk=$x
+    elif x=${short_trunk##*/} 
+         [[ $x != $short_trunk && ${#x} -gt 0 ]]; then
+      short_trunk=$x
+    fi
+    short_cell="$short_trunk$dim_string"
+
+    log_return_vars=short_cell
+  end_function
+  handle_return
+}
+
 execute_command() {
   local cell_path=$(realpath $1) current_command=$2 \
     log_show_vars='^cell_path current_command' 
@@ -1046,69 +1111,6 @@ make_or_load_dna_contents() {
       write_or_load var "$array_assignment" || fail
     fi
 
-  end_function
-  handle_return
-}
-
-branch_local_vars='branch_dims branch_members branch_hashes branch_dim_count trunk_cell short_cell'
-load_branch_info() {
-  local cell_path=${1:-$cell_path}
-
-  begin_function
-
-    branch_dims=() \
-    branch_members=() \
-    branch_hashes=() \
-
-    local c=$cell_path p d m
-    begin_while [[ $c == *:* ]]; doo
-      p=${c##*/}
-      if [[ $p == *:* ]]; then
-
-        d=${p%%:*}
-        branch_dims=( $d ${branch_dims[*]} )
-
-        m=${p#*:}
-        branch_hashes=( $m ${branch_hashes[*]} )
-
-        local member_var_path=$c/.member
-        if [[ -f $member_var_path ]]; then
-          m=$(<$member_var_path) || fail
-        fi
-        branch_members=( "$m" "${branch_members[@]}" )
-
-      fi
-      c=${c%/*}
-    end_while
-
-    trunk_cell=$c
-    branch_dim_count=${#branch_dims[*]}
-
-    if [[ "${branch_dims:-}" ]]; then
-      log_debug "Branch dims found: ${branch_dims[*]}" || fail
-    fi
-
-    local x y dim_string= 
-    if [[ "${branch_hashes:-}" ]]; then
-      dim_string="${branch_hashes[*]}"
-      dim_string=:${dim_string// /\/}
-    fi
-    local short_trunk=$trunk_cell
-    if   y=${short_trunk%/*/*/*} 
-         x=${short_trunk#$y/}
-         [[ $x != $short_trunk && ${#x} -gt 0 ]]; then
-      short_trunk=$x
-    elif y=${short_trunk%/*/*} 
-         x=${short_trunk#$y/}
-         [[ $x != $short_trunk && ${#x} -gt 0 ]]; then
-      short_trunk=$x
-    elif x=${short_trunk##*/} 
-         [[ $x != $short_trunk && ${#x} -gt 0 ]]; then
-      short_trunk=$x
-    fi
-    short_cell="$short_trunk$dim_string"
-
-    log_return_vars=short_cell
   end_function
   handle_return
 }
