fix needs_update check

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -251,6 +251,9 @@ create_sub_cells() {
 if [[ "$sub_path" ]]; then
   create_sub_cells2 $cell_path '' || return 1
 fi
+if [[ "$status_path" ]]; then
+  touch $status_path/subs-up-to-date || return 1
+fi
 return 0
 }
 
@@ -398,16 +401,17 @@ local context_dim=$1
 begin_function_flat
   context_dim=${context_dim##*/}
   context_dim=${context_dim#*-}
-  if [[ ! -v $context_dim ]]; then
-    err "internal error: while trying to create a branch sub cell, required dim value $context_dim is missing."
+  local ddim=d_$context_dim
+  if [[ ! -v $ddim ]]; then
+    err "Internal error: While trying to create a branch sub cell, required dim value $context_dim is missing."
     fail1
   fi
-  local value=${!context_dim}
+  local value=${!ddim}
   if [[ "$value" == $empty_member ]]; then
     value=
   fi
   echo "# Generated by create_sub_branch from $cell_path
-d_$context_dim='$value'" >$sub_dna_path/context-before || fail
+$ddim='$value'" >$sub_dna_path/context-before || fail
 end_function_flat
 handle_return
 }
@@ -564,6 +568,7 @@ local vars='cell command'; begin_function
     err "Context failed to load for $cell"
     fail1
     }
+  eval "$localize_dim_vars" || fail
   if type -t $command &>/dev/null; then
     $command || fail
   else
@@ -717,26 +722,17 @@ begin_function_flat
       fi
     fi
 
-    # if [[ "$ref_group" && ! "${!ref_group:-}" ]]; then
-    #   err "Problem executing step $step"
-    #   err "Could not find ref group for $ref. Should be named either ${ref}s, ${ref}es, or ${ref%?}ies, "
-    #   err "or override it with a different folder name."
-    #   err "Or if this is a custom loop with a block-before file in it, set ref_group= (to nothing) in that file."
-    #   fail1
-    # fi
-
   fi
 
-  # This can be overridden in a prep_code_file to provide custom looping
+  # This can be overridden in a block-before file to provide custom looping
   handle_step_loop || fail
 
-  # NOT USED YET
-  # local after_block_files=( $(find1 $step -regex '.*/after-block.*') ) || fail
-  # local after_block_file
-  # begin_for after_block_file in "${after_block_files[@]}"; doo
-  #   # recursive
-  #   execute_command_step "$after_block_file" || fail
-  # end_for
+  local after_block_files=( $(find1 $step -regex '.*/block-after.*' | sort -g) ) || fail
+  local after_block_file
+  begin_for after_block_file in "${after_block_files[@]}"; doo
+    # recursive
+    execute_command_step "$after_block_file" || fail
+  end_for
 
 end_function_flat
 handle_return
@@ -1393,7 +1389,7 @@ local vars=dim; begin_function
 
   begin_for member in "${values[@]}"; doo
 
-    eval "local $dim='$member' d_$dim='$member'"
+    eval "local d_$dim='$member'"
 
     if [[ $parallel == t ]]; then
       $function &
@@ -1477,11 +1473,13 @@ handle_return
 expand_values() {
 begin_function_flat
 
-  local dims=${dim}s \
+  local dims=${dim}s 
+  local ddims=d_$dims \
+        ddim=d_$dim \
         new_value_list= new_values= value \
         has_member_expand_function=f
 
-  values=( ${!dim:-} )
+  values=( ${!ddim:-} )
   type -t ${dim}_member_expand >/dev/null && has_member_expand_function=t
 
   local problem=
@@ -1535,7 +1533,7 @@ expand_values_plural() {
 
 begin_function_flat
 
-  values=( ${!dims:-} )
+  values=( ${!ddims:-} )
 
   if [[ ! "${values:-}" ]]; then
 
@@ -1596,7 +1594,7 @@ begin_function_flat
 
   begin_for value in "${values[@]}"; doo
 
-    eval "local $dim='$value' d_$dim='$value'"
+    eval "local d_$dim='$value'"
     cell_values[-1]=$value
 
     if [[ "$branch_function" ]]; then
@@ -1747,7 +1745,7 @@ if [[ -d $cell/.dna/dim ]]; then
     fi
     dim_var_plural=${dim_var}s
     leaf_dims+=( $dim_var )
-    localize_dim_vars+="local $dim_var=\${$dim_var:-} $dim_var_plural=\${$dim_var_plural:-}; "
+    localize_dim_vars+="local d_$dim_var=\${d_$dim_var:-\${$dim_var:-}} d_$dim_var_plural=\${d_$dim_var_plural:-\${$dim_var_plural:-}}; "
   done
 fi
 
@@ -1762,7 +1760,7 @@ if [[ -d $cell/.dna/sub-dim ]]; then
     fi
     dim_var_plural=${dim_var}s
     sub_dims+=( $dim_var )
-    localize_dim_vars+="local $dim_var=\${$dim_var:-} $dim_var_plural=\${$dim_var_plural:-}; "
+    localize_dim_vars+="local d_$dim_var=\${d_$dim_var:-\${$dim_var:-}} d_$dim_var_plural=\${d_$dim_var_plural:-\${$dim_var_plural:-}}; "
   done
 fi
 }
