Remove handle_unknown

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -2616,28 +2616,28 @@ calc_coordinates_row_end() {
 
     if [[ "$unknown_dims" ]]; then
 
-      case $handle_unknown in
-        error)
-          log_fatal "Could not resolve dims: $unknown_dims"
-          fail1
-        ;;
-        blank)
-          for d in ${unknown_dims[*]}; do
-            local -n m=d_$d
-            m=$empty_member
-          done
-          calc_coordinates_add_row || fail
-          progress_bar_nudge
-        ;;
-        skip)
+      #case $handle_unknown in
+      #  error)
+      #    log_fatal "Could not resolve dims: $unknown_dims"
+      #    fail1
+      #  ;;
+      #  blank)
+      #    for d in ${unknown_dims[*]}; do
+      #      local -n m=d_$d
+      #      m=$empty_member
+      #    done
+      #    calc_coordinates_add_row || fail
+      #    progress_bar_nudge
+      #  ;;
+      #  skip)
           log_debug "Skipped row because of unresolvable dims: $unknown_dims"
           progress_bar_nudge x
-        ;;
-        *)
-          log_fatal "Internal error: invalid handle_unknown value: $handle_unknown"
-          fail1
-        ;;
-      esac
+      #  ;;
+      #  *)
+      #    log_fatal "Internal error: invalid handle_unknown value: $handle_unknown"
+      #    fail1
+      #  ;;
+      #esac
 
     else
       calc_coordinates_add_row || fail
@@ -3153,7 +3153,6 @@ calc_coordinates_slow() {
         begin_for (( row_index = 0; row_index < coordinate_rows; row_index++ )); doo
           target_dim_var_type=sdims convert_coords_to_dims || fail
           expand_dims $known_dims || fail
-          handle_unknown=skip \
           calc_coordinates_next_known_dim || fail
           progress_bar_next
           log_debug "Finished coordinate row $((row_index+1)) of $coordinate_rows"
@@ -3199,7 +3198,7 @@ xlr8_get_dim_fields() {
 # assumes all checks were done previously to determine if this is needed
 calc_coordinates() {
   local clear_existing_coords=${clear_existing_coords:-t} coord_type=$coord_type \
-    handle_unknown=${handle_unknown:-${default_handle_unknown:-error}} coord_limit=${coord_limit:-}
+    coord_limit=${coord_limit:-}
   begin_function
 
     localize
@@ -3270,7 +3269,6 @@ build_context_leaf() {
     local unknown_dims=() \
       coord_type=branch \
 
-    handle_unknown=skip \
     calc_coordinates || fail
     fence
 
