.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -3384,27 +3384,41 @@ cell_unlock() {
   return 0
 }
 
-magic_shell_prompt='$=-=$'$NL
 # input:
-#   pipe
-#   command
-#   timeout
-# output: 
-#   result
-run_pipe_command() {
-  local pipe=$pipe command=$command timeout=${timeout:-30}
-  local log_show_vars='pipe command'
+#   line        command to send to pipe
+#   pipe_in
+#   pipe_out
+#   timeout_ms 
+# output:
+#   
+to_background_shell_single() {
   begin_function
-    command_successful=f
-    from_var=command \
-      to_background_shell || fail
-    local stop_after=$magic_shell_prompt
-    literal_to_regex stop_after
-    to_var=result \
-      from_background_shell || fail
-    if [[ $timed_out == f && $failed == f ]]; then
-      command_successful=t
+
+    local timeout_ms=${timeout_ms:-0}
+    if (( timeout_ms == 0 )); then
+      echo -n "$line" >$pipe_in || fail
+    else
+
+      local pid \
+        time_left=$timeout_ms \
+        delay_ms=250
+      echo -n "$line" >$pipe_in & 
+      pid=$!
+
+      timed_out=f
+      begin_while ps $pid &>/dev/null; doo
+        local seconds_to_wait=$(dc -e "2 k $delay_ms 1000 / p")
+        sleep $seconds_to_wait
+        (( time_left -= $delay_ms ))
+        if (( time_left <= 0 )); then
+          log_debug "Timed out trying to execute: $line"
+          timed_out=t
+          break
+        fi
+      end_while
+
     fi
+
   end_function
   handle_return
 }
@@ -3412,7 +3426,7 @@ run_pipe_command() {
 to_background_shell() {
   local pipe_in=${pipe}_in pipe_out=${pipe}_out \
     secret=${secret:-none} \
-    sleep_between_lines=${sleep_between_lines:-0}
+    sleep_between_lines=${sleep_between_lines:-0} 
   local -n from=$from_var
   local masked_from=$from
   if [[ "$secret" != none ]]; then
@@ -3428,12 +3442,15 @@ to_background_shell() {
     if (( sleep_between_lines > 0 )); then
       local line
       while IFS= read -r line || [[ "$line" ]]; do
-        echo "$line" >$pipe_in || fail
+        to_background_shell_single || fail
+        if [[ $timed_out == t ]]; then
+          succeed
+        fi
         sleep $sleep_between_lines
       done <<<"$from"
       handle_break
     else
-      echo -n "$from" >$pipe_in || fail
+      to_background_shell_single || fail
     fi
 
   end_function
@@ -3617,6 +3634,34 @@ from_background_shell() {
     #   fail1
     # fi
 
+  end_function
+  handle_return
+}
+
+magic_shell_prompt='$=-=$'$NL
+# input:
+#   pipe
+#   command
+#   timeout
+# output: 
+#   result
+run_pipe_command() {
+  local pipe=$pipe command=$command 
+  local log_show_vars='pipe command'
+  begin_function
+    command_successful=f
+    from_var=command \
+      to_background_shell || fail
+    if [[ $timed_out == t ]]; then
+      succeed
+    fi
+    local stop_after=$magic_shell_prompt
+    literal_to_regex stop_after
+    to_var=result \
+      from_background_shell || fail
+    if [[ $timed_out == f && $failed == f ]]; then
+      command_successful=t
+    fi
   end_function
   handle_return
 }
