.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -105,7 +105,15 @@ make_cyto_vars() {
       var=${var_path##*/}
       content=$(<$var_path)
       trim_ws content
-      echo "${NL}local $var=\"$content\"" >>$context_path || fail
+      case "$content" in
+        \"*|\'*|\(*)
+          :
+        ;;
+        *)
+          content="'${content//\'/\'\\\'\'}'"
+        ;;
+      esac
+      echo "${NL}$var=$content" >>$context_path || fail
     end_for
   end_function
   handle_return
@@ -1226,7 +1234,7 @@ execute_command_internal() {
           mkdir $key_path || fail
         fi
       ;;
-      log|dim-add)
+      log|dim-*)
         :
       ;;
       *)
