.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -168,6 +168,8 @@ begin_function_flat
     key_path=$dna_path/key
   fi
 
+  lock_path=$job_path/lock 
+
   op_path=$dna_path/op
 
   dna_up_path=$dna_path/up
@@ -551,6 +553,7 @@ get_needs_update() {
 
     if [[ $needs_update == t && ${pre_validate:-f} == t ]]; then
 
+      local check_successful=f
       if execute_op check; then
         if [[ $check_successful == t ]]; then
           needs_update=f
@@ -2394,6 +2397,7 @@ init_context() {
   in_path= \
   out_path=out \
   update_cost=1 \
+  cell_usage_lock=f \
   refresh_less_than=${refresh_less_than:-1} 
   return 0
 }
@@ -3288,6 +3292,23 @@ cd_to_plant() {
     echo "No plant found" >&2
     return 1
   fi
+  return 0
+}
+
+# locks the given cell, or fails if it can't obtain a lock
+cell_lock() {
+  local cell_path=$1
+  local timeout=$lock_timeout
+  local lock_path=$cell_path/.job/lock
+  fd_write_lock || return 1
+  return 0
+}
+
+# locks the given cell, or fails if it can't obtain a lock
+cell_unlock() {
+  # local cell_path=$1
+  # local lock_path=$cell_path/.job/lock
+  fd_unlock || return 1
   return 0
 }
 
