.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -124,7 +124,15 @@ write_or_load() {
       echo "$content" >>$context_path.new || fail
       last_type=$new_type
     fi
-    eval "$content" || fail
+    eval "$content" || {
+      if [[ "${var_full_path:-}" ]]; then
+        log_fatal "Invalid dna file: $var_full_path"
+      else
+        log_fatal "Invalid dna file. Contents:"
+        log_fatal "$content"
+      fi
+      fail1
+    }
   end_function
   handle_return
 }
@@ -1186,7 +1194,9 @@ make_or_load_context() {
 
   end_function
   if failed; then
-    rm $context_path.new
+    if [[ -e $context_path.new ]]; then
+      rm $context_path.new
+    fi
   fi
   handle_return
 }
