Use secret_vars instead of secret for all background interaction and logging

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -3181,18 +3181,6 @@ get_cell_id() {
   cell_id=${cell_id#_}
 }
 
-# log_and_run() {
-#   local command=$* secret=${secret:-}
-# 
-#   local masked_command=$command
-#   if [[ "$secret" ]]; then
-#     masked_command="${masked_command//$secret/****}"
-#   fi
-# 
-#   log_info "$masked_command"
-#   eval "$command"
-# }
-
 encrypt_file() {
   local user_private_key=${user_private_key:-~/.ssh/id_rsa}
   local from=$from \
@@ -3797,6 +3785,7 @@ get_replay_file() {
 
 update_replay_hash() {
   pipe_replay_hash=$(echo -n "$command" | sha1sum | awk '{print $1}')
+  debug_return_vars=pipe_replay_hash
 }
 
 # This can be used directly if a background process is already running
@@ -3821,7 +3810,7 @@ prep_background_communication() {
       ;;
       replaying)
         update_replay_hash "$command" || fail
-        log_verbose "Replaying pre-recorded $masked_command responses" || fail
+        log_verbose "Replaying pre-recorded $command responses" || fail
       ;;
       disabled)
         :
@@ -3837,7 +3826,7 @@ prep_background_communication() {
 }
 
 start_background_process() {
-  local command="$*" secret=${secret:-}
+  local command="$*" 
   begin_function
     prep_background_communication || fail
     case $pipe_replay_state in
@@ -3866,16 +3855,11 @@ to_background_process_single() {
     local timeout_ms=$(dc -e "$timeout 1000 * p")
     timeout_ms=${timeout_ms%.*}
 
-    local masked_command=$command
-    if [[ "$secret" ]]; then
-      masked_command="${masked_command//$secret/****}"
-    fi
-
     if (( timeout_ms == 0 )); then
-      log_debug "Sending output to process without timeout: $masked_command" || fail
+      log_debug "Sending output to process without timeout: $command" || fail
       if [[ $pretend == f ]]; then
         if [[ "${background_log:-}" ]]; then
-          echo -n "$YELLOW$masked_command$RESET" >>$background_log || fail
+          echo -n "$YELLOW$command$RESET" >>$background_log || fail
         fi
         case $pipe_replay_state in recording|replaying)
           update_replay_hash "$command" || fail
@@ -3892,12 +3876,12 @@ to_background_process_single() {
         delay_ms=250
       local delay_s=$(dc -e "$delay_ms 1000 3 k / p")
 
-      log_debug "Sending output to process with ${timeout}s timeout: $masked_command" || fail
+      log_debug "Sending output to process with ${timeout}s timeout: $command" || fail
 
       timed_out=f wait_time=0
 
       if [[ "${background_log:-}" ]]; then
-        echo -n "$YELLOW$masked_command$RESET" >>$background_log || fail
+        echo -n "$YELLOW$command$RESET" >>$background_log || fail
       fi
 
       if [[ $pipe_replay_state != replaying ]]; then
@@ -3914,7 +3898,7 @@ to_background_process_single() {
            , wait_time += delay_ms ))
 
           if (( time_left <= 0 )); then
-            log_debug "Timed out trying to execute: $masked_command" || fail
+            log_debug "Timed out trying to execute: $command" || fail
             timed_out=t
             kill $pid || log_warn "Failed to kill $pid"
             break
@@ -3940,14 +3924,8 @@ to_background_process_single() {
 to_background_process() {
 
   local -n from=$from_var
-  local masked_from=$from \
-      secret=${secret:-} \
 
-  if [[ "$secret" ]]; then
-    masked_from=${from//$secret/****}
-  fi
-
-  local log_show_vars='from=masked_from pipe_replay timeout_to' \
+  local log_show_vars='from pipe_replay timeout_to' \
     log_vars='pipe pretend'
   begin_function_hi
 
@@ -4029,7 +4007,7 @@ from_background_process__check_line() {
         if [[ "$line" =~ ${interact_in[$i]} ]]; then
           log_debug "Interact matched [${interact_in[$i]}]" || fail
           local output=${interact_out[$i]}
-          pretend=$pretend secret="$secret" from_var=output to_background_process || fail
+          pretend=$pretend from_var=output to_background_process || fail
           interacted=t
           undefer "exec $back_fd>&-" || fail
           get_replay_file || fail
@@ -4199,7 +4177,6 @@ from_background_process() {
       fail_after=${fail_after:-} \
       required_output=${required_output:-} \
       interact=${interact:-} \
-      secret=${secret:-} \
       pretend_out=${pretend_out:-} \
       pretending=f \
       timeout=${timeout:-0} \
