Fix FROM root bug

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -2083,11 +2083,11 @@ load_parent_context() {
     local root_path=$path/.root
     if [[ -e $root_path ]]; then
       log_debug "Appending parent trunk context ${path#/*/*/}"
-      echo "# This section was generated from $root_path" >>$context_path.new || fail
+      echo "$NL# FROM $root_path" >>$context_path-$context_type.new || fail
       if [[ -d $root_path ]]; then
         load_dna_contents $root_path || fail
       elif [[ -f $root_path ]]; then
-        cat $root_path >>$context_path.new || fail
+        cat $root_path >>$context_path-$context_type.new || fail
       fi
     fi
   end_function
