.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -2907,9 +2907,10 @@ execute_command() {
 #      should_fork=f
     fi
     
-    if [[ $should_fork == t ]]; then
-      fork execute_command_internal || fail_later
-    else
+    # forking should be handled outside of execute_command, to improve performance
+#    if [[ $should_fork == t ]]; then
+#      fork execute_command_internal || fail_later
+#    else
       if [[ $disable_log == f ]]; then
         : ${omni_log_fork_child:=0}
         (( omni_log_fork_child++ ))
@@ -2921,7 +2922,7 @@ execute_command() {
       if [[ $disable_log == f ]]; then
         cell_close_log_file || fail
       fi
-    fi
+#    fi
 
   end_function
   handle_return
