.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -4425,15 +4425,17 @@ calc_coordinates_next_dim_member() {
     log_debug "Processing $dim = $member in phase $phase"
     local validated_dims=${validated_dims:-} conflicting_values=() is_valid
 
-    if [[ $needs_validation == t && " $validated_dims " != *" $dim "* ]]; then
-      calc_coords_validate_member "$member" || fail
-      log_show_vars='dim member'
-      fence
-    else
-      is_valid=t
-    fi
+    #  should not need validation now
+    #  instead, 
+    #if [[ $needs_validation == t && " $validated_dims " != *" $dim "* ]]; then
+    #  calc_coords_validate_member "$member" || fail
+    #  log_show_vars='dim member'
+    #  fence
+    #else
+    #  is_valid=t
+    #fi
 
-    if [[ $is_valid == t ]]; then
+    #if [[ $is_valid == t ]]; then
 
       conflict=
       if [[ -v key_tables ]]; then
