Fix top cell create_cyto bug

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -94,16 +94,14 @@ begin_function_flat
   record_context $cell || fail
 
   get_top_cell $cell || fail
-  if [[ "$top_cell" != $cell ]]; then
-    if [[ -d $top_cell/.dna/command ]]; then
-      safe_link $top_cell/.dna/command $new_cyto/command || fail
-    else
-      err "Top cell doesn't have a command folder ($top_cell/.dna/command missing)"
-      fail1
-    fi
-    if [[ -d $top_cell/.dna/lib ]]; then
-      safe_link $top_cell/.dna/lib $new_cyto/lib || fail
-    fi
+  if [[ -d $top_cell/.dna/command ]]; then
+    safe_link $top_cell/.dna/command $new_cyto/command || fail
+  else
+    err "Top cell doesn't have a command folder ($top_cell/.dna/command missing)"
+    fail1
+  fi
+  if [[ -d $top_cell/.dna/lib ]]; then
+    safe_link $top_cell/.dna/lib $new_cyto/lib || fail
   fi
 
   #   older more powerful, but more fragile way
