Improve mock command

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -3024,7 +3024,8 @@ execute_command() {
     fi
 
     if [[ $disable_log == t ]]; then
-      log_debug "Logging disabled." || fail
+      #log_debug "Logging disabled." || fail
+      :
     else
       execute_command_log_prep || fail
     fi
