Remove tabs

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -246,8 +246,8 @@ setup_cell_path_vars() {
 
     # create this folder as needed
     cyto_up_path=$cyto_path/up
-		# to make update ops simpler
-		up_path=$cyto_up_path
+    # to make update ops simpler
+    up_path=$cyto_up_path
 
     dna_down_path=$dna_path/down
     if [[ ! -d $dna_down_path ]]; then
@@ -602,12 +602,12 @@ fork_inside() {
     cleanup_on_exit=
     setup_exit_trap
 
-		if [[ "$to_var" ]]; then
-			eval "$to_var=\$($command)"; return_code=$?
-			reply_to_caller "$to_var='${!to_var}'" || fail
-		else
-			eval "$command"; return_code=$?
-		fi
+    if [[ "$to_var" ]]; then
+      eval "$to_var=\$($command)"; return_code=$?
+      reply_to_caller "$to_var='${!to_var}'" || fail
+    else
+      eval "$command"; return_code=$?
+    fi
 
     if [[ $change_log == t ]]; then
       cell_close_log_file || fail
@@ -636,8 +636,8 @@ fork_inside() {
 after_fork() {
   if [[ -f "${reply_file:-}" ]]; then
 
-		# DEBUGGING
-		local file=$(<$reply_file)
+    # DEBUGGING
+    local file=$(<$reply_file)
 
     source $reply_file || return 1
     if [[ ${debugging:-f} == t ]]; then
@@ -657,29 +657,29 @@ after_fork() {
 # usage: fork {command to execute}
 #  background=f (whether to run as a background process)
 #  change_log=f (whether to change the log)
-#  to_var				(write output to the given var instead of stdout)
+#  to_var        (write output to the given var instead of stdout)
 fork() {
 
   local reply_file command=$* return_code=0 \
     background=${background:-f} \
     change_log=${change_log:-f} \
-		to_var=${to_var:-}
+    to_var=${to_var:-}
 
-	if [[ $background == t ]]; then
-		change_log=t
-	fi
+  if [[ $background == t ]]; then
+    change_log=t
+  fi
 
-	get_new_reply_file || return 1
-	defer "rm $reply_file"
+  get_new_reply_file || return 1
+  defer "rm $reply_file"
 
-	if [[ $background == t ]]; then
-		( fork_inside ) &
-	else
-		( fork_inside )
-	fi
-	return_code=$?
+  if [[ $background == t ]]; then
+    ( fork_inside ) &
+  else
+    ( fork_inside )
+  fi
+  return_code=$?
 
-	after_fork || (( return_code++ ))
+  after_fork || (( return_code++ ))
 
   return $return_code
 }
@@ -1873,7 +1873,7 @@ validate_dims() {
 log_and_run() {
   local command=$*
   echo "$command" >&2
-	eval "$command"
+  eval "$command"
 }
 
 encrypt_file() {
@@ -2301,7 +2301,7 @@ get_workspace() {
 }
 
 # inputs:
-#   from		encrypted file to decrypt
+#   from    encrypted file to decrypt
 #   to      (optional) file to save decrypted form to
 #           if 'to' is missing, then it writes the decrypted value to stdout
 decrypt_file() {
@@ -2312,7 +2312,7 @@ decrypt_file() {
 
   begin_function
 
-		pause_tee
+    pause_tee
 
     if [[ ! -f $from ]]; then
       log_fatal "File doesn't exist: $from"
@@ -2324,24 +2324,24 @@ decrypt_file() {
       fail1
     fi
      
-		if [[ "$to" ]]; then
-			if [[ -e $to ]]; then
-				log_fatal "File already exists: $to"
-				fail1
-			fi
-			setup_tmp_path || fail
-			if ! openssl pkeyutl -decrypt -inkey $key -in $from -out $to; then
-				log_fatal "Failed to decrypt file: $from"
-				fail1
-			fi
-		else
-			if ! openssl pkeyutl -decrypt -inkey $key -in $from; then
-				log_fatal "Failed to decrypt file: $from"
-				fail1
-			fi
-		fi
+    if [[ "$to" ]]; then
+      if [[ -e $to ]]; then
+        log_fatal "File already exists: $to"
+        fail1
+      fi
+      setup_tmp_path || fail
+      if ! openssl pkeyutl -decrypt -inkey $key -in $from -out $to; then
+        log_fatal "Failed to decrypt file: $from"
+        fail1
+      fi
+    else
+      if ! openssl pkeyutl -decrypt -inkey $key -in $from; then
+        log_fatal "Failed to decrypt file: $from"
+        fail1
+      fi
+    fi
      
-		unpause_tee
+    unpause_tee
 
   end_function
   handle_return
@@ -3135,7 +3135,7 @@ to_background_shell() {
   fi
 
   local log_show_vars='from=masked_from' \
-		log_vars=pipe
+    log_vars=pipe
   begin_function
 
     if [[ ! -p $pipe_in ]]; then
@@ -3282,7 +3282,7 @@ from_background_shell() {
   local -n to=$to_var
 
   local log_vars='pipe interact' \
-	  log_show_vars='timeout stop_after fail_after'
+    log_show_vars='timeout stop_after fail_after'
   begin_function
 
     timed_out=f
@@ -3294,8 +3294,8 @@ from_background_shell() {
 
     from_background_shell__prep || fail
 
-		log_vars=pipe_out \
-			log_debug "Waiting for background job output"
+    log_vars=pipe_out \
+      log_debug "Waiting for background job output"
 
     if [[ $buffering == line ]]; then
       while true; do
