.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -760,6 +760,22 @@ switch_context_calc_coordinates() {
   handle_return
 }
 
+extract_resolvable_dims() {
+  begin_function
+    local i field coord_type=branch values=() count
+    begin_for (( i = 0; i < ${#branch_coordinate_fields[*]}; i++ )); doo
+      field=${branch_coordinate_fields[$i]}
+      fetch_values_from_coordinates $field || fail
+      local -n dim=d_$field
+      count=${#values[*]}
+      if (( count == 1 )); then
+        dim=${values[0]}
+      fi
+    end_for
+  end_function
+  handle_return
+}
+
 prep_dims() {
   local dim_types=$*
   begin_function
@@ -2915,7 +2931,9 @@ execute_command() {
       ;;
     esac
 
-    strong_log=t log_info "Executing cell command: $short_cell $cell_command" || fail
+    if [[ $top_level_command == f ]]; then
+      strong_log=t log_info "Executing cell command: $short_cell $cell_command" || fail
+    fi
 
     if [[ ! -e "$cell_path" ]]; then
       plant_seed $cell_path || {
diff --git a/lib/help-lib b/lib/help-lib
--- a/lib/help-lib
+++ b/lib/help-lib
@@ -235,44 +235,44 @@ show_cell_help() {
       out "${NL}Required parameters: ${required[*]}"
     fi
 
-    if [[ "${trunk_dims:-}" ]]; then
-      local i pretty_form= member dim show_header=t
-      #begin_for (( i = 0; i < ${#branch_dims[*]}; i++ )); doo
-      #  dim=${branch_dims[$i]}
-      #  eval "member=\${branch_members[$i]}"
-      #  local pretty_function_name=trunk_dims_${dim}_pretty
-      #  if function_exists $pretty_function_name; then
-      #    eval "$pretty_function_name member" || fail
-      #    pretty_form=" ($member)"
-      #  else
-      #    pretty_form=
-      #  fi
-      #  out "  $dim=${branch_members[$i]}$pretty_form"
-      #end_for
-      (( indent += 2 ))
-      begin_for (( i = 0; i < ${#trunk_dims[*]}; i++ )); doo
-        dim_var=${trunk_dims[$i]}
-        local -n dim=d_$dim_var
-        local pretty_function_name=trunk_dims_${dim_var}_pretty
-        if function_exists $pretty_function_name; then
-          eval "$pretty_function_name $dim_var" || fail
-          pretty_form=" ($value)"
-        else
-          pretty_form=
-        fi
-        local value=${dim:-}
-        if [[ "${value:-}" ]]; then
-          if [[ $show_header == t ]]; then
-            indent=$((indent-2)) out "${NL}Branch dimensions:"
-            show_header=f
-          fi
-          if [[ "$value" == $empty_member ]]; then
-            value='(empty)'
-          fi
-          out "$dim_var=$value$pretty_form"
-        fi
-      end_for
-    fi
+#    if [[ "${trunk_dims:-}" ]]; then
+#      local i pretty_form= member dim show_header=t
+#      #begin_for (( i = 0; i < ${#branch_dims[*]}; i++ )); doo
+#      #  dim=${branch_dims[$i]}
+#      #  eval "member=\${branch_members[$i]}"
+#      #  local pretty_function_name=trunk_dims_${dim}_pretty
+#      #  if function_exists $pretty_function_name; then
+#      #    eval "$pretty_function_name member" || fail
+#      #    pretty_form=" ($member)"
+#      #  else
+#      #    pretty_form=
+#      #  fi
+#      #  out "  $dim=${branch_members[$i]}$pretty_form"
+#      #end_for
+#      (( indent += 2 ))
+#      begin_for (( i = 0; i < ${#trunk_dims[*]}; i++ )); doo
+#        dim_var=${trunk_dims[$i]}
+#        local -n dim=d_$dim_var
+#        local pretty_function_name=trunk_dims_${dim_var}_pretty
+#        if function_exists $pretty_function_name; then
+#          eval "$pretty_function_name $dim_var" || fail
+#          pretty_form=" ($value)"
+#        else
+#          pretty_form=
+#        fi
+#        local value=${dim:-}
+#        if [[ "${value:-}" ]]; then
+#          if [[ $show_header == t ]]; then
+#            indent=$((indent-2)) out "${NL}Branch dimensions:"
+#            show_header=f
+#          fi
+#          if [[ "$value" == $empty_member ]]; then
+#            value='(empty)'
+#          fi
+#          out "$dim_var=$value$pretty_form"
+#        fi
+#      end_for
+#    fi
 
   end_function
   handle_return
