Improve cell command logging

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -2932,11 +2932,11 @@ execute_command_internal() {
 
     command_history+="$cell_command $short_cell "
 
-    if [[ ${cell_is_leaf:-t} == t || $show_branches == t ]]; then
-      log_info "Executing cell command: $short_cell $cell_command" || fail
-    else
-      log_verbose "Executing cell command: $short_cell $cell_command" || fail
-    fi
+    #if [[ ${cell_is_leaf:-t} == t || $show_branches == t ]]; then
+    #  log_info "Executing cell command: $short_cell $cell_command" || fail
+    #else
+    #  log_verbose "Executing cell command: $short_cell $cell_command" || fail
+    #fi
 
     local command_function=${cell_command//-/_}_command
     if function_exists $command_function; then
@@ -2983,6 +2983,8 @@ execute_command() {
       background_log \
       running_job_path \
       recursive_command=${recursive_command:-${recursive:-f}} \
+
+    log_verbose "Executing cell command: ${cell_path#/work/*/} $cell_command" || fail
 
     if [[ ! -e "$cell_path" ]]; then
       plant_seed $cell_path || {
