Implement bash function auto repair

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -1561,6 +1561,27 @@ setup_cell_path_vars() {
   handle_return
 }
 
+# inputs: up_path up_name choice
+link_choice() {
+  begin_function
+    local choice2=${choice//-/_} \
+      up_name2=${up_name//-/_} \
+      dep_path=$up_path/$up_name
+    local path_var=up_${up_name2}_choices_${choice2}_path
+    local -n path=$path_var
+    if [[ ! -v $path_var ]]; then
+      log_fatal "Missing choice path var"
+      fail1
+    fi
+    if [[ ! -d $path ]]; then
+      log_fatal "Missing choice path"
+      fail1
+    fi
+    safe_link $path $dep_path/choices/$choice || fail
+  end_function
+  handle_return
+}
+
 make_cyto_up() {
   begin_function
     mkdir $up_path || fail
@@ -1574,18 +1595,7 @@ make_cyto_up() {
         local -n choices=$choices_var
         mkdir $dep_path/choices || fail
         begin_for choice in ${choices[*]}; doo
-          local choice2=${choice//-/_}
-          local path_var=up_${up_name2}_choices_${choice2}_path
-          local -n path=$path_var
-          if [[ ! -v $path_var ]]; then
-            log_fatal "Missing choice path var"
-            fail1
-          fi
-          if [[ ! -d $path ]]; then
-            log_fatal "Missing choice path"
-            fail1
-          fi
-          safe_link $path $dep_path/choices/$choice || fail
+          link_choice || fail
         end_for
       else
         log_fatal "Invalid upstream config for $up_path: Missing choices folder."
