Get upstream calculation working

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -217,9 +217,10 @@ make_or_load_dna_contents2() {
       split_ordinal item_name o item_name
       if [[ "$current_var" ]]; then
         eval "$current_var+=( $item_name )"
-        if [[ -L $item ]]; then
-          local linktarget=$(realpath $item)
-          result="${current_var}_${item_name//-/_}_linktarget=$linktarget"
+        local path
+        if [[ -L $item || -d $item ]]; then
+          path=$(realpath $item)
+          result="${current_var}_${item_name//-/_}_path=$path"
           eval "$result" || fail
           write_to_context var "$result" || fail
         fi
@@ -858,14 +859,26 @@ make_cyto_up() {
     mkdir $up_path || fail
     local up_name
     begin_for up_name in ${up[*]}; doo
-      local dep_path=$up_path/$up_name
+      local dep_path=$up_path/$up_name \
+        up_name2=${up_name//-/_}
       mkdir $dep_path || fail
-      if [[ -v up_${up_name}_choices ]]; then
-        local from
-        local -n choices=up_${up_name}_choices
+      if [[ -v up_${up_name2}_choices ]]; then
+        local choice choices_var=up_${up_name2}_choices
+        local -n choices=$choices_var
         mkdir $dep_path/choices || fail
-        begin_for from in ${choices[*]}; doo
-          safe_link $from $dep_path/choices/ || fail
+        begin_for choice in ${choices[*]}; doo
+          local choice2=${choice//-/_}
+          local path_var=up_${up_name2}_choices_${choice2}_path
+          local -n path=$path_var
+          if [[ ! -v $path_var ]]; then
+            log_fatal "Missing choice path var"
+            fail1
+          fi
+          if [[ ! -d $path ]]; then
+            log_fatal "Missing choice path"
+            fail1
+          fi
+          safe_link $path $dep_path/choices/$choice || fail
         end_for
       else
         log_fatal "Invalid upstream config for $up_path: Missing choices folder."
