.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -511,6 +511,70 @@ plant_seed() {
   handle_return
 }
 
+init_context() {
+  # required_freshness:
+  #   inf means infinite (never refresh based on time). 30s means refresh if it is older than 30 seconds.
+  #   1w means refresh if it's older than a week.
+  # shuffle_chance:
+  #   chance out of 1000 of not following the computed strategy order
+  # min_pause:
+  #   number of ms to wait between cycles
+  #   this number doubles each time there is nothing to do, until it reaches max_pause
+  # reuse_existing_out:
+  #   if set to t: 
+  #   new output folder won't be created when updating, but the existing one will be used
+  #   should set to true when creating a new output folder would be expensive
+  #   these cells must detect for themselves whether a change has happened in an
+  #     update and set something_changed=t accordingly. 
+
+  cell_expiration= \
+  cell_is_external=f \
+  cell_is_persistent=f \
+  command_path= \
+  current_pause=250 \
+  default_freshness= \
+  default_strategies=crl \
+  localize_dims= \
+  lock_timeout=2 \
+  max_pause=60000 \
+  min_pause=250 \
+  out_fields_choices= \
+  out_file= \
+  out_form_choices='raw simple table json kv' \
+  out_path= \
+  post_validate=f \
+  pre_validate=f \
+  props=() \
+  refresh_less_than=${refresh_less_than:-1} \
+  retry_delay=1 \
+  retry_max=1 \
+  retry_scale=2 \
+  reuse_existing_out=t \
+  shuffle_chance=100 \
+  sub_dims=() \
+  trunk_dims=() \
+  up=() \
+  update_cost=1 \
+
+  unset dim_constraints_all_fields \
+    dim_constraints_all_table \
+
+  if [[ "${current_command:-}" ]]; then
+    command_path=$path_to_commands/$current_command
+    if [[ -e $command_path.info ]]; then
+      source $command_path.info || return 1
+    else
+      log_warn "Missing file $command_path.info" || return 1
+    fi
+  fi
+
+  unset \
+    check_op \
+    update_op \
+
+  return 0
+}
+
 switch_context() {
 
   if [[ "${last_context_loaded:-}" != $cell_path ]]; then
@@ -1445,67 +1509,6 @@ setup_cell_path_vars() {
 
   end_function
   handle_return
-}
-
-init_context() {
-  # required_freshness:
-  #   inf means infinite (never refresh based on time). 30s means refresh if it is older than 30 seconds.
-  #   1w means refresh if it's older than a week.
-  # shuffle_chance:
-  #   chance out of 1000 of not following the computed strategy order
-  # min_pause:
-  #   number of ms to wait between cycles
-  #   this number doubles each time there is nothing to do, until it reaches max_pause
-  # reuse_existing_out:
-  #   if set to t: 
-  #   new output folder won't be created when updating, but the existing one will be used
-  #   should set to true when creating a new output folder would be expensive
-  #   these cells must detect for themselves whether a change has happened in an
-  #     update and set something_changed=t accordingly. 
-
-  cell_expiration= \
-  cell_is_external=f \
-  cell_is_persistent=f \
-  command_path= \
-  current_pause=250 \
-  default_freshness= \
-  default_strategies=crl \
-  localize_dims= \
-  lock_timeout=2 \
-  max_pause=60000 \
-  min_pause=250 \
-  out_fields_choices= \
-  out_file= \
-  out_form_choices='raw simple table json kv' \
-  out_path= \
-  post_validate=f \
-  pre_validate=f \
-  props=() \
-  refresh_less_than=${refresh_less_than:-1} \
-  retry_delay=1 \
-  retry_max=1 \
-  retry_scale=2 \
-  reuse_existing_out=t \
-  shuffle_chance=100 \
-  sub_dims=() \
-  trunk_dims=() \
-  up=() \
-  update_cost=1 \
-
-  if [[ "${current_command:-}" ]]; then
-    command_path=$path_to_commands/$current_command
-    if [[ -e $command_path.info ]]; then
-      source $command_path.info || return 1
-    else
-      log_warn "Missing file $command_path.info" || return 1
-    fi
-  fi
-
-  unset \
-    check_op \
-    update_op \
-
-  return 0
 }
 
 make_cyto_up() {
