Change prep_background_communication

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -3790,8 +3790,9 @@ update_replay_hash() {
 
 # This can be used directly if a background process is already running
 prep_background_communication() {
-  local command=$command
+  local command=$1
   begin_function
+
     if [[ ! "${pipe_replay_state:-}" ]]; then
       pipe_replay=${pipe_replay:-${replay:-f}}
       # pipe_replay may be: replaying recording disabled
@@ -3801,25 +3802,26 @@ prep_background_communication() {
       else
         pipe_replay_state=${pipe_replay_state:-recording}
       fi
-    fi
 
-    pipe_replay_hash=none
-    case $pipe_replay_state in
-      recording)
-        update_replay_hash "$command" || fail
-      ;;
-      replaying)
-        update_replay_hash "$command" || fail
-        log_verbose "Replaying pre-recorded $command responses" || fail
-      ;;
-      disabled)
-        :
-      ;;
-      *)
-        log_fatal "Unknown pipe_replay_state: $pipe_replay_state"
-        fail1
-      ;;
-    esac
+      pipe_replay_hash=none
+      case $pipe_replay_state in
+        recording)
+          update_replay_hash "$command" || fail
+        ;;
+        replaying)
+          update_replay_hash "$command" || fail
+          log_verbose "Replaying pre-recorded $command responses" || fail
+        ;;
+        disabled)
+          :
+        ;;
+        *)
+          log_fatal "Unknown pipe_replay_state: $pipe_replay_state"
+          fail1
+        ;;
+      esac
+
+    fi
 
   end_function
   handle_return
@@ -3828,7 +3830,7 @@ prep_background_communication() {
 start_background_process() {
   local command="$*" 
   begin_function
-    prep_background_communication || fail
+    prep_background_communication "$command" || fail
     case $pipe_replay_state in
       recording|disabled)
         log_and_run "$command" || fail
