.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -1394,42 +1394,42 @@ build_context_expand_members_known() {
   local members_with_pipes=${members_with_pipes// /\|}
 
   code+="
-  all)
-    _out=( $quoted_members )
-  ;;
-  $members_with_pipes)
-    _out=( \$_in )
-  ;;
-  *)
-    problem=\"Invalid $dim: \$_in\"
-  ;;
-esac
+    all)
+      _out=( $quoted_members )
+    ;;
+    $members_with_pipes)
+      _out=( \$_in )
+    ;;
+    *)
+      problem=\"Invalid $dim: \$_in\"
+    ;;
+  esac
 }"
 }
 
 build_context_expand_members() {
   code+="
-  all)
-    local -n members=dim_${dim}_members
-    if [[ -v members ]]; then
-      _out=( \"\${members[@]}\" )
-    else
-      problem=\"Can't use all value for a dynamic dim\"
-    fi
-  ;;
-  *)
-    local -n members=dim_${dim}_members \
-      member_type=dim_${dim}_member_type \
+    all)
+      local -n members=dim_${dim}_members
+      if [[ -v members ]]; then
+        _out=( \"\${members[@]}\" )
+      else
+        problem=\"Can't use all value for a dynamic dim\"
+      fi
+    ;;
+    *)
+      local -n members=dim_${dim}_members \\
+        member_type=dim_${dim}_member_type \\
 
-    if [[ -v members ]] && array_contains members \"\$_in\"; then
-      _out=( \"\$_in\" )
-    elif [[ ! -v member_type || \$member_type == dynamic ]]; then
-      _out=( \"\$_in\" )
-    else
-      problem=\"Invalid dim member for $dim: \$_in\"
-    fi
-  ;;
-esac
+      if [[ -v members ]] && array_contains members \"\$_in\"; then
+        _out=( \"\$_in\" )
+      elif [[ \${member_type:-dynamic} == dynamic ]]; then
+        _out=( \"\$_in\" )
+      else
+        problem=\"Invalid dim member for $dim: \$_in\"
+      fi
+    ;;
+  esac
 }"
 }
 
@@ -6727,57 +6727,49 @@ switch_context() {
   module_path=${cell_path#/*/*/}
   module_path=${cell_path%/$module_path}
 
-  if [[ "${last_context_loaded:-}" != $cell_path ]]; then
+  local log_show_vars=^cell_path rebuild_attempted=f
+  begin_function
 
-    local log_show_vars=^cell_path rebuild_attempted=f
-    begin_function
+    get_short_cell
+    log_debug "Loading context for $short_cell"
 
-      get_short_cell
-      log_debug "Loading context for $short_cell"
+    if [[ "$cell_path" == /seed/* ]]; then
+      log_fatal "Can't switch contexts to a seed path. Make sure to run this command in a work folder."
+      fail1
+    fi
 
-      if [[ "$cell_path" == /seed/* ]]; then
-        log_fatal "Can't switch contexts to a seed path. Make sure to run this command in a work folder."
+    dna_path=$cell_path/.dna \
+    cyto_path=$cell_path/.cyto \
+
+    local dna_exists=f
+    if [[ -e $dna_path ]]; then
+      dna_exists=t
+    fi
+
+    context_path=$cyto_path/context
+    init_context || fail
+
+    seed_path=
+    if [[ $dna_exists == t ]]; then
+
+      if [[ ! -f $context_path ]]; then
+        log_fatal "Context has not been generated yet. Run the grow command first."
         fail1
       fi
 
-      dna_path=$cell_path/.dna \
-      cyto_path=$cell_path/.cyto \
+      source $context_path || fail
+      setup_dims || fail
 
-      local dna_exists=f
-      if [[ -e $dna_path ]]; then
-        dna_exists=t
-      fi
+    fi
 
-      context_path=$cyto_path/context
-      init_context || fail
+    load_post_context_dynamic_vars || fail
+    last_context_loaded=$cell_path
 
-      seed_path=
-      if [[ $dna_exists == t ]]; then
+    error_if_unresolved=t \
+    handle_questions || fail
 
-        if [[ ! -f $context_path ]]; then
-          log_fatal "Context has not been generated yet. Run the grow command first."
-          fail1
-        fi
-
-        source $context_path || fail
-        setup_dims || fail
-
-      fi
-
-      load_post_context_dynamic_vars || fail
-      last_context_loaded=$cell_path
-
-      error_if_unresolved=t \
-      handle_questions || fail
-
-    end_function
-    handle_return
-
-  else
-    log_debug "Context already loaded: $short_cell"
-  fi
-
-  return 0
+  end_function
+  handle_return
 }
 
 cell_open_log_file() {
diff --git a/lib/grow-lib b/lib/grow-lib
--- a/lib/grow-lib
+++ b/lib/grow-lib
@@ -54,7 +54,6 @@ make_dim_cache() {
       dim_group \
       secret_vars \
       all_dims \
-      dim_shorts \
       || fail
 
     mv $cache_path.new $cache_path || fail
@@ -464,21 +463,21 @@ grow_context() {
       fi
 
       if [[ $dna_exists == t ]]; then
-        if [[ "$clean_cells" ]]; then
-          local cell_to_clean
-          cells_already_cleaned=${cells_already_cleaned:-}
-          if [[ " $cells_already_cleaned " == *" $cell_path "* ]]; then
-            log_debug "Cell already cleaned: $cell_path"
+        if [[ "${regrow_cells:-}" ]]; then
+          local cell_to_regrow
+          cells_already_regrown=${cells_already_regrown:-}
+          if [[ " $cells_already_regrown " == *" $cell_path "* ]]; then
+            log_debug "Cell already regrown: $cell_path"
           else
-            begin_for cell_to_clean in $clean_cells; doo
-              if [[ $cell_path == *$cell_to_clean* ]]; then
+            begin_for cell_to_regrow in $regrow_cells; doo
+              if [[ $cell_path == *$cell_to_regrow* ]]; then
                 if [[ -e $cyto_path ]]; then
-                  log_info "Cleaning cell ${cell_to_clean#/work/*/} => $short_cell..."
+                  log_info "Cleaning cell ${cell_to_regrow#/work/*/} => $short_cell..."
                   rm -rf $cell_path/!(.*) $cyto_path || fail
                 else
-                  log_info "Cell already clean: $cell_to_clean => $short_cell"
+                  log_info "Cell already regrown: $cell_to_regrow => $short_cell"
                 fi
-                cells_already_cleaned+=" $cell_path"
+                cells_already_regrown+=" $cell_path"
                 break
               fi
             end_for
@@ -492,7 +491,7 @@ grow_context() {
       seed_path=
       if [[ $dna_exists == t ]]; then
 
-        check_foundation || fail
+        #check_foundation || fail
 
         if [[ ! -f $context_path ]]; then
           fork build_cyto $cell_path || fail
@@ -1005,14 +1004,7 @@ grow_command() {
       needs_inner=f \
       grow_successful=t \
 
-    if [[ "${refresh:-f}" == t ]]; then
-      refresh=f
-      #find $cell_path -path '*/.cyto/status/up-to-date' -delete || fail
-      rm $cyto_path/status/up-to-date || fail
-    fi
-
     grow_context $cell_path || fail
-    switch_context $cell_path || fail
     fence
 
     if [[ "${upstream_cell_link:-}" ]]; then
