.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -1711,25 +1711,26 @@ return 0
 
 # 'value' is the loop var
 parallel_loop() {
-local loop_over_var=$loop_over_var head=${head:-} \
-  body=$body tail=${tail:-} array par=${par:-t} fork=${fork:-f}
+local loop_over_var2=$loop_over_var head2=${head:-} \
+  body2=$body tail2=${tail:-} \
+  par2=${par:-t} fork2=${fork:-f} \
+  array 
 
 # Make sure these variables don't get passed into inner loops
-body="local loop_over_var= head= body= tail= par= fork=
-$body"
+local loop_over_var= head= body= tail= par= fork=
 
-local vars='loop_over_var par fork'
+local vars='loop_over_var=loop_over_var2 par=par2 fork=fork2'
 begin_function
 
-  if [[ ! -v $loop_over_var ]]; then
-    fatal "Internal error: Variable doesn't exist: $loop_over_var"
+  if [[ ! -v $loop_over_var2 ]]; then
+    fatal "Internal error: Variable doesn't exist: $loop_over_var2"
     stack_trace
     fail
   fi
 
-  eval "array=( \"\${$loop_over_var[@]}\" )"
+  eval "array=( \"\${$loop_over_var2[@]}\" )"
   local parallel=f
-  if [[ ${#array[*]} -gt 1 && $parallel_execution == t && $par == t ]]; then
+  if [[ ${#array[*]} -gt 1 && $parallel_execution == t && $par2 == t ]]; then
     parallel=t
     wait_for_low_load || fail
   fi
@@ -1737,24 +1738,24 @@ begin_function
   local processes= leave_loop=0 value
   begin_for value in "${array[@]}"; doo
 
-    if [[ "$head" ]]; then
-      eval "$head" || fail
+    if [[ "$head2" ]]; then
+      eval "$head2" || fail
     fi
 
     if [[ $parallel == t ]]; then
-      { begin_fork; eval "$body"; } &
+      { begin_fork; eval "$body2"; } &
       after_fork
       processes+=" $!"
     else
-      if [[ $fork == t ]]; then
-        fork "$body" || fail
+      if [[ $fork2 == t ]]; then
+        fork "$body2" || fail
       else
-        eval "$body" || fail
+        eval "$body2" || fail
       fi
     fi
 
-    if [[ "$tail" ]]; then
-      eval "$tail" || fail
+    if [[ "$tail2" ]]; then
+      eval "$tail2" || fail
     fi
 
   end_for
