work on upstream consolidation

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -6264,6 +6264,11 @@ load_post_context_dynamic_vars() {
   handle_return
 }
 
+# inputs:
+#   up_var
+#   up_name
+#   choice_name
+#   dep_path
 link_single() {
   local only_one=${only_one:-f}
   begin_function
@@ -6283,7 +6288,7 @@ link_single() {
     fi
 
     if [[ ! -d $choice_path ]]; then
-      log_fatal "Missing choice path"
+      log_fatal "Missing choice directory for $up_name"
       fail1
     fi
 
@@ -6303,6 +6308,7 @@ link_single() {
 make_cyto_up() {
   begin_function
 
+    zombie_debug
     local dep_path=$cyto_path/$up_cell_type/$up_name \
       up_var=${up_name//-/_} \
       only_one=t \
@@ -6318,13 +6324,13 @@ make_cyto_up() {
       local choice_count=${#choices[*]}
 
       if (( choice_count == 1 )); then
-        choice_name=$up_name \
         link_single || fail
       elif (( choice_count == 0 )); then
         log_fatal "$up_cell_type cell has no choices."
         fail1
       else
-        local choice_path=$cyto_path/$up_cell_type-choices choice_name
+        local choice_name
+        only_one=f
         mkdir -p $choice_path || fail
         begin_for choice_name in ${choices[*]}; doo
           link_single || fail
@@ -6370,7 +6376,7 @@ build_cyto() {
         local -n upstream_var=$up_cell_type
         if [[ -v upstream_var ]]; then
           begin_for up_name in ${upstream_var[*]}; doo
-            make_cyto_up
+            make_cyto_up || fail
           end_for
         fi
       end_for
