.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -202,7 +202,7 @@ load_dims() {
         trunk_dims=( $d ${trunk_dims[*]} )
         branch_dims=( $d ${branch_dims[*]} )
 
-        local member_var_path=$c/.dna/member_value.var
+        local member_var_path=$c/.member
         if [[ -f $member_var_path ]]; then
           load_var $member_var_path m
         else
@@ -489,8 +489,8 @@ get_branch_dims_from_path() {
     if [[ $part == *:* ]]; then
       dim=${part%%:*}
       branch_dims+=( $dim )
-      if [[ -f $path/.dna/member.var ]]; then
-        member=$(<$path/.dna/member.var)
+      if [[ -f $path/.member ]]; then
+        member=$(<$path/.member)
       else
         member=${part#*:}
       fi
@@ -1694,21 +1694,20 @@ plant_member() {
       fi
 
       mkdir $new_path || fail
-      safe_link $parent_path/.dna $new_path/ || fail
       if [[ "$member" != "$sane_value" ]]; then
-        echo "$member" >$new_path/.dna/member.var || fail
+        echo "$member" >$new_path/.member || fail
       fi
 
       local from=
 
-      if [[ -d $seed_path/$m ]]; then
-        from=$seed_path/$m
-      elif [[ -d $seed_path/_other ]]; then
-        from=$seed_path/_other
+      if [[ -d $seed_path/$dim:$sane_value ]]; then
+        from=$seed_path/$dim:$sane_value
+      elif [[ -d $seed_path/$dim:_other ]]; then
+        from=$seed_path/$dim:_other
       fi
 
       if [[ "$from" ]]; then
-        safe_link $from/* $new_path/ || fail
+        safe_link $from/.dna $from/* $new_path/ || fail
         if [[ $deep == t ]]; then
           # recursive
           plant_seed $from $new_path || fail
