Fix omni-nav bug

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -763,11 +763,11 @@ make_or_load_context() {
   local log_vars=cell_path log_show_vars=short_cell
   begin_function
 
-    local action=Loading
+    local context_action=Loading
     if [[ $context_make == t ]]; then
-      action=Making
+      context_action=Making
     fi
-    log_debug "$action context for $short_cell" || fail
+    log_debug "$context_action context for $short_cell" || fail
 
     local item_name last_part dna_full_item suffix
     local -A append_vars
@@ -2580,6 +2580,7 @@ execute_command_internal() {
 
     if [[ " ${command_history:-}" == *" $cell_command $short_cell "* ]]; then
       log_fatal "Circular dependency found: arrived at $cell_command $short_cell a second time."
+      debug_start
       fail1
     fi
 
