implement context load

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -108,7 +108,7 @@ local step=$1
 vars=step; begin_function
   local step_name=${step##*/} prefix=
 
-  if [[ $target_file =~ ([0-9]+)-(.*) ]]; then
+  if [[ $target_file =~ ([0-9]+|\^+)-(.*) ]]; then
     prefix=${BASH_REMATCH[1]}
     base=${BASH_REMATCH[2]}
   fi
@@ -124,12 +124,12 @@ vars=step; begin_function
     if [[ $base =~ ^choose-.* ]]; then
       # TODO ...
       incomplete
-    elif [[ $base =~ ^serial-each-.* ]]; then
-      serial=t execute_command_step_each || fail
+    elif [[ $base =~ ^loop-.* ]]; then
+      ( serial=t execute_command_step_each ) || fail
     elif [[ $base =~ ^each-.* ]]; then
-      serial=f execute_command_step_each || fail
+      ( serial=f execute_command_step_each ) || fail
     else
-      execute_command_step_plain_folder $step || fail
+      ( execute_command_step_plain_folder $step ) || fail
     fi
   elif [[ -f $step ]]; then
     execute_command_step_file $step || fail
@@ -164,7 +164,8 @@ begin_function_flat
       source $step || fail
       local function_name=${step%.bash}
       function_name=${function_name##*/}
-      local function_exists=`type -t $function_name &>/dev/null && echo true`
+      function_name=${function_name//-/_}
+      local function_exists=$(type -t $function_name &>/dev/null && echo true)
       if [[ "$function_exists" ]]; then
         $function_name || fail
       else
@@ -184,43 +185,66 @@ handle_return
 execute_command_step_each() {
 local serial=$serial
 begin_function_flat
+
   local ref ref_group
-  if [[ $base =~ each-([^-]+)-in-([^-]+) ]]; then
-    ref=${BASH_REMATCH[1]}
-    ref_group=${BASH_REMATCH[2]}
-  elif [[ $base =~ each-([^-]+) ]]; then
-    ref=${BASH_REMATCH[1]}
+  if [[ $base =~ (each|loop)-([^-]+)-in-([^-]+) ]]; then
+    ref=${BASH_REMATCH[2]}
+    ref_group=${BASH_REMATCH[3]}
+  elif [[ $base =~ (each|loop)-([^-]+) ]]; then
+    ref=${BASH_REMATCH[2]}
     ref_group=${ref}s
   fi
-  if [[ ! -v $ref_group ]]; then
-    err "var doesn't exist: $ref_group"
-    fail1
-  fi
-  local v a
-  eval "a=( \"$ref_group[@]}\" )"
 
-  local parallel=f processes=
-  if [[ "${#a[*]}" -gt 1 ]]; then
-    if [[ "$parallel_execution" == t && $serial == f ]]; then
-      parallel=t
-      wait_for_low_load || fail
-    fi
-  fi
-
-  begin_for v in "${a[@]}"; doo
-    let "$ref=\$v"
-    if [[ $parallel == t ]]; then
-      execute_command_step_plain_folder $step &
-      processes+=" $!"
-    else
-      execute_command_step_plain_folder $step || fail
-    fi
+  setup_default_each_handler || fail
+  local prep_code_files=( $(find1 $step -regex '.*/\^+-.*') )
+  local prep_code_file
+  begin_for prep_code_file in "${prep_code_files[@]}"; doo
+    execute_command_step "$prep_code_file" || fail
   end_for
 
-  wait_for_sub_processes || fail
+  # This can be overridden in a prep_code_file to provide custom looping
+  handle_step_each || fail
 
 end_function_flat
 handle_return
+}
+
+setup_default_each_handler() {
+  handle_step_each() {
+
+  begin_function_flat
+
+    if [[ ! -v $ref_group ]]; then
+      err "var doesn't exist: $ref_group"
+      fail1
+    fi
+    local v a
+    eval "a=( \"$ref_group[@]}\" )"
+
+    local parallel=f processes=
+    if [[ "${#a[*]}" -gt 1 ]]; then
+      if [[ "$parallel_execution" == t && $serial == f ]]; then
+        parallel=t
+        wait_for_low_load || fail
+      fi
+    fi
+
+    begin_for v in "${a[@]}"; doo
+      let "$ref=\$v"
+      if [[ $parallel == t ]]; then
+        execute_command_step_plain_folder $step &
+        processes+=" $!"
+      else
+        ( execute_command_step_plain_folder $step ) || fail
+      fi
+    end_for
+
+    wait_for_sub_processes || fail
+
+  end_function_flat 
+  handle_return
+
+  }
 }
 
 # may be run in a subshell
@@ -230,7 +254,7 @@ begin_function_flat
 
   change_log_file || fail
 
-  local contents=$(find1 -not -name ".*" $step | sort -g) || fail
+  local contents=$(find1 -not -name ".*" -not -name "*^-*" $step | sort -g) || fail
   local files i=0 file_index
   [[ ! "$contents" ]] && succeed
 
@@ -278,7 +302,7 @@ begin_function_flat
         processes+=" $!"
       else
         # recursive
-        execute_command_step $step || fail
+        ( execute_command_step $step ) || fail
       fi
     end_for
 
@@ -373,7 +397,7 @@ begin_function
   if [[ $changed == t ]]; then
     from=$new_unsafe_file to=$new_file encrypt_file || fail
     mv $new_file $old_file || fail
-    update_modify_times "${new_file%/*}" "${current_cube}" || fail
+    update_modify_times "${new_file%/*}" "${current_stem}" || fail
   fi
 
 end_function
@@ -406,7 +430,7 @@ begin_function
 
   if [[ $changed == t ]]; then
     mv $new_file $old_file || fail
-    update_modify_times "${new_file%/*}" "$cube_path" || fail
+    update_modify_times "${new_file%/*}" "$stem_path" || fail
   fi
 
 end_function
@@ -414,21 +438,21 @@ handle_return
 }
 
 # input must be a folder
-setup_cube_path_vars() {
+setup_stem_path_vars() {
 begin_function_flat
 
   if [[ ! "${top_stem:-}" ]]; then
     get_top_stem "$subject" || fail
   fi
 
-  cube_path=$(realpath $1) \
-    dna_path=$cube_path/.dna \
-    cube_cyto_path=$cube_path/.cyto \
-    short_cube=${cube_path#$top_stem}
+  stem_path=$(realpath $1) \
+    dna_path=$stem_path/.dna \
+    stem_cyto_path=$stem_path/.cyto \
+    short_stem=${stem_path#$top_stem}
 
   if [[ ! -d $dna_path ]]; then
 
-    cube_type=constant
+    stem_type=constant
     dna_path=
 
   else
@@ -441,14 +465,14 @@ begin_function_flat
 
   fi
 
-  cube_up_path=$dna_path/up
-  if [[ ! -d $cube_up_path ]]; then
-    cube_up_path=
+  stem_up_path=$dna_path/up
+  if [[ ! -d $stem_up_path ]]; then
+    stem_up_path=
   fi
 
-  cube_down_path=$cube_cyto_path/down
-  if [[ ! -d $cube_down_path ]]; then
-    cube_down_path=
+  stem_down_path=$stem_cyto_path/down
+  if [[ ! -d $stem_down_path ]]; then
+    stem_down_path=
   fi
 
   # context can override these as needed
@@ -458,47 +482,47 @@ begin_function_flat
 
   if [[ "$in_path" ]]; then
     if [[ "$in_path" == . ]]; then
-      cube_in_path=$cube_path
+      stem_in_path=$stem_path
     else
-      cube_in_path=$cube_path/$in_path
+      stem_in_path=$stem_path/$in_path
     fi
   fi
 
   if [[ "$out_path" ]]; then
     if [[ "$out_path" == . ]]; then
-      cube_out_path=$cube_path
+      stem_out_path=$stem_path
     else
-      cube_out_path=$cube_path/$out_path
+      stem_out_path=$stem_path/$out_path
     fi
   fi
 
-  cube_status_path=$cube_cyto_path/status
-  if [[ ! -d $cube_status_path ]]; then
-    cube_status_path=
+  stem_status_path=$stem_cyto_path/status
+  if [[ ! -d $stem_status_path ]]; then
+    stem_status_path=
   fi
 
-  cube_lock_path=$cube_cyto_path/lock
-  if [[ ! -d $cube_lock_path ]]; then
-    cube_lock_path=
+  stem_lock_path=$stem_cyto_path/lock
+  if [[ ! -d $stem_lock_path ]]; then
+    stem_lock_path=
   fi
 
-  cube_log_path=$cube_cyto_path/log
-  if [[ ! -d $cube_log_path ]]; then
-    cube_log_path=
+  stem_log_path=$stem_cyto_path/log
+  if [[ ! -d $stem_log_path ]]; then
+    stem_log_path=
   fi
 
-  cube_debug_path=$cube_cyto_path/debug
-  if [[ ! -d $cube_debug_path ]]; then
-    cube_debug_path=
+  stem_debug_path=$stem_cyto_path/debug
+  if [[ ! -d $stem_debug_path ]]; then
+    stem_debug_path=
   fi
 
-  req_path=$cube_cyto_path/req
+  req_path=$stem_cyto_path/req
   if [[ ! -d $req_path ]]; then
     req_path=
   fi
 
   # if there are dims, this will be overridden in setup_batch_path_vars
-  batch_path=$cube_cyto_path/batch
+  batch_path=$stem_cyto_path/batch
 
 end_function_flat
 handle_return
@@ -533,23 +557,23 @@ fi
 return 0
 }
 
-# This is run if cube hasn't been initialized = missing .cyto folder
+# This is run if stem hasn't been initialized = missing .cyto folder
 # Context should be loaded before this is run
-init_cube() {
+init_stem() {
 local subject=$1
 begin_function_flat
-  cube_cyto_path=$subject/.cyto
-  mkdir $cube_cyto_path || fail
+  stem_cyto_path=$subject/.cyto
+  mkdir $stem_cyto_path || fail
   local feature
-  cube_lock_path=
-  if [[ "${cube_features:-}" ]]; then
-    begin_for feature in "${cube_features[@]}"; doo
+  stem_lock_path=
+  if [[ "${stem_features:-}" ]]; then
+    begin_for feature in "${stem_features[@]}"; doo
       case $feature in
         req)
-          mkdir -p $cube_cyto_path/$feature/new || fail
+          mkdir -p $stem_cyto_path/$feature/new || fail
         ;;
         log)
-          mkdir -p $cube_cyto_path/$feature || fail
+          mkdir -p $stem_cyto_path/$feature || fail
         ;;
         *)
           err "Unknown feature $feature"
@@ -559,8 +583,8 @@ begin_function_flat
     end_for
   fi
   if [[ -d $subject/.dna ]]; then
-    mkdir $cube_cyto_path/batch \
-          $cube_cyto_path/status || fail
+    mkdir $stem_cyto_path/batch \
+          $stem_cyto_path/status || fail
   fi
 end_function_flat
 handle_return
@@ -583,7 +607,7 @@ init_context() {
   # min_pause:
   #   number of ms to wait between cycles
   #   this number doubles each time there is nothing to do, until it reaches max_pause
-  # cube_type:
+  # stem_type:
   #   can be: constant info change
   #   constant means it just holds a fixed value that never changes
   #   info means it only fetches information 
@@ -595,8 +619,8 @@ init_context() {
   in_paths= \
   out_path= \
   out_paths= \
-  cube_in_path= \
-  cube_out_path= \
+  stem_in_path= \
+  stem_out_path= \
   batch_in_path= \
   batch_out_path= \
   default_fresh=inf \
@@ -617,7 +641,7 @@ init_context() {
   generators=gen_copy \
   min_pause=250 \
   current_pause=250 \
-  cube_type=info \
+  stem_type=info \
   max_pause=60000 \
   top_stem=${top_stem:-}
 
@@ -650,10 +674,10 @@ init_context() {
 setup_batch_path_vars() {
 begin_function_flat
 
-  require_var cube_path cube_cyto_path
+  require_var stem_path stem_cyto_path
 
   # batch id is quite different than batch path, given new structure: .cyto/dim/env/e1...
-  batch_path=$cube_cyto_path/batch
+  batch_path=$stem_cyto_path/batch
   batch_dna_path=$dna_path/batch
   batch_id=only
   batch_value_path=
@@ -665,11 +689,11 @@ begin_function_flat
 
       d=${batch_dims[$i]}
       if [[ ! "$d" ]]; then
-        err "Invalid cube config: batch_values array has more elements than the number of batch_dims"
+        err "Invalid stem config: batch_values array has more elements than the number of batch_dims"
         fail1
       fi
       if [[ ! "$d" =~ ^[A-Za-z0-9_\.:\-]+$ ]]; then
-        err "Invalid cube config: Bad dim name: $d"
+        err "Invalid stem config: Bad dim name: $d"
         fail1
       fi
 
@@ -691,14 +715,14 @@ begin_function_flat
 
   update_batch_value_file || fail
 
-  if [[ "$cube_lock_path" ]]; then
+  if [[ "$stem_lock_path" ]]; then
     # Will be created when a lock on this batch is obtained
     batch_lock_path=$batch_path/lock
   else
     batch_lock_path=
   fi
 
-  if [[ "$cube_status_path" ]]; then
+  if [[ "$stem_status_path" ]]; then
     batch_status_path=$batch_path/status
     if [[ ! -d $batch_status_path ]]; then
       mkdir -p $batch_status_path || fail
@@ -712,21 +736,21 @@ begin_function_flat
     mkdir -p $batch_tmp_path || fail
   fi
 
-  if [[ "$cube_log_path" ]]; then
+  if [[ "$stem_log_path" ]]; then
     batch_log_path=$batch_path/log
     mkdir -p $batch_log_path || fail
   else
     batch_log_path=
   fi
 
-  if [[ "$cube_debug_path" ]]; then
+  if [[ "$stem_debug_path" ]]; then
     batch_debug_path=$batch_path/debug
     mkdir -p $batch_debug_path || fail
   else
     batch_debug_path=
   fi
 
-  if [[ "$cube_up_path" ]]; then
+  if [[ "$stem_up_path" ]]; then
     batch_up_path=$batch_path/up
     # Don't create the up path here, but instead allow it to be created 
     #   inside of batch_update -> batch_setup_up
@@ -734,7 +758,7 @@ begin_function_flat
     batch_up_path=
   fi
 
-  if [[ "$cube_down_path" ]]; then
+  if [[ "$stem_down_path" ]]; then
     batch_down_path=$batch_path/down
     # Created on demand
   else
@@ -743,9 +767,9 @@ begin_function_flat
 
   if [[ "$in_path" ]]; then
     if [[ "$in_path" == . ]]; then
-      batch_in_path=$cube_path$batch_value_path
+      batch_in_path=$stem_path$batch_value_path
     else
-      batch_in_path=$cube_in_path$batch_value_path
+      batch_in_path=$stem_in_path$batch_value_path
     fi
     mkdir -p $batch_in_path || fail
   else
@@ -754,9 +778,9 @@ begin_function_flat
 
   if [[ "$out_path" ]]; then
     if [[ "$out_path" == . ]]; then
-      batch_out_path=$cube_path$batch_value_path
+      batch_out_path=$stem_path$batch_value_path
     else
-      batch_out_path=$cube_out_path$batch_value_path
+      batch_out_path=$stem_out_path$batch_value_path
     fi
     mkdir -p $batch_out_path || fail
   else
@@ -767,18 +791,18 @@ end_function_flat
 handle_return
 }
 
-get_cube() {
-cube_path=$1
-[[ ${#cube_path} -lt 3 ]] && return 1
-[[ -d $cube_path/.dna ]] && return 0
-[[ -d $cube_path/.cyto ]] && return 0
-get_cube ${cube_path%/*} || return 1
+get_stem() {
+stem_path=$1
+[[ ${#stem_path} -lt 3 ]] && return 1
+[[ -d $stem_path/.dna ]] && return 0
+[[ -d $stem_path/.cyto ]] && return 0
+get_stem ${stem_path%/*} || return 1
 return 0
 }
 
 setup_tmp_path() {
 if [[ ! "$tmp_path" ]]; then
-  err "Missing tmp_path. Maybe you needed to run setup_cube_path_vars first"
+  err "Missing tmp_path. Maybe you needed to run setup_stem_path_vars first"
   return 1
 fi
 if [[ ! -d $tmp_path ]]; then
@@ -803,9 +827,9 @@ done
 }
 
 get_tmp_path() {
-local current_cube=$1
-if [[ -d $current_cube/tmp ]]; then
-  tmp_path=$current_cube/tmp
+local current_stem=$1
+if [[ -d $current_stem/tmp ]]; then
+  tmp_path=$current_stem/tmp
 elif [[ -d ~/tmp ]]; then
   tmp_path=~/tmp
 else
@@ -814,7 +838,7 @@ fi
 return 0
 }
 
-# inputs: from to tmp_path current_cube
+# inputs: from to tmp_path current_stem
 # will write output to file at $to
 decrypt_file() {
 
@@ -852,7 +876,7 @@ begin_function
   fi
 
   if [[ ! -f "$key_path/key.$USER" ]]; then
-    err "You don't have a key for this cube ($USER). Ask someone who does to add you. Existing keys:" 
+    err "You don't have a key for this stem ($USER). Ask someone who does to add you. Existing keys:" 
     find -L $key_path -name "key.*" >&2
     fail1
   fi
@@ -916,13 +940,13 @@ begin_function
 
     if [[ $key_count -gt 0 ]]; then
 
-      err "You don't have a key for this cube ($USER). Ask someone who does to add you. Existing keys:" 
+      err "You don't have a key for this stem ($USER). Ask someone who does to add you. Existing keys:" 
       find -L $key_path -name "key.*" >&2
       fail1
 
     else
 
-      trace $log_info "There are no keys for this cube yet. Will create a new key."
+      trace $log_info "There are no keys for this stem yet. Will create a new key."
 
       # create a new main key
       if ! openssl rand -base64 40 >$tmp_path/main; then
@@ -1137,11 +1161,11 @@ fi
 return 0
 }
 
-is_cube() {
+is_stem() {
 [[ -d "$1/.dna" ]]
 }
 
-is_inside_of_cube() {
+is_inside_of_stem() {
 local c=$1
 if [[ $c == "$top_stem"/* ]]; then
   while [[ $c == "$top_stem"/* ]]; do
@@ -1159,5 +1183,99 @@ else
   done
 fi
 return 1
+}
+
+load_context() {
+local subject=$1
+last_context_loaded=${last_context_loaded:-}
+[[ "$last_context_loaded" == $subject ]] && return 0
+init_context || return 1
+if [[ -f $subject/.dna/context ]]; then
+  source $subject/.dna/context || return 1
+fi
+last_context_loaded=$subject
+}
+
+readonly context_vars='
+batch_dims
+cell_dims
+'
+
+# should be run before spawn update function
+init_context() {
+
+  # default_fresh:
+  #   inf means infinite (never refresh based on time). 30s means refresh if it is older than 30 seconds.
+  #   1w means refresh if it's older than a week.
+  # high_volume_cell:
+  #   does the cell have thousands of cells or more? If so we will use another folder level
+  # ignore_fresh:
+  #   whether freshness is used to determine if a cell needs to be updated
+  # cell_storage:
+  #   contains pairs of var_name/default values used to store data in this cell
+  # shuffle_chance:
+  #   chance out of 1000 of not following the computed strategy order
+  # min_pause:
+  #   number of ms to wait between cycles
+  #   this number doubles each time there is nothing to do, until it reaches max_pause
+  # cube_type:
+  #   can be: constant info change
+  #   constant means it just holds a fixed value that never changes
+  #   info means it only fetches information 
+  #   change means that it applies a change
+
+  batch_dims= \
+  cell_dims= \
+  in_path= \
+  in_paths= \
+  out_path= \
+  out_paths= \
+  cube_in_path= \
+  cube_out_path= \
+  batch_in_path= \
+  batch_out_path= \
+  default_fresh=inf \
+  require_fresh_greater_than= \
+  retry_max=1 \
+  retry_delay=1 \
+  retry_scale=2 \
+  cell_expiration= \
+  high_volume_cell=f \
+  ignore_fresh=f \
+  default_strategies=crl \
+  cell_storage=() \
+  shuffle_chance=100 \
+  force_update=${p_force_update:-f} \
+  lock_timeout=${lock_timeout:-30} \
+  prevalidate=f \
+  postvalidate=f \
+  generators=gen_copy \
+  min_pause=250 \
+  current_pause=250 \
+  cube_type=info \
+  max_pause=60000 \
+  top_path=${top_path:-}
+
+  # override this if there are parameter requirements that must be met before attempting to update the cell
+  are_batch_params_valid() {
+    return 0
+  }
+
+  # override this if there are some batch id combinations which are not valid even when
+  # composed of valid dim members
+  # returns 0 if it's not a valid combination of members
+  skip_batch() {
+    return 1
+  }
+
+  # this may be overridden to provide a custom cooldown calculation
+  get_cooldown_delay() {
+    [[ -z "${cooldown_delay:-}" ]] && cooldown_delay=1
+    let cooldown_delay*=2
+  }
+
+  # override this function to implement custom update logic
+  unset execute_update
+
 }
 
