.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -638,6 +638,52 @@ load_branch_info() {
   handle_return
 }
 
+git_commit_check() {
+  begin_function
+
+    local status_file=$status_path/git-commit-when-built \
+      changed=f \
+      module_name=$(realpath $dna_path)
+    module_name=${module_name#/seed/}
+    module_name=${module_name%%/*}
+
+    if ! is_array repo_paths; then
+      load_repo_paths || fail
+    fi
+
+    local repo_path=${repo_paths[$module_name]}
+    local new_hash=$(git -C $repo_path rev-list HEAD --max-count=1) || fail
+
+    if [[ ! -f $status_file ]]; then
+      changed=t
+    else
+      local old_hash=$(<$status_file)
+      if [[ "$old_hash" != "$new_hash" ]]; then
+        changed=t
+      fi
+    fi
+
+    if [[ $changed == t ]]; then
+      rm -rf $cyto_path || fail
+      mkdir -p $status_path || fail
+      echo "$new_hash" >$status_file || fail
+    fi
+
+  end_function
+  handle_return
+}
+
+broken_link_check() {
+  begin_function
+    local broken_links=( $(find -L $cyto_path -type l -print -o -name ".*" -prune) ) || fail
+     if [[ "${broken_links:-}" ]]; then
+       log_debug "Broken links found in cyto: $broken_links. Will rebuild cyto."
+       rm -rf $cyto_path || fail
+     fi
+  end_function
+  handle_return
+}
+
 switch_context() {
 
   if [[ "${last_context_loaded:-}" != $cell_path ]]; then
@@ -657,10 +703,12 @@ switch_context() {
       setup_cell_path_vars $cell_path || fail
       init_context || fail
 
+      if [[ $trunk_changed == t && -e $cyto_path ]]; then
+        git_commit_check || fail
+        broken_link_check || fail
+      fi
+
       if [[ $can_create_cyto == t ]]; then
-        if [[ $trunk_changed == t && -e $cyto_path ]]; then
-          git_commit_check || fail
-        fi
 
         if [[ ! -e $cyto_path ]]; then
           mkdir $cyto_path || fail
@@ -1563,41 +1611,6 @@ load_repo_paths() {
         end_for
       fi
     end_for
-  end_function
-  handle_return
-}
-
-git_commit_check() {
-  begin_function
-
-    local status_file=$status_path/git-commit-when-built \
-      changed=f \
-      module_name=$(realpath $dna_path)
-    module_name=${module_name#/seed/}
-    module_name=${module_name%%/*}
-
-    if ! is_array repo_paths; then
-      load_repo_paths || fail
-    fi
-
-    local repo_path=${repo_paths[$module_name]}
-    local new_hash=$(git -C $repo_path rev-list HEAD --max-count=1) || fail
-
-    if [[ ! -f $status_file ]]; then
-      changed=t
-    else
-      local old_hash=$(<$status_file)
-      if [[ "$old_hash" != "$new_hash" ]]; then
-        changed=t
-      fi
-    fi
-
-    if [[ $changed == t ]]; then
-      rm -rf $cyto_path || fail
-      mkdir -p $status_path || fail
-      echo "$new_hash" >$status_file || fail
-    fi
-
   end_function
   handle_return
 }
@@ -2538,7 +2551,8 @@ for_each_member() {
   local dim=$1 \
     function=$function leave_loop=${leave_loop:-0} \
     fork=${fork:-t} \
-    par=${par:-t}
+    par=${par:-t} \
+    cell_path=${cell_path:-}
 
   member_count=0
   local log_vars='fork par' \
