fix bugs

diff --git a/lib/cell-update b/lib/cell-update
--- a/lib/cell-update
+++ b/lib/cell-update
@@ -208,25 +208,34 @@ begin_function
     values=( ${!dims} )
 
     if [[ ! "${values:-}" ]]; then
-      err "Missing value for dimension $dim"
-      fail
+
+      # see if a default value is defined
+      value= result_var=new_values expand_member || fail
+      if [[ ! "${new_values:-}" ]]; then
+        err "Missing value for dimension $dim"
+        fail
+      fi
+
+    else
+
+      begin_for value in "${values[@]}"; doo
+        value=$value result_var=new_values expand_members || fail
+        if [[ ! "${new_values:-}" ]]; then
+          value=$value result_var=new_values expand_member || fail
+          if [[ ! "${new_values:-}" ]]; then
+            err "Dim $dims has invalid value '$value'"
+            fail
+          fi
+        fi
+      end_for
+
     fi
 
-    begin_for value in "${values[@]}"; doo
-      value=$value result_var=new_values expand_members || fail
-      if [[ ! "${new_values:-}" ]]; then
-        value=$value result_var=new_values expand_member || fail
-        if [[ ! "${new_values:-}" ]]; then
-          err "Dim $dims has invalid value '$value'"
-          fail
-        fi
+    for new_value in $new_values; do
+      if [[ ! $new_value_list =~ \ $new_value\  ]]; then
+        new_value_list+=" $new_value "
       fi
-      for new_value in $new_values; do
-        if [[ ! $new_value_list =~ \ $new_value\  ]]; then
-          new_value_list+=" $new_value "
-        fi
-      done
-    end_for
+    done
 
   else
 
