Make return folder hold files returned by sub cube execution

diff --git a/lib/cell-common b/lib/cell-common
--- a/lib/cell-common
+++ b/lib/cell-common
@@ -215,16 +215,19 @@ begin_function
   fi
 
   if [[ "${save_info_path:-}" ]]; then
+
     local save_info_prefix=${save_info_path##*/}
-    if [[ "${parallel:-f}" == f ]]; then
-      trace -5 "Saving into var: ${save_info_prefix}_id=$cell_id"
-      eval "${save_info_prefix}_id=$cell_id"
-      eval "${save_info_prefix}_path=$current_cube"
-    else
-      trace -5 "Saving into file: $save_info_path ${save_info_prefix}_id=$cell_id"
-      echo "${save_info_prefix}_id=$cell_id" >$save_info_path || fail
-      echo "${save_info_prefix}_path=$current_cube" >>$save_info_path || fail
+    trace -5 "Saving into file: $save_info_path ${save_info_prefix}_id=$cell_id"
+
+    if [[ -e $save_info_path ]]; then
+      err "Save info file already exists: $save_info_path"
+      err "Make sure there this cube ($short_cube) doesn't have a one-to-many dependency."
+      fail
     fi
+
+    echo "${save_info_prefix}_id=$cell_id" >$save_info_path || fail
+    echo "${save_info_prefix}_path=$current_cube" >>$save_info_path || fail
+
   fi
 
 end_function
