.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -3730,10 +3730,18 @@ build_context_leaf() {
       rm $context_path-$context_type.new || fail
     fi
 
-    #local coord_type=branch
 
-    #calc_coordinates || fail
-    #fence
+    # ----------------------------------------------------------------------------------------------------
+    #  MERGE IN
+    # ----------------------------------------------------------------------------------------------------
+    local coord_type=branch
+
+    calc_coordinates || fail
+    fence
+    # ----------------------------------------------------------------------------------------------------
+    #  MERGE IN
+    # ----------------------------------------------------------------------------------------------------
+
 
     # TODO how to resolve leaf dims?
     if [[ "${unknown_dims:-}" ]]; then
@@ -4025,6 +4033,37 @@ for_each_member() {
 
     local dims values=() member_count=0
     get_plural $dim dims
+
+
+    # ----------------------------------------------------------------------------------------------------
+    #  MERGE IN
+    # ----------------------------------------------------------------------------------------------------
+    case $get_members_from in
+      coords)
+        coord_type=branch \
+        fetch_values_from_coordinates $dim || fail
+        if [[ "$values" != *"$NL"* ]]; then
+          sort_array values
+        fi
+      ;;
+      existing_dims)
+        local -n dims_members=d_$dims dim_members=d_$dim
+        values=( "${dims_members[@]:-${dim_members[@]:-}}" )
+      ;;
+      existing_branches)
+        get_members_from_branches || fail
+      ;;
+      *)
+        log_fatal "Internal error: invalid get_members_from value: $get_members_from"
+        fail1
+      ;; 
+    esac
+
+    member_count=${#values[*]}
+    # ----------------------------------------------------------------------------------------------------
+    #  MERGE IN
+    # ----------------------------------------------------------------------------------------------------
+
 
     local -n member=d_$dim members=d_$dims
 
