begin log dup fix

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -1305,14 +1305,14 @@ execute_command_internal() {
 
   local log_vars='cell_path' \
     log_show_vars='short_cell current_command' 
-  begin_function_flat
+  begin_function
 
     if [[ " ${command_history:-}" == *" $current_command $short_cell "* ]]; then
       log_fatal "Circular dependency found: arrived at $current_command $short_cell a second time."
       fail1
     fi
 
-    command_history="${command_history:- }$current_command $short_cell "
+    command_history+="$current_command $short_cell "
 
     case $current_command in
       edit)
@@ -1433,7 +1433,7 @@ execute_command() {
 
   local log_vars='cell_path' \
     log_show_vars='short_cell current_command' 
-  begin_function
+  begin_function_flat
 
     if [[ ! -e "$starting_point" ]]; then
       log_fatal "Folder doesn't exist: $starting_point"
@@ -1732,7 +1732,7 @@ validate_dims() {
         fi
       fi
       if [[ ! "$value" ]]; then
-        log_fatal "Missing require parameter: $dim"
+        log_fatal "Missing required parameter: $dim"
         return 1
       fi
     fi
@@ -3494,7 +3494,7 @@ up_delegate() {
     fi
 
     local out_item
-    out_items=$(find1 $cyto_up_path -not -name ".*") || fail
+    out_items=$(find1 $cyto_up_path/chosen -not -name ".*") || fail
     begin_for out_item in $out_items; doo
       safe_link $out_item $cell_path/ || fail
     end_for
