Add trace_condition

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -1228,7 +1228,7 @@ switch_context() {
       setup_cell_path_vars $cell_path || fail
       init_context || fail
 
-      if [[ $trunk_changed == t && -e $cyto_path ]]; then
+      if [[ $trunk_changed == t && -e $status_path ]]; then
         git_commit_check || fail
         broken_link_check || fail
       fi
@@ -1558,41 +1558,87 @@ execute_command_internal_prep() {
 }
 
 cell_open_log_file() {
-  if [[ "${omni_log_job_id:-0}" != 0 && $disable_log == f ]]; then
-    cell_log_file_stack+=( $logging_to_file )
-    previous_fork_id=$omni_log_fork_id
-    get_new_fork_id || return 1
-    local new_log_file=$log_path/$omni_log_job_id:$new_fork_id.olog
-    local first_log_path=${new_log_file%/*}/first.olog
-    if [[ ! -f $first_log_path ]]; then
-      from_must_exist=f \
-        safe_link $new_log_file $first_log_path || return 1
+  begin_function
+    if [[ ! "${log_path:-}" ]]; then
+      log_fatal "Internal error: log_path should be set at this point"
+      fail1
     fi
-    omni_log_fork_id=$new_fork_id
-    log_function=${FUNCNAME[1]} \
-      change_log_file || return 1
-  fi
+     
+    if [[ "${omni_log_job_id:-0}" != 0 && $disable_log == f ]]; then
+      cell_log_file_stack+=( $logging_to_file )
+      previous_fork_id=$omni_log_fork_id
+      get_new_fork_id || fail
+      local new_log_file=$log_path/$omni_log_job_id:$new_fork_id.olog
+      local first_log_path=${new_log_file%/*}/first.olog
+      if [[ ! -f $first_log_path ]]; then
+        from_must_exist=f \
+          safe_link $new_log_file $first_log_path || fail
+      fi
+      omni_log_fork_id=$new_fork_id
+      log_function=${FUNCNAME[1]} \
+        change_log_file || fail
+    fi
+  end_function
+  handle_return
 }
 
 cell_close_log_file() {
-  if [[ "${cell_log_file_stack:-}" ]]; then
-    local previous_log=${cell_log_file_stack[-1]}
-    omni_log_fork_id=$previous_fork_id
-    unset cell_log_file_stack[-1]
-    log_function=${FUNCNAME[1]} \
-      new_log_file=$previous_log \
-      resume_existing_log=t \
-      logging_to_file= \
-      change_log_file || return 1
-  fi
+  begin_function
+    if [[ "${cell_log_file_stack:-}" ]]; then
+      local previous_log=${cell_log_file_stack[-1]}
+      omni_log_fork_id=$previous_fork_id
+      unset cell_log_file_stack[-1]
+      log_function=${FUNCNAME[1]} \
+        new_log_file=$previous_log \
+        resume_existing_log=t \
+        logging_to_file= \
+        change_log_file || fail
+    fi
+  end_function
+  handle_return
+}
+
+get_job_id() {
+  begin_function
+
+    if [[ ! -v job_id_log ]]; then
+      log_fatal "Internal error: Missing job_id_log"
+      fail1
+    fi
+
+    timeout=5 lock_path=$job_id_log fd_write_lock || {
+      log_fatal "Failed to get lock on $job_id_log" 
+      fail1
+    }
+
+    if [[ -f "$job_id_log" ]]; then
+      local last_id=$(tail -n1 $job_id_log | awk '{print $1}')
+      (( omni_log_job_id = last_id + 1 ))
+    else
+      omni_log_job_id=1
+    fi
+
+    if [[ ! "$command_to_log" ]]; then
+      log_fatal "Missing command to log."
+      fail1
+    fi
+
+    echo "$omni_log_job_id $cell_path $command_to_log" >>$job_id_log || fail
+
+    fd_unlock
+
+  end_function
+  handle_return
 }
 
 execute_command_log_prep() {
   begin_function
+    local cyto_path=$cell_path/.cyto
     if [[ ! -d $cyto_path ]]; then
       mkdir $cyto_path || fail
     fi
 
+    local job_path=$cyto_path/job
     if [[ ! -d $job_path ]]; then
       mkdir $job_path || fail
     fi
@@ -1647,12 +1693,6 @@ execute_command_internal() {
 
     local coordinates=() 
     execute_command_internal_prep || fail
-
-    if [[ $disable_log == t ]]; then
-      log_debug "Logging disabled." || fail
-    else
-      execute_command_log_prep || fail
-    fi
 
     # This is in this function twice, because it changes after switch_context
     if [[ "${localize_dims:-}" ]]; then
@@ -1738,13 +1778,19 @@ execute_command() {
       esac
     fi
 
+    if [[ $disable_log == t ]]; then
+      log_debug "Logging disabled." || fail
+    else
+      execute_command_log_prep || fail
+    fi
+
     local should_fork=t 
     if [[ ${top_level_command:=t} == t ]]; then
       should_fork=f
     elif [[ "$prev_trunk_cell" == "$trunk_cell" ]]; then
       should_fork=f
     fi
-
+    
     if [[ $should_fork == t ]]; then
       fork execute_command_internal || fail_later
     else
@@ -1936,7 +1982,6 @@ fork_inside() {
 
     if [[ $change_log2 == t ]]; then
       previous_log_pos=$omni_log_pos
-      #side_log "begin of fork_inside: previous_log_pos=$previous_log_pos"
       cell_open_log_file || fail
       (( previous_log_pos++ ))
     fi
@@ -2558,39 +2603,6 @@ execute_op() {
       fi
 
     fi
-
-  end_function
-  handle_return
-}
-
-get_job_id() {
-  begin_function
-
-    if [[ ! -v job_id_log ]]; then
-      log_fatal "Internal error: Missing job_id_log"
-      fail1
-    fi
-
-    timeout=5 lock_path=$job_id_log fd_write_lock || {
-      log_fatal "Failed to get lock on $job_id_log" 
-      fail1
-    }
-
-    if [[ -f "$job_id_log" ]]; then
-      local last_id=$(tail -n1 $job_id_log | awk '{print $1}')
-      (( omni_log_job_id = last_id + 1 ))
-    else
-      omni_log_job_id=1
-    fi
-
-    if [[ ! "$command_to_log" ]]; then
-      log_fatal "Missing command to log."
-      fail1
-    fi
-
-    echo "$omni_log_job_id $cell_path $command_to_log" >>$job_id_log || fail
-
-    fd_unlock
 
   end_function
   handle_return
