.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -54,9 +54,7 @@ make_cyto_vars() {
       var=${var_path##*/}
       content=$(<$var_path)
       trim_ws content
-      echo -n "
-local $var=\"$content\"
-" >>$context_path || fail
+      echo "local $var=\"$content\"" >>$context_path || fail
     end_for
   end_function
   handle_return
