Make trace_vars handle arrays better

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -1932,9 +1932,13 @@ execute_command_internal_prep() {
 show_parameter_help() {
   local name=$1
   begin_function
-    out "Parameter: $name"
+
+    local found=f choices=()
+
     begin_for i in ${!parameter_names[*]}; doo
       if [[ "${parameter_names[$i]}" == $name ]]; then
+        out "Parameter: $name"
+
         if [[ -v parameter_descriptions[$i] && "${parameter_descriptions[$i]}" ]]; then
           indent=2 out_wrap "${parameter_descriptions[$i]}"
         fi
@@ -1948,15 +1952,19 @@ show_parameter_help() {
         elif [[ -v ${name}_choices ]]; then
           eval "local -n choices=${name}_choices"
         elif function_exists ${name}_get_choices; then
-          local choices
           ${name}_get_choices || fail
-        else
-          local choices=()
         fi
-
-        choose "Which $name? " $name "${choices[@]}" || fail
+        found=t
       fi
     end_for
+
+    if [[ $found == f ]]; then
+      log_warn "No description found for parameter $name"
+    fi
+
+    #choose "What should $name be set to? " $name "${choices[@]}" || fail
+    choose "$name=" $name "${choices[@]}" || fail
+
   end_function
   handle_return
 }
