Centralizing cyto up/validator/reactor creation

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -6081,141 +6081,6 @@ broken_link_check() {
   handle_return
 }
 
-link_single() {
-  local only_one=${only_one:-f}
-  begin_function
-
-    extract_simple_name choice_name o choice_name
-    local choice_var=${choice_name//-/_}
-
-    if [[ $only_one == t ]]; then
-      local -n choice_path=up_${up_var}_path
-    else
-      local -n choice_path=up_${up_var}_choices_${choice_var}_path
-    fi
-
-    if [[ ! -v choice_path ]]; then
-      log_fatal "Missing choice path var"
-      fail1
-    fi
-
-    if [[ ! -d $choice_path ]]; then
-      log_fatal "Missing choice path"
-      fail1
-    fi
-
-    if [[ $only_one == t ]]; then
-      safe_link $choice_path $dep_path || fail
-    else
-      safe_link $choice_path $dep_path/choices/$choice_name || fail
-    fi
-
-  end_function
-  handle_return
-}
-
-# inputs: dep_path up_name 
-link_choices() {
-  begin_function
-    local choice_var choice_name o
-    begin_for choice_name in ${choices[*]}; doo
-      link_single || fail
-    end_for
-  end_function
-  handle_return
-}
-
-make_cyto_reactors() {
-  begin_function
-    mkdir $reactor_path || fail
-    local reactor_name
-    for reactor_name in ${reactors[*]}; do
-      local dep_path=$reactor_path/$reactor_name \
-        reactor_var=${reactor_name//-/_}
-      local -n path=reactors_${reactor_var}_path
-      if [[ ! -v path ]]; then
-        log_fatal "Missing reactor path var"
-        fail1
-      fi
-      if [[ ! -d $path ]]; then
-        log_fatal "Missing reactor path"
-        fail1
-      fi
-      safe_link $path $dep_path || fail
-    done; maybe_break
-  end_function
-  handle_return
-}
-
-make_cyto_up_single() {
-  local up_name=$1
-  begin_function
-    local dep_path=$up_path/$up_name \
-      up_var
-    local up_var=${up_name//-/_}
-    local -n choices=up_${up_var}_choices
-    if [[ -v choices ]]; then
-      mkdir -p $dep_path/choices || fail
-      link_choices || fail
-    else
-      local choice_name=$up_name
-      if [[ -d $dep_path ]]; then
-        rm -rf $dep_path || fail
-      fi
-      only_one=t link_single || fail
-    fi
-  end_function
-  handle_return
-}
-
-make_cyto_up() {
-  begin_function
-    if [[ ! -e $up_path ]]; then
-      mkdir $up_path || fail
-    fi
-    local up_name o
-    begin_for up_name in ${up[*]}; doo
-      make_cyto_up_single $up_name || fail
-    end_for
-  end_function
-  handle_return
-}
-
-make_cyto_validator_single() {
-  local validator_name=$1
-  begin_function
-
-    local validator_var=${validator_name//-/_} \
-      dep_path \
-
-    validator_var=${validator_var%%,*}
-    validator_var=${validator_var%%:*}
-    dep_path=$validator_path/$validator_var \
-
-    if [[ -d $dep_path ]]; then
-      rm -rf $dep_path || fail
-    fi
-
-    local -n choice_path=validator_${validator_var}_path
-    safe_link $choice_path $dep_path || fail
-
-  end_function
-  handle_return
-}
-
-make_cyto_validator() {
-  begin_function
-    if [[ ! -e $validator_path ]]; then
-      mkdir $validator_path || fail
-    fi
-    local validator_name o
-    begin_for validator_name in ${validator[*]}; doo
-      make_cyto_validator_single $validator_name || fail
-    end_for
-  end_function
-  handle_return
-}
-
 get_required_freshness() {
   required_freshness=${fresh:-${default_freshness:-}}
 
@@ -6397,6 +6262,81 @@ load_post_context_dynamic_vars() {
   handle_return
 }
 
+link_single() {
+  local only_one=${only_one:-f}
+  begin_function
+
+    extract_simple_name choice_name o choice_name
+    local choice_var=${choice_name//-/_}
+
+    if [[ $only_one == t ]]; then
+      local -n choice_path=up_${up_var}_path
+    else
+      local -n choice_path=up_${up_var}_choices_${choice_var}_path
+    fi
+
+    if [[ ! -v choice_path ]]; then
+      log_fatal "Missing choice path var"
+      fail1
+    fi
+
+    if [[ ! -d $choice_path ]]; then
+      log_fatal "Missing choice path"
+      fail1
+    fi
+
+    if [[ $only_one == t ]]; then
+      safe_link $choice_path $dep_path || fail
+    else
+      safe_link $choice_path $dep_path/choices/$choice_name || fail
+    fi
+
+  end_function
+  handle_return
+}
+
+# input: 
+#   up_cell_type
+#   up_name
+make_cyto_up() {
+  begin_function
+
+    local dep_path=$cyto_path/$up_cell_type/$up_name \
+      up_var=${up_name//-/_} \
+      only_one=t \
+      choice_name=$up_name \
+
+    if [[ -d $dep_path ]]; then
+      rm -rf $dep_path || fail
+    fi
+
+    local -n choices=up_${up_var}_choices
+
+    if [[ -v choices ]]; then
+      local choice_count=${#choices[*]}
+
+      if (( choice_count == 1 )); then
+        choice_name=$up_name \
+        link_single || fail
+      elif (( choice_count == 0 )); then
+        log_fatal "$up_cell_type cell has no choices."
+        fail1
+      else
+        local choice_path=$cyto_path/$up_cell_type-choices choice_name
+        mkdir -p $choice_path || fail
+        begin_for choice_name in ${choices[*]}; doo
+          link_single || fail
+        end_for
+      fi
+
+    else
+      link_single || fail
+    fi
+
+  end_function
+  handle_return
+}
+
 build_cyto() {
   local cell_path=$1
 
@@ -6414,8 +6354,6 @@ build_cyto() {
       mkdir $status_path || fail
     fi
 
-    #  This already happened earlier
-    #init_context || fail
     load_branch_info || fail
     find_seed_path $cell_path || fail
 
@@ -6424,17 +6362,17 @@ build_cyto() {
     fi
 
     if [[ $cell_is_leaf == t ]]; then
-      if [[ "${up:-}" && ! -d $up_path ]]; then
-        make_cyto_up || fail
-      fi
 
-      if [[ "${validator:-}" && ! -d $validator_path ]]; then
-        make_cyto_validator || fail
-      fi
+      local up_cell_type up_name
+      begin_for up_cell_type in up validator reactor; doo
+        local -n upstream_var=$up_cell_type
+        if [[ -v upstream_var ]]; then
+          begin_for up_name in ${upstream_var[*]}; doo
+            make_cyto_up
+          end_for
+        fi
+      end_for
 
-      if [[ "${reactors:-}" && ! -d $reactor_path ]]; then
-        make_cyto_reactors || fail
-      fi
     fi
 
   end_function
