Make bash-debugger more portable

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -1580,9 +1580,7 @@ execute_command() {
       ;;
     esac
 
-    if [[ $top_level_command == f ]]; then
-      strong_log=t log_info "Executing cell command: $short_cell $cell_command" || fail
-    fi
+    strong_log=t log_verbose "Executing cell command: $short_cell $cell_command" || fail
 
     if [[ ! -e "$cell_path" ]]; then
       plant_seed $cell_path || {
