.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -226,25 +226,43 @@ load_arr_to_code() {
   handle_return
 }
 
-load_derive_table_make_index() {
+# inputs:
+#   table     name of table variable prefix
+# outputs:
+#   ${table}_index_${field}   map of field value to spaced array of row indexes
+make_table_index() {
 
-  local values
+  local table=$table
+  local row_index \
+    field_index \
+    data_offset \
+    field \
+    value \
+    values \
+    row_count \
+
+  local -n table_fields=${table}_fields \
+    table_data=${table}_data \
+
+  local \
+    field_count=${#table_fields[*]} \
+    data_count=${#table_data[*]} \
+
+  (( row_count = data_count / field_count ))
 
   for (( field_index = 0; field_index < field_count; field_index++ )); do
 
-    field=${derive_table_fields[$field_index]}
-    local -n index=derive_table_${name}_index_${field}
+    field=${table_fields[$field_index]}
+    local -n index=${table}_index_${field}
 
     if [[ ! -v index[*] ]]; then
-      eval "declare -gA derive_table_${name}_index_${field}=()"
+      eval "declare -gA ${table}_index_${field}=()"
     fi
 
     for (( row_index = 0; row_index < row_count; row_index++ )); do
 
-      fence_zombie
-
       (( data_offset = row_index * field_count + field_index ))
-      value=${derive_table_data[$data_offset]}
+      value=${table_data[$data_offset]}
 
       if [[ -v all_dims[$field] ]]; then
         values=()
@@ -267,6 +285,8 @@ load_derive_table_make_index() {
 }
 
 load_derive_table_card_and_cross() {
+
+  local field_index field
 
   for (( field_index = 0; field_index < field_count; field_index++ )); do
 
@@ -309,19 +329,22 @@ load_derive_table() {
 
   if [[ ! -v derive_table_data ]]; then
 
-    log_verbose "Loading derive table $name"
+    log_debug "Loading derive table $name"
     local -n dtp=derive_table_${name}_path \
       derive_table_fields=derive_table_${name}_fields \
 
     load_dna_tab $dtp derive_table_$name || fail
 
-    local row_index field_index row_count field_count data_count data_offset field value
+    local row_count field_count data_count
     field_count=${#derive_table_fields[*]}
     data_count=${#derive_table_data[*]}
     (( row_count = data_count / field_count ))
 
-    load_derive_table_make_index || fail
+    table=derive_table_${name} \
+    make_table_index || fail
+
     fence_grip
+
     load_derive_table_card_and_cross || fail
 
   fi
@@ -921,7 +944,28 @@ write_coordinates_to_shell_file() {
 
     done
 
-    echo ")" >>$target_file || fail
+    echo ")$NL" >>$target_file || fail
+
+    for (( field_index = 0; field_index < c_fields_count; field_index++ )); do
+
+      field=${c_fields[$field_index]}
+      local -n table_index=${coord_type}_coordinate_index_${field}
+      if [[ ! -v table_index[*] ]]; then
+        log_fatal "Internal error: Missing index ${coord_type}_coordinate_index_${field}"
+        fail1
+      fi
+
+      echo "declare -Ag ${coord_type}_coordinate_index_${field}=(" >>$target_file || fail
+
+      local k v
+      for k in "${!table_index[@]}"; do
+        v=${table_index[$k]}
+        echo "  ['$k']='$v'" >>$target_file || fail
+      done
+
+      echo ")$NL" >>$target_file || fail
+
+    done
 
   end_function
   handle_return
@@ -4517,6 +4561,11 @@ build_context() {
       coord_type=branch \
       target_form=seed \
       calc_coordinates || fail
+
+      fence
+
+      table=branch_coordinate \
+      make_table_index || fail
 
       fence
 
