.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -3841,9 +3841,9 @@ plant_seed_internal() {
   local from=$1 to=$2 contents x x_part deep=${deep:-t} plant_branches=${plant_branches:-f}
   begin_function
 
-    log_verbose "Planting seed from $from to $to" || fail
-
     if [[ ! -d $to ]]; then
+
+      log_verbose "Planting seed from $from to $to" || fail
 
       if [[ $from == /seed/* && -d $from ]]; then
         plant_seed_internal ${from%/*} ${to%/*} || fail
