.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -2318,12 +2318,12 @@ decrypt_file() {
 				fail1
 			fi
 			setup_tmp_path || fail
-			if ! log_and_run openssl pkeyutl -decrypt -inkey $key -in $from -out $to; then
+			if ! openssl pkeyutl -decrypt -inkey $key -in $from -out $to; then
 				log_fatal "Failed to decrypt file: $from"
 				fail1
 			fi
 		else
-			if ! log_and_run openssl pkeyutl -decrypt -inkey $key -in $from; then
+			if ! openssl pkeyutl -decrypt -inkey $key -in $from; then
 				log_fatal "Failed to decrypt file: $from"
 				fail1
 			fi
@@ -3266,8 +3266,7 @@ from_background_shell() {
 
   local -n to=$to_var
 
-  local log_show_vars='pipe' \
-    log_vars='timeout stop_after fail_after interact'
+  local log_vars='pipe timeout stop_after fail_after interact'
   begin_function
 
     timed_out=f
