.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -296,6 +296,19 @@ load_tab() {
   handle_return
 }
 
+load_auto() {
+
+  begin_function
+    local full_path=$1 content name=$2 append=f
+
+    local tmp_table tmp_fields
+    load_tab $realpath tmp_table || fail
+#    begin_for 
+
+  end_function
+  handle_return
+}
+
 make_or_load_dna_item() {
   begin_function
     local var_full_path=$1 prefix=${prefix:-} \
@@ -343,6 +356,12 @@ make_or_load_dna_item() {
           fail1
         }
         load_type=fun
+      ;;
+      auto)
+        load_auto $var_full_path $item_name || {
+          log_fatal "Failed to load auto variable from $var_full_path"
+          fail1
+        }
       ;;
       *)
         log_fatal "Unknown dna object: $item."
@@ -1544,11 +1563,11 @@ execute_command_internal() {
 
     command_history+="$current_command $short_cell "
 
-    # if [[ ${cell_is_leaf:-t} == t || $show_branches == t ]]; then
-    #   log_info "Executing cell command: $short_cell $current_command"
-    # else
+    if [[ ${cell_is_leaf:-t} == t || $show_branches == t ]]; then
+      log_info "Executing cell command: $short_cell $current_command"
+    else
       log_verbose "Executing cell command: $short_cell $current_command" || fail
-    # fi
+    fi
 
     if [[ -f $command_path.info ]]; then
       execute_command_internal_setup_params || fail
