.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -4664,17 +4664,17 @@ build_constellation_table_handle_tab() {
     if [[ $current_dim == $first_field ]]; then
 
       local field
-      for field in ${table_fields[*]:1}; do
+      begin_for field in ${table_fields[*]:1}; doo
         if [[ ! -v current_dim_values[$field] ]]; then
-          return
+          abort
         fi
-      done
+      end_for
       build_constellation_table_handle_tab_reverse || fail
 
     else
 
       if [[ ! -v current_dim_values[$first_field] ]]; then
-        return
+        abort
       fi
       build_constellation_table_handle_tab_forward || fail
 
@@ -4966,17 +4966,30 @@ set_cross_dims() {
 #   current_dim_values (set)
 #   con_table_fields
 #   con_table_data
+#   current_dim
 # outputs:
 #   con_table_fields
 #   con_table_data
 build_constellation_table() {
   local field_index=$field_index con=$con \
-    interesting_vars='con field_index' \
+    interesting_vars='con field_index member' \
+    member=${member:-} \
 
   local -I current_dim_values \
     current_row \
 
   begin_function
+    if [[ "$member" ]]; then
+      current_row+=( "$member" )
+      current_dim_values[$current_dim]=$member
+
+      # takes from the callers current_dim before it is localized here
+      dim=$current_dim \
+      set_dims_directly=f \
+      allow_dims=${con_table_fields[*]} \
+      set_cross_dims || fail
+    fi
+
     if (( field_index + 1 > field_count )); then
       log_debug "Wrote constellation row: ${current_row[@]}"
       con_table_data+=( "${current_row[@]}" )
@@ -4999,55 +5012,44 @@ build_constellation_table() {
       array_to_set current_dim_members dim_members
     else # $dim_index > 0
       # loop over all derive tools related to the current dim
-      local -n narrowed_from=dim_${current_dim}_narrowed_from
-      local row tool row_array tool_dims
+      local -n derived_from=dim_${current_dim}_derived_from
+      local row tool row_array tool_dims tool_valid
       local -A tool_possibilities=()
 
-      begin_for row in "${narrowed_from[@]}"; doo
+      begin_for row in "${derived_from[@]}"; doo
         row_array=( $row )
         tool=${row_array[0]}
         interesting_vars+=' tool'
         tool_possibilities=()
         tool_dims=${row_array[1]}
         tool_dims=${tool_dims//,/ }
+        tool_valid=f
 
         if [[ $tool == *.tab ]]; then
           build_constellation_table_handle_tab || fail
         elif [[ $tool == *.fun ]]; then
           build_constellation_table_handle_fun || fail
         else
-          log_fatal "Unknown tool: $tool in narrowed_from of $current_dim"
+          log_fatal "Unknown tool type: $tool in derived_from of $current_dim"
           fail1
         fi
 
-        if [[ ! "${tool_possibilities:-}" ]]; then
-          continue
+        if [[ $tool_valid == t ]]; then
+          intersect_with_all dim_members tool_possibilities dim_members
+          if (( ${#dim_members[*]} == 0 )); then
+            log_debug "Row invalidated by tool: $tool"
+            abort
+          fi
         fi
 
-        intersect_with_all dim_members tool_possibilities dim_members
       end_for
 
     fi
     
-    #if (( ${#dim_members[*]} == 0 )) && [[ "${current_dim_members:-}" ]]; then
-    #  # TODO what if the tools conflict?
-    #  array_to_set current_dim_members dim_members
-    #fi
-
     if (( ${#dim_members[*]} == 0 )); then
-      current_row+=( "none" )
-      current_dim_values[$current_dim]=none
-      field_index=$((field_index+1)) build_constellation_table || fail
+      log_debug "No tools found which can be used to derive $current_dim in this row"
     else
       begin_for member in "${!dim_members[@]}"; doo
-        current_row+=( "$member" )
-        current_dim_values[$current_dim]=$member
-
-        dim=$current_dim \
-        set_dims_directly=f \
-        allow_dims=${con_table_fields[*]} \
-        set_cross_dims || fail
-
         field_index=$((field_index+1)) build_constellation_table || fail
       end_for
     fi
@@ -5252,6 +5254,8 @@ rename_constellation() {
       fi
     done
 
+    log_debug "Renamed constellation $from_con to $to_con"
+
   end_function
   handle_return
 }
@@ -5302,7 +5306,8 @@ make_derive_cache_constellation() {
 
       fi
 
-      field_index=0 build_constellation_table || fail
+      log_debug "Building constellation table for $con"
+      field_index=0 member= build_constellation_table || fail
       write_vars_to_context con_${con}_table_fields con_${con}_table_data || fail
     fi
   end_function
