.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -2359,16 +2359,24 @@ fetch_values_from_coordinates2_row() {
     target_dim_var_type=ddim \
     convert_table_to_dims || fail
 
-    local -A derive_tried=()
-    value_found=f
-    skip_dims= \
-    attempt_derive || fail
-
-    if [[ $value_found == t ]]; then
-      new_values+=( "${values[@]}" )
+    local -n ddim=d_$dim
+    if [[ -v ddim ]]; then
+      new_values[$ddim]=1
     else
-      log_fatal "Could not extract dim $dim from ${coord_type}_coordinate table at row $row_index"
-      fail1
+      #local -A derive_tried=()
+      #value_found=f
+      #skip_dims= \
+      #attempt_derive || fail
+
+      #if [[ $value_found == t ]]; then
+      #  local value
+      #  for value in "${values[@]}"; do
+      #    new_values[$value]=1
+      #  done
+      #else
+        log_fatal "Could not extract dim $dim from ${coord_type}_coordinate table at row $row_index"
+        fail1
+      #fi
     fi
 
   end_function
@@ -2381,15 +2389,17 @@ fetch_values_from_coordinates2() {
     local -n table_data=${table_var}_data
     local data_count=${#table_data[*]} \
       field_count=${#table_fields[*]} \
-      new_values=() \
       value_found \
+
+    local -A new_values=()
 
     local row_count=$(( data_count / field_count ))
     for (( row_index = 0; row_index < row_count; row_index++ )); do
       fetch_values_from_coordinates2_row || fail
     done
 
-    values=( "${new_values[@]}" )
+    values=( "${!new_values[@]}" )
+    sort_array values
 
   end_function
   handle_return
