.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -1406,13 +1406,14 @@ get_plural() {
   return 0
 }
 
-switch_context_prep_dims() {
+prep_dims() {
+  local dim_types=$*
   begin_function
 
     localize_dims=local
     localize_reverse_dims=local
     local dim_var dim_type dims_var
-    begin_for dim_type in trunk_dims sub_dims control_props data_props; doo
+    begin_for dim_type in $dim_types; doo
       local -n dim_array=$dim_type
       local -n plural_array=${dim_type}_plural
       plural_array=()
@@ -1489,7 +1490,7 @@ expand_dim() {
 #   $*           members to expand
 # outputs:
 #   new_values   array of expanded members
-expand_dims() {
+expand_dim_members() {
   begin_function
     local value
     new_values=()
@@ -1503,7 +1504,7 @@ expand_dims() {
 
 # expands aliases for the known dims array
 # collapses singular and plural dims into plural dims
-switch_context_expand_dims() {
+expand_dims() {
   begin_function
 
     local dim_var plural dim_type
@@ -1530,7 +1531,7 @@ switch_context_expand_dims() {
         ddims=
 
         local value new_values
-        expand_dims "$members" || fail
+        expand_dim_members $members || fail
 
         if [[ $single == t ]]; then
           if (( ${#new_values[*]} > 1 )); then
@@ -1804,7 +1805,7 @@ calc_coordinates_next_unknown_dim() {
 
           # don't support aliases here (yet?)
           # local new_values
-          # expand_dims "${values[@]}" || fail
+          # expand_dim_members "${values[@]}" || fail
 
           members=( "${values[@]}" )
 
@@ -2108,10 +2109,10 @@ setup_dims() {
     local known_dims=()
     local missing_dims=()
 
-    switch_context_prep_dims || fail
+    prep_dims trunk_dims || fail
 
     if [[ "${known_dims:-}" ]]; then
-      switch_context_expand_dims || fail
+      expand_dims || fail
     fi
 
     if [[ $cell_is_leaf == t ]]; then
