.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -2583,6 +2583,64 @@ load_child_dims() {
   handle_return
 }
 
+set_dim_defaults() {
+  local default_value=$1; shift
+  local dims=$*
+
+  begin_function
+    local dim dims problem values
+    get_plural $dim dims
+    for dim in $dims; do
+      local -n ddim=d_$dim \
+        ddims=d_$dims \
+
+      # if function_exists dim_${dim}_default; then
+      #   dim_${dim}_default || fail
+
+      #   if [[ " $trace_dims " == *" $dim "* && "$values" ]]; then
+      #     var=values \
+      #     show_trace_dim_message "Default value taken from default function: dim_${dim}_default"
+      #   fi
+
+      # fi
+
+      # if [[ ! "${values:-}" ]] && function_exists dim_${dim}_expand; then
+      #   value= dim_${dim}_expand || fail
+
+      #   if [[ " $trace_dims " == *" $dim "* && "$values" ]]; then
+      #     if [[ -v dim_${dim}_default ]]; then
+      #       var=values \
+      #       show_trace_dim_message "Default value taken from default value: dim_${dim}_default"
+      #     else
+      #       var=values \
+      #       show_trace_dim_message "Default value taken from expand function: dim_${dim}_expand"
+      #     fi
+      #   fi
+
+      # fi
+
+      # if [[ "${values:-}" == ask ]]; then
+      #   read_dim values || fail
+      # fi
+
+      if [[ ! "${values:-}" ]]; then
+
+        if [[ " $optional_dims " == *" $dim "* ]]; then
+          values=( $empty_member )
+        elif [[ $dim_type == trunk_dims ]]; then
+          # not sure if we should do this
+          :
+        else
+          values=( all )
+        fi
+
+      fi
+
+    done
+  end_function
+  handle_return
+}
+
 setup_dims() {
   begin_function
 
@@ -2594,6 +2652,9 @@ setup_dims() {
     else
       expand_dims ${trunk_dims_expanded[*]:-} ${support_dims_expanded[*]:-} || fail
     fi
+
+    #set_dim_defaults none "${trunk_dims_expanded[*]}" || fail
+    #set_dim_defaults all "${support_dims_expanded[*]}" || fail
 
   end_function
   handle_return
@@ -3920,48 +3981,6 @@ attempt_default() {
   local dim=$1
   begin_function_lo
 
-    local problem
-    local -n dim_type=dim_${dim}_type
-
-    if function_exists dim_${dim}_default; then
-      dim_${dim}_default || fail
-
-      if [[ " $trace_dims " == *" $dim "* && "$values" ]]; then
-        var=values \
-        show_trace_dim_message "Default value taken from default function: dim_${dim}_default"
-      fi
-
-    fi
-
-    if [[ ! "${values:-}" ]] && function_exists dim_${dim}_expand; then
-      value= dim_${dim}_expand || fail
-      already_expanded=t
-
-      if [[ " $trace_dims " == *" $dim "* && "$values" ]]; then
-        if [[ -v dim_${dim}_default ]]; then
-          var=values \
-          show_trace_dim_message "Default value taken from default value: dim_${dim}_default"
-        else
-          var=values \
-          show_trace_dim_message "Default value taken from expand function: dim_${dim}_expand"
-        fi
-      fi
-
-    fi
-
-    if [[ "${values:-}" == ask ]]; then
-      read_dim values || fail
-      already_expanded=t
-    fi
-
-    if [[ ! "${values:-}" ]]; then
-
-      if [[ " $optional_dims " == *" $dim "* ]]; then
-        values=( $empty_member )
-      fi
-      already_expanded=t
-
-    fi
 
   end_function
   handle_return
