Fix required parameter bug

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -826,11 +826,7 @@ begin_function_flat
       local old_from=$from
       from=$from/.dim/$sane_value
       if [[ ! -d $from ]]; then
-        (
-        # recursive
-        cell=$old_from cell_context_load && \
-        create_sub_cell $from
-        ) || fail
+        ( load_context_and_create_sub $old_from $from ) || fail
       fi
     else
       break
@@ -839,6 +835,17 @@ begin_function_flat
   end_for
 end_function_flat
 handle_return
+}
+
+load_context_and_create_sub() {
+local parent_cell=$1 sub_cell=$2
+# recursive
+cell=$parent_cell cell_context_load || return 1
+if [[ "$localize_dim_vars" != local ]]; then
+  eval "$localize_dim_vars" || return 1
+fi
+create_sub_cell $sub_cell || return 1
+return 0
 }
 
 get_dep_member() {
@@ -876,13 +883,18 @@ end_for
 }
 
 append_dim_var_to_context() {
-local context_dim=$1
+local dim=$1
 begin_function_flat
-  context_dim=${context_dim##*/}
-  context_dim=${context_dim#*-}
-  local ddim=d_$context_dim
+  dim=${dim##*/}
+  dim=${dim#*-}
+
+  local plural
+  get_plural $dim
+  local dims=$plural
+  local ddim=d_$dim ddims=d_$dims
+
   if [[ ! -v $ddim ]]; then
-    fatal "Internal error: While trying to create a branch sub cell, required dim value $context_dim is missing."
+    fatal "Internal error: While trying to create a branch sub cell, required dim value $dim is missing."
     fail1
   fi
   local value=${!ddim}
@@ -891,7 +903,7 @@ begin_function_flat
   fi
   echo "# Generated by create_sub_branch from $cell_path
 $ddim='$value'
-localize_dim_vars+=' $ddim=\${$ddim:-\${$context_dim:-}}'" >$sub_dna_path/context-before || fail
+localize_dim_vars+=' $ddim=\${$ddim:-\${$dim:-}} $ddims=\${$ddims:-\${$dims:-\${$ddim:-\${$dim:-}}}}'" >$sub_dna_path/context-before || fail
 end_function_flat
 handle_return
 }
@@ -1365,7 +1377,10 @@ validate_dims() {
 local dim
 for dim in ${leaf_dims[*]} ${sub_dims[*]} ${props[*]}; do
   if dim_is_required $dim; then
-    if [[ ! -v d_$dim && ! -v d_${dim}s ]]; then
+    local plural
+    get_plural $dim
+    eval "local value=\${d_$plural:-\${$plural:-\${d_$dim:-\${$dim}}}}"
+    if [[ ! "$value" ]]; then
       fatal "Missing require parameter: $dim"
       return 1
     fi
@@ -2454,45 +2469,47 @@ load_props $cell/.dna/leaf/prop || return 1
 }
 
 load_dims() {
-local dim_path=$1 dim dim_var dim_var_plural 
-dims=()
-if [[ -d $dim_path ]]; then
-  debug "Loading dims from $dim_path"
-  local contents=$(find1 $dim_path -not -name ".*" | sort -g) || return 1
-  for dim in $contents; do
-    source $dim || return 1
-    dim_var=${dim##*/}
-    if [[ $dim_var =~ [0-9]+-(.*) ]]; then
-      dim_var=${BASH_REMATCH[1]}
+local dims_path=$1 dim_path dim 
+dim_array=()
+if [[ -d $dims_path ]]; then
+  debug "Loading dims from $dims_path"
+  local contents=$(find1 $dims_path -not -name ".*" | sort -g) || return 1
+  for dim_path in $contents; do
+    source $dim_path || return 1
+    dim=${dim_path##*/}
+    if [[ $dim =~ [0-9]+-(.*) ]]; then
+      dim=${BASH_REMATCH[1]}
     fi
-    dim_var_plural=${dim_var}s
-    dims+=( $dim_var )
-    eval "d_$dim_var=\${d_$dim_var:-\${$dim_var:-}} d_$dim_var_plural=\${d_$dim_var_plural:-\${$dim_var_plural:-}}"
-    localize_dim_vars+=" d_$dim_var=\${d_$dim_var:-\${$dim_var:-}} d_$dim_var_plural=\${d_$dim_var_plural:-\${$dim_var_plural:-}}"
+    get_plural $dim
+    dims=$plural
+    local ddim=d_$dim ddims=d_$dims
+    dim_array+=( $dim )
+    localize_dim_vars+=" $ddim=\${$ddim:-\${$dim:-}} $ddims=\${$ddims:-\${$dims:-\${$ddim:-\${$dim:-}}}}"
   done
 fi
+dims=( ${dim_array[*]} )
 }
 
 load_props() {
-local prop_path=$1 dim dim_var
+local prop_path=$1 dim_path dim
 if [[ -d $prop_path ]]; then
   local contents=$(find1 $prop_path -not -name ".*" | sort -g) || return 1
-  for dim in $contents; do
-    source $dim || return 1
-    dim_var=${dim##*/}
-    if [[ $dim_var =~ [0-9]+-(.*) ]]; then
-      dim_var=${BASH_REMATCH[1]}
+  for dim_path in $contents; do
+    source $dim_path || return 1
+    dim=${dim_path##*/}
+    if [[ $dim =~ [0-9]+-(.*) ]]; then
+      dim=${BASH_REMATCH[1]}
     fi
-    props+=( $dim_var )
+    props+=( $dim )
 
     local value= values=
-    if [[ -v $dim_var ]]; then
-      value=${!dim_var}
+    if [[ -v $dim ]]; then
+      value=${!dim}
       if [[ $value == $empty_member ]]; then
         value=
       fi
     fi
-    local f=${dim_var}_member_expand 
+    local f=${dim}_member_expand 
     if type -t $f &>/dev/null; then
       $f || true
     fi
@@ -2500,10 +2517,25 @@ if [[ -d $prop_path ]]; then
       value=$values
     fi
 
-    eval "d_$dim_var=$value"
-    localize_dim_vars+=" d_$dim_var=\${d_$dim_var:-\${$dim_var:-}"
+    eval "$dim=\$value" || return 1
+
+    get_plural $dim
+    local dims=$plural
+    local ddim=d_$dim ddims=d_$dims
+
+    localize_dim_vars+=" $ddim=\${$ddim:-\${$dim:-}} $ddims=\${$ddims:-\${$dims:-\${$ddim:-\${$dim:-}}}}"
   done
 fi
+}
+
+get_plural() {
+local dim=$1
+if [[ ${dim%s} != $dim ]]; then
+  plural=${dim}es
+else
+  plural=${dim}s
+fi
+return 0
 }
 
 dim_is_required() {
