.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -308,8 +308,8 @@ load_derive_table_card_and_cross() {
 
     local card=${#index[*]}
     if (( card == row_count )); then
-      local -n cross_dim_tables=dim_${field}_cross_dim_tables
-      cross_dim_tables+="$name "
+      local -n key_tables=dim_${field}_key_tables
+      key_tables+="$name "
     fi
 
     local -n card_table=dim_${field}_card_table
@@ -326,6 +326,326 @@ load_derive_table_card_and_cross() {
 
   done
 
+}
+
+init_context() {
+  begin_function
+
+    # required_freshness:
+    #   inf means infinite (never refresh based on time). 30s means refresh if it is older than 30 seconds.
+    #   1w means refresh if it's older than a week.
+    # shuffle_chance:
+    #   chance out of 1000 of not following the computed strategy order
+    # min_pause:
+    #   number of ms to wait between cycles
+    #   this number doubles each time there is nothing to do, until it reaches max_pause
+    # reuse_existing_out:
+    #   if set to t: 
+    #   new output folder won't be created when updating, but the existing one will be used
+    #   should set to true when creating a new output folder would be expensive
+    #   these cells must detect for themselves whether a change has happened in an
+    #     update and set something_changed=t accordingly. 
+
+    # need to make sure that expand functions don't bleed into sub command execution
+
+    unset ${!dim_*} \
+      ${!derive_table*} \
+      ${!branch_coordinate_*} \
+      ${!leaf_coordinate_*} \
+      ${!sub_coordinate_*} \
+      ${!tree_coordinate_*} \
+
+    declare -Ag all_dims=()
+
+    auto_loads=() \
+    cell_expiration= \
+    cell_is_outdated=t \
+    check_op_var=f \
+    child_dims=() \
+    control_props=() \
+    control_props_short=() \
+    current_pause=250 \
+    data_props=() \
+    data_props_short=() \
+    default_anchor_dims= \
+    default_freshness= \
+    default_strategies=crl \
+    derive_caches= \
+    dna_up_files=() \
+    implicit_dims=() \
+    key_path= \
+    localize_dims= \
+    localize_reverse_dims= \
+    lock_timeout=2 \
+    max_attempts=1 \
+    max_pause=60000 \
+    min_pause=250 \
+    optional_dims= \
+    out_file= \
+    out_path= \
+    post_validate=f \
+    pre_validate=f \
+    refresh_less_than=${refresh_less_than:-1} \
+    retry_delay=1 \
+    retry_delay_max=10 \
+    retry_scale=2 \
+    reuse_existing_out=t \
+    shuffle_chance=100 \
+    sub_dims=() \
+    sub_dims_short=() \
+    support_dims=() \
+    support_dims_short=() \
+    trunk_dims=() \
+    trunk_dims_short=() \
+    up=() \
+    update_cost=1 \
+    update_risk=3 \
+
+    unset \
+      check_op \
+      update_op \
+      get_op \
+      aggregate_op \
+
+    context_path=$cyto_path/context \
+    dna_key_path=$dna_path/key \
+    down_path=$cyto_path/down \
+    job_path=$cyto_path/job \
+    key_path=$cyto_path/key \
+    req_path=$cyto_path/req \
+    status_path=$cyto_path/status \
+    tmp_path=$cyto_path/tmp \
+    up_path=$cyto_path/up \
+    up_chosen_path=$cyto_path/up-chosen \
+    reactor_path=$cyto_path/reactors \
+
+    lock_path=$context_path \
+    replay_path=$job_path/pipe_replay \
+
+  end_function
+  handle_return
+}
+
+setup_cell_paths() {
+  dna_path=$cell_path/.dna
+  cyto_path=$cell_path/.cyto
+  init_context
+}
+
+branch_local_vars='branch_dims branch_members branch_hashes branch_dim_count trunk_cell short_cell prev_branch_info_cell'
+load_branch_info() {
+  local cell_path=${1:-$cell_path}
+
+  begin_function
+
+    if [[ "${prev_branch_info_cell:-}" == $cell_path ]]; then
+      # already loaded
+      abort
+    fi
+    prev_branch_info_cell=$cell_path
+
+    branch_dims=() \
+    branch_members=() \
+    branch_hashes=() \
+
+    local c=$cell_path p d m
+    while [[ $c == *:* ]]; do
+      p=${c##*/}
+      if [[ $p == *:* ]]; then
+
+        d=${p%%:*}
+
+        if [[ " ${branch_dims[*]} " == *" $d "* ]]; then
+          log_fatal "Duplicate branch dim found: $d in $cell_path"
+          fail1
+        fi
+
+        branch_dims=( $d ${branch_dims[*]} )
+
+        m=${p#*:}
+        branch_hashes=( $m ${branch_hashes[*]} )
+
+        local member_var_path=$c/.member
+        if [[ -f $member_var_path ]]; then
+          IFS= read -r -d '' m <$member_var_path
+        fi
+        branch_members=( "$m" "${branch_members[@]}" )
+
+        local -n ddim=d_$d idim=i_$d
+        ddim=$m
+        idim=$m
+
+      fi
+      c=${c%/*}
+    done
+
+    trunk_cell=$c
+    branch_dim_count=${#branch_dims[*]}
+
+    if (( branch_dim_count > 0 )); then
+      cell_is_trunk=f
+    else
+      cell_is_trunk=t
+    fi
+
+    if [[ "${branch_dims:-}" ]]; then
+      log_debug "Branch dims found: ${branch_dims[*]}"
+    fi
+
+    local x y dim_string= 
+    if [[ "${branch_hashes:-}" ]]; then
+      dim_string="${branch_hashes[*]}"
+      dim_string=:${dim_string// /\/}
+    fi
+    local short_trunk=${trunk_cell#/*/*/}
+
+  end_function
+  handle_return
+}
+
+execute_command_prep() {
+  begin_function
+
+    get_short_cell
+    load_branch_info || fail
+
+    trunk_changed=f
+    if [[ $trunk_cell != "${previous_trunk:-}" ]]; then
+      trunk_changed=t
+      previous_trunk=$trunk_cell
+    fi
+
+    setup_cell_paths
+
+    unset default_anchor_dims
+    if [[ $top_level_command == f ]]; then
+      anchor_dims=
+    fi
+
+  end_function
+  handle_return
+}
+
+# inputs:
+#   $1    cell_path   should be real path
+#   $2... commands
+execute_commands() {
+  local cell_path=$1; shift
+  local cell_commands=( $* ) cell_command
+  local log_show_vars='^cell_path cell_commands'
+  begin_function
+
+    if [[ "$pause_at_cells" ]]; then
+      local pac
+      for pac in $pause_at_cells; do
+        if [[ "$cell_path" == *"$pac"* ]]; then
+          handle_user_interrupt "Cell reached (execute_command): $pac."
+        fi
+      done
+    fi
+
+    local top_level_command=${top_level_command_next:-t}
+
+    # so top_level_command is set to t throughout this function, yet if it's called again, it will
+    #   be set to f
+    top_level_command_next=f
+
+    eval "local $branch_local_vars" || fail
+    local previous_trunk=${previous_trunk:-}
+    execute_command_prep || fail
+
+    begin_for cell_command in ${cell_commands[*]}; doo
+
+      local original_cell_command=$cell_command
+      substitute_command_alias || fail
+      init_command_vars || fail
+
+      if [[ -e $cell_command_path.info ]]; then
+        source $cell_command_path.info || fail
+        handle_questions || fail
+      else
+        log_warn "Missing file $cell_command_path.info"
+      fi
+
+      if [[ ! -d $cell_path/.dna && $command_requires_cell == t ]]; then
+
+        if [[ $top_level_command == t ]]; then
+          log_warn "Skipping $cell_path because it is not a cell"
+        else
+          log_verbose "Skipping $cell_path because it is not a cell"
+        fi
+
+      else
+
+        if [[ -e $cell_command_path ]]; then
+          source $cell_command_path || fail
+        else
+          log_fatal "Internal error: Missing $cell_command command in $cell_command_path"
+          fail1
+        fi
+
+        validate_command_parameters || fail
+        execute_command $cell_path $cell_command || fail
+
+        if [[ $command_modifies_context == t \
+           || $command_modifies_upstream == t ]]; then
+          # make sure cell rebuilds context next time it's updated
+          if [[ -e $context_path ]]; then
+            rm $context_path* || fail
+          fi
+        fi
+
+        if [[ $command_modifies_upstream == t ]]; then
+          if [[ -e $up_path ]]; then
+            rm -rf $up_path || fail
+          fi
+          if [[ -e $up_chosen_path ]]; then
+            rm -rf $up_chosen_path || fail
+          fi
+        fi
+
+      fi
+
+    end_for
+
+  end_function
+  handle_return
+}
+
+load_dna_contents_update_cell() {
+  local file=$1 original_cell_path=$cell_path cell_path work_path
+  begin_function
+
+    local bottom_cell cell_path parent=${file%/*}
+    if [[ ! -d "$parent" ]]; then
+      ignore_nonexistent=t plant_seed $parent || fail
+      cell_path=$work_path
+    else
+      get_bottom_cell $parent
+      if [[ ! "$bottom_cell" ]]; then
+        log_fatal "Could not find cell for $file"
+        fail1
+      fi
+      cell_path=$bottom_cell
+    fi
+    local short_cell
+    get_short_cell
+
+    if [[ " ${command_history:-}" == *" update $short_cell "* ]]; then
+      # can't update a cell we are already updating
+      abort
+    fi
+
+    needs_update= \
+    fork execute_commands "$cell_path" update || fail
+
+    if [[ ! -f "$file" ]]; then
+      log_fatal "Cell $short_cell did not produce file at $file as required by dna of $original_cell_path"
+      fail1
+    fi
+
+  end_function
+  handle_return
 }
 
 # Will load the given derive table if not already loaded
@@ -390,7 +710,9 @@ load_derive_table() {
 #   name
 #   cache_path
 add_derive_item_table() {
-  # loop over each
+  # loop over each field
+  # if field is pk, add "to one" derive_from
+  # write to cache_path
 }
 
 # inputs:
@@ -414,6 +736,7 @@ add_derive_item() {
     local type=${derive_path##*.}
     case $type in
       *tab)
+
         local -n dtp=derive_table_${name}_path
         dtp=$derive_path
         load_derive_table $name || fail
@@ -425,6 +748,7 @@ add_derive_item() {
 
       ;;
       fun)
+
         local code
         load_fun_to_code $var_full_path derive_function_$name || fail
         eval "$code" || fail
@@ -2116,204 +2440,6 @@ init_command_vars() {
     command_modifies_upstream=f
 }
 
-init_context() {
-  begin_function
-
-    # required_freshness:
-    #   inf means infinite (never refresh based on time). 30s means refresh if it is older than 30 seconds.
-    #   1w means refresh if it's older than a week.
-    # shuffle_chance:
-    #   chance out of 1000 of not following the computed strategy order
-    # min_pause:
-    #   number of ms to wait between cycles
-    #   this number doubles each time there is nothing to do, until it reaches max_pause
-    # reuse_existing_out:
-    #   if set to t: 
-    #   new output folder won't be created when updating, but the existing one will be used
-    #   should set to true when creating a new output folder would be expensive
-    #   these cells must detect for themselves whether a change has happened in an
-    #     update and set something_changed=t accordingly. 
-
-    # need to make sure that expand functions don't bleed into sub command execution
-
-    unset ${!dim_*} \
-      ${!derive_table*} \
-      ${!branch_coordinate_*} \
-      ${!leaf_coordinate_*} \
-      ${!sub_coordinate_*} \
-      ${!tree_coordinate_*} \
-
-    declare -Ag all_dims=()
-
-    auto_loads=() \
-    cell_expiration= \
-    cell_is_outdated=t \
-    check_op_var=f \
-    child_dims=() \
-    control_props=() \
-    control_props_short=() \
-    current_pause=250 \
-    data_props=() \
-    data_props_short=() \
-    default_anchor_dims= \
-    default_freshness= \
-    default_strategies=crl \
-    derive_caches= \
-    dna_up_files=() \
-    implicit_dims=() \
-    key_path= \
-    localize_dims= \
-    localize_reverse_dims= \
-    lock_timeout=2 \
-    max_attempts=1 \
-    max_pause=60000 \
-    min_pause=250 \
-    optional_dims= \
-    out_file= \
-    out_path= \
-    post_validate=f \
-    pre_validate=f \
-    refresh_less_than=${refresh_less_than:-1} \
-    retry_delay=1 \
-    retry_delay_max=10 \
-    retry_scale=2 \
-    reuse_existing_out=t \
-    shuffle_chance=100 \
-    sub_dims=() \
-    sub_dims_short=() \
-    support_dims=() \
-    support_dims_short=() \
-    trunk_dims=() \
-    trunk_dims_short=() \
-    up=() \
-    update_cost=1 \
-    update_risk=3 \
-
-    unset \
-      check_op \
-      update_op \
-      get_op \
-      aggregate_op \
-
-    context_path=$cyto_path/context \
-    dna_key_path=$dna_path/key \
-    down_path=$cyto_path/down \
-    job_path=$cyto_path/job \
-    key_path=$cyto_path/key \
-    req_path=$cyto_path/req \
-    status_path=$cyto_path/status \
-    tmp_path=$cyto_path/tmp \
-    up_path=$cyto_path/up \
-    up_chosen_path=$cyto_path/up-chosen \
-    reactor_path=$cyto_path/reactors \
-
-    lock_path=$context_path \
-    replay_path=$job_path/pipe_replay \
-
-  end_function
-  handle_return
-}
-
-setup_cell_paths() {
-  dna_path=$cell_path/.dna
-  cyto_path=$cell_path/.cyto
-  init_context
-}
-
-branch_local_vars='branch_dims branch_members branch_hashes branch_dim_count trunk_cell short_cell prev_branch_info_cell'
-load_branch_info() {
-  local cell_path=${1:-$cell_path}
-
-  begin_function
-
-    if [[ "${prev_branch_info_cell:-}" == $cell_path ]]; then
-      # already loaded
-      abort
-    fi
-    prev_branch_info_cell=$cell_path
-
-    branch_dims=() \
-    branch_members=() \
-    branch_hashes=() \
-
-    local c=$cell_path p d m
-    while [[ $c == *:* ]]; do
-      p=${c##*/}
-      if [[ $p == *:* ]]; then
-
-        d=${p%%:*}
-
-        if [[ " ${branch_dims[*]} " == *" $d "* ]]; then
-          log_fatal "Duplicate branch dim found: $d in $cell_path"
-          fail1
-        fi
-
-        branch_dims=( $d ${branch_dims[*]} )
-
-        m=${p#*:}
-        branch_hashes=( $m ${branch_hashes[*]} )
-
-        local member_var_path=$c/.member
-        if [[ -f $member_var_path ]]; then
-          IFS= read -r -d '' m <$member_var_path
-        fi
-        branch_members=( "$m" "${branch_members[@]}" )
-
-        local -n ddim=d_$d idim=i_$d
-        ddim=$m
-        idim=$m
-
-      fi
-      c=${c%/*}
-    done
-
-    trunk_cell=$c
-    branch_dim_count=${#branch_dims[*]}
-
-    if (( branch_dim_count > 0 )); then
-      cell_is_trunk=f
-    else
-      cell_is_trunk=t
-    fi
-
-    if [[ "${branch_dims:-}" ]]; then
-      log_debug "Branch dims found: ${branch_dims[*]}"
-    fi
-
-    local x y dim_string= 
-    if [[ "${branch_hashes:-}" ]]; then
-      dim_string="${branch_hashes[*]}"
-      dim_string=:${dim_string// /\/}
-    fi
-    local short_trunk=${trunk_cell#/*/*/}
-
-  end_function
-  handle_return
-}
-
-execute_command_prep() {
-  begin_function
-
-    get_short_cell
-    load_branch_info || fail
-
-    trunk_changed=f
-    if [[ $trunk_cell != "${previous_trunk:-}" ]]; then
-      trunk_changed=t
-      previous_trunk=$trunk_cell
-    fi
-
-    setup_cell_paths
-
-    unset default_anchor_dims
-    if [[ $top_level_command == f ]]; then
-      anchor_dims=
-    fi
-
-  end_function
-  handle_return
-}
-
 # Inputs:
 #   $1    cell_path   should be real path
 #   $2    command
@@ -2418,128 +2544,6 @@ substitute_command_alias() {
         abort
       fi
     done
-  end_function
-  handle_return
-}
-
-# inputs:
-#   $1    cell_path   should be real path
-#   $2... commands
-execute_commands() {
-  local cell_path=$1; shift
-  local cell_commands=( $* ) cell_command
-  local log_show_vars='^cell_path cell_commands'
-  begin_function
-
-    if [[ "$pause_at_cells" ]]; then
-      local pac
-      for pac in $pause_at_cells; do
-        if [[ "$cell_path" == *"$pac"* ]]; then
-          handle_user_interrupt "Cell reached (execute_command): $pac."
-        fi
-      done
-    fi
-
-    local top_level_command=${top_level_command_next:-t}
-
-    # so top_level_command is set to t throughout this function, yet if it's called again, it will
-    #   be set to f
-    top_level_command_next=f
-
-    eval "local $branch_local_vars" || fail
-    local previous_trunk=${previous_trunk:-}
-    execute_command_prep || fail
-
-    begin_for cell_command in ${cell_commands[*]}; doo
-
-      local original_cell_command=$cell_command
-      substitute_command_alias || fail
-      init_command_vars || fail
-
-      if [[ -e $cell_command_path.info ]]; then
-        source $cell_command_path.info || fail
-        handle_questions || fail
-      else
-        log_warn "Missing file $cell_command_path.info"
-      fi
-
-      if [[ ! -d $cell_path/.dna && $command_requires_cell == t ]]; then
-
-        if [[ $top_level_command == t ]]; then
-          log_warn "Skipping $cell_path because it is not a cell"
-        else
-          log_verbose "Skipping $cell_path because it is not a cell"
-        fi
-
-      else
-
-        if [[ -e $cell_command_path ]]; then
-          source $cell_command_path || fail
-        else
-          log_fatal "Internal error: Missing $cell_command command in $cell_command_path"
-          fail1
-        fi
-
-        validate_command_parameters || fail
-        execute_command $cell_path $cell_command || fail
-
-        if [[ $command_modifies_context == t \
-           || $command_modifies_upstream == t ]]; then
-          # make sure cell rebuilds context next time it's updated
-          if [[ -e $context_path ]]; then
-            rm $context_path* || fail
-          fi
-        fi
-
-        if [[ $command_modifies_upstream == t ]]; then
-          if [[ -e $up_path ]]; then
-            rm -rf $up_path || fail
-          fi
-          if [[ -e $up_chosen_path ]]; then
-            rm -rf $up_chosen_path || fail
-          fi
-        fi
-
-      fi
-
-    end_for
-
-  end_function
-  handle_return
-}
-
-load_dna_contents_update_cell() {
-  local file=$1 original_cell_path=$cell_path cell_path work_path
-  begin_function
-
-    local bottom_cell cell_path parent=${file%/*}
-    if [[ ! -d "$parent" ]]; then
-      ignore_nonexistent=t plant_seed $parent || fail
-      cell_path=$work_path
-    else
-      get_bottom_cell $parent
-      if [[ ! "$bottom_cell" ]]; then
-        log_fatal "Could not find cell for $file"
-        fail1
-      fi
-      cell_path=$bottom_cell
-    fi
-    local short_cell
-    get_short_cell
-
-    if [[ " ${command_history:-}" == *" update $short_cell "* ]]; then
-      # can't update a cell we are already updating
-      abort
-    fi
-
-    needs_update= \
-    fork execute_commands "$cell_path" update || fail
-
-    if [[ ! -f "$file" ]]; then
-      log_fatal "Cell $short_cell did not produce file at $file as required by dna of $original_cell_path"
-      fail1
-    fi
-
   end_function
   handle_return
 }
@@ -3827,7 +3831,7 @@ set_cross_dims() {
     local -n member=d_$dim 
     local derive_table
 
-    for derive_table in $cross_dim_tables; do
+    for derive_table in $key_tables; do
       set_cross_dims_single
     done
 
@@ -3940,7 +3944,7 @@ calc_coordinates_next_unknown_dim_found() {
       fail1
     fi
 
-    local -n cross_dim_tables=dim_${dim}_cross_dim_tables
+    local -n key_tables=dim_${dim}_key_tables
 
     unset ddims
     local m
@@ -4181,7 +4185,7 @@ calc_coordinates_next_dim_member() {
     if [[ $is_valid == t ]]; then
 
       conflict=
-      if [[ -v cross_dim_tables ]]; then
+      if [[ -v key_tables ]]; then
         set_cross_dims || fail
 
         local d
@@ -4278,7 +4282,7 @@ calc_coordinates_next_dim() {
           fi
         fi
 
-        local -n cross_dim_tables=dim_${dim}_cross_dim_tables
+        local -n key_tables=dim_${dim}_key_tables
 
         unset members
         unset -n members member
