Fix coordinate display

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -1389,7 +1389,7 @@ write_coordinates_to_shell_file() {
   handle_return
 }
 
-display_coordinates_veritcal() {
+display_coordinates_vertical() {
   begin_function
     for (( row_index = 0; row_index < c_rows; row_index++ )); do
       echo "$hbar_minus" >&$fd_original_err
@@ -1417,7 +1417,7 @@ display_coordinates_horizontal() {
         apad line $field ${field^^}
       fi
     done
-    echo "$line" >$fd_original_err || fail
+    echo "$line" >&$fd_original_err || fail
 
     for (( row_index = 0; row_index < c_rows; row_index++ )); do
       line=
@@ -1430,7 +1430,7 @@ display_coordinates_horizontal() {
         fi
       done
 
-      echo "$line" >$fd_original_err || fail
+      echo "$line" >&$fd_original_err || fail
     done
   end_function
   handle_return
@@ -1479,7 +1479,7 @@ display_coordinates() {
 
     if (( max_row_width > ${COLUMNS:-120} )) \
     || [[ "${out_form:-${form:-}}" == l* ]]; then
-      display_coordinates_veritcal || fail
+      display_coordinates_vertical || fail
     else
       display_coordinates_horizontal || fail
     fi
