out migration

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -771,6 +771,8 @@ handle_return
 migrate_deps() {
 begin_function_flat
 
+  debug_start
+  migrate_out $dna_path/out $sub_dna_path/out || fail
   if [[ $is_branch == t ]]; then
     migrate_dep $dna_path/up $sub_dna_path/up || fail
     migrate_dep $dna_path/down $sub_dna_path/down || fail
@@ -783,6 +785,25 @@ begin_function_flat
 
 end_function_flat
 handle_return
+}
+
+migrate_out() {
+local from=$1
+local -r to=$2
+if [[ -d $from ]]; then
+  local -r dim_var=d_${leaf_dims}
+  local -r value=${!dim_var}
+  local sane_value
+  get_sane_value "$values" || return 1
+  from+=/$sane_value
+  from=$(realpath $from)
+  if [[ ! -d $from ]]; then
+    fatal "dna out dim path is missing: $from"
+    return 1
+  fi
+  safe_link $from $to || return 1
+fi
+return 0
 }
 
 migrate_dep() {
