Cleanup coord calculation

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -1642,7 +1642,7 @@ execute_command() {
   end_function
 
   if failed; then
-    log_fatal "Failed while executing command: $cell_command $short_cell in folder $cell_path"
+    log_fatal "Failed while executing command: $cell_command in folder $cell_path"
   fi
   handle_return
 }
@@ -3804,26 +3804,36 @@ calc_coords_branch() {
   handle_return
 }
 
+# should only be executed on leaf cells
 calc_coords_leaf() {
   begin_function
     local coord_type=leaf
-    if [[ $cell_is_leaf == t && ! "${leaf_coordinate_count:-}" ]]; then
-      if (( branch_coordinate_count > 0 )); then
-        target_dim_var_type=ddim convert_coords_to_dims || fail
-      fi
+    if [[ ! "${leaf_coordinate_count:-}" ]]; then
+      #  already happened in switch_context
+      #if (( branch_coordinate_count > 0 )); then
+      #  target_dim_var_type=ddim convert_coords_to_dims || fail
+      #fi
       calc_coordinates || fail
     fi
-    if (( leaf_coordinate_count > 0 )); then
+    if (( leaf_coordinate_rows == 1 )); then
       target_dim_var_type=ddim convert_coords_to_dims || fail
     fi
   end_function
   handle_return
 }
 
-# needs to be explicity called in commands which need coords
-calc_coords() {
-  calc_coords_branch || return 1
-  calc_coords_leaf || return 1
+# should only be executed on leaf cells
+calc_coords_sub() {
+  begin_function
+    local coord_type=sub
+    if [[ ! "${sub_coordinate_count:-}" ]]; then
+      calc_coordinates || fail
+    fi
+    if (( sub_coordinate_rows == 1 )); then
+      target_dim_var_type=ddim convert_coords_to_dims || fail
+    fi
+  end_function
+  handle_return
 }
 
 load_post_context_dynamic_vars() {
diff --git a/lib/help-lib b/lib/help-lib
--- a/lib/help-lib
+++ b/lib/help-lib
@@ -376,15 +376,15 @@ show_cell_help() {
 
     setup_dims || fail
 
-    handle_unknown=skip \
-    handle_no_coords=ignore \
-    calc_coords || fail
+    #handle_unknown=skip \
+    #handle_no_coords=ignore \
+    #calc_coords || fail
 
-    if [[ $cell_is_leaf == t ]]; then
-      coord_type=branch \
-      target_dim_var_type=ddim \
-      convert_coords_to_dims || fail
-    fi
+    #if [[ $cell_is_leaf == t ]]; then
+    #  coord_type=branch \
+    #  target_dim_var_type=ddim \
+    #  convert_coords_to_dims || fail
+    #fi
 
     indent=0
 
