.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -2302,6 +2302,7 @@ build_context() {
           check_op_var \
           data_props \
           || fail
+        mv $context_path-check.new $context_path-check || fail
       fi
 
       if [[ "${up:-}" && ! -d $up_path && $cell_is_leaf == t ]]; then
@@ -2417,12 +2418,17 @@ switch_context() {
       dna_path=$cell_path/.dna \
       cyto_path=$cell_path/.cyto \
 
-      context_path=$cyto_path/context \
+      if [[ ! -e $dna_path ]]; then
+        log_fatal "Internal error: attempted switch_context on an invalid cell: $cell_path"
+        fail1
+      fi
+
+      context_path=$cyto_path/context
 
       init_context || fail
       load_branch_info || fail
 
-      if [[ -e $dna_path && ! -d $cyto_path ]]; then
+      if [[ ! -d $cyto_path ]]; then
         mkdir $cyto_path || fail
         mkdir $status_path || fail
       fi
@@ -3938,10 +3944,10 @@ cell_lock() {
   local log_show_vars="timeout ^cell_path"
   begin_function_hi
 
-    if [[ -e $cell_path/.cyto ]]; then
+    if [[ -e $cell_path/.cyto/context ]]; then
       lock_path=$cell_path/.cyto/context
     else
-      log_fatal "Invalid lock path: $cell_path"
+      log_fatal "Missing context: $cell_path/.cyto/context"
       fail1
     fi
 
