m

diff --git a/lib/cell-update b/lib/cell-update
--- a/lib/cell-update
+++ b/lib/cell-update
@@ -337,7 +337,7 @@ flock -e -w $lock_timeout $lock_fd || {
 }
 
 unlock() {
-flock -u $lock_fd
+flock -u $1
 }
 
 write_persist_file() {
@@ -401,10 +401,11 @@ return 0
 }
 
 cell_update() {
-local fd= 
+local fd= extra_fds=
 get_cell_id || return 1
 if [[ -d $current_cube/lock$cell_id && ($keep_read_locks == t || $keep_write_locks == t) ]]; then
   exec {fd}<$current_cube/lock$cell_id || return 1
+  extra_fds+="$fd "
 fi
 outer_lock_fd=$fd cell_update_inner || return 1
 return 0
@@ -456,6 +457,7 @@ begin_function
       lock_fd=$outer_lock_fd
     else
       exec {lock_fd}<>"$lock_path" || fail
+      extra_fds+="$lock_fd "
     fi
   fi
 
@@ -533,18 +535,28 @@ begin_function
   local needs_update
   does_cube_need_update || fail
   if [[ $needs_update == f ]]; then
-    trace 0 "Update not needed"
+    if [[ $quick_check == t ]]; then
+      trace 5 "Quick check finished: Update not needed"
+    else
+      trace 0 "Update not needed"
+    fi
     succeed
   fi
 
   if [[ $quick_check == t ]]; then
-    trace 5 "Quick check finished"
+    trace 5 "Quick check finished: Update needed"
     fail
   fi
 
   if [[ "$up_path" ]]; then
     new_stage update-deps || fail
     cell_update_deps || fail
+  fi
+
+  if [[ "$res_path" ]]; then
+    trace 0 "Getting resources for cell"
+    new_stage get-resources || fail
+    cell_get_resources "$res_path" || fail
   fi
 
   new_stage write-lock || fail
@@ -559,12 +571,6 @@ begin_function
       rm -rf $out_path.new || fail
     fi
     mkdir $out_path.new || fail
-  fi
-
-  if [[ "$res_path" ]]; then
-    trace 0 "Getting resources for cell"
-    new_stage get-resources || fail
-    cell_get_resources "$res_path" || fail
   fi
 
   if [[ "$in_path" && "$out_path" ]]; then
@@ -651,17 +657,27 @@ begin_function
 
   fi
 
+  local do_unlocks=f
   if [[ "$outer_lock_fd" ]]; then
     if [[ $keep_write_locks == f ]]; then
       if [[ $keep_read_locks == t ]]; then
         # convert back to read lock so it doesn't change when downstream update is proceeding
         get_read_lock "$lock_path" || fail
       else
-        unlock || fail
+        do_unlocks=t
       fi
     fi
   else
-    unlock || fail
+    do_unlocks=t
+  fi
+
+  if [[ $do_unlocks == t ]]; then
+    trace 5 "Releasing locks"
+    local fd
+    begin_for fd in $extra_fds; doo
+      unlock $fd || fail
+      eval "exec $fd>&-" || fail
+    end_for
   fi
 
 end_function
@@ -726,21 +742,16 @@ begin_function
 
   [[ ! "$out_path" ]] && succeed
   
-  # TODO deps need to be checked for changes also
-
-  if [[ "$in_path" ]]; then
+  if [[ "$in_path" && "$out_path" ]]; then
     if [[ "$in_path" -nt "$out_path" ]]; then
-      trace 0 "Local changes were made, needs update"
+      trace 5 "Local changes were made, needs update"
       succeed
     fi
   fi
 
-  # nothing needs to be done in execution phase if execute_update function isn't defined
-  type execute_update &>/dev/null || succeed
-
-  if [[ "$up_path" ]]; then
+  if [[ "$up_path" && "$out_path" ]]; then
     if [[ "$up_path" -nt "$out_path" ]]; then
-      trace 0 "Upstream changes were made, needs update"
+      trace 5 "Upstream changes were made, needs update"
       succeed
     fi
   fi
@@ -751,10 +762,20 @@ begin_function
     local fresh_cutoff=$((EPOCHSECONDS-fresh_seconds))
     local out_timestamp=$(date -r "$out_path" +%s)
     if [ $out_timestamp -lt $fresh_cutoff ]; then
-      trace 0 "Freshness requirement ($fresh) not met, needs update"
+      trace 5 "Freshness requirement ($fresh) not met, needs update"
       succeed
     fi
   fi
+
+  local deps=( $(find "$current_cube/up" -mindepth 1 -maxdepth 1 -type d) )
+  local dep
+  begin_for dep in ${deps[*]}; doo
+    if ! quick_check=t cube_update "$dep"; then
+      # if cube_update fails, then an update is needed
+      trace 5 "Upstream $dep needs update"
+      succeed 
+    fi
+  end_for
 
   needs_update=f
 
