.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -2289,10 +2289,10 @@ validate_dims() {
 }
 
 encrypt_file() {
-  local user_public_key=${user_public_key:-~/.ssh/id_rsa.pub}
+  local user_private_key=${user_private_key:-~/.ssh/id_rsa}
   local from=$from \
     to=$to \
-    key=${key:-$user_public_key}
+    key=${key:-$user_private_key}
 
   begin_function
 
@@ -2312,7 +2312,7 @@ encrypt_file() {
     fi
      
     setup_tmp_path || fail
-    if ! log_and_run openssl pkeyutl -encrypt -pubin -inkey $key -in $from -out $to; then
+    if ! log_and_run openssl pkeyutl -encrypt -inkey $key -in $from -out $to; then
       log_fatal "Failed to encrypt file: $from"
       fail1
     fi
@@ -2642,183 +2642,216 @@ setup_branch_dims() {
 
 # returns array of dims, which may be empty if there are no dims
 get_dims() {
-local -r cell=$1
-if [[ -d $cell/.dna/dim ]]; then
-  dims=( $( \
-    find1 $cell/.dna/dim \
-    -not -name '.*' \
-    -printf '%f\n' \
-    | sort -g \
-    | sed -E 's/^[0-9]+-(.*)/\1/' \
-    ) ) || return 1
-else
-  dims=()
-fi
-return 0
+  local -r cell=$1
+  if [[ -d $cell/.dna/dim ]]; then
+    dims=( $( \
+      find1 $cell/.dna/dim \
+      -not -name '.*' \
+      -printf '%f\n' \
+      | sort -g \
+      | sed -E 's/^[0-9]+-(.*)/\1/' \
+      ) ) || return 1
+  else
+    dims=()
+  fi
+  return 0
 }
 
 
 update_cell_value_file() {
-begin_function_flat
-  if [[ "${cell_values:-}" && ! -f $cell_path/cell_values ]]; then
-    local v s='cell_values=( '
-    for v in "${cell_values[@]}"; do
-      s+="\"$v\" "
-    done
-    s+=')'
-    echo "$s" >$cell_path/cell_values || fail
-  fi
-end_function
-handle_return
+  begin_function_flat
+    if [[ "${cell_values:-}" && ! -f $cell_path/cell_values ]]; then
+      local v s='cell_values=( '
+      for v in "${cell_values[@]}"; do
+        s+="\"$v\" "
+      done
+      s+=')'
+      echo "$s" >$cell_path/cell_values || fail
+    fi
+  end_function
+  handle_return
 }
 
 get_cell() {
-cell_path=$1
-[[ ${#cell_path} -lt 3 ]] && return 1
-[[ -d $cell_path/.dna ]] && return 0
-[[ -d $cell_path/.cyto ]] && return 0
-get_cell ${cell_path%/*} || return 1
-return 0
+  cell_path=$1
+  [[ ${#cell_path} -lt 3 ]] && return 1
+  [[ -d $cell_path/.dna ]] && return 0
+  [[ -d $cell_path/.cyto ]] && return 0
+  get_cell ${cell_path%/*} || return 1
+  return 0
 }
 
 setup_tmp_path() {
-if [[ ! "${tmp_path:-}" ]]; then
-  if [[ -d ${cell_path:-}/.cyto/tmp ]]; then
-    tmp_path=$cell_path/.cyto/tmp
-  elif [[ -d ~/tmp ]]; then
-    tmp_path=~/tmp
-  else
-    tmp_path=/tmp
+  if [[ ! "${tmp_path:-}" ]]; then
+    if [[ -d ${cell_path:-}/.cyto/tmp ]]; then
+      tmp_path=$cell_path/.cyto/tmp
+    elif [[ -d ~/tmp ]]; then
+      tmp_path=~/tmp
+    else
+      tmp_path=/tmp
+    fi
   fi
-fi
-if [[ ! -d $tmp_path ]]; then
-  mkdir -p $tmp_path || return 1
-fi
-return 0
+  if [[ ! -d $tmp_path ]]; then
+    mkdir -p $tmp_path || return 1
+  fi
+  return 0
 }
 
 # params: $1 (subject)
 # output: workspace
 get_workspace() {
-local subject=$1
-workspace=
-while [[ ${#subject} -gt 1 && $subject =~ / ]]; do
-  if [[ "$subject" == "$top_cell"/* ]]; then
-    workspace=$subject
-    break
-  fi
-  subject=${subject%/*}
-done
-[[ "$workspace" ]]
+  local subject=$1
+  workspace=
+  while [[ ${#subject} -gt 1 && $subject =~ / ]]; do
+    if [[ "$subject" == "$top_cell"/* ]]; then
+      workspace=$subject
+      break
+    fi
+    subject=${subject%/*}
+  done
+  [[ "$workspace" ]]
+}
+
+decrypt_file() {
+  local user_private_key=${user_private_key:-~/.ssh/id_rsa}
+  local from=$from \
+    to=$to \
+    key=${key:-$user_private_key}
+
+  begin_function
+
+    if [[ ! -f $from ]]; then
+      log_fatal "File doesn't exist: $from"
+      fail1
+    fi
+     
+    if [[ -e $to ]]; then
+      log_fatal "File already exists: $to"
+      fail1
+    fi
+     
+    if [[ ! -f $key ]]; then
+      log_fatal "Key doesn't exist: $key"
+      fail1
+    fi
+     
+    setup_tmp_path || fail
+    if ! log_and_run openssl pkeyutl -decrypt -inkey $key -in $from -out $to; then
+      log_fatal "Failed to decrypt file: $from"
+      fail1
+    fi
+
+  end_function
+  handle_return
 }
 
 # inputs: from to tmp_path current_cell
 # will write output to file at $to
 decrypt_file_with_shared_key() {
 
-setup_tmp_path || return 1
+  setup_tmp_path || return 1
 
-local from=$from
-local to=$to
-local tmp_path=$tmp_path
-local key_path=$key_path
-local user_private_key=${user_private_key:-~/.ssh/id_rsa}
+  local from=$from
+  local to=$to
+  local tmp_path=$tmp_path
+  local key_path=$key_path
+  local user_private_key=${user_private_key:-~/.ssh/id_rsa}
 
-log_debug "Decrypting $from to $to"
+  log_debug "Decrypting $from to $to"
 
-local log_vars='from to'
-begin_function
+  local log_vars='from to'
+  begin_function
 
-  if [[ ! -f "$from" ]]; then
-    log_fatal "Attempting to decrypt non-existent file: $from"
-    fail1
-  fi
+    if [[ ! -f "$from" ]]; then
+      log_fatal "Attempting to decrypt non-existent file: $from"
+      fail1
+    fi
 
-  if [[ -s "$to" ]]; then
-    log_fatal "Decrypt: target file already exists: $to"
-    fail1
-  fi
+    if [[ -s "$to" ]]; then
+      log_fatal "Decrypt: target file already exists: $to"
+      fail1
+    fi
 
-  if [[ ! -f "$user_private_key" ]]; then
-    log_fatal "Private key is missing. Set path to it with user_private_key env var, or put it here: $user_private_key"
-    log_fatal "You may create one using: ssh-keygen -mPEM"
-    fail1
-  fi
+    if [[ ! -f "$user_private_key" ]]; then
+      log_fatal "Private key is missing. Set path to it with user_private_key env var, or put it here: $user_private_key"
+      log_fatal "You may create one using: ssh-keygen -mPEM"
+      fail1
+    fi
 
-  if [[ ! "$tmp_path" ]]; then
-    log_fatal "tmp_path must be set to a directory before calling decrypt_file_with_shared_key."
-    fail1
-  fi
+    if [[ ! "$tmp_path" ]]; then
+      log_fatal "tmp_path must be set to a directory before calling decrypt_file_with_shared_key."
+      fail1
+    fi
 
-  if [[ ! -d $tmp_path ]]; then
-    mkdir -p $tmp_path || fail
-  fi
+    if [[ ! -d $tmp_path ]]; then
+      mkdir -p $tmp_path || fail
+    fi
 
-  if [[ ! -d $key_path ]]; then
-    mkdir $key_path || fail
-  fi
+    if [[ ! -d $key_path ]]; then
+      mkdir $key_path || fail
+    fi
 
-  if [[ ! -f "$key_path/key.$USER" ]]; then
-    log_fatal "You don't have a key for this cell ($USER). Ask someone who does to add you. Existing keys:" 
-    find -L $key_path -name "key.*" >&2
-    fail1
-  fi
+    if [[ ! -f "$key_path/key.$USER" ]]; then
+      log_fatal "You don't have a key for this cell ($USER). Ask someone who does to add you. Existing keys:" 
+      find -L $key_path -name "key.*" >&2
+      fail1
+    fi
 
-  # extract the main key
-  if ! log_and_run openssl pkeyutl -decrypt -inkey $user_private_key -in "$key_path/key.$USER" -out $tmp_path/main; then
-    log_fatal "Failed to decrypt main key." 
-    fail1
-  fi
-  defer "rm $tmp_path/main"
+    # extract the main key
+    if ! log_and_run openssl pkeyutl -decrypt -inkey $user_private_key -in "$key_path/key.$USER" -out $tmp_path/main; then
+      log_fatal "Failed to decrypt main key." 
+      fail1
+    fi
+    defer "rm $tmp_path/main"
 
-  # decrypt the secret file
-  if ! log_and_run openssl enc -aes256 -pbkdf2 -in $from -out $to -d -pass file:$tmp_path/main; then 
-    log_fatal "Failed to decrypt secret file." 
-    fail1
-  fi
+    # decrypt the secret file
+    if ! log_and_run openssl enc -aes256 -pbkdf2 -in $from -out $to -d -pass file:$tmp_path/main; then 
+      log_fatal "Failed to decrypt secret file." 
+      fail1
+    fi
 
-end_function
-handle_return
+  end_function
+  handle_return
 
 }
 
 # input: dim
 # output: values 
 expand_values() {
-begin_function_flat
+  begin_function_flat
 
-  local dims=${dim}s 
-  local ddims=d_$dims \
-        ddim=d_$dim \
-        new_value_list= new_values= value \
-        has_member_expand_function=f
+    local dims=${dim}s 
+    local ddims=d_$dims \
+          ddim=d_$dim \
+          new_value_list= new_values= value \
+          has_member_expand_function=f
 
-  values=( ${!ddim:-} )
-  type -t ${dim}_member_expand >/dev/null && has_member_expand_function=t
+    values=( ${!ddim:-} )
+    type -t ${dim}_member_expand >/dev/null && has_member_expand_function=t
 
-  local problem= failed=f
-  if [[ ! "${values:-}" ]]; then
-    expand_values_plural || failed=t
-  else
-    expand_values_single || failed=t
-  fi
-  if [[ "$problem" ]]; then
-    log_fatal "$problem"
-    fail1
-  elif [[ $failed == t ]]; then
-    if [[ ! "$values" ]]; then
-      log_fatal "Missing required dimension: $dim"
-      fail1
+    local problem= failed=f
+    if [[ ! "${values:-}" ]]; then
+      expand_values_plural || failed=t
     else
-      log_fatal "Error expanding values for dimension: $dim"
-      fail1
+      expand_values_single || failed=t
     fi
-  fi
+    if [[ "$problem" ]]; then
+      log_fatal "$problem"
+      fail1
+    elif [[ $failed == t ]]; then
+      if [[ ! "$values" ]]; then
+        log_fatal "Missing required dimension: $dim"
+        fail1
+      else
+        log_fatal "Error expanding values for dimension: $dim"
+        fail1
+      fi
+    fi
 
-  values=( $new_value_list )
+    values=( $new_value_list )
 
-end_function
-handle_return
+  end_function
+  handle_return
 }
 
 # input: 
diff --git a/lib/omni-navigator b/lib/omni-navigator
--- a/lib/omni-navigator
+++ b/lib/omni-navigator
@@ -460,7 +460,7 @@ omni_exit_sub_log() {
 #   cursor
 #   reverse_index
 omni_show_line() {
-  local reverse_index=$reverse_index \
+  local reverse_index=${reverse_index:-} \
     cursor=$cursor \
     out_to_var=${out_to_var:-} \
     result= \
@@ -471,7 +471,7 @@ omni_show_line() {
     index=cursor_${cursor}_log_array_index \
 
   local reverse=f
-  if (( reverse_index == index )); then
+  if [[ "$reverse_index" ]] && (( reverse_index == index )); then
     reverse=t
   fi
 
@@ -528,7 +528,8 @@ push_to_function_stack() {
 omni_search_next() {
   begin_function_flat
 
-    failed_to_move=f
+    local original_index=$index \
+      original_log=$log_file
 
     if [[ ${action_map[$index]} == log_to && $allow_in_log == t ]]; then
 
@@ -557,7 +558,7 @@ omni_search_next() {
       if [[ $direction == 1 ]]; then
 
         if [[ "$pre_action" == call ]]; then
-          push_to_function_stack $((index - 1 )) || fail
+          push_to_function_stack $(( index - 1 )) || fail
         fi
 
         if [[ "$post_action" == return\(* && -v function_call_stack && ${#function_call_stack[*]} -gt 0 ]]; then
@@ -585,14 +586,12 @@ omni_search_next() {
             omni_exit_sub_log || fail
           else
             (( index = log_array_size - 1 ))
-            failed_to_move=t
           fi
         elif [[ $direction == -1 ]]; then
           if [[ $allow_out_log == t && -v log_file_stack ]] && (( ${#log_file_stack[*]} > 0 )); then
             omni_exit_sub_log || fail
           else
             index=0
-            failed_to_move=t
           fi
         else
           log_fatal "omni_search_next: invalid direction: $direction"
@@ -601,6 +600,13 @@ omni_search_next() {
       fi
 
     fi
+
+    if [[ $original_index == $index && $original_log == $log_file ]]; then
+      failed_to_move=t
+    else
+      failed_to_move=f
+    fi
+
   end_function
   handle_return
 }
@@ -721,6 +727,11 @@ omni_copy_cursor() {
 }
 
 # will move the cursor according to the parameters given
+# inputs
+#   count=1           set to inf for unlimited matches
+#   each_match=       function to execute each time a match is found
+#   from_cursor=      cursor to copy to move_cursor. Determines starting point of search
+#   move_cursosr=s    which cursor is changed in the process
 omni_search() {
   local log_vars='from_log from_index move_cursor count deep'
   begin_function_flat
@@ -729,6 +740,7 @@ omni_search() {
       from_cursor=${from_cursor:-} \
       original_cursor=${cursor:-} \
       move_cursor=${move_cursor:-s} \
+      each_match=${each_match:-} \
       find_level=${find_level:-} \
       find_action=${find_action:-} \
       find_log_id=${find_log_id:-} \
@@ -744,8 +756,8 @@ omni_search() {
       allow_diff_plane=${allow_diff_plane:-f} \
       allow_all=${allow_all:-f} \
       allow_all_in_same_log=${allow_all_in_same_log:-f} \
-      count=${count:-1} \
-      omni_prev_go_to_string=${omni_prev_go_to_string:-} \
+      count=${count:-1} 
+    local -n log_file=cursor_${move_cursor}_log_file
 
     # implications
     if [[ $allow_all == t ]]; then
@@ -807,23 +819,35 @@ omni_search() {
       found_matching_line=t \
       restore_backup=f \
       failed_to_move=f \
+      lid \
+      visited=() \
+      visited_backup=()
 
     begin_loop
 
+      # infinite loop detection
+      lid=$log_file:$index
+      if [[ " ${visited[*]} " =~ \ $lid\  ]]; then
+        debug_start
+        log_fatal "Infinite loop detected in omni_search"
+        fail1
+      fi
+      visited+=( $lid )
+
       if [[ $found_matching_line == t ]]; then
         omni_copy_cursor $cursor backup
+        visited_backup=( "${visited[@]}" )
       fi
 
       omni_search_next || fail
 
-      found_matching_line=t
-      omni_search_get_matches || fail
-      
       if [[ $failed_to_move == t ]]; then
-
         break
       fi
 
+      found_matching_line=t
+      omni_search_get_matches || fail
+      
       if [[ $found_matching_line == t ]]; then
 
         (( cursor_moved += direction ))
@@ -831,9 +855,15 @@ omni_search() {
           (( count -= direction ))
         fi
         restore_backup=f
+
+        if [[ "$each_match" ]]; then
+          eval "$each_match" || fail
+        fi
+
         if [[ $count == 0 ]]; then
           break
         fi
+
       else
         restore_backup=t
       fi
@@ -841,13 +871,12 @@ omni_search() {
     end_loop
 
     if [[ $restore_backup == t ]]; then
-
       omni_copy_cursor backup $cursor || fail
+      visited=( "${visited_backup[@]}" )
     fi
 
     # restore original cursor
     if [[ "$original_cursor" ]]; then
-
       new_cursor=$original_cursor \
         omni_select_cursor || fail
     fi
@@ -1368,6 +1397,37 @@ omni_navigator() (
           omni_show_context || fail
           no_follow_once=t
           ;;
+        ,)
+          echo >&$fd_original_err
+          read -er -p "Search for substring: " omni_prev_grep_string <&$fd_original_in >&$fd_original_err
+          if [[ "${omni_prev_grep_string:-}" ]]; then
+            local find_substring find_regex
+            if [[ "$omni_prev_grep_string" == ~* ]]; then
+              find_regex=${omni_prev_grep_string#\~}
+              find_substring=
+            else
+              find_substring=$omni_prev_grep_string
+              find_regex=
+            fi
+
+            local cursor_moved=0
+            from_cursor=$cursor \
+              allow_all=t \
+              each_match='cursor=s omni_show_line' \
+              count=inf \
+              omni_search || fail
+
+            find_substring= find_regex=
+
+            if (( cursor_moved == 0 )); then
+              echo "Not found" >&$fd_original_err
+            else
+              echo "Found $cursor_moved log entries" >&$fd_original_err
+              no_follow_once=t
+            fi
+
+          fi
+          ;;
         /)
           echo >&$fd_original_err
           local go_to_string=
@@ -1429,7 +1489,9 @@ omni_navigator() (
           echo "]  go to last log line within the same plane" >&$fd_original_err
           echo "{  go to first log line within the log file" >&$fd_original_err
           echo "}  go to last log line within the log file" >&$fd_original_err
-          echo "f  search forward for a string" >&$fd_original_err
+          echo ",  grep logs for a given string, listing all matching lines" >&$fd_original_err
+          echo ".  repeat previous grep" >&$fd_original_err
+          echo "/  search forward for a string" >&$fd_original_err
           no_follow_once=t
           ;;
         *)
