Fix seed bug

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -305,7 +305,8 @@ local vars=sub_cell; begin_function
       create_sub_branch_or_leaf $sub_cell.new || fail
     else
       mkdir -p $sub_cell.new || fail
-      find_seed_dna ${seed:-$parent} ${sub_cell#$parent/} || fail
+      seed=${seed:-$parent}
+      find_seed_dna $seed ${sub_cell#$seed/} || fail
       if [[ "$seed_dna" ]]; then
         safe_link $(realpath $seed_dna) $sub_cell.new/.dna || fail
       fi
@@ -560,7 +561,7 @@ handle_return
 }
 
 execute_command() {
-local cell=$1 command=$2
+local cell=$(realpath $1) command=$2
 local vars='cell command'; begin_function
   cell_context_load || {
     err "Context failed to load for $cell"
