improve coord calculation

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -110,6 +110,20 @@ get_tmp_file() {
   return 0
 }
 
+init_dims() {
+  local types=${*:-trunk_dims sub_dims control_props data_props}
+  begin_function
+    begin_for dim_type in $types; doo
+      local -n dims=$dim_type
+      begin_for dim in ${dims[*]:-}; doo
+        local -n ddim=d_$dim
+        ddim=
+      end_for
+    end_for
+  end_function
+  handle_return
+}
+
 write_to_context() {
   local context_type=$context_type new_type=$1 content=$2
   begin_function_lo
@@ -704,68 +718,6 @@ build_context_expand() {
         fi
       end_for
     end_for
-
-  end_function
-  handle_return
-}
-
-# inputs:
-#   coord_type
-calc_coordinates() {
-  begin_function
-
-    local coord_type=${coord_type} dim_var
-
-    local -n coordinate_data=${coord_type}_coordinate_data \
-      coordinate_count=${coord_type}_coordinate_count \
-      coordinate_rows=${coord_type}_coordinate_rows \
-      coordinate_fields=${coord_type}_coordinate_fields \
-      coordinate_fields_count=${coord_type}_coordinate_fields_count \
-      coordinate_fields_plural=${coord_type}_coordinate_fields_plural \
-
-    coordinate_data=() \
-    coordinate_count=0 \
-    coordinate_rows=0 \
-    missing_dims=() \
-
-    case $coord_type in
-      branch)
-        coordinate_fields=( ${trunk_dims[*]:-} )
-        coordinate_fields_plural=( ${trunk_dims_plural[*]:-} )
-      ;;
-      leaf)
-        coordinate_fields=( ${sub_dims[*]:-} ${control_props[*]:-} ${data_props[*]:-} )
-        coordinate_fields_plural=( ${sub_dims_plural[*]:-} ${control_props_plural[*]:-} ${data_props_plural[*]:-} )
-      ;;
-      *)
-        log_fatal "Internal error: invalid coord_type=$coord_type"
-        fail1
-      ;;
-    esac
-
-    coordinate_fields_count=${#coordinate_fields[*]}
-
-    declare -Ag coordinate_dim_index
-    local d i=0
-    for d in ${coordinate_fields[*]}; do
-      coordinate_dim_index[$d]=$i
-      (( i++ ))
-    done
-
-    if [[ "${coordinate_fields:-}" ]]; then
-      log_verbose "Calculating $coord_type cell coordinates for dims: ${coordinate_fields[*]}"
-      calc_coordinates_next_known_dim 0 || fail
-
-      if [[ ! "${missing_dims:-}" ]]; then
-        if [[ ! "${coordinate_data:-}" ]]; then
-          calc_coordinates_add_row || fail
-        fi
-
-        coordinate_count=${#coordinate_data[*]}
-        coordinate_rows=$(( coordinate_count / coordinate_fields_count ))
-        log_verbose "$coordinate_rows $coord_type coordinates found" 
-      fi
-    fi
 
   end_function
   handle_return
@@ -1525,6 +1477,276 @@ handle_missing_dims() {
   handle_return
 }
 
+calc_coordinates_process_member() {
+  begin_function
+
+    #if [[ "$localize_dims" ]]; then
+    #  eval "local $localize_dims" || fail
+    #fi
+
+    local -n member=d_$dim \
+      members=d_$dims
+    member=$current_member
+
+    if (( $current_dim_index < ${#coordinate_fields[*]} )); then
+
+      if [[ $phase == known ]]; then
+        # recursive
+        calc_coordinates_next_known_dim $current_dim_index || fail
+      else
+        # recursive
+        calc_coordinates_next_unknown_dim $current_dim_index || fail
+      fi
+
+    else
+
+      if [[ $phase == known && "${missing_dims:-}" ]]; then
+        log_debug "Attempting to resolve unknowns: ${missing_dims[*]}"
+        missing_dims=()
+        # recursive
+        calc_coordinates_next_unknown_dim 0 || fail
+      fi
+
+    fi
+
+  end_function
+  handle_return
+}
+
+# inputs:
+#   phase     known or unknown
+#   members   array containing dim members to loop over
+# outputs:
+#   member    var to set with currently selected member
+#   current_dim_index
+calc_coordinates_loop_members() {
+  local phase=$phase
+  begin_function
+    (( current_dim_index++ ))
+    local current_member
+    begin_for current_member in "${members[@]}"; doo
+      calc_coordinates_process_member || fail
+      if [[ "${missing_dims:-}" ]]; then
+        break
+      fi
+    end_for
+  end_function
+  handle_return
+}
+
+calc_coordinates_add_row() {
+  begin_function
+    local i new_coords=()
+    for (( i = 0; i < coordinate_fields_count; i++ )); do
+      local -n dim_value=d_${coordinate_fields[$i]}
+      if [[ "${dim_value:-}" == \$* ]]; then
+        # lets keep an eye on this for now
+        log_fatal "Internal error: bad dim_value"
+        debug_start
+      fi
+      coordinate_data+=( "$dim_value" )
+      new_coords+=( "$dim_value" )
+    done
+    log_verbose "${coord_type}_coordinate_data+=( ${new_coords[*]} )"
+  end_function
+  handle_return
+}
+
+calc_coordinates_next_unknown_dim() {
+  local current_dim_index=$1
+  begin_function
+    local dim dims changed=f phase=derive
+    begin_loop; doo
+
+      dim=${coordinate_fields[$current_dim_index]}
+      dims=${coordinate_fields_plural[$current_dim_index]}
+      local -n member=d_$dim \
+        members=d_$dims
+
+      if [[ ! "${members:-}" ]]; then
+
+        log_debug "Finding values for $dim in phase $phase"
+        local values= prev_phase=$phase
+        if [[ $phase == derive ]]; then
+          expand_values_check_derive || fail
+        else
+          expand_values_check_default || fail
+        fi
+
+        if [[ "${values:-}" ]]; then
+
+          changed=t
+          if [[ "$phase" == default ]]; then
+            # go back to derive phase since calculating a new default could
+            # open up new derive possibilities
+            phase=derive
+          fi
+
+          log_debug "Resolved $dim with $prev_phase: ${values[*]:0:30}"
+
+          # don't support aliases here (yet?)
+          # local new_values
+          # expand_dim_members "${values[@]}" || fail
+
+          members=( "${values[@]}" )
+
+          if (( ${#members[*]} > 1 )); then
+            phase=unknown \
+            calc_coordinates_loop_members || fail
+            break
+          else
+            member=$members
+          fi
+
+        else
+          log_debug "Failed to resolve $dim in phase $prev_phase"
+          missing_dims+=( $dim )
+        fi
+
+      fi
+
+      (( current_dim_index++ ))
+      if (( $current_dim_index >= ${#coordinate_fields[*]} )); then
+        if (( ${#missing_dims[*]} > 0 )); then
+          if [[ $changed == t ]]; then
+            # an unknown dim was resolved, so we need to go through again to see if we can resolve more
+            changed=f
+            current_dim_index=0
+            missing_dims=()
+          else
+            if [[ $phase == derive ]]; then
+              phase=default
+              current_dim_index=0
+              missing_dims=()
+            else
+              break
+            fi
+          fi
+        else # all dims were resolved
+          calc_coordinates_add_row || fail
+          break
+        fi
+      fi
+
+    end_loop
+
+  end_function
+  handle_return
+}
+
+# inputs:
+#   coordinate_fields        array of dims to process
+#   coordinate_fields_plural array of dim plurals to process
+#   $1   index of dim to process
+calc_coordinates_next_known_dim() {
+  local current_dim_index=$1
+  begin_function
+    local dim dims
+    begin_loop; doo
+
+      dim=${coordinate_fields[$current_dim_index]}
+      dims=${coordinate_fields_plural[$current_dim_index]}
+      local -n member=d_$dim \
+        members=d_$dims
+
+      if [[ "${members:-}" ]]; then
+
+        local member_array=( $members )
+        if (( ${#member_array[*]} > 1 )); then
+          phase=known \
+          calc_coordinates_loop_members || fail
+          break
+        else
+          member=$members
+        fi
+
+      else
+        missing_dims+=( $dim )
+      fi
+
+      (( current_dim_index++ ))
+      if (( current_dim_index >= ${#coordinate_fields[*]} )); then
+        break
+      fi
+
+    end_loop
+
+    if [[ "${missing_dims:-}" ]]; then
+      log_debug "Attempting to resolve unknowns: ${missing_dims[*]}"
+      missing_dims=()
+      calc_coordinates_next_unknown_dim 0 || fail
+    fi
+
+  end_function
+  handle_return
+}
+
+# inputs:
+#   coord_type
+calc_coordinates() {
+  begin_function
+
+    local coord_type=${coord_type} dim_var
+
+    local -n coordinate_data=${coord_type}_coordinate_data \
+      coordinate_count=${coord_type}_coordinate_count \
+      coordinate_rows=${coord_type}_coordinate_rows \
+      coordinate_fields=${coord_type}_coordinate_fields \
+      coordinate_fields_count=${coord_type}_coordinate_fields_count \
+      coordinate_fields_plural=${coord_type}_coordinate_fields_plural \
+
+    coordinate_data=() \
+    coordinate_count=0 \
+    coordinate_rows=0 \
+    missing_dims=() \
+
+    case $coord_type in
+      branch)
+        coordinate_fields=( ${trunk_dims[*]:-} )
+        coordinate_fields_plural=( ${trunk_dims_plural[*]:-} )
+      ;;
+      leaf)
+        coordinate_fields=( ${sub_dims[*]:-} ${control_props[*]:-} ${data_props[*]:-} )
+        coordinate_fields_plural=( ${sub_dims_plural[*]:-} ${control_props_plural[*]:-} ${data_props_plural[*]:-} )
+      ;;
+      tree)
+        coordinate_fields=( ${trunk_dims[*]:-} ${sub_dims[*]:-} )
+        coordinate_fields_plural=( ${trunk_dims_plural[*]:-} ${sub_dims_plural[*]:-} )
+      ;;
+      *)
+        log_fatal "Internal error: invalid coord_type=$coord_type"
+        fail1
+      ;;
+    esac
+
+    coordinate_fields_count=${#coordinate_fields[*]}
+
+    declare -Ag coordinate_dim_index
+    local d i=0
+    for d in ${coordinate_fields[*]}; do
+      coordinate_dim_index[$d]=$i
+      (( i++ ))
+    done
+
+    if [[ "${coordinate_fields:-}" ]]; then
+      log_verbose "Calculating $coord_type cell coordinates for dims: ${coordinate_fields[*]}"
+      calc_coordinates_next_known_dim 0 || fail
+
+      if [[ ! "${missing_dims:-}" ]]; then
+        if [[ ! "${coordinate_data:-}" ]]; then
+          calc_coordinates_add_row || fail
+        fi
+
+        coordinate_count=${#coordinate_data[*]}
+        coordinate_rows=$(( coordinate_count / coordinate_fields_count ))
+        log_verbose "$coordinate_rows $coord_type coordinates found" 
+      fi
+    fi
+
+  end_function
+  handle_return
+}
+
 # only run if the cell is actually a leaf
 build_context_leaf() {
   begin_function
@@ -1960,10 +2182,10 @@ init_context() {
     done
 
     branch_coordinate_count= \
-    branch_coordinate_data= \
-    branch_coordinate_fields= \
+    branch_coordinate_data=() \
+    branch_coordinate_fields=() \
     branch_coordinate_fields_count= \
-    branch_coordinate_fields_plural= \
+    branch_coordinate_fields_plural=() \
     branch_coordinate_rows= \
     cell_expiration= \
     cell_is_external=f \
@@ -1977,10 +2199,10 @@ init_context() {
     default_freshness= \
     default_strategies=crl \
     leaf_coordinate_count= \
-    leaf_coordinate_data= \
-    leaf_coordinate_fields= \
+    leaf_coordinate_data=() \
+    leaf_coordinate_fields=() \
     leaf_coordinate_fields_count= \
-    leaf_coordinate_fields_plural= \
+    leaf_coordinate_fields_plural=() \
     leaf_coordinate_rows= \
     localize_dims= \
     localize_reverse_dims= \
@@ -2000,6 +2222,12 @@ init_context() {
     reuse_existing_out=t \
     shuffle_chance=100 \
     sub_dims=() \
+    tree_coordinate_count= \
+    tree_coordinate_data=() \
+    tree_coordinate_fields=() \
+    tree_coordinate_fields_count= \
+    tree_coordinate_fields_plural=() \
+    tree_coordinate_rows= \
     trunk_dims=() \
     up=() \
     update_cost=1 \
@@ -2503,210 +2731,6 @@ expand_values_check_default() {
         values=( $empty_member )
       fi
 
-    fi
-
-  end_function
-  handle_return
-}
-
-calc_coordinates_process_member() {
-  begin_function
-
-    #if [[ "$localize_dims" ]]; then
-    #  eval "local $localize_dims" || fail
-    #fi
-
-    local -n member=d_$dim \
-      members=d_$dims
-    member=$current_member
-
-    if (( $current_dim_index < ${#coordinate_fields[*]} )); then
-
-      if [[ $phase == known ]]; then
-        # recursive
-        calc_coordinates_next_known_dim $current_dim_index || fail
-      else
-        # recursive
-        calc_coordinates_next_unknown_dim $current_dim_index || fail
-      fi
-
-    else
-
-      if [[ $phase == known && "${missing_dims:-}" ]]; then
-        log_debug "Attempting to resolve unknowns: ${missing_dims[*]}"
-        missing_dims=()
-        # recursive
-        calc_coordinates_next_unknown_dim 0 || fail
-      fi
-
-    fi
-
-  end_function
-  handle_return
-}
-
-# inputs:
-#   phase     known or unknown
-#   members   array containing dim members to loop over
-# outputs:
-#   member    var to set with currently selected member
-#   current_dim_index
-calc_coordinates_loop_members() {
-  local phase=$phase
-  begin_function
-    (( current_dim_index++ ))
-    local current_member
-    begin_for current_member in "${members[@]}"; doo
-      calc_coordinates_process_member || fail
-      if [[ "${missing_dims:-}" ]]; then
-        break
-      fi
-    end_for
-  end_function
-  handle_return
-}
-
-calc_coordinates_add_row() {
-  begin_function
-    local i new_coords=()
-    for (( i = 0; i < coordinate_fields_count; i++ )); do
-      local -n dim_value=d_${coordinate_fields[$i]}
-      if [[ "${dim_value:-}" == \$* ]]; then
-        # lets keep an eye on this for now
-        log_fatal "Internal error: bad dim_value"
-        debug_start
-      fi
-      coordinate_data+=( "$dim_value" )
-      new_coords+=( "$dim_value" )
-    done
-    log_verbose "${coord_type}_coordinate_data+=( ${new_coords[*]} )"
-  end_function
-  handle_return
-}
-
-calc_coordinates_next_unknown_dim() {
-  local current_dim_index=$1
-  begin_function
-    local dim dims changed=f phase=derive
-    begin_loop; doo
-
-      dim=${coordinate_fields[$current_dim_index]}
-      dims=${coordinate_fields_plural[$current_dim_index]}
-      local -n member=d_$dim \
-        members=d_$dims
-
-      if [[ ! "${members:-}" ]]; then
-
-        log_debug "Finding values for $dim in phase $phase"
-        local values= prev_phase=$phase
-        if [[ $phase == derive ]]; then
-          expand_values_check_derive || fail
-        else
-          expand_values_check_default || fail
-        fi
-
-        if [[ "${values:-}" ]]; then
-
-          changed=t
-          if [[ "$phase" == default ]]; then
-            # go back to derive phase since calculating a new default could
-            # open up new derive possibilities
-            phase=derive
-          fi
-
-          log_debug "Resolved $dim with $prev_phase: ${values[*]:0:30}"
-
-          # don't support aliases here (yet?)
-          # local new_values
-          # expand_dim_members "${values[@]}" || fail
-
-          members=( "${values[@]}" )
-
-          if (( ${#members[*]} > 1 )); then
-            phase=unknown \
-            calc_coordinates_loop_members || fail
-            break
-          else
-            member=$members
-          fi
-
-        else
-          log_debug "Failed to resolve $dim in phase $prev_phase"
-          missing_dims+=( $dim )
-        fi
-
-      fi
-
-      (( current_dim_index++ ))
-      if (( $current_dim_index >= ${#coordinate_fields[*]} )); then
-        if (( ${#missing_dims[*]} > 0 )); then
-          if [[ $changed == t ]]; then
-            # an unknown dim was resolved, so we need to go through again to see if we can resolve more
-            changed=f
-            current_dim_index=0
-            missing_dims=()
-          else
-            if [[ $phase == derive ]]; then
-              phase=default
-              current_dim_index=0
-              missing_dims=()
-            else
-              break
-            fi
-          fi
-        else # all dims were resolved
-          calc_coordinates_add_row || fail
-          break
-        fi
-      fi
-
-    end_loop
-
-  end_function
-  handle_return
-}
-
-# inputs:
-#   coordinate_fields        array of dims to process
-#   coordinate_fields_plural array of dim plurals to process
-#   $1   index of dim to process
-calc_coordinates_next_known_dim() {
-  local current_dim_index=$1
-  begin_function
-    local dim dims
-    begin_loop; doo
-
-      dim=${coordinate_fields[$current_dim_index]}
-      dims=${coordinate_fields_plural[$current_dim_index]}
-      local -n member=d_$dim \
-        members=d_$dims
-
-      if [[ "${members:-}" ]]; then
-
-        local member_array=( $members )
-        if (( ${#member_array[*]} > 1 )); then
-          phase=known \
-          calc_coordinates_loop_members || fail
-          break
-        else
-          member=$members
-        fi
-
-      else
-        missing_dims+=( $dim )
-      fi
-
-      (( current_dim_index++ ))
-      if (( current_dim_index >= ${#coordinate_fields[*]} )); then
-        break
-      fi
-
-    end_loop
-
-    if [[ "${missing_dims:-}" ]]; then
-      log_debug "Attempting to resolve unknowns: ${missing_dims[*]}"
-      missing_dims=()
-      calc_coordinates_next_unknown_dim 0 || fail
     fi
 
   end_function
