.

diff --git a/lib/cell-lib b/lib/cell-lib
--- a/lib/cell-lib
+++ b/lib/cell-lib
@@ -81,15 +81,19 @@ get_tmp_file() {
 }
 
 write_to_context() {
-  local context_type=$context_type new_type=$1 
+  local context_type=$context_type new_type=$1 context_file=${context_file:-}
   local -n _content=$2
   begin_function_lo
+    if [[ ! "$context_file" ]]; then
+      context_file=$context_path-$context_type.new
+    fi
+
     last_type=${last_type:-var}
     if [[ $last_type == fun || $new_type == fun ]]; then
-      echo >>$context_path-$context_type.new || fail
+      echo >>$context_file || fail
     fi
     trim_ws _content
-    echo "${_content}" >>$context_path-$context_type.new || fail
+    echo "${_content}" >>$context_file || fail
     last_type=$new_type
     eval "$_content" || {
       if [[ "${var_full_path:-}" ]]; then
@@ -357,7 +361,12 @@ load_derive_table() {
       fi
     fi
 
-    load_dna_tab $dtp derive_table_$name || fail
+    local type=${dtp##*.}
+    if [[ $type == tab ]]; then
+      load_dna_tab $dtp derive_table_$name || fail
+    else
+      load_dna_vtab $dtp derive_table_$name || fail
+    fi
 
     local row_count field_count data_count
     field_count=${#derive_table_fields[*]}
@@ -378,25 +387,59 @@ load_derive_table() {
 }
 
 # inputs:
-#   $1   path to derive table
-#   $2   name of derive table
-add_derive_table() {
+#   name
+#   cache_path
+add_derive_item_table() {
+  # loop over each
+}
+
+# inputs:
+#   $1          path to derive item
+#   $2          name of derive item
+#   cache_path
+add_derive_item() {
   local derive_path=$1 name=${2:-}
   begin_function_grip
+
+    debug_start
 
     local name
     if [[ ! "$name" ]]; then
       name=${derive_path##*/}
-      name=${name%.*tab}
+      name=${name%.*}
       name=${name//-/_}
+      name=${name#derive_}
     fi
 
-    derive_tables+=( $name )
+    local type=${derive_path##*.}
+    case $type in
+      *tab)
+        local -n dtp=derive_table_${name}_path
+        dtp=$derive_path
+        load_derive_table $name || fail
+        add_derive_item_table || fail
+        derive_tables+=( $name )
 
-    local -n dtp=derive_table_${name}_path
-    dtp=$derive_path
+        context_file=$cache_path \
+        write_to_context var derive_table_${name}_path || fail
 
-    write_vars_to_context derive_table_${name}_path || fail
+      ;;
+      fun)
+        local code
+        load_fun_to_code $var_full_path derive_function_$name || fail
+        eval "$code" || fail
+        add_derive_item_function || fail
+        derive_functions+=( $name )
+
+        context_file=$cache_path \
+        write_to_context fun code || fail
+
+      ;;
+      *)
+        log_fatal "Unidentified file in derive folder: $dt. It should either be a table (ending in .tab) or a function (ending in .fun)."
+        fail1
+      ;;
+    esac
 
   end_function
   handle_return
@@ -2115,6 +2158,7 @@ init_context() {
     default_anchor_dims= \
     default_freshness= \
     default_strategies=crl \
+    derive_caches= \
     dna_up_files=() \
     implicit_dims=() \
     key_path= \
@@ -3072,39 +3116,46 @@ build_context_gather_derive_tables_single() {
       build_context_gather_derive_tables_single ${start_path%/*} || fail
     fi
 
-    lib_dt_path=$start_path/.lib/derive
+    local lib_dt_path=$start_path/.lib/derive
 
     if [[ -d $lib_dt_path ]]; then
-      local dt from_written=f files links link
+      local dt files links link \
+        cache_path=$start_path/.lib/derive_cache \
 
-      links=$(find -L $lib_dt_path -type l -not -name '.*' -name '*.*tab' | sort -g) || fail
-      for link in $links; do
+      if [[ -f $cache_path ]]; then
+        source $cache_path || fail
+      else # build the cache
 
-        local real_path=$(realpath -m $link)
-        local real_path_parent=${real_path%/*}
+        log_debug "Generating derive cache for $lib_dt_path"
 
-        if [[ -d $real_path_parent/.dna && $real_path == /work/* ]]; then
-          dna_up_files+=( "$link" )
-        else
-          log_fatal "Broken link found when trying to gather derive tables: $link"
-          fail1
+        if [[ -f $cache_path.new ]]; then
+          rm $cache_path.new || fail
         fi
 
-        add_derive_table $link || fail
+        files=$(find -L $lib_dt_path \( -type f -or -type l \) -not -name '.*' -name '*.*tab' | sort -g) || fail
+        for dt in $files; do
 
-      done; maybe_break
+          dna_up_files+=( "$dt" )
 
-      files=$(find -L $lib_dt_path -type f -not -name '.*' -name '*.*tab' | sort -g) || fail
-      for dt in $files; do
+          if [[ ! -f $dt ]]; then
+            local real_path=$(realpath -m $dt)
+            local real_path_parent=${real_path%/*}
+            if [[ -d $real_path_parent/.dna && $real_path == /work/* ]]; then
+              log_debug "Executing cell update to generate $dt"
+              load_dna_contents_update_cell $real_path || fail
+            else
+              log_fatal "Broken link found when trying to gather derive tables: $dt"
+              fail1
+            fi
+          fi
 
-        if [[ $from_written == f ]]; then
-          echo "$NL# FROM $lib_dt_path" >>$context_path-$context_type.new || fail
-          from_written=t
-        fi
+          add_derive_item $dt || fail
 
-        add_derive_table $dt || fail
+        done; maybe_break
 
-      done; maybe_break
+        # TODO mv cache.new to cache
+
+      fi
     fi
 
   end_function
@@ -3115,8 +3166,9 @@ build_context_gather_derive_tables() {
   begin_function_grip
 
     derive_tables=()
+    derive_functions=()
     build_context_gather_derive_tables_single $cell_path || fail
-    write_vars_to_context derive_tables || fail
+    write_vars_to_context derive_tables derive_functions || fail
 
   end_function
   handle_return
@@ -3135,7 +3187,7 @@ build_context_trunk() {
 
     build_context_trunk_dna || fail
 
-    if (( ${#all_dims[*]} > 0 )); then
+    if [[ "$trunk_dims$sub_dims$control_props$data_props" ]]; then
 
       build_context_gather_derive_tables || fail
 
@@ -3153,7 +3205,6 @@ build_context_trunk() {
       fi
 
     fi
-
 
     if [[ ! -d $status_path ]]; then
       mkdir -p $status_path || fail
@@ -5606,8 +5657,6 @@ switch_context() {
                 else
                   log_info "Cell already clean: $cell_to_clean => $short_cell"
                 fi
-                #  no we want to clean all matching cells
-                #remove_word_from_string clean_cells "$cell_to_clean" 
                 cells_already_cleaned+=" $cell_path"
                 break
               fi
@@ -5626,6 +5675,12 @@ switch_context() {
         fi
 
         source $context_path || fail
+        if [[ "$derive_caches" ]]; then
+          local derive_cache
+          for derive_cache in $derive_caches; do
+            source $derive_cache || fail
+          done
+        fi
 
         if [[ -f $context_path-branch-coords ]]; then
           source $context_path-branch-coords || fail
