.

diff --git a/lib/clean-lib b/lib/clean-lib
--- a/lib/clean-lib
+++ b/lib/clean-lib
@@ -85,7 +85,7 @@ clean_cell() {
           rm -rf $x &>/dev/null
         end_for
         clean_cell_remove_trunk_context || fail
-        clean_derive_caches $cell_path || fail
+        #clean_derive_caches $cell_path || fail
       ;;
       co*)
         if [[ -d $cell_path/.cyto ]]; then
