Fix dna move bugs

diff --git a/lib/dna-link b/lib/dna-link
--- a/lib/dna-link
+++ b/lib/dna-link
@@ -7,14 +7,14 @@ dna_link() {
 local from=$1; shift
 local to=$1
 
+if [[ ! -f $from/cube-context ]]; then
+  err "Source cube is invalid: $from"
+  err "Either it is not a cube, or the folder doesn't exist"
+  return 1
+fi
+
 trace 0 "Linking cell ${from##*/work/} to ${to##*/work/}"
 begin_function
-
-  if [[ ! -f $from/cube-context ]]; then
-    err "Source cube is invalid: $from"
-    err "Either it is not a cube, or the folder doesn't exist"
-    fail1
-  fi
 
   if [[ ${to} != ${to%/} ]]; then
     to=$to/${from##*/}
@@ -22,7 +22,7 @@ begin_function
 
   if [[ -e $to || -L $to ]]; then
     if [[ ${force:-f} == t ]]; then
-      rm -rf $to || fail
+      maybe rm -r $to || fail
     else
       err "Target cube already exists or a folder or link is already there."
       err "Delete it if you want to create it again"
@@ -34,7 +34,7 @@ begin_function
   # ln -s $(realpath --relative-to=${to%/*} $from) $to || fail
 
   # for absolute link
-  ln -s $(realpath -eL $from) $to || fail
+  maybe ln -s $(realpath -eL $from) $to || fail
 
 end_function
 handle_return
