Add maybe function

diff --git a/lib/dna-link b/lib/dna-link
--- a/lib/dna-link
+++ b/lib/dna-link
@@ -13,7 +13,7 @@ begin_function
   if [[ ! -f $from/cube-context ]]; then
     err "Source cube is invalid: $from"
     err "Either it is not a cube, or the folder doesn't exist"
-    fail
+    fail1
   fi
 
   if [[ ${to} != ${to%/} ]]; then
@@ -26,11 +26,15 @@ begin_function
     else
       err "Target cube already exists or a folder or link is already there."
       err "Delete it if you want to create it again"
-      fail
+      fail1
     fi
   fi
 
-  ln -s $(realpath --relative-to=${to%/*} $from) $to || fail
+  # for relative link
+  # ln -s $(realpath --relative-to=${to%/*} $from) $to || fail
+
+  # for absolute link
+  ln -s $(realpath -eL $from) $to || fail
 
 end_function
 handle_return
diff --git a/lib/post-bash b/lib/post-bash
--- a/lib/post-bash
+++ b/lib/post-bash
@@ -800,6 +800,44 @@ local first=${contents[0]}
 [[ "${first%\*}" != "$first" ]]
 }
 
+pretend=${pretend:-ask}
+maybe() {
+local command_to_execute="$*"
+local execute
+
+case $pretend in
+  t)
+    execute=t
+  ;;
+  f)
+    echo "Pretending to execute: $command_to_execute" >&fd_trace
+    execute=f
+  ;;
+  a|ask)
+    local response
+    echo "Command to be executed: $command_to_execute" >&fd_trace
+    read -p 'Are you sure you want to run this? [y/n] ' -s -n1 response >&fd_trace
+    if [[ "$response" == y ]]; then
+      echo "yes" >&fd_trace
+      execute=t
+    else
+      echo "no" >&fd_trace
+      execute=f
+    fi
+  ;;
+  *)
+    err "Invalid pretend value: $pretend. Must be one of: t f ask"
+    return 1
+  ;;
+esac
+
+if [[ $execute == t ]]; then
+  eval "$command_to_execute" || return $?
+fi
+
+return 0
+}
+
 # used in if condition to be more clear.
 # instead of:
 #   if ! diff $f1 $f2; then ...
