add locking and parameterize out and meta

diff --git a/lib/execute b/lib/execute
--- a/lib/execute
+++ b/lib/execute
@@ -5,8 +5,9 @@
 execute() {
 
 local subject=$1
+local lock_timeout=${lock_timeout:-0}
 
-trace 0 "Executing subject: $subject"
+trace 0 "Executing subject: $small_subject"
 
 begin_function
 
@@ -17,20 +18,7 @@ trace -5 "Sourcing context files"
 init_context || fail
 load_context "$subject_folder" || fail
 
-if [ $subject_type == folder ]; then
-
-  trace -5 "Checking if subject needs to be executed"
-  is_refresh_needed "$subject" || fail
-  if [ $refresh_needed == f ]; then
-    trace 0 "Refresh is not needed"
-    succeed
-  else
-    trace 0 "Refresh is needed"
-  fi
-
-fi
-
-deal_with "$subject" || fail
+deal_with || fail
 
 trace 0 "Subject executed successfully"
 
@@ -46,7 +34,7 @@ subject_folder=$subject
 if [ ! -d "$subject" ]; then
   subject_folder="${subject%/*}"
   if  [ ! -d "$subject_folder" ]; then
-    err "Subject doesn't exist: $subject"
+    err "Subject doesn't exist: $small_subject"
     fail
   else
     if [ -f "$subject" ]; then
@@ -62,26 +50,67 @@ handle_return
 
 deal_with() {
 
-local file_or_folder handler_to_try handler_path_to_try handler_found handler_name
-file_or_folder=$1
-trace 0 "Figuring out what to do with $file_or_folder"
+local handler_to_try handler_path_to_try handler_found handler_name
+trace 0 "Figuring out what to do with $subject"
 
 begin_function
 
-find_handler "$file_or_folder" || fail
+if [ $subject_type == folder ]; then
+
+  trace -5 "Checking if subject needs to be executed"
+  is_refresh_needed "$subject" || fail
+  if [ $refresh_needed == f ]; then
+    trace 0 "Refresh is not needed"
+    succeed
+  else
+    trace 0 "Refresh is needed"
+  fi
+
+fi
+
+find_handler "$subject" || fail
 
 if [ "$handler_found" ]; then
+
+  if [ $subject_type == folder ]; then
+    lock "$subject_meta/lock" $lock_timeout || fail
+    touch "$subject_meta/last-run-began" || fail
+    mkdir -p "$subject_out" || fail
+    mkdir -p "$subject_log" || fail
+    mkdir -p "$subject_meta" || fail
+  fi
+
   trace -5 "Executing handler $handler_found"
   source "$handler_found" || fail
-  handle "$file_or_folder" || fail
+
+  [ $subject_type == folder ] && tee_output_to "$subject_log/log-current"
+
+  local handler_failed=f
+  handle "$subject" || handler_failed=t
+
+  if [ $subject_type == folder ]; then
+    untee_output
+    touch "$subject_meta/last-run-ended" || fail
+    unlock "$subject_meta/lock"
+    if [ "$handler_failed" == f ]; then
+      touch -r "$subject_meta/last-run-began" "$subject_meta/last-success-began" || fail
+      mv "$subject_log/log-current" "$subject_log/log-last-error"
+      ln -s "$subject_log/log-last-error" "$subject_log/log-previous"
+    else
+      mv "$subject_log/log-current" "$subject_log/log-last-success"
+      ln -s "$subject_log/log-last-success" "$subject_log/log-previous"
+    fi
+  fi
+
 else # no handler found
-  if [ -d "$file_or_folder" ]; then
-    trace 0 "Processing contents of $file_or_folder folder"
-    begin_for file_or_folder in $(find "$subject" -mindepth 1 -maxdepth 1 -not -name ".*" | sort); doo
-      execute "$file_or_folder" || fail
+  if [ -d "$subject" ]; then
+    trace 0 "Processing contents of $subject folder"
+    local f
+    begin_for f in $(find "$subject" -mindepth 1 -maxdepth 1 -not -name ".*" | sort); doo
+      execute "$f" || fail
     end_for
   else
-    trace -5 "Ignoring file $file_or_folder"
+    trace -5 "Ignoring file $subject"
   fi
 fi
 
@@ -125,15 +154,20 @@ is_refresh_needed() {
 local subject=$1
 
 if [ ! -d "$subject" ]; then
-  return 0
-fi
-
-if [ ! -e "$subject/out" ]; then 
   refresh_needed=t
   return 0
 fi
 
-local newer_file_found=$(find "$subject_folder" -mindepth 1 -not -name out -not -name meta -not -name .git -newer "$subject_folder/out" -print -quit)
+if [ ! -e "$subject_meta/last-success-began" ]; then 
+  refresh_needed=t
+  return 0
+fi
+
+local newer_file_found=$(
+  find "$subject_folder" -mindepth 1 \
+    -not -name out -not -name meta -not -name log -not -name .git \
+    -newer "$subject_meta/last-success-began" -print -quit
+  )
 if [ "$newer_file_found" ]; then 
   trace -5 "Found file that is newer than out: $newer_file_found"
   refresh_needed=t
@@ -156,3 +190,15 @@ is_subject_fresh() {
 subject_fresh=t
 }
 
+tee_output_to() {
+local target=$1
+exec 1> >(tee "$target")
+exec 2> >(tee -a "$target")
+exec ${fd_trace}> >(tee -a "$target")
+}
+
+untee_output() {
+exec 1> &${fd_original_out}
+exec 2> &${fd_original_err}
+exec ${fd_trace}> &${fd_original_trace}
+}
