Make ? faster

diff --git a/lib/help-lib b/lib/help-lib
--- a/lib/help-lib
+++ b/lib/help-lib
@@ -376,21 +376,21 @@ show_cell_help() {
 
     setup_dims || fail
 
-    if [[ $cell_is_leaf == f ]]; then
-      coord_limit=2 \
-      calc_coords_branch || fail
-    fi
-    fence
+    #if [[ $cell_is_leaf == f ]]; then
+    #  coord_limit=2 \
+    #  calc_coords_branch || fail
+    #fi
+    #fence
 
-    local branch_coordinate_data_count=${#branch_coordinate_data[*]} \
-      branch_coordinate_field_count=${#branch_coordinate_fields[*]} \
+    #local branch_coordinate_data_count=${#branch_coordinate_data[*]} \
+    #  branch_coordinate_field_count=${#branch_coordinate_fields[*]} \
 
-    local branch_coordinate_rows=$(( branch_coordinate_data_count / branch_coordinate_field_count ))
-    if (( branch_coordinate_rows == 1 )); then
-      target_dim_var_type=ddim \
-      table=branch_coordinate \
-      convert_table_to_dims || fail
-    fi
+    #local branch_coordinate_rows=$(( branch_coordinate_data_count / branch_coordinate_field_count ))
+    #if (( branch_coordinate_rows == 1 )); then
+    #  target_dim_var_type=ddim \
+    #  table=branch_coordinate \
+    #  convert_table_to_dims || fail
+    #fi
 
     indent=0
 
@@ -445,7 +445,7 @@ show_cell_help() {
     fi
 
     local dim member show_header=t
-    if (( branch_coordinate_rows == 1 )); then
+    if (( ${branch_coordinate_rows:-0} == 1 )); then
       show_branch_members || fail
     fi
 
