.

diff --git a/lib/help-lib b/lib/help-lib
--- a/lib/help-lib
+++ b/lib/help-lib
@@ -298,6 +298,36 @@ show_upstream_recursive() {
   handle_return
 }
 
+show_reactor_single() {
+  local reactor_name=$1 reactor_path=$2
+  begin_function
+    local message="$reactor_name"
+    if (( command_detail > -1 )); then
+      message+=": $reactor_path"
+    fi
+    out "$message"
+    #  not sure if this makes sense here
+    #if (( command_detail > 0 )) || [[ $recursive_command == t ]]; then
+    #  # recursive
+    #  fork show_upstream_recursive $reactor_path || fail
+    #fi
+  end_function
+  handle_return
+}
+
+show_reactors() {
+  begin_function
+    local reactor_name
+    debug_start
+    begin_for reactor_name in ${reactors[*]}; doo
+      local reactor_var=${reactor_name//-/_}
+      local -n reactor_path=reactor_${reactor_var}_path
+      show_reactor_single $reactor_name $reactor_path || fail
+    end_for
+  end_function
+  handle_return
+}
+
 show_branch_members() {
   begin_function
     if [[ "${trunk_dims:-}" ]]; then
