Fix some help bugs

diff --git a/lib/help-lib b/lib/help-lib
--- a/lib/help-lib
+++ b/lib/help-lib
@@ -610,9 +610,9 @@ show_parameter_help_single() {
         local aliases=${parameter_aliases[$i]:-}
         if [[ "$name" == "${parameter_names[$i]}"
            || " $aliases " == *" $name "* ]]; then
-          found=t
+          found_help=t
           show_parameter_help_inner || fail
-          succeed
+          abort
         fi
       end_for
     end_for
@@ -623,8 +623,8 @@ show_parameter_help_single() {
       begin_for dim in ${dims[*]}; doo
         if [[ "$name" == "$dim" ]]; then
           show_dimension $dim || fail
-          found=t
-          succeed
+          found_help=t
+          abort
         fi
       end_for
     end_for
@@ -636,13 +636,13 @@ show_parameter_help_single() {
 show_parameter_help() {
   local names=$* indent=${indent:-0}
   begin_function
-    local found
+    local found_help
     out "Parameters:"
     indent=$((indent+2)) 
     begin_for name in $names; doo
-      found=f
+      found_help=f
       show_parameter_help_single || fail
-      if [[ $found == f ]]; then
+      if [[ $found_help == f ]]; then
         log_warn "No description found for parameter $name" || fail
       fi
     end_for
@@ -656,13 +656,14 @@ show_parameters_help() {
     load_branch_info || fail
     anchor_dims= \
     switch_context $cell_path || fail
-    begin_for p in ${parameter_questions[*]}; doo
-      if [[ " ${parameter_delayed_questions:-} " == *\ $p\ * ]]; then
-        continue
-      fi
-      show_parameter_help $p || fail
-      showed_parameter_help=t
-    end_for
+    handle_questions || fail
+    #begin_for p in ${parameter_questions[*]}; doo
+    #  if [[ " ${parameter_delayed_questions:-} " == *\ $p\ * ]]; then
+    #    continue
+    #  fi
+    #  show_parameter_help $p || fail
+    #  showed_parameter_help=t
+    #end_for
   end_function
   handle_return
 }
