Fix lifted bugs

diff --git a/lib/lifted-bash b/lib/lifted-bash
--- a/lib/lifted-bash
+++ b/lib/lifted-bash
@@ -12,82 +12,24 @@ set -u +Hm -o pipefail
 shopt -s expand_aliases extglob dotglob globstar huponexit
 umask 0077  # to make created files readable only by the user by default
 
-handle_special_vars() {
-  local -n vars=$1
-  local t new_vars=
-  for t in $vars; do
-    if [[ ! "${t#^}" =~ ^[a-zA-Z0-9_]+$ ]]; then
-      echo "Invalid var name: ${t#^}" >&$fd_original_err
-      vars=
-      return 1
-    fi
-  done
-  vars=${new_vars% }
-}
+set -u +Hm -o pipefail
+shopt -s expand_aliases extglob dotglob globstar huponexit
+umask 0077  # to make created files readable only by the user by default
+
+if [[ ! -v fd_original_in ]]; then
+  exec {fd_original_in}<&0
+  exec {fd_original_out}>&1
+  exec {fd_original_err}>&2
+fi
+
+# don't actually need the fds, only need the allocated descriptor numbers
+exec 10<&0
+exec 11>&1
+exec 12>&2
 
 # Run this near the top of scripts using this functionality, after the commandline parameters 
 #   have been processed
 bash_lifted_init() {
-
-  if [[ ! -v fd_original_in ]]; then
-    exec {fd_original_in}<&0
-    exec {fd_original_out}>&1
-    exec {fd_original_err}>&2
-  fi
-
-  # don't actually need the fds, only need the allocated descriptor numbers
-  exec 10<&0
-  exec 11>&1
-  exec 12>&2
-
-  NL=$'\n'
-  CR=$'\r'
-  TAB=$'\t'
-  ESC=$'\e'
-  DQ='"'
-  SQ="'"
-  CONTROL_N=$'\xe'
-  CONTROL_O=$'\xf'
-
-     DIM_RED=$'\033[0;31m'
-       RED=$'\033[1;31m'
-   DIM_GREEN=$'\033[0;32m'
-     GREEN=$'\033[1;32m'
-  DIM_YELLOW=$'\033[0;33m'
-    YELLOW=$'\033[1;33m'
-    DIM_BLUE=$'\033[0;34m'
-      BLUE=$'\033[1;34m'
-  DIM_PURPLE=$'\033[0;35m'
-    PURPLE=$'\033[1;35m'
-    DIM_CYAN=$'\033[0;36m'
-      CYAN=$'\033[1;36m'
-   DIM_WHITE=$'\033[0;37m'
-     WHITE=$'\033[1;37m'
-   DIM_BLACK=$'\033[0;38m'
-     BLACK=$'\033[1;38m'
-     RESET=$'\033[0m'
-  CLEAR_LINE=$'\033[2K\r'
-     CLEAR=$'\033[2J'
-  CLEAR_SCREEN=$'\033[2J\r\033[H'
-   CURSOR_UP=$'\033[1A'
-     REVERSE=$'\033[7m'
-   HIGHLIGHT=$'\033[1;37m'
-
-  COL0=$'\n\e[A\e[0G'     COL5=$'\n\e[A\e[5G'     COL10=$'\n\e[A\e[10G'
-  COL15=$'\n\e[A\e[15G'   COL20=$'\n\e[A\e[20G'   COL25=$'\n\e[A\e[25G'
-  COL30=$'\n\e[A\e[30G'   COL35=$'\n\e[A\e[35G'   COL40=$'\n\e[A\e[40G'
-  COL45=$'\n\e[A\e[45G'   COL50=$'\n\e[A\e[50G'   COL55=$'\n\e[A\e[55G'
-  COL60=$'\n\e[A\e[60G'   COL65=$'\n\e[A\e[65G'   COL70=$'\n\e[A\e[70G'
-  COL75=$'\n\e[A\e[75G'   COL80=$'\n\e[A\e[80G'   COL85=$'\n\e[A\e[85G'
-  COL90=$'\n\e[A\e[90G'   COL95=$'\n\e[A\e[95G'   COL100=$'\n\e[A\e[100G'
-  COL110=$'\n\e[A\e[110G' COL120=$'\n\e[A\e[120G' COL130=$'\n\e[A\e[130G'
-  COL140=$'\n\e[A\e[140G' COL150=$'\n\e[A\e[150G' COL160=$'\n\e[A\e[160G'
-  COL170=$'\n\e[A\e[170G' COL180=$'\n\e[A\e[180G' COL190=$'\n\e[A\e[190G'
-  COL200=$'\n\e[A\e[200G'
-
-  eval "printf -v hbar_tilde '%.s~' {1..${COLUMNS:-80}}"
-  eval "printf -v hbar_equals '%.s=' {1..${COLUMNS:-80}}"
-  eval "printf -v hbar_minus '%.s-' {1..${COLUMNS:-80}}"
 
   debug_id_current=0
 
@@ -102,6 +44,51 @@ bash_lifted_init() {
   trace_vars=${trace_vars:-${trace_var:-${traces:-${trace:-}}}}
 
   handle_special_vars trace_vars || return 1
+
+  NL=$'\n'
+  CR=$'\r'
+  TAB=$'\t'
+  ESC=$'\e'
+  DQ='"'
+  SQ="'"
+  CONTROL_N=$'\xe'
+  CONTROL_O=$'\xf'
+
+	   DIM_RED=$'\033[0;31m'
+		   RED=$'\033[1;31m'
+	 DIM_GREEN=$'\033[0;32m'
+		 GREEN=$'\033[1;32m'
+	DIM_YELLOW=$'\033[0;33m'
+		YELLOW=$'\033[1;33m'
+	  DIM_BLUE=$'\033[0;34m'
+		  BLUE=$'\033[1;34m'
+	DIM_PURPLE=$'\033[0;35m'
+		PURPLE=$'\033[1;35m'
+	  DIM_CYAN=$'\033[0;36m'
+		  CYAN=$'\033[1;36m'
+	 DIM_WHITE=$'\033[0;37m'
+		 WHITE=$'\033[1;37m'
+	 DIM_BLACK=$'\033[0;38m'
+		 BLACK=$'\033[1;38m'
+		 RESET=$'\033[0m'
+	CLEAR_LINE=$'\033[2K\r'
+		 CLEAR=$'\033[2J'
+  CLEAR_SCREEN=$'\033[2J\r\033[H'
+	 CURSOR_UP=$'\033[1A'
+	   REVERSE=$'\033[7m'
+	 HIGHLIGHT=$'\033[1;37m'
+
+  COL0=$'\n\e[A\e[0G'     COL5=$'\n\e[A\e[5G'     COL10=$'\n\e[A\e[10G'
+  COL15=$'\n\e[A\e[15G'   COL20=$'\n\e[A\e[20G'   COL25=$'\n\e[A\e[25G'
+  COL30=$'\n\e[A\e[30G'   COL35=$'\n\e[A\e[35G'   COL40=$'\n\e[A\e[40G'
+  COL45=$'\n\e[A\e[45G'   COL50=$'\n\e[A\e[50G'   COL55=$'\n\e[A\e[55G'
+  COL60=$'\n\e[A\e[60G'   COL65=$'\n\e[A\e[65G'   COL70=$'\n\e[A\e[70G'
+  COL75=$'\n\e[A\e[75G'   COL80=$'\n\e[A\e[80G'   COL85=$'\n\e[A\e[85G'
+  COL90=$'\n\e[A\e[90G'   COL95=$'\n\e[A\e[95G'   COL100=$'\n\e[A\e[100G'
+  COL110=$'\n\e[A\e[110G' COL120=$'\n\e[A\e[120G' COL130=$'\n\e[A\e[130G'
+  COL140=$'\n\e[A\e[140G' COL150=$'\n\e[A\e[150G' COL160=$'\n\e[A\e[160G'
+  COL170=$'\n\e[A\e[170G' COL180=$'\n\e[A\e[180G' COL190=$'\n\e[A\e[190G'
+  COL200=$'\n\e[A\e[200G'
 
   DEBUG_COLOR=$CYAN
   DIM_DEBUG_COLOR=$DIM_CYAN
@@ -126,13 +113,36 @@ bash_lifted_init() {
     echo "${DEBUG_COLOR}Disabling all debug features to boost speed to max" >&2
   fi
 
-  help_depth=0
   parameter_questions=() 
+
+  declare -gA log_level_num_map=( 
+    [off]=0
+    [fatal]=1 
+    [error]=2 
+    [warn]=3 
+    [info]=4 
+    [verbose]=5 
+    [debug]=6 
+    [trace]=7 
+    [all]=8
+    )
+
+  declare -gA log_level_color_map=( 
+    [all]= 
+    [trace]= 
+    [debug]= 
+    [verbose]= 
+    [info]=
+    [warn]=$YELLOW
+    [error]=$RED 
+    [fatal]=$RED 
+    [off]=
+    )
 
   # Make sure that Control-C exits this script, even if running a subcommand which doesn't handle Control-C properly.
   trap '
-  trap - INT # restore default INT handler
-  kill -s INT "$$"
+	trap - INT # restore default INT handler
+	kill -s INT "$$"
   ' INT
 
   # some required defaults
@@ -141,6 +151,10 @@ bash_lifted_init() {
 
   export tracing_depth=${tracing_depth:-0}
   export no_trace_depth=${no_trace_depth:-0}
+
+  eval "printf -v hbar_tilde '%.s~' {1..${COLUMNS:-80}}"
+  eval "printf -v hbar_equals '%.s=' {1..${COLUMNS:-80}}"
+  eval "printf -v hbar_minus '%.s-' {1..${COLUMNS:-80}}"
 
   pretend_filter=
   case "${pretend:-}" in
@@ -218,7 +232,6 @@ debugger_init() {
     handle_user_interrupt
     is_array
     is_set
-    load_log_vars_and_write_to_log
     log_debug
     log_error
     log_fatal
@@ -273,6 +286,19 @@ debugger_init() {
     rm -rf $tmp_folder/debug_highlight &>/dev/null
     mkdir -p $tmp_folder/debug_highlight || exit 1
   fi
+}
+
+handle_special_vars() {
+  local -n vars=$1
+  local t new_vars=
+  for t in $vars; do
+    if [[ ! "${t#^}" =~ ^[a-zA-Z0-9_]+$ ]]; then
+      echo "Invalid var name: ${t#^}" >&$fd_original_err
+      vars=
+      return 1
+    fi
+  done
+  vars=${new_vars% }
 }
 
 # Used to pass vars to parent of forked processes
@@ -797,7 +823,6 @@ if [[ "${no_debug:-f}" == f ]]; then
 alias begin_function_hi='
   (( no_trace_depth++ )) || true
   local return_value=0 break_out=f function_level=2 repair_attempted=f current_function=${function_override:-${FUNCNAME:-unknown}} function_override= timebox_stack=( $FUNCNAME ) trace_time_start trace_time_start_debug_id trace_time_stop time_dur stack_pos=$(( ${#FUNCNAME[*]} - 1 ))
-  (( log_depth_current++ )) || true
   if [[ $trace_time == t ]]; then
     trace_time_open
   fi
@@ -925,8 +950,6 @@ alias handle_return='
     2)
       timebox=$FUNCNAME
       trace_time_close
-      load_log_vars_and_write_to_log
-      (( log_depth_current-- )) || true
     ;;
     1)
       timebox=$FUNCNAME
