.

diff --git a/lib/omni-navigator b/lib/omni-navigator
--- a/lib/omni-navigator
+++ b/lib/omni-navigator
@@ -178,10 +178,11 @@ omni_select_cursor='
     output_array=cursor_${cursor}_output_array \
     plane_depth_map=cursor_${cursor}_plane_depth_map \
     plane_map=cursor_${cursor}_plane_map \
-    plane_stack_map=cursor_${cursor}_plane_stack_map 
+    plane_stack_map=cursor_${cursor}_plane_stack_map \
 
   local fork_id=${log_file_id#*:} \
-    plane_map_size=${#plane_map[*]} 
+    plane_map_size=${#plane_map[*]} \
+    plane_id=0 \
 '
 
 # inputs:
@@ -265,13 +266,29 @@ enter_log_file() {
   return 0
 }
 
+# inputs:
+#   index: where in the current log to extract the vars from
+#   vars: space separated list of vars to extract from the given log line
+omni_extract_vars() {
+  local line=${log_array[$index]} \
+    ts pid log_id depth level action function entries info old_log_file new_log_file \
+    var entries
+  if [[ "$line" == \=\ * ]]; then
+    entries=${line#= }
+    eval "$entries" || return 1
+    for var in $vars; do
+      eval "declare -g $var=\$$var"
+    done
+  fi
+  return 0
+}
+
 omni_step_in() {
   local action=${action_map[$index]}
   if [[ $action == log_to ]]; then
-    local i=$index line=${log_array[$index]} \
-      ts pid log_id depth level action function entries info new_log_file
-    entries=${line#= }
-    eval "$entries" || return 1
+    local new_log_file
+    vars=new_log_file \
+      omni_extract_vars || return 1
     if [[ ! "${new_log_file:-}" ]]; then
       log_fatal "log_to action is missing the new_log_file key"
       return 1
@@ -314,7 +331,29 @@ omni_search() {
     local plane_id=${plane_map[$index]}
 
     if [[ $skip_first == t ]]; then
-      (( index++ ))
+
+      if [[ $deep == t && ${action_map[$index]} == log_to ]]; then
+
+        index=$from_index \
+          vars=new_log_file \
+          omni_extract_vars || fail
+
+        if [[ -e "$new_log_file" ]]; then
+          from_log=$new_log_file
+            from_index=0
+            omni_search || fail
+          if [[ "$found_index" ]]; then
+            index=$found_index
+            log_file=$found_log
+          fi
+        else
+          log_error "Internal error: log points to non-existent file: $new_log_file"
+        fi
+
+      else
+        (( index++ ))
+      fi
+
     fi
 
     begin_while (( index < plane_map_size )); doo
@@ -325,11 +364,11 @@ omni_search() {
 }
 
 omni_next_error() {
-from_log=$log_file
-  from_index=$index
-  skip_first=t
-  direction=1
-  find_level='(error|fatal)'
+from_log=$log_file \
+  from_index=$index \
+  skip_first=t \
+  direction=1 \
+  find_level='(error|fatal)' \
   omni_search || return 1
 if [[ $found_index ]]; then
   if [[ $log_file != $found_log ]]; then
