.

diff --git a/lib/omni-navigator b/lib/omni-navigator
--- a/lib/omni-navigator
+++ b/lib/omni-navigator
@@ -196,6 +196,8 @@ omni_select_cursor() {
       plane_stack_map=cursor_${cursor}_plane_stack_map \
       log_file_stack=cursor_${cursor}_log_file_stack \
       log_file_pos_stack=cursor_${cursor}_log_file_pos_stack \
+      function_call_stack=cursor_${cursor}_function_call_stack \
+
     update_cursor_vars || return 1
   fi
 
@@ -393,31 +395,61 @@ omni_extract_vars() {
 # Move to the next log line to search
 # This is meant to be able to move past the boundaries if there are no other possibilities
 omni_search_next() {
-  if [[ $deep == t && ${action_map[$index]} == log_to ]]; then
-    local new_index=0
-    if [[ $direction == -1 ]]; then
-      new_index=-1
-    fi
-    local new_log_file
-    vars=new_log_file \
-      omni_extract_vars || fail
-    omni_enter_sub_log || return 1
-  else
-    (( index += direction ))
-    if [[ $direction == 1 ]]; then
-      if (( index >= log_array_size && ${#log_file_stack[*]} > 0 )); then
-        omni_exit_sub_log || return 1
+  begin_function_flat
+    if [[ $deep == t && ${action_map[$index]} == log_to ]]; then
+      local new_index=0
+      if [[ $direction == -1 ]]; then
+        new_index=-1
       fi
-    elif [[ $direction == -1 ]]; then
-      if (( index < 0 && ${#log_file_stack[*]} > 0 )); then
-        omni_exit_sub_log || return 1
-      fi
+      local new_log_file
+      vars=new_log_file \
+        omni_extract_vars || fail
+      omni_enter_sub_log || fail
     else
-      log_fatal "omni_search_next: invalid direction: $direction"
-      return 1
+
+      local plane_id=${plane_map[$index]} \
+        action
+
+      if [[ $deep == t && $direction == 1 ]]; then
+        action=${action_map[$index]}
+        if [[ $action == call ]]; then
+          function=
+          vars=function \
+            omni_extract_vars || fail
+          if [[ ! "$function" ]]; then
+            log_error "Bad log file: has call action without function"
+          fi
+          function_call_stack+=( $function )
+        fi
+      fi
+
+      (( index += direction ))
+
+      if [[ $direction == -1 ]]; then
+        action=${action_map[$index]}
+        if [[ $action == call ]]; then
+          unset function_call_stack[-1]
+        fi
+      fi
+
+      if (( index >= log_array_size || index < 0 )); then
+        # out of bounds
+        if [[ $direction == 1 ]]; then
+          if (( index >= log_array_size && ${#log_file_stack[*]} > 0 )); then
+            omni_exit_sub_log || fail
+          fi
+        elif [[ $direction == -1 ]]; then
+          if (( index < 0 && ${#log_file_stack[*]} > 0 )); then
+            omni_exit_sub_log || fail
+          fi
+        else
+          log_fatal "omni_search_next: invalid direction: $direction"
+          fail1
+        fi
+      fi
     fi
-  fi
-  return 0
+  end_function_flat
+  handle_return
 }
 
 omni_search_get_matches() {
@@ -484,6 +516,9 @@ omni_search() {
       index=$from_index
     fi
 
+    local original_log=$log_file \
+      original_index=$index
+
     local original_plane_id=${plane_map[$index]}
     local plane_id=$original_plane_id
 
@@ -509,6 +544,11 @@ omni_search() {
 
     end_while
 
+    # restore position of this cursor
+    new_log_file=$original_log \
+      omni_change_cursor_log || fail
+    index=$original_index
+
     # restore original cursor
     if [[ "$original_cursor" ]]; then
       new_cursor=$original_cursor \
@@ -519,54 +559,42 @@ omni_search() {
   handle_return
 }
 
-omni_next_error() {
+omni_copy_cursor() {
+  local from=$1 to=$2
 
-from_log=$log_file \
-  from_index=$index \
-  skip_first=t \
-  direction=1 \
-  find_level='(error|fatal)' \
-  find_action='return\([^0].*\)' \
-  omni_search || return 1
+  local -n \
+    from_log_file=cursor_${from}_log_file \
+    to_log_index=cursor_${to}_log_array_index \
 
-if [[ $found_index ]]; then
-  new_log_file=$found_log \
-    new_index=$found_index \
+  new_log_file=$from_log_file \
+    cursor=$to \
     omni_change_cursor_log || return 1
-  new_index=$found_index \
-    omni_change_index || return 1
-else
-  echo "No errors found." >&$fd_original_err
-fi
 
-return 0
+  to_log_index=from_log_index
+
+  return 0
 }
 
-# deprecated
-# inputs: 
-#   var
-#   offset
-#   plane_id plane_map
-omni_offset_index() {
-  local -n current_index=$var
-  local amount=$offset i adjusted=0 d=1
+omni_next_error() {
 
-  if (( amount < 0 )); then
-    d=-1
-    (( amount = -amount ))
+  local entry_matches
+
+  from_log=$log_file \
+    from_index=$index \
+    direction=1 \
+    find_level='(error|fatal)' \
+    find_action='return\([^0].*\)' \
+    omni_search || return 1
+
+  if [[ $entry_matches == t ]]; then
+    omni_copy_cursor s $cursor || return 1
+    new_cursor=$cursor omni_select_cursor || return 1
+  else
+    echo "No errors found." >&$fd_original_err
   fi
 
-  for (( i = current_index + d;
-         i >= 0 
-         && adjusted < amount 
-         && i < log_array_size;
-         i += d )); do
-    if (( plane_map[i] == plane_id )); then
-      current_index=$i
-      (( adjusted++ ))
-    fi
-  done
   return 0
+
 }
 
 omni_show_call_stack() {
