Add l option to soft interrupt

diff --git a/lib/omni-log b/lib/omni-log
--- a/lib/omni-log
+++ b/lib/omni-log
@@ -80,6 +80,51 @@ resolve_log_var() {
   esac
 }
 
+log_level_filter_changed() {
+
+  case $log_level_filter in
+    none)
+      log_format=
+    ;;
+    fatal|error|warn|info|verbose)
+      if [[ "$log_format" == default ]]; then
+        log_format='$level_color$message$RESET'
+      fi
+    ;;
+    debug)
+      if [[ "$log_format" == default ]]; then
+        log_format='$debug_id$level_color$message$RESET'
+      fi
+    ;;
+    trace|all)
+      if [[ "$log_format" == default ]]; then
+        log_format='$debug_id$level_color$action$COL25$function$COL50$log_vars$message$RESET'
+      fi
+    ;;
+    *)
+      log_fatal "Invalid log_level value. Must be one of: none, error, warn, info, verbose, debug, trace"
+      exit 1
+    ;;
+  esac
+
+  case $log_format in
+    tiny)
+      log_format='$level_color$message$RESET'
+    ;;
+    short)
+      log_format='$level_color$action$COL15$function$COL45$log_vars$message$RESET'
+    ;;
+    compact)
+      log_format='$level_color$action$function$log_vars$message$RESET'
+    ;;
+  esac
+
+  if [[ $show_debug_id == t || $show_debug_id == a ]]; then
+    log_format='$debug_id$level_color$message$RESET'
+  fi
+
+}
+
 omni_log_init() {
   begin_function
     local command="$*"  
@@ -113,47 +158,7 @@ omni_log_init() {
     declare -gA trace_var_value
 
     resolve_log_var || fail
-
-    case $log_level_filter in
-      none)
-        log_format=
-      ;;
-      fatal|error|warn|info|verbose)
-        if [[ "$log_format" == default ]]; then
-          log_format='$level_color$message$RESET'
-        fi
-      ;;
-      debug)
-        if [[ "$log_format" == default ]]; then
-          log_format='$debug_id$level_color$message$RESET'
-        fi
-      ;;
-      trace|all)
-        if [[ "$log_format" == default ]]; then
-          log_format='$debug_id$level_color$action$COL25$function$COL50$log_vars$message$RESET'
-        fi
-      ;;
-      *)
-        log_fatal "Invalid log_level value. Must be one of: none, error, warn, info, verbose, debug, trace"
-        exit 1
-      ;;
-    esac
-
-    case $log_format in
-      tiny)
-        log_format='$level_color$message$RESET'
-      ;;
-      short)
-        log_format='$level_color$action$COL15$function$COL45$log_vars$message$RESET'
-      ;;
-      compact)
-        log_format='$level_color$action$function$log_vars$message$RESET'
-      ;;
-    esac
-
-    if [[ $show_debug_id == t || $show_debug_id == a ]]; then
-      log_format='$debug_id$level_color$message$RESET'
-    fi
+    log_level_filter_changed
 
     var_stack=( ) \
       var_stack2=( ) \
