.

diff --git a/lib/omni-navigator b/lib/omni-navigator
--- a/lib/omni-navigator
+++ b/lib/omni-navigator
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-type -t init_omni_navigator >/dev/null && return 0
+type -t omni_navigator_init >/dev/null && return 0
 
-init_omni_navigator() {
+omni_navigator_init() {
   omni_list_window=${omni_list_window:-20}
   if [[ ! -v fd_original_in ]]; then
     exec {fd_original_in}<&0
@@ -13,29 +13,48 @@ init_omni_navigator() {
 }
 
 omni_navigator() (
-  local cursor_a_job_id=${cursor_a_job_id:-${cursor_job_id:-}} \
-    cursor_a_fork_id=${cursor_a_fork_id:-${cursor_fork_id:-}} \
-    cursor_a_log_pos=${cursor_a_log_pos:-${cursor_log_pos:-}} \
-    cursor_a_all_forks_log=${cursor_a_all_forks_log:-${cursor_all_forks_log:-}} \
-    cursor_a_log_file=${cursor_a_log_file:-${cursor_log_file:-}} 
-
-  local cursor_a_array_index cursor_a_array
+  local \
+    cursor_a_log_file=${cursor_a_log_file:-${cursor_log_file:-${log_file:-}}} \
+    cursor_a_array=${cursor_a_array:-} \
+    cursor_a_index=${cursor_a_index:-${cursor_index:-${index:-0}}} \
+    cursor_a_fork_id
 
   begin_function_flat
+
     if [[ -L "$cursor_a_log_file" ]]; then
       cursor_a_log_file=$(realpath $cursor_a_log_file)
     fi
-    begin_loop
-      debug_start
 
-      update_log_cursor || fail
-      declare -n cursor_a_array=omni_log_array_$cursor_a_fork_id
+    if [[ ! -f "$cursor_a_log_file" ]]; then
+      fatal "Can't find log file: $cursor_a_log_file"
+      fail1
+    fi
+
+    if [[ ! "${cursor_a_fork_id:-}" ]]; then
+      cursor_a_fork_id=${cursor_a_log_file%.olog}
+      cursor_a_fork_id=${cursor_a_fork_id##*-}
+    fi
+
+    if [[ ! "$cursor_a_fork_id" =~ ^[0-9]+$ ]]; then
+      fatal "Could not figure out fork id. Got [$cursor_a_fork_id]"
+      fatal "Maybe log file doesn't comply with convention: {path}/{log}-{fork_id}.olog"
+      fail1
+    fi
+
+    if [[ ! -v omni_log_array_$cursor_a_fork_id ]]; then
+      eval "declare -ga omni_log_array_$cursor_a_fork_id"
+      mapfile omni_log_array_$cursor_a_fork_id < <(cat $cursor_a_log_file) || fail
+    fi
+    declare -n cursor_a_array=omni_log_array_$cursor_fork_id
+    
+    begin_loop
 
       local current_log_line=${cursor_a_array[$cursor_a_array_index]}
-      local omni_list_offset=$(( -omni_list_window / 2 + 1 )) || true
+      local offset=$(( -omni_list_window / 2 + 1 )) || true
       omni_show_log || fail
       local omni_list_dir=forwards
       let omni_list_offset+=omni_list_window-1 || true
+      succeed
     end_loop
   end_function_flat
 
@@ -63,22 +82,6 @@ update_log_cursor() {
       fi
     fi
 
-    if [[ ! "$cursor_log_file" ]]; then
-      fatal "Can't determine log file. Either pass in cursor_a_log_file explicitly, or give the fork id and all forks log."
-      fail1
-    fi
-
-    if [[ ! "$cursor_fork_id" ]]; then
-      cursor_fork_id=${cursor_log_file%.olog}
-      cursor_fork_id=${cursor_fork_id##*-}
-    fi
-
-    if [[ ! "$cursor_fork_id" =~ ^[0-9]+$ ]]; then
-      fatal "Could not figure out fork id. Got [$cursor_fork_id]"
-      fatal "Maybe log file doesn't comply with convention: {path}/{log}-{fork_id}.olog"
-      fail1
-    fi
-
     if [[ ! -v omni_log_array_$cursor_fork_id ]]; then
       eval "declare -ga omni_log_array_$cursor_fork_id"
       mapfile omni_log_array_$cursor_fork_id < <(cat $cursor_log_file) || fail
@@ -86,8 +89,9 @@ update_log_cursor() {
     eval "declare -n cursor_${cursor}_array=omni_log_array_$cursor_fork_id"
     declare -n cursor_array=cursor_${cursor}_array
 
-    cursor_array_index=0
-    if (( $cursor_log_pos > 0 )); then
+    if [[ ! "${cursor_array_index:-}" \
+       && "$cursor_log_pos" ]] \
+       && (( cursor_log_pos > 0 )); then
 
       local i found=f array_size=${#cursor_array[*]} entries line
       begin_for ((i=0; i < array_size; i++)); doo
@@ -123,8 +127,34 @@ update_log_cursor() {
 }
 
 omni_show_log() {
+  local offset=$offset \
+    to_show_index to_show_start to_show_end \
+    omni_list_window=$omni_list_window
+  local -a to_show
+
   begin_function_flat
+
+    local -n plane_map=omni_plane_map_$cursor_a_fork_id
+    local -r plane_id=${plane_map[$cursor_a_index]}
+    local -n plane=omni_plane_${cursor_a_fork_id}_${plane_id}
+
+    if (( offset < 0 ); then
+      (( to_show_start = 0 ))
+      (( to_show_index = -offset ))
+    else
+      (( to_show_start = offset ))
+      (( to_show_index = 0 ))
+    fi
+    (( to_show_end = to_show_start + omni_list_window ))
+
     omni_show_reversed_line || fail
+    local remaining_lines=$omni_list_window
+    local found_line i
+    begin_while (( remaining_lines-- > 0 )); doo
+      found_line=f
+      begin_while (( i=omni_list_offset
+
+    end_while
   end_function_flat
   handle_return
 }
@@ -133,7 +163,7 @@ omni_show_reversed_line() {
   echo -n "$REVERSE" >&$fd_original_err
   local processed_line
   omni_get_processed_line "$current_log_line" || return 1
-  local -n line=$processed_line
+  local -n line=processed_line
   local pad_size line_length=${#line}
   ((pad_size=COLUMNS-line_length))
   echo -n "$line" >&$fd_original_err
@@ -154,6 +184,9 @@ omni_get_processed_line() {
       ;;
       return\(*)
         processed_line="$action from $function"
+      ;;
+      log_from)
+        processed_line="$action $old_log_file"
       ;;
       debug)
         processed_line="$action $info"
