Add grip and slow paramters

diff --git a/lib/omni-log b/lib/omni-log
--- a/lib/omni-log
+++ b/lib/omni-log
@@ -576,21 +576,31 @@ change_log_file() {
 }
 
 log_trace() {
-  begin_function_lo
-    local $snapshot_source_location_locals
-    offset=1 snapshot_source_location
-    write_to_log trace "${action:-}" "$*" || fail
-  end_function
-  handle_return
+  if log_level_at_least trace; then
+    #begin_function_grip
+      local m=
+      if [[ $show_debug_id != f ]]; then
+        m="${DIM_DEBUG_COLOR}debug_id=$fork_debug_id$RESET "
+      fi
+      echo " $m$*" >&$fd_original_err
+    #end_function
+    #handle_return
+  fi
+  #local $snapshot_source_location_locals
+  #offset=1 snapshot_source_location
+  #write_to_log trace "${action:-}" "$*" || fail
 }
 
 log_debug() {
   if log_level_at_least debug; then
-    local m=
-    if [[ $show_debug_id != f ]]; then
-      m="${DIM_DEBUG_COLOR}debug_id=$fork_debug_id$RESET "
-    fi
-    echo " $m$*" >&$fd_original_err
+    begin_function_grip
+      local m=
+      if [[ $show_debug_id != f ]]; then
+        m="${DIM_DEBUG_COLOR}debug_id=$fork_debug_id$RESET "
+      fi
+      echo " $m$*" >&$fd_original_err
+    end_function
+    handle_return
   fi
   #begin_function_lo
   #  local $snapshot_source_location_locals
@@ -602,11 +612,14 @@ log_debug() {
 
 log_verbose() {
   if log_level_at_least verbose; then
-    local m=
-    if [[ $show_debug_id != f ]]; then
-      m="${DIM_DEBUG_COLOR}debug_id=$fork_debug_id$RESET "
-    fi
-    echo " $*" >&$fd_original_err
+    begin_function_grip
+      local m=
+      if [[ $show_debug_id != f ]]; then
+        m="${DIM_DEBUG_COLOR}debug_id=$fork_debug_id$RESET "
+      fi
+      echo " $*" >&$fd_original_err
+    end_function
+    handle_return
   fi
   #begin_function_lo
   #  local $snapshot_source_location_locals
