.

diff --git a/lib/omni-navigator b/lib/omni-navigator
--- a/lib/omni-navigator
+++ b/lib/omni-navigator
@@ -166,7 +166,7 @@ omni_load_log_array() {
 
     end_for
 
-    plane_map_size=${#plane_map[*]}
+    log_array_size=${#log_array[*]}
   
   end_function
   handle_return
@@ -188,10 +188,12 @@ omni_select_cursor() {
       plane_depth_map=cursor_${cursor}_plane_depth_map \
       plane_map=cursor_${cursor}_plane_map \
       plane_stack_map=cursor_${cursor}_plane_stack_map \
+      log_file_stack=cursor_${cursor}_log_file_stack \
+      log_file_pos_stack=cursor_${cursor}_log_file_pos_stack \
 
     log_fork_id=${log_file_id#*:} \
     log_job_id=${log_file_id%:*} \
-    plane_map_size=${#plane_map[*]} 
+    log_array_size=${#log_array[*]} 
   fi
 
   return 0
@@ -240,6 +242,40 @@ omni_change_cursor_log() {
 
   end_function
   handle_return
+}
+
+# inputs:
+#   new_log_file
+#   new_index
+omni_enter_sub_log() {
+  local new_index=${new_index:-0}
+  log_file_stack+=( $log_file )
+  log_file_pos_stack+=( $log_array_index )
+  omni_change_cursor_log || return 1
+  if [[ $new_index == -1 ]]; then
+    (( new_index = log_array_size - 1 ))
+  fi
+  log_array_index=$new_index
+  return 0
+}
+
+omni_exit_sub_log() {
+  if (( ${#log_file_stack[*]} == 0 )); then
+    log_fatal "Internal error: attempted omni_exit_sub_log when log_file_stack size is 0"
+    return 1
+  fi
+
+  local parent_log_file=${log_file_stack[-1]}
+  unset log_file_stack[-1]
+
+  local parent_pos=${log_file_pos_stack[-1]}
+  unset log_file_pos_stack[-1]
+
+  new_log_file=$parent_log_file \
+    omni_change_cursor_log || return 1
+  log_array_index=$parent_pos
+
+  return 0
 }
 
 # inputs: {index}
@@ -291,7 +327,7 @@ omni_show_line() {
 omni_show_log() {
   begin_function_flat
 
-    local -r plane_map_size=${#plane_map[*]}
+    local -r log_array_size=${#log_array[*]}
 
     # display lines until end
     local remaining_lines=$(( omni_list_radius * 2 + 1 ))
@@ -339,16 +375,39 @@ omni_extract_vars() {
   return 0
 }
 
+# Move to the next log line to search
+omni_search_next() {
+  if [[ $deep == t && ${action_map[$index]} == log_to ]]; then
+    local new_index=0
+    if [[ $direction == -1 ]]; then
+      new_index=-1
+    fi
+    local new_log_file
+    vars=new_log_file \
+      omni_extract_vars || fail
+    omni_enter_sub_log || return 1
+  else
+    # TODO handle edge
+    (( index += direction ))
+    if [[ $direction == 1 ]]; then
+      if (( index >= log_array_size )); then
+      else
+      fi
+    else
+    fi
+  fi
+  return 0
+}
+
 # will move the cursor according to the parameters given
-# inputs:
-#   cursor
 omni_search() {
-  local log_vars='from_log from_index cursor direction count deep'
+  local log_vars='from_log from_index move_cursor direction count deep'
   begin_function
 
     local \
       from_log=${from_log:-} \
       from_index=${from_index:-} \
+      original_cursor=${cursor:-} \
       move_cursor=${move_cursor:-s} \
       direction=${direction:-1} \
       count=${count:-} \
@@ -356,35 +415,36 @@ omni_search() {
       find_action=${find_action:-} \
       deep=${deep:-t} \
 
+    debug_start
     # TODO: put in correct place
-    # log_file_stack+=( $log_file )
-    # log_file_pos_stack+=( $log_array_index )
+    # use: omni_enter_sub_log and omni_exit_sub_log
 
     found_index= found_log=
 
-    local cursor=s 
+    zombie "Starting omni_search: from_log=$from_log from_index=$from_index move_cursor=$move_cursor"
 
-    zombie "Starting omni_search for $from_log / $from_index"
-    new_log_file=$from_log \
-      new_index=$from_index \
-      new_cursor=$cursor \
-      omni_change_cursor_log || fail
-
-    if [[ -v omni_search_stack && "$omni_search_stack" =~ \ $from_log\  ]]; then
-      log_fatal "Infinite loop detected in omni_search, hit $from_log twice"
-      fail1
+    if [[ "$from_log" ]]; then
+      new_log_file=$from_log \
+        omni_change_cursor_log || fail
     fi
-    omni_search_stack+=" $from_log "
 
-    eval "$omni_select_cursor" || fail
+    omni_select_cursor || fail
+
+    local -n index=log_array_index
+    if [[ "$from_index" ]]; then
+      index=$from_index
+    fi
 
     local original_plane_id=${plane_map[$index]}
     local plane_id=$original_plane_id
 
-    local entry_matches
-    begin_while (( index < plane_map_size && index >= 0 )); doo
+    local entry_matches 
+    begin_while true; doo
 
-      zombie "Checking index $index / $plane_map_size of $log_file"
+      omni_search_next || fail
+
+      (( index < log_array_size && index >= 0 ))
+      zombie "Checking index $index / $log_array_size of $log_file"
       entry_matches=t
       if [[ $deep == f && $plane_id != $original_plane_id ]]; then
         entry_matches=f
@@ -452,8 +512,13 @@ omni_search() {
         omni_change_index || fail
     end_while
 
+    # restore original cursor
+    if [[ "$original_cursor" ]]; then
+      new_cursor=$original_cursor \
+        omni_select_cursor || fail
+    fi
+
   end_function
-  omni_search_stack=${omni_search_stack// $from_log /}
   handle_return
 }
 
@@ -497,7 +562,7 @@ omni_offset_index() {
   for (( i = current_index + d;
          i >= 0 
          && adjusted < amount 
-         && i < plane_map_size;
+         && i < log_array_size;
          i += d )); do
     if (( plane_map[i] == plane_id )); then
       current_index=$i
@@ -640,8 +705,8 @@ omni_navigator() (
           var=index offset=1 match_action=call omni_offset_index || fail
           if [[ $p == $index ]]; then
             (( index++ ))
-            if (( index >= plane_map_size )); then
-              (( index = plane_map_size - 1 ))
+            if (( index >= log_array_size )); then
+              (( index = log_array_size - 1 ))
             fi
             plane_id=${plane_map[$index]}
           fi
@@ -651,7 +716,7 @@ omni_navigator() (
         o)
           echo "# Step out" >&$fd_original_err
           local i=$index base_depth=${plane_depth_map[$index]}
-          begin_while (( ++i < plane_map_size )); doo
+          begin_while (( ++i < log_array_size )); doo
             if (( ${plane_depth_map[$i]} < base_depth )); then
               index=$i
               plane_id=${plane_map[$index]}
@@ -676,8 +741,8 @@ omni_navigator() (
           var=index offset=1 omni_offset_index || fail
           if [[ $p == $index ]]; then
             (( index++ ))
-            if (( index >= plane_map_size )); then
-              (( index = plane_map_size - 1 ))
+            if (( index >= log_array_size )); then
+              (( index = log_array_size - 1 ))
             fi
             plane_id=${plane_map[$index]}
           fi
