Improve help for clean command and trace_time output

diff --git a/lib/omni-log b/lib/omni-log
--- a/lib/omni-log
+++ b/lib/omni-log
@@ -428,7 +428,7 @@ write_to_log() {
     write_to_log_log_var
 
     if [[ ${disable_log:-f} == f && $log_to_file == t && "${logging_to_file:-}" ]]; then
-      echo "$NL$to_log" >>$logging_to_file
+      echo "$NL$to_log" >>$logging_to_file || fail
     fi
 
     write_to_log_update_cooked
