Added safe_link and avoid updating timing stats when debugging

diff --git a/lib/post-bash b/lib/post-bash
--- a/lib/post-bash
+++ b/lib/post-bash
@@ -741,7 +741,7 @@ begin_function
     fail
   fi
 
-  defer "rm -r '$pid_file' '$folder_to_lock'"
+  defer "rm -r '$pid_file' '$folder_to_lock' &>/dev/null"
 
   # lock obtained
   trace ${log_trace:--10} "Succeeded in obtaining lock."
@@ -893,6 +893,18 @@ for ((i=0; i < count; i++)); do
   eval "var=\${$array[$i]}"
   eval "$var=$i"
 done
+}
+
+safe_link() {
+local from=$1 to=$2
+if [[ $to != */ && ( -e "$to" || -L "$to" ) ]]; then
+  rm -r "$to" || return 1
+fi
+if [[ ! -e "$from" ]]; then
+  err "Interal error: Source of link doesn't exist: $from"
+  return 1
+fi
+ln -s "$from" "$to" 
 }
 
 # used in if condition to be more clear.
