Fix debugger bug

diff --git a/lib/post-bash b/lib/post-bash
--- a/lib/post-bash
+++ b/lib/post-bash
@@ -10,16 +10,12 @@ export tracing_depth=${tracing_depth:-0}
 export no_trace_depth=${no_trace_depth:-0}
 
 alias start_tracing='
-  side_bug "tracing_depth from $tracing_depth"
   [[ $tracing_depth == 0 ]] && set -x
   let tracing_depth++ || true
-  side_bug "tracing_depth to $tracing_depth"
   '
 alias stop_tracing='
-  side_bug "tracing_depth from $tracing_depth"
   let tracing_depth-- || true
   [[ $tracing_depth -le 0 ]] && { set +x; tracing_depth=0; }
-  side_bug "tracing_depth to $tracing_depth"
   '
 
 alias begin_no_tracing_zone='[[ $no_trace_depth == 0 && $tracing_depth -gt 0 ]] && set +x || true; let no_trace_depth++ || true'
@@ -784,9 +780,9 @@ read -p "${1:-Press any key}" -n 1 none || true
 # should run in a subprocess so dir change doesn't affect caller
 # normal usage: x=$(unrealpath "$some_path")
 unrealpath() {
-local p=$PWD
+local p=$PWD x=$1
 cd /
-realpath -s "$p/$1"
+realpath -s "$p/$x" || { fatal "Internal error: could not resolve $p/$x"; return 1; }
 }
 
 remove_from_string() {
