Fix background log bug

diff --git a/lib/ssh-lib b/lib/ssh-lib
--- a/lib/ssh-lib
+++ b/lib/ssh-lib
@@ -532,7 +532,7 @@ ssh_connect() {
     fi
 
     if [[ $connect_successful == t ]]; then
-      from_must_exist=f safe_link $background_log $out_path/background || fail
+      #from_must_exist=f safe_link $background_log $out_path/background || fail
       ssh_handle_jumps || fail
     fi
 
