Make background process execution support allow_return_codes=all

diff --git a/lib/update-lib b/lib/update-lib
--- a/lib/update-lib
+++ b/lib/update-lib
@@ -111,11 +111,11 @@ validate_cell() {
   begin_function
 
     if [[ $cell_is_leaf == t && "${validator:-}" ]]; then
-      local target target_var target_cell real_cell
+      local target target_var target_name target_cell real_cell
       begin_for target in "${validator[@]}"; doo
 
-        target_var=${target%%,*}
-        target_var=${target_var//-/_}
+        target_name=${target%%,*}
+        target_var=${target_name//-/_}
 
         strong_log=t log_verbose "$validate_type-validating using $target_var (from $short_cell)"
 
@@ -124,7 +124,7 @@ validate_cell() {
           conditions=${target#*,}
         fi
 
-        local target_cell=$validator_path/$target_var invalid_dep=f
+        local target_cell=$validator_path/$target_name invalid_dep=f
 
         during_validation=t \
         fresh=0 \
@@ -431,7 +431,7 @@ update_upstream() {
     up_cell=$upstream \
     execute_up || fail
 
-    if [[ -f $upstream/color.var ]]; then
+    if [[ -f $upstream/out_color.var ]]; then
       color_upstream_found=t
     fi
 
@@ -1107,8 +1107,8 @@ update_handle_color() {
         path=${up_path}/$up_name
         up_color=
         up_problem=
-        if [[ -f $path/color.var ]]; then
-          up_color=$(<$path/color.var)
+        if [[ -f $path/out_color.var ]]; then
+          up_color=$(<$path/out_color.var)
           get_max_color "$up_color" "$color" || fail
           color=$max_color
           if [[ -f $path/problem_detail.var ]]; then
@@ -1125,7 +1125,7 @@ update_handle_color() {
 
     fi
 
-    echo "$color" >$cell_path/color.var || fail
+    echo "$color" >$cell_path/out_color.var || fail
     if [[ "${problem_detail:-}" ]]; then
       echo "$problem_detail" >$cell_path/problem_detail.var || fail
     fi
