.

diff --git a/lib/update-lib b/lib/update-lib
--- a/lib/update-lib
+++ b/lib/update-lib
@@ -129,12 +129,6 @@ execute_up() {
       upstream_cell_link \
       downstream_cell_name \
 
-    up_cell_path=$(realpath $up_cell) || fail
-    if [[ $up_cell_path == */.cyto/* ]]; then
-      log_fatal "Internal error: up_cell_path is in cyto: $up_cell_path"
-      fail1
-    fi
-
     if [[ $up_cell_type == up ]]; then
       upstream_cell_link=$up_cell
       get_short_cell $cell_path
@@ -144,6 +138,12 @@ execute_up() {
     if [[ $needs_update == t ]]; then
       
       maybe_fix_up || fail
+
+      up_cell_path=$(realpath $up_cell) || fail
+      if [[ $up_cell_path == */.cyto/* ]]; then
+        log_fatal "Internal error: up_cell_path is in cyto: $up_cell_path"
+        fail1
+      fi
 
       needs_update=
 
