.

diff --git a/lib/update-lib b/lib/update-lib
--- a/lib/update-lib
+++ b/lib/update-lib
@@ -66,6 +66,15 @@ maybe_fix_choice() {
           invalid_dep=t
         fi
       fi
+
+      if [[ $invalid_dep == t ]]; then
+        rm -rf ${choice%/choices/*} || fail
+        make_cyto_up_single ${choice##*/} || fail
+        choice_target=$(realpath $choice) || invalid_dep=t
+        get_trunk_cell $choice_target || fail
+        invalid_dep=f
+      fi
+
       if [[ $invalid_dep == f ]]; then
         safe_link $trunk_cell $choice || fail
       else
