Improve validator support

diff --git a/lib/update-lib b/lib/update-lib
--- a/lib/update-lib
+++ b/lib/update-lib
@@ -77,7 +77,7 @@ prep_upstream() {
   handle_return
 }
 
-maybe_fix_validate() {
+maybe_fix_validation() {
   local choice=$1
   begin_function
     if [[ ! -e "$choice" ]]; then
@@ -86,7 +86,7 @@ maybe_fix_validate() {
 
       if [[ $invalid_dep == t ]]; then
         rm -rf ${choice} || fail
-        make_cyto_validate_single ${choice##*/} || fail
+        make_cyto_validator_single ${choice##*/} || fail
         invalid_dep=f
       fi
 
@@ -182,9 +182,9 @@ load_upstream_vars() {
 validate_cell() {
   begin_function
 
-    if [[ $cell_is_leaf == t && "${validate:-}" ]]; then
+    if [[ $cell_is_leaf == t && "${validator:-}" ]]; then
       local target target_var target_cell real_cell
-      begin_for target in "${validate[@]}"; doo
+      begin_for target in "${validator[@]}"; doo
 
         target_var=${target%%,*}
         target_var=${target_var//-/_}
@@ -196,9 +196,9 @@ validate_cell() {
           conditions=${target#*,}
         fi
 
-        local target_cell=$validate_path/$target_var invalid_dep=f
+        local target_cell=$validator_path/$target_var invalid_dep=f
         if [[ ! -e $target_cell ]]; then
-          maybe_fix_validate $target_cell || fail
+          maybe_fix_validator $target_cell || fail
         fi
 
         real_cell=$(realpath $target_cell) || fail
@@ -211,7 +211,7 @@ validate_cell() {
         fork execute_commands "$real_cell" update || fail
         load_upstream_vars || fail
 
-        local post_function=validate_${target_var}_post
+        local post_function=validator_${target_var}_post
         if function_exists $post_function; then
           log_debug "Executing validation post function: $post_function"
           $post_function || fail
@@ -229,26 +229,26 @@ validate_cell() {
             if [[ $negative == f ]]; then
               if [[ "${up_var:-}" == "$value" ]]; then
                 validation_says_already_done=t
-                touch $status_path/last-validate-good || fail
-                touch $status_path/last-validate-${target_var}-good || fail
+                touch $status_path/last-validation-good || fail
+                touch $status_path/last-validation-${target_var}-good || fail
                 strong_log=t log_verbose "Validation result: DONE"
               else
                 validation_says_already_done=f
-                touch $status_path/last-validate-bad || fail
-                touch $status_path/last-validate-${target_var}-bad || fail
+                touch $status_path/last-validation-bad || fail
+                touch $status_path/last-validation-${target_var}-bad || fail
                 strong_log=t log_verbose "Validation result: NOT DONE"
                 break 2
               fi
             else
               if [[ "${up_var:-}" != "$value" ]]; then
                 validation_says_already_done=t
-                touch $status_path/last-validate-good || fail
-                touch $status_path/last-validate-${target_var}-good || fail
+                touch $status_path/last-validation-good || fail
+                touch $status_path/last-validation-${target_var}-good || fail
                 strong_log=t log_verbose "Validation result: DONE"
               else
                 validation_says_already_done=f
-                touch $status_path/last-validate-bad || fail
-                touch $status_path/last-validate-${target_var}-bad || fail
+                touch $status_path/last-validation-bad || fail
+                touch $status_path/last-validation-${target_var}-bad || fail
                 strong_log=t log_verbose "Validation result: NOT DONE"
                 break 2
               fi
