Fix filter of implicit dims

diff --git a/lib/update-lib b/lib/update-lib
--- a/lib/update-lib
+++ b/lib/update-lib
@@ -1825,7 +1825,8 @@ update_command() {
           if [[ "${child_dims:-}" ]]; then
             update_members || fail
             if [[ $update_successful == t ]]; then
-              update_aggregation || fail
+              :
+              #update_aggregation || fail
             else
               log_error "Some members of $short_cell failed to update successfully."
             fi
