.

diff --git a/lib/update-lib b/lib/update-lib
--- a/lib/update-lib
+++ b/lib/update-lib
@@ -1309,6 +1309,11 @@ update_command() {
       needs_update=${needs_update:-} \
       needs_inner=f \
 
+    switch_context $cell_path || {
+      log_fatal "Context failed to load for $short_cell"
+      fail1
+    }
+
     if [[ ${branches_only:-f} == t && $cell_is_leaf == t ]]; then
       update_successful=t
       succeed
