.

diff --git a/lib/update-lib b/lib/update-lib
--- a/lib/update-lib
+++ b/lib/update-lib
@@ -127,7 +127,7 @@ load_upstream_vars() {
       dna_roots= \
       context_type= \
 
-#      auto_loads=() \
+    prefix=${prefix//-/_}
 
     pass_thru=t \
     recursive=f \
@@ -140,10 +140,6 @@ load_upstream_vars() {
       pass_thru=t \
       load_dna_contents $export_path || fail
     fi
-
-    #  not sure this is relevant any more
-    #prefix=
-    #execute_auto_loads "${auto_loads[@]}" || fail
 
     if [[ $update_successful == f ]]; then
       break
@@ -169,6 +165,8 @@ validate_cell() {
 
         target_var=${target%%,*}
         target_var=${target_var//-/_}
+
+        log_debug "Validating using $target_var"
 
         local conditions=
         if [[ $target_var != "$target" ]]; then
@@ -209,10 +207,12 @@ validate_cell() {
                 validation_says_already_done=t
                 touch $status_path/last-validate-good || fail
                 touch $status_path/last-validate-${target_var}-good || fail
+                log_debug "Validation good"
               else
                 validation_says_already_done=f
                 touch $status_path/last-validate-bad || fail
                 touch $status_path/last-validate-${target_var}-bad || fail
+                log_debug "Validation bad"
                 break 2
               fi
             else
@@ -220,10 +220,12 @@ validate_cell() {
                 validation_says_already_done=t
                 touch $status_path/last-validate-good || fail
                 touch $status_path/last-validate-${target_var}-good || fail
+                log_debug "Validation good"
               else
                 validation_says_already_done=f
                 touch $status_path/last-validate-bad || fail
                 touch $status_path/last-validate-${target_var}-bad || fail
+                log_debug "Validation bad"
                 break 2
               fi
             fi
@@ -695,7 +697,7 @@ update_upstreams() {
           fi
         fi
 
-        local target_cell=$orig_up_chosen_path
+        local target_cell=$orig_up_chosen_path/$upstream_name
         load_upstream_vars || fail
 
       end_for
@@ -1601,9 +1603,9 @@ post_update() {
       touch -d @$completion_time $status_path/last-good-update-end || fail
       cp -a $status_path/last-update-start \
             $status_path/last-good-update-start || fail
-      if [[ -v current_job_path ]]; then
-        force=t safe_link $current_job_path $job_path/last-success || fail
-      fi
+      #if [[ -v current_job_path ]]; then
+      #  force=t safe_link $current_job_path $job_path/last-success || fail
+      #fi
       if [[ "${data_props_expanded:-}" ]]; then
         update_prop_hash || fail
       fi
@@ -1613,7 +1615,7 @@ post_update() {
       fi
     else
       touch -d @$completion_time $status_path/last-bad-update-end || fail
-      force=t safe_link $current_job_path $job_path/last-failure || fail
+      #force=t safe_link $current_job_path $job_path/last-failure || fail
       cp -a $status_path/last-update-start \
             $status_path/last-bad-update-start || fail
     fi
