Display properties as well as coords

diff --git a/lib/update-lib b/lib/update-lib
--- a/lib/update-lib
+++ b/lib/update-lib
@@ -878,9 +878,10 @@ pre_update() {
       rm $status_path/last-good-update-end || fail
     fi
 
-    if [[ $cell_is_leaf == t ]]; then
-      calc_coords_leaf || fail
-    fi
+    #  already done elsewhere
+    #if [[ $cell_is_leaf == t ]]; then
+    #  calc_coords_leaf || fail
+    #fi
 
   end_function
   handle_return
@@ -1648,6 +1649,10 @@ show_coordinates() {
           local c_rows=
           coord_type=branch \
           display_coordinates || fail
+          if [[ $cell_is_leaf == t ]]; then
+            coord_type=leaf \
+            display_coordinates || fail
+          fi
           coords_displayed_for_cell=$short_cell
           if [[ ${confirm_dims:-t} == a \
              || $top_level_command == t \
