Fix pre_react bug

diff --git a/lib/update-lib b/lib/update-lib
--- a/lib/update-lib
+++ b/lib/update-lib
@@ -1669,16 +1669,19 @@ update_command() {
             r \
 
           if [[ "${reactor:-}" ]]; then
+            local rs
             begin_for r in $pre_react; doo
-              if [[ " ${reactor_short[*]} " == *" $r "*
-                || " ${reactor_short[*]} " == *" "*"-$r "*
-                ]]; then
-                update_successful=f
-                update_reactor $r || fail
-                if [[ $update_successful == f ]]; then
-                  log_warn "Failed to update reactor $r as pre_react (from $short_cell)"
+              begin_for rs in ${reactor_short[*]}; doo
+                if [[ "$rs" == "$r"
+                  || "$rs" == *"-$r"
+                  ]]; then
+                  update_successful=f
+                  update_reactor $rs || fail
+                  if [[ $update_successful == f ]]; then
+                    log_warn "Failed to update reactor $rs as pre_react (from $short_cell)"
+                  fi
                 fi
-              fi
+              end_for
             end_for
           fi
 
