Fix cyto up bug

diff --git a/lib/update-lib b/lib/update-lib
--- a/lib/update-lib
+++ b/lib/update-lib
@@ -1609,7 +1609,8 @@ update_command() {
       fail1
     fi
 
-    setup_dims || fail
+    # this already happened in switch_context
+    #setup_dims || fail
 
     if [[ "${auto_loads:-}" ]]; then
       execute_auto_loads "${auto_loads[@]}" || fail
