Fix plural_array bug

diff --git a/lib/update-lib b/lib/update-lib
--- a/lib/update-lib
+++ b/lib/update-lib
@@ -704,14 +704,15 @@ pre_update() {
       kind=data clean_cell $cell_path || fail
     fi
 
-    if [[ $cell_is_leaf == t ]]; then
-      local known_dims=()
-      local missing_dims=()
-      prep_dims sub_dims control_props data_props || fail
-      expand_dims || fail
-      coord_type=leaf \
-      switch_context_calc_coordinates || fail
-    fi
+    # This already happens in switch_context
+    #if [[ $cell_is_leaf == t ]]; then
+    #  local known_dims=()
+    #  local missing_dims=()
+    #  prep_dims sub_dims control_props data_props || fail
+    #  expand_dims || fail
+    #  coord_type=leaf \
+    #  switch_context_calc_coordinates || fail
+    #fi
 
   end_function
   handle_return
