m

diff --git a/lib/update b/lib/update
--- a/lib/update
+++ b/lib/update
@@ -2,12 +2,23 @@
 
 # usage: cell_set {subject}
 #   executes the given subject, which is a full path to a folder
-cell_set() {
+cell_update() {
 
 local subject=$1
 local lock_timeout=${lock_timeout:-0}
 local handler_path=( )
 local archetype_path=( )
+
+local cell_max_load=${cell_max_load:-100}
+local current_load=$(uptime | sed -E 's/.*averages: ([0-9]*).*/\1/')
+
+if [ $current_load -gt $cell_max_load ]; then
+  trace 5 "Load average is too high ($current_load > $cell_max_load), waiting until things cool down first."
+  while [ $current_load -gt $cell_max_load ]; do
+    current_load=$(uptime | sed -E 's/.*averages: ([0-9]*).*/\1/')
+    sleep 1
+  done
+fi
 
 trace 0 "Executing subject: $small_subject"
 
@@ -21,11 +32,11 @@ fi
 
 local subject_info="$SIMPLETON_WORK/$small_subject/cell-info"
 
-if [ -d "$subject_info" ]; then
+if [ -d "$cell_info" ]; then
 
   local handler_found
-  if [ -d "$subject_info/handler" ]; then
-    handler_found="$subject_info/handler"
+  if [ -d "$cell_info/handler" ]; then
+    handler_found="$cell_info/handler"
     absolute_path handler_found || fail
   else
     find_handler "$subject" || fail
@@ -33,7 +44,7 @@ if [ -d "$subject_info" ]; then
 
   if [ "$handler_found" ]; then
 
-    ln -sf "$handler_found" "$subject_info/handler" || fail
+    ln -sf "$handler_found" "$cell_info/handler" || fail
 
     trace -5 "Sourcing context files"
     local subject_out="$SIMPLETON_WORK/$small_subject/cell-out"
@@ -52,9 +63,9 @@ if [ -d "$subject_info" ]; then
 
     mkdir -p "$subject_out" || fail
     mkdir -p "$subject_log" || fail
-    mkdir -p "$subject_info" || fail
-    lock "$subject_info/lock" $lock_timeout || fail
-    touch "$subject_info/last-run-began" || fail
+    mkdir -p "$cell_info" || fail
+    lock "$cell_info/lock" $lock_timeout || fail
+    touch "$cell_info/last-update-began" || fail
 
     trace -5 "Executing handler $handler_found"
     source "$handler_found" || fail
@@ -64,34 +75,32 @@ if [ -d "$subject_info" ]; then
     local handler_failed=f
     handle "$subject" || handler_failed=t
 
-    if [ $subject_type == folder ]; then
-      untee_output
-      touch "$subject_info/last-run-ended" || fail
-      unlock "$subject_info/lock"
-      if [ "$handler_failed" == f ]; then
-        touch -r "$subject_info/last-run-began" "$subject_info/last-success-began" || fail
-        mv "$subject_log/log-current" "$subject_log/log-last-error"
-        ln -s "$subject_log/log-last-error" "$subject_log/log-previous"
-      else
-        mv "$subject_log/log-current" "$subject_log/log-last-success"
-        ln -s "$subject_log/log-last-success" "$subject_log/log-previous"
-      fi
+    untee_output
+    touch "$cell_info/last-run-ended" || fail
+    unlock "$cell_info/lock"
+    if [ "$handler_failed" == f ]; then
+      touch -r "$cell_info/last-run-began" "$cell_info/last-success-began" || fail
+      mv "$subject_log/log-current" "$subject_log/log-last-error"
+      ln -s "$subject_log/log-last-error" "$subject_log/log-previous"
+    else
+      mv "$subject_log/log-current" "$subject_log/log-last-success"
+      ln -s "$subject_log/log-last-success" "$subject_log/log-previous"
     fi
 
   else # no handler found
-    ....
-  fi
-
-else # subject-info missing
-  if [ -d "$subject" ]; then
+    
     trace 0 "Processing contents of $subject folder"
     local f
-    begin_for f in $(find "$subject" -mindepth 1 -maxdepth 1 -not -name ".*" | sort); doo
-      execute "$f" || fail
+    begin_for f in $(find "$subject" -mindepth 1 -maxdepth 1 -not -name ".*" -not -name "cell-*" | sort); doo
+      cell_update "$f" || fail
     end_for
-  else
-    trace -5 "Ignoring file $subject"
+
   fi
+
+else # cell-info missing
+
+  trace -5 "Ignoring file $subject"
+
 fi
 
 trace 0 "Subject executed successfully"
@@ -142,7 +151,7 @@ done
 is_refresh_needed() {
 local subject=$1
 
-if [ ! -e "$subject_info/last-success-began" ]; then 
+if [ ! -e "$cell_info/last-success-began" ]; then 
   refresh_needed=t
   return 0
 fi
@@ -150,7 +159,7 @@ fi
 local newer_file_found=$(
   find "$subject_folder" -mindepth 1 \
     -not -name 'cell-*' -not -name 'simpleton-*' -not -name '.*' \
-    -newer "$subject_info/last-success-began" -print -quit
+    -newer "$cell_info/last-success-began" -print -quit
   )
 if [ "$newer_file_found" ]; then 
   trace -5 "Found file that is newer than out: $newer_file_found"
